강원대 BE_오승환_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #10
Opened 2024-06-25 06:38 UTC by humpose

GET, POST, PUT, DELETE와 관련된 기능은 POSTMAN으로 잘 동작하는지 테스트를 진행하였습니다.

강의에서 getter와 setter의 사용을 지양하라고 말씀하셨는데, 그것이 제 코드처럼 product클래스의 getter와 setter를 말씀하시는 건지, 다른 부분을 말씀하시는 건지 궁금합니다.

또한, 필수적인 기능만 구현해놓았는데 더 추가할 기능이 있는지, 제 코드가 적절하게 작성되었는지도 궁금합니다.

2024-06-29 12:34 UTC, pci2676 requested changes
반갑습니다 🤠 

조금 질문에 대한 답변과 조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

모든 요구사항을 한번에 개선하시기 어렵다면 코멘트를 남겨주시고 할 수 있는 부분부터 점진적으로 적용해주시면 됩니다. 다음 단계로 넘어가면서 조금씩 개선하셔도 좋습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/resources/application.properties
> +spring.datasource.username=sa
앞으로 properties, yml을 통해 애플리케이션의 설정값을 정의하는 경우가 많이 있을텐데 

이럴때 단순히 값을 찾아서 넣기만 하지말고

왜 이러한 설정을 해야하는지 잘 파악하시고 정리해두신다음 다른 동료들에게 공유해보시면 큰 자산이 될 것 같습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        model.addAttribute("products", products);
구현하신 내용이 잘 동작하는지 확인하기 위해 postman을 이용하여 api를 직접호출하셨다고 했는데 코드를 변경할 때 마다 새롭게 애플리케이션을 실행하고 다시 api를 호출하는 과정이 꽤 번거롭지 않으셨나요?

이러한 기능을 수행하는 책임을 가진 클래스를 생성해보고 해당 클래스의 테스트 코드를 작성해보시면 위와 같은 번거로움을 덜어낼 수 있으니 알아보시면 큰 도움이 될 것 같습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        return "Add_product";
어떻게 파일의 이름을 문자열로 반환했을 뿐인데 html 파일이 렌더링되는 걸까요? 

지금은 처음 프레임워크를 사용해보시는 단계이니 어려울 수 있으니 시간이 여유로워지는 시점에 어떻게 이렇게 동작하는지 알아보시고 동료들에게 공유해보시면 좋을것 같습니다. 😄

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/Product.java
> +    // Getters and Setters
본문에 질문을 주신것을 보면 이 부분에 대해 고민이 있으신 것 같습니다.

getter와 setter를 지양하라는 것은 객체지향적인 사고를 통해 코드를 작성해보라는 것으로 이해해보시면 좋을것 같습니다.

보통 메세지를 던지는 방식으로 코드를 작성하라고 하는데요.

양수를 나타내는 클래스(ex. PositiveNumber)가 있을때 다른 양수를 입력받아 두개의 합을 반환하는 메서드를 작성해본다고 가정해보겠습니다.

그럼 무분별한 getter, setter를 활용한다면 아래와 같이 동작하는 것을 말합니다.

```java
class PositiveNumber {
    private Integer value;

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        if (value < 1) {
            throw new IllegalArgumentException("양수 값이어야 합니다. input=" + value);
        }
        this.value = value;
    }
}



public Integer plus(int number, int otherNumber) {
  PositiveNumber positiveNumber1 = new PositiveNumber();
  PositiveNumber positiveNumber2 = new PositiveNumber();

  positiveNumber1.setValue(number);
  positiveNumber2.setValue(number);

  return positiveNumber1.getValue() + positiveNumber2.getValue()
}
```

위와 같이 작성하지말고 아래와 같이 PositiveNumber에게 메세지를 던지는 방법이 있습니다.

```java
class PositiveNumber {
    private final Integer value;

    public PositiveNumber(Integer value) {
        if (value < 1) {
            throw new IllegalArgumentException("양수 값이어야 합니다. input=" + value);
        }
        this.value = value;
    }
    
    public Integer add(PositiveNumber positiveNumber) {
        return new PositiveNumber(this.value + positiveNumber.value).value;
    }
    
}


    public Integer plus(Integer number, Integer otherNumber) {
        PositiveNumber positiveNumber1 = new PositiveNumber(number);
        PositiveNumber positiveNumber2 = new PositiveNumber(otherNumber);

        return positiveNumber1.add(positiveNumber2);
    }

```

위 PositiveNumber 클래스에서 getter와 settter가 필요하지 않아보이지 않나요? 

위와 같이 PositiveNumber 객체에게 메세지를 던지는 형태로 작성하는 것을 고민해보시면 좋을것 같습니다.

아래 동영상을 함께 시청해보시면 도움이 될 것 같습니다.

https://www.youtube.com/watch?v=3etKkkna-f0&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC

+사용하지 않고 불필요한 setter는 제거해주시면 좋을것 같습니다. 😄

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/add")
GetMapping을 사용하신 이유가 있을까요?

RestFul하게 API를 작성한다면 어떠한 http method를 사용하도록 할 수 있을까요?

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/edit/{id}")
이 부분도 마찬가지 입니다. GetMapping을 사용한 이유가 있을까요 다른 httpMethod는 고려해보면 좋을것 같습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/delete/{id}")
이 부분도 마찬가지 입니다. GetMapping을 사용한 이유가 있을까요?? 다른 httpMethod는 고려해보면 좋을것 같습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    @PostMapping("/update/{id}")
update라는 특정행위에 대한 명시가 반드시 필요했을까요?

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
Autowired를 사용하여 Spring Bean을 주입하였군요!

다른 방식으로 주입할 수 있는 방법에 대해 아실까요?

모르신다면 차이점과 장단점에대해 알아보시면 좋을것 같습니다.

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    }
상품을 저장할때 DB에 이미 저장된 ID가 있다면 문제가 발생하지 않을까요?

요구사항에 대해 구현을 할 때 발생할 수 있는 예외 상황에 대한 대처도 같이 작업해주시면 좋을것 같습니다.

애플리케이션의 기능을 요구한 클라이언트가 어느정도 당연하다고 생각할 수 있는 부분에 한해서요. 😄

2024-06-29 12:34 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public String addProduct(@ModelAttribute Product product) {
Product는 DB에 저장되는 데이터모델로 보이는데요. 이러한 데이터 모델을 외부에서 전달받는 요청/응답 객체로도 사용하고 계신것 같습니다.

이러한 경우 외부의 요청사항에 변경이 생겼을때 DB 데이터모델로서는 필요하지 않은 변경점이 생겨날 수 있습니다.

단일 책임 원칙(SRP)을 준수할 수 있도록 용도에 맞는 클래스를 생성하여 사용해보시면 좋을것 같습니다.

2024-06-30 01:25 UTC, humpose commented on src/main/resources/application.properties
> +spring.datasource.username=sa
spring.h2.console.enabled=true는 H2 데이터베이스의 웹 콘솔을 활성화하고,
 spring.datasource.username=sa는 데이터베이스를 접속할 때 사용자 이름을 설정하고,
spring.datasource.url=jdbc:h2:mem:test는 데이터베이스의 URL을 설정하며 특히 jdbc:h2:mem 부분은 데이터를 디스크가 아닌 시스템의 주 메모리에 저장하는 인메모리 데이터베이스를 설정하고, test는 데이터베이스 이름이라는 것을 알 수 있었습니다. 이러한 내용들에 살을 붙여 동료들에게 공유하도록 하겠습니다.

2024-06-30 01:33 UTC, humpose commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
예. 잘 몰라서 공부해보았습니다.
제가 사용한 방법은 필드 주입으로, 코드가 간단하고 읽기 쉽지만, 필드가 private이기 때문에 리플렉션을 사용하지 않으면 테스트 시 주입이 어렵다는 단점이 있습니다.
생성자 주입은 생성자를 통해 주입하기 때문에 테스트 시 mock 객체(단위 테스트에서 실제 객체를 대신하여 사용되는 객체)를 주입하기 쉽지만, 클래스의 의존성이 많아질수록 생성자 코드가 길어질 수 있다는 단점이 있습니다.
세터 주입은 유연하지만, 불변성을 보장하지 못하고, 의존성이 누락될 가능성이 있다는 단점이 있습니다.
생성자와 세터 주입은 생성자로 @Autowired 한다는 것이 큰 차이점인 것 같습니다.

2024-06-30 01:34 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    }
예외처리는 다음 주차 2주차 과제 step1에 있으므로 그 때 수정하도록 하겠습니다!

2024-06-30 01:40 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    //쿼리로 모든 상품을 조회하여 모델에 추가한 후, products.html Thymeleaf 템플릿으로 렌더링
네 우선 다른 부분을 수정하고 공부해보면서 테스트를 작성하도록 하겠습니다!

2024-06-30 02:32 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    public String addProduct(@ModelAttribute Product product) {
네. 맨 위에 말씀해주신 부분의 일부이므로 수정할 때 참고하겠습니다.

2024-06-30 02:42 UTC, humpose commented on src/main/java/gift/ProductController.java
> +        return "Add_product";
공부해보니, Spring이  설정된 뷰 리졸버를 사용하여 반환된 뷰 이름을 기반으로 실제 뷰 파일(HTML 파일)을 찾는다는 걸 알 수 있었습니다. 시간이 더 생긴다면 추가로 공부해서 동료에게 공유하도록 하겠습니다!

2024-06-30 02:44 UTC, humpose commented on src/main/java/gift/Product.java
> +    // Getters and Setters
사용하지 않는 불필요한 setter를 모두 제거하였습니다!

2024-06-30 03:36 UTC, humpose commented on src/main/java/gift/Product.java
> +    // Getters and Setters
삭제한 후 실행해보니, 웹페이지에서 입력한 값이 제대로 반영되지 않음을 알 수 있었습니다. 검색해보니 html파일에서 각 필드에 대응하는 값이 객체에 설정될 때, Spring MVC는 자동으로 해당 필드의 setter 메소드를 호출한다는 사실을 알 수 있었습니다.

2024-06-30 03:54 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/add")
해당 메서드는 수정없이 특정 상품의 현재 데이터를 조회해서 수정 폼에 미리 채워서 보여주는 데 목적이 있기 때문에 get을 사용했습니다. post를 사용할 수는 있겠으나, RestFul 기준에서도 get이 잘못되었다고 생각하지는 않는데요. 혹시 제 판단이 틀린건지, 조언자님은 어떻게 생각하지는지 궁금합니다.

2024-06-30 03:55 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/edit/{id}")
위와 동일합니다.

2024-06-30 03:55 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/delete/{id}")
예 이분은 DeleteMapping으로 수정하겠습니다

2024-06-30 06:27 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    @PostMapping("/update/{id}")
필요없을 것 같습니다. 수정하겠습니다.

2024-06-30 06:28 UTC, humpose commented on src/main/java/gift/ProductController.java
> +    };
예. 조언해 주신 대로 ProductController의 기능을 각각 나누어 구현하도록 하겠습니다.

2024-06-30 06:30 UTC, humpose commented on src/main/java/gift/ProductController.java
> +        model.addAttribute("products", products);
예. 위에서 말씀하셨던 controller 테스트 작성과 동일하게 공부하면서 테스트 코드 작성해보도록 하겠습니다.

2024-06-30 06:33 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    @GetMapping("/add")
아 이 부분은 제가 잘못 보았네요~

Http method는 올바르게 사용해주신것 같습니다

다만 uri에 있는 add 말고 다른 방향으로 표현해보면 좋을것 같습니다

2024-06-30 12:50 UTC, pci2676 commented on src/main/java/gift/Product.java
> +    // Getters and Setters
> 검색해보니 html파일에서 각 필드에 대응하는 값이 객체에 설정될 때, Spring MVC는 자동으로 해당 필드의 setter 메소드를 호출한다는 사실을 알 수 있었습니다.

하나의 객체를 여러가지 목적으로 사용하게 된다면 SRP를 위반하는것으로 볼 수 있습니다. 용도에 맞게 클래스를 분리하여 사용하시는 것을 권장드립니다.

2024-07-01 08:11 UTC, pci2676 approved these changes
다음단계를 수행할때 이번 단계에서 개선하지 못한 부분을 함께 개선해보시면 좋을것 같습니다. 😄

2024-07-01 08:11 UTC, merged