전남대 BE_서지우 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #101
Opened 2024-06-27 07:06 UTC by seojiu

spring이 아직 익숙하지 않아서 기본적인 기능 구현에 집중했습니다. 

ProductController부분에서 예외 처리할 때  http 상태 메서드를 꼭 사용해야 하는지 궁금합니다. 현재 코드처럼 string으로만 오류가 발생했음을 알렸을 때 어떤 문제가 있는지도 궁금합니다.

2024-06-29 07:51 UTC, pkeugine requested changes
안녕하세요 지우님! 반갑습니다.
커밋을 깔끔하게 나눠주셔서 리뷰하기도 좋았고,
코드가 전반적으로 깔끔하네요.

간단한 리뷰와 질문 남겨보았으니 한 번 읽어보시고
반영하거나 댓글 남겨주세요.
댓글은 제가 나중에 다시 확인하러 올게요 :)

2024-06-29 07:51 UTC, pkeugine commented on README.md
> +# spring-gift-product
커밋 단위를 깔끔하게 분리해주셨네요!
덕분에 리뷰하기가 정말 수월해요 💯 💯 💯

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +    public Product() {}
해당 생성자는 왜 필요한가요?

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +    }
해당 생성자는 사용되지 않고 있네요!
setter 를 삭제하면 사용될 것 같긴한데,
앞으로는 사용되지 않는 코드는 미리 만드는 것을 지양해보도록 하죠 :)

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +    }
앞서 말했던 사용되지 않는 코드는 제거해보면 좋을 것 같고,
더 나아가 setter 를 지양해보면 어떨까요? 생성자를 이용해서 객체를 만들어보면 좋을 것 같아요.
왜 그런지 한 번 알아보도록 하죠!

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +}
파일의 끝에 empty line 을 추가해주면 좋을 것 같아요.
이 역시 왜 그런지 알아보는 시간을 가져보아요 :)

추가로 intelliJ 설정에는 empty line 을 자동으로 추가해주는 기능이 있어요.
이 옵션을 활성화하면 이런 일이 발생하는 것을 신경쓰지 않고 비교적 쉽게 코드를 관리할 수 있답니다.
<img width="1094" alt="Screenshot 2024-06-08 at 2 05 28 PM" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/48251668/b95eb954-70a7-4370-bc46-f6897a852be4">

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +import org.springframework.web.bind.annotation.*;
import 문에 wildcard 사용하는 것을 지양해보면 어떨까요?
그 이유는... 역시 알아보면 좋겠죠? 😄 
(다른 파일의 import 문도 확인해주세요)

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +
불필요한 공백이 있어요!

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +@RequestMapping("/api/products")
`@RequestMapping` 을 사용해서 공통적인 uri 를 잘 묶어주셨네요 👍 👍 👍

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    }
`@Autowired` 를 사용하지 않았는데도 bean 주입이 잘되네요!
어떻게 이게 가능한걸까요?

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        return product; // 성공 시 추가된 Product 반환
코드를 통해 충분히 이 로직을 이해할 수 있는 것 같아요.
잘 만들어주셔서요! 💯 💯 💯 
그러니 주석은 제거해볼까요?

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +            return result; // 오류 메시지 반환
> ProductController부분에서 예외 처리할 때 http 상태 메서드를 꼭 사용해야 하는지 궁금합니다.

현재 http 상태코드를 사용하지 않는 상태죠?
꼭 사용해야하는지는 답이 정해져있지 않아요.
결국 응답 형태는 정답이 있는게 아닌, 상호간의 약속이라서요.

이런 고민을 하시게된건 에러가 생겼을 때 사용하고자하는 응답코드가 있어서일까요?

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        return productService.deleteProduct(id); // 성공 시 null 반환, 오류 시 오류 메시지 반환
현재 프로젝트 내에 있는 주석은 충분히 코드로 이해할 수 있는 부분들이라 싹! 제거해도 좋을 것 같아요 :)

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        }
오 꼼꼼한 id 변경 여부 확인 좋네요 👍 👍 👍

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    public Object addProduct(@RequestBody Product product) {
id 는 클라이언트가 미리 결정해서 보내주나요?
만약 그렇다면, 서버에서 id 를 정할 수 있게 하면 좋을 것 같네요!

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +import org.springframework.stereotype.Service;
여긴 오히려 필요한 공백이 누락됐어요!

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +
또다른 불필요한 공백이네요 :)

2024-06-29 07:51 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +        return "상품이 없습니다.";
> 현재 코드처럼 string으로만 오류가 발생했음을 알렸을 때 어떤 문제가 있는지도 궁금합니다.

흠 어떤 문제가 있을까요 🤔 
앞서 말한 http 응답 코드처럼 에러가 발생했을시 보여주는 응답 역시 클라이언트와 서버간의 약속이기 때문에
딱히 문제가 발생하지는 않아요.
하지만 보통은 정해진 응답 틀을 갖추고, 그 틀 안에 예외 관련 정보를 넣어서 응답으로 보여주죠.
프로젝트를 발전시켜 나가며 지우님은 어떤 방식으로 그 틀을 만들면 좋을지 고민해보셔도 좋을 것 같아요.
하지만 아직은 예외처리를 깊게 다루지는 않으니, 요구사항과 Spring / Java 학습에 조금 더 집중하셔도 괜찮습니다.

2024-07-01 14:31 UTC, pkeugine commented
안녕하세요 지우님,
다음 단계를 진행하시는 것을 확인해서 해당 pr 은 머지하도록 할게요.
진행하시면서 여기 있는 리뷰를 한 번씩 확인해주셨는지 다시 한 번 봐주시면 좋을 것 같아요!

2024-07-01 14:31 UTC, pkeugine approved these changes

2024-07-01 14:31 UTC, merged

2024-07-12 10:58 UTC, seojiu commented on src/main/java/gift/ProductController.java
> +import org.springframework.web.bind.annotation.*;
런타임에는 영향을 미치지 않지만 컴파일 시간에 다소 영향을 준다고 공부했습니다. 또한 클린코드를 위해서 wildcard 사용을 지양해야한다고 배웠습니다.  2주차 코드에서 반영했습니다!!

2024-07-12 11:00 UTC, seojiu commented on src/main/java/gift/ProductController.java
> +    }
생성자가 하나밖에 없다면 생략이 가능하다고 공부했습니다!

2024-07-12 11:00 UTC, seojiu commented on src/main/java/gift/ProductController.java
> +    public Object addProduct(@RequestBody Product product) {
1주차 step2에서 반영했습니다

2024-07-12 11:26 UTC, seojiu commented on src/main/java/gift/Product.java
> +    public Product() {}
지금 보니 필요없는 생성자 같네요!!