Step1
kakao-tech-campus-2nd-step2/spring-gift-product pull request #102
Opened 2024-06-27 07:13 UTC by amm0124

1. hashmap을 사용해서 임시로 데이터를 저장하라고 한 이유가 궁금합니다. 
data 객체를 record로 지정해서 key로 data의 hashcode를 사용을 할 지, 그냥 data의 row를 나타내려고 index를 key로 사용할지 고민을 했습니다. 어떤 것이 더 옳은 선택인가요?

2. 제가 스프링을 처음해봐서 어떤 것이 좋은 코드인지 잘 모르겠습니다. 훌륭한 예제 코드가 있으면 참조할 수 있도록 알려주시면 감사하겠습니다.

2024-06-30 04:59 UTC, jadie0319 requested changes
미션 진행하시느라 고생하셨습니다!
좀 더 개선 또는 고민하면 좋을 것들에 대해 메모해놨어요!
피드백 반영하시다 궁금한게 있으시면 남겨주세요!

2024-06-30 04:59 UTC, jadie0319 commented on src/main/java/gift/AdminController.java
> +package gift;
인텔리제이 reformat code, optimize imports 사용하시면 코드 정리를 도와줍니다!
Optimize Imports action ⌃⌥O (macOS) / Ctrl+Alt+O (Windows/Linux)
Reformat Code" ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux)

2024-06-30 04:59 UTC, jadie0319 commented on src/main/java/gift/ProductController.java
> +    }
현재 RestController 에서 요청을 받고, 쿼리 실행, 응답을 반환하는 일 등 많은 일을 하고 있어요.
JdbcTemplate 을 사용하는 로직은 다른 클래스로 분리하는 것에 대해 어떻게 생각하시나요?

참고링크
- https://escapefromcoding.tistory.com/732
- https://blogshine.tistory.com/213

2024-06-30 04:59 UTC, jadie0319 commented on src/main/java/gift/AdminController.java
> +    }
아래 ProductController 에 드린 피드백을 반영하면 
AdminController 가 ProductController 를 의존하지 않게 변경할 수 있을 것 같아요. :)

2024-06-30 04:59 UTC, jadie0319 commented on src/main/java/gift/ProductController.java
> +    public Collection<Product> getProducts() {
이 메서드에서만 ResponseEntity 를 사용하지 않으신 이유가 있을까요?

2024-06-30 04:59 UTC, jadie0319 commented on src/main/java/gift/AdminController.java
> +public class AdminController {
RestController 와 Controller 클래스를 나눠서 개발하니 역할이 더 명확하게 보여서 좋아요! 👍

2024-06-30 06:20 UTC, jadie0319 commented
안녕하세요! 카카오테크 캠퍼스 2기 백엔드 과정의 멘토링을 맡게된 멘토 제이디 입니다. 부족하지만 앞으로 6주간 좋은 시간이 되게 노력하겠습니다. 잘부탁드립니다~! 그리고 질문은 많으면 많을수록 좋습니다. 많이 질문해주세요! 이번 PR 에서 질문해주신 부분에 대해서 아래 정리했습니다.

### 질문 1 : 맨 처음 hashmap을 사용해서 임시로 데이터를 저장하라고 한 이유가 궁금합니다.

요구사항을 구현 후 실행하기 위한 목적으로 DB를 대체하기 위한 자료구조 중 HashMap 이 적절해서 사용을 한 것 같아요. 
이 과정에서 데이터의 조회, 저장, 변경, 삭제를 하기 위한 인터페이스에 대해서도 고민해볼 수 있어요. DB 를 사용하든 HashMap 을 사용하든 메서드의 요청값, 응답값, 메서드 이름등은 똑같을 것이니 공통 인터페이스를 만들고 DB 사용에 대한 구현 로직 또는 HashMap 사용에 대한 구현 로직은 인터페이스 뒤로 숨길 수 있겠네요 :)

참고자료

- https://velog.io/@hansoleee/%EA%B0%9D%EC%B2%B4-%EC%A7%80%ED%96%A5-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EC%9E%85%EB%AC%B8-DIP-9y7ddfjo

- https://javacan.tistory.com/entry/Implement-high-level-policy-without-low-level-detail


### 질문 2: data 객체를 record로 지정해서 key로 data의 hashcode를 사용을 할 지, 그냥 data의 row를 나타내려고 index를 key로 사용할지 고민을 했습니다. 어떤 것이 더 옳은 선택인가요?

데이터를 조회하는 메서드를 비교해볼까요.
```java
getProduct(해쉬코드) vs getProduct(index)
```
만약 해쉬코드를 key 로 사용한다면 상품의 해쉬코드를 알아야 데이터를 조회할 수 있어요. 하지만 알 수 있는 방법이 없으니 index 를 key로 사용하는게 맞는 것 같아요


### 질문 3 : 제가 스프링을 처음해봐서 어떤 것이 좋은 코드인지 잘 모르겠습니다. 훌륭한 예제 코드가 있으면 참조할 수 있도록 알려주시면 감사하겠습니다.

좋은 코드의 기준은 상대적이어서 정의하기 어려운 것 같아요. 우선 스프링에 대해 잘 알아야 좋은 코드를 만들 수 있고, 좋은 코드가 어떤 코드인지도 판단할 수 있는 힘이 생기실 것 같아요. 이제 스프링을 처음 배우시는 단계이니 미션들을 진행하며 천천히 함께 알아가면 되니 많이 질문해주세요!  우선 스프링 공부에 도움이 되실만한 키워드와 링크 공유해드릴게요! :)

- 키워드 : IOC, DI, AOP
- https://velog.io/@think2wice/Spring-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85DI%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC
- https://velog.io/@minji/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B9%88Bean-%EC%97%90-%EB%8C%80%ED%95%9C-%EC%9D%B4%ED%95%B4

 좋은 코드의 기준은 상대적이지만 , 흔히 말하는 좋은 코드를 짜기 위해서 지키면 좋은 원칙 같은 것들이 있어요. 도움이 되실만한 키워드나 책 공유해드릴게요! :) 

- 키워드 : 객체지향설계 원칙, SOLID
- 객체지향과 디자인 패턴 - 최범균
- 객체지향의 사실과 오해 - 조영호
- 클린코드 - 로버트 C.마틴


### 질문 4 : thymeleaf를 사용해서 SSR을 구현하라고 하셨는데, 보통 현업에서 SSR을 구현할 때 어떤 도구를 제일 많이 사용하나요?

SSR 구현을 해보지 않아서 잘 모르지만, React 를 많이 사용한다고 합니다.


### 질문 5 : 저는 add/delete/update/get을 각각 다른 화면에서 구현하였는데, 보통은 어떤 식으로 하는 것이 좋은 선택인가요? (저는 한 페이지에 나타내는 것이 더 좋다고 생각하긴 합니다 . .. )

하나의 html 에 모든 기능 구현 vs 각 기능별로 html 구현을 말씀하신게 맞을까요? 화면을 구현해 본 경험이 없지만, 개인적인 생각으로는 지금 구현하신 것처럼 각 기능별로 html 을 구현하는게 더 좋아보여요! 

하나의 html 에  모든 코드가 있으면 코드의 길이가 길어집니다. 그리고 의도치 않은 문제가 발생할 가능성이 높아집니다. 예를 들어 update 기능을 고쳤는데 갑자기 get 이 잘 안되는 버그가 발생한다고 하면, 예사잋 못한 버그이기 때문에 원인 찾기가 어렵고, 코드가 길기 때문에 찾아봐야할 코드도 많습니다. 그래서 저는 여러 html 로 구현하는게 좋을 것 같습니다. 

이것은 html 뿐만 아니라 자바 클래스 설계시에도 똑같이 적용됩니다. :)


### 질문 6 :  controller <-> service <-> repository <-> Entity를 분리해서 구현해야 하고 각 계층은 연결된 계층끼리 통신해야 한다고 들었습니다! 제 코드에서 어떻게 고쳐야 이를 잘 지킬 수 있을지 궁금합니다.

우선 각 계층이 하는 일에 대해서 아시면 도움이 될 것 같아요. 각 계층을 맡고 있는 객체에 어울리는 코드를 위치시키고, 객체간 메서드 호출을 통해 요구사항을 만족시키면 됩니다. 피드백 드린 것을 하나씩 반영해 보시면 될 것 같아요!

참고링크
- https://escapefromcoding.tistory.com/732


### 질문 7 : java가 거의 처음이라 잘 하지 못하는데 . . 좋은 코드가 있으면 공유 부탁 드립니다!!

java 기본 문법에 대한 공부와 위에서 말씀드린 객체지향 설계에 대해 공부하시면 도움이 될거에요! 그리고 다른 사람이 내 코드를 봤을 때 이해하기 쉬운 코드일까? 도 함께 고민하시면서 코딩을 하시면 도움이 많이 되실 것 같아요. 미션을 진행하면서 천천히 함께 알아가시죠! 이제 시작하는 단계이시니 천천히 기초부터 닦아 나가면 될 것 같아요! :)

다음 미션에서도 지금과 같이 많이 고민하시고 많이 질문 주세요! 화이팅 입니다!

2024-07-01 07:37 UTC, merged

2024-07-02 06:28 UTC, amm0124 commented on README.md
> +# spring-gift-product
다음부턴 대괄호를 사용해서 checkbox를 만들어보겠습니다

2024-07-02 06:30 UTC, amm0124 commented on src/main/java/gift/AdminController.java
> +package gift;
이런 꿀기능이! 감사합니다

2024-07-02 06:31 UTC, amm0124 commented on src/main/java/gift/ProductController.java
> +    }
넵! repository class를 만들어서 분리해보도록 하겠습니다

2024-07-02 06:32 UTC, amm0124 commented on src/main/java/gift/AdminController.java
> +    }
그렇다면 service class를 만들어서 기능을 구현하고, service class의 method를 호출하는 형태로 구현해보겠습니다!

2024-07-02 06:33 UTC, amm0124 commented on src/main/java/gift/ProductController.java
> +    public Collection<Product> getProducts() {
전체를 다 return하는 get method였는데, ResponseEntity를 사용해서 고쳐보겠습니다!!

2024-07-02 06:34 UTC, amm0124 commented on src/main/java/gift/AdminController.java
> +public class AdminController {
감사합니다! 
RestController는 Controller + ResponseBody로 알고 있습니다. 이는 API를 제공할 때 사용하고,
일반 Controller는 API를 제공하지 않을 때 사용한다고 알면 될까요?