부산대 BE_황수환_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #104
Opened 2024-06-27 07:36 UTC by HSHwan

## 코드 작성하면서 어려웠던 점
서비스와 컨트롤러 단위 테스트에서 Mockito와 MockMvc를 처음 사용하다보니
새로 알게 된 내용이 많아 테스트 코드를 작성하기 어려웠던 것 같습니다.

## 코드 리뷰 시 멘토님이 중점적으로 리뷰해줬으면 하는 부분

1. 도메인과 DTO와 같은 기본적인 동작만 하는 객체는 따로 단위 테스트를 하지 않아도 되는지 궁금합니다.

2. parameter를 ProductRequest로만 제한해서 Product 생성자를 설계했는데, Builder 패턴을 사용하는 것이 더 좋은 방법인지 궁금합니다. 

3. Mock 테스트에서 given과 when을 혼용해서 사용해도 되는지 궁금합니다.

2024-06-28 04:33 UTC, HSHwan reviewed
# STEP2

2024-06-29 01:51 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +        Product product = productRepository.findById(id).orElseThrow(
데이터가 없는 경우에 대한 예외처리 좋습니다😀

2024-06-29 01:52 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +                () -> new IllegalArgumentException("해당 상품은 존재하지 않습니다")
데이터가 없을 때 던질 예외로 NoSuchElementException 을 사용해보는 것은 어떨까요?!😀
```suggestion
                () -> new NoSuchElementException("해당 상품은 존재하지 않습니다")
```

- NoSuchElementException: 이 예외는 주로 컬렉션이나 데이터베이스에서 특정 요소를 찾을 수 없을 때 사용됩니다.
- IllegalArgumentException: 이 예외는 메서드에 전달된 인수가 적절하지 않을 때 사용됩니다.

2024-06-29 02:50 UTC, hocaron requested changes
수환님, 안녕하세요👋
이번 step 을 함께할 호선우입니다!

여러 계층의 테스트 코드를 만들어주셔서, 리뷰하는데 도움이 많이 되었습니다👍
함께 작업하는 입장에서 반영하면 좋을 리뷰를 남겼는데, 궁금한 점이나 의문이 생기면 편하게 코멘트나 DM 주세요.

1. 도메인과 DTO와 같은 기본적인 동작만 하는 객체는 따로 단위 테스트를 하지 않아도 되는지 궁금합니다.</br>
비즈니스 로직이 포함되어있지 않은, 매핑 역할만 하는 객체는 따로 테스트가 필요없을 것 같습니다😀

2. parameter를 제한해서 Product 생성자를 설계했는데, Builder 패턴을 사용하는 것이 더 좋은 방법인지 궁금합니다.</br>
저는 파리미터 개수가 3개를 초과하면 Builder 을 사용합니다. 파리미터 수가 많아져서, 같이 작업하는 분들이 파라미터를 잘못 넘겨 데이터가 잘못 생성되는 케이스도 있기 때문입니다🥲
현재 Product의 필드개수가 4개 인데, 적용해봐도 좋을 것 같습니다👍

3. Mock 테스트에서 given과 when을 혼용해서 사용해도 되는지 궁금합니다.</br>
given 은 특정 메서드 호출에 대한 반환값을 지정하여 테스트 케이스에 대한 설정을 하고, when 은 테스트의 실제 동작을 정의할 때 사용하는데요, 각 메서드의 목적에 맞게 함께 사용하면 테스트가 더 읽기 쉬워지더라고요!

5. 서버를 거치지 않고 admin-product-list에서 상품 삭제하려고 했으나 response body 내용이 반환되어 나와서 어떻게 처리하는 게 좋을지 궁금합니다.</br>
제가 해당 질문은 이해를 하지 못해서, 부연 설명해주시면 좋을 것 같습니다😎

7. 커밋을 너무 쪼개서 하는 느낌이 들어 더 큰 단위로 커밋을 해야하는지 궁금합니다.</br>
기능 단위로 조금 더 크게 커밋해도 좋을 것 같습니다👍
예시) 상품 생성 API 구현

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/dao/ProductDao.java
> +        );
`.queryForObject()` 사용시에 데이터가 없으면 EmptyResultDataAccessException 에러가 나지 않았을까요?!  데이터가 없는 경우에 Optional 을 반환하기 위해서는 아래 코드로 변경이 필요할 것 같습니다. 
```suggestion
                return jdbcTemplate.query(
                sql,
                (rs, rowNum) -> new Product(
                    rs.getLong("id"),
                    rs.getString("name"),
                    rs.getInt("price"),
                    rs.getString("image_url")
                ),
                id
            )
            .stream()
            .findFirst();
```

fyi; JdbcClient queryForObject 내부에서 수행되는 코드
```java
    public static <T> T requiredSingleResult(@Nullable Collection<T> results) throws IncorrectResultSizeDataAccessException {
        if (CollectionUtils.isEmpty(results)) { // 🔥🔥🔥 데이터가 null 인경우, 에러 발생
            throw new EmptyResultDataAccessException(1);
        } else if (results.size() > 1) {
            throw new IncorrectResultSizeDataAccessException(1, results.size());
        } else {
            return results.iterator().next();
        }
    }
```

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/dao/ProductRepository.java
> +    Optional<Product> findById(Long id);
반환값을 Optional 로 하여 팀원들에게 해당 객체가 nullable 하다는 것을 인지할 수 있어서 좋습니다👍

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +    private final ProductRepository productRepository;
인터페이스와 구현체를 통해 구현체 변경 시에 유연하게 대응할 수 있어서 좋습니다👍

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +    }
[반영하지 않으셔도 좋습니다😀]

매개변수의 이름과 일치하는 빈 이름으로 주입할 수 있습니다. 예를 들어, 다음과 같이 매개변수 이름을 지정하면, 해당 이름과 일치하는 빈이 주입됩니다. MemoryProductRepository 에도 @Repository 를 추가하여 빈으로 사용되어야 하는 상황이라면 이렇게 bean 을 주입시킬 수 있을 것 같습니다.

```suggestion
    public ProductService(ProductRepository productDao) {
        this.productRepository = productDao;
    }
```

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +        }
findById 에서 정상적으로 optional 반환이 된다면 코드를 이렇게도 변경할 수 있을 것 같습니다😀
1. 이미 존재하는지 데이터 체크
2. 존재하면 예외 반환 / 존재하지 않으면 저장
```suggestion
        productRepository.findById(request.id())
            .ifPresent(product -> {
                throw new IllegalArgumentException("해당 상품은 이미 존재하고 있습니다.");
            });

        return new ProductResponse(productRepository.save(new Product(request)));
```

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/dto/ProductRequest.java
> +                             String imageUrl) { }
현재는 DB 에서 채번한 값을 가지고 Product 의 PK 가 정해지고 있어서 id 필드는 제거해도 될 것 같습니다😀

만약 DB 를 사용하지 않는다면 클라이언트로부터 PK 를 생성하는 것보다는 서버쪽에서 AtonomicLong 등의 threadsafe 한 PK 생성기롤 만들어보는 것도 좋을 것 같아요!

fyi; [AtomicLong 관련 문서](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/package-summary.html)
```suggestion
public record ProductRequest(String name,
                             int price,
                             String imageUrl) { }
```

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/application/ProductService.java
> +            return request.id();
ProductRequest 의 id 필드가 제거된다면 해당 로직도 제거될 수 있겠군요😎
```suggestion
```

2024-06-29 02:50 UTC, hocaron commented on src/main/resources/script/schema.sql
> +                         price INT NOT NULL CHECK (price >= 0),
price 가 음수인 경우에 대한 제약 사항 좋습니다👍

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/dto/ProductRequest.java
> +                             int price,
DB 단에서 price 에 대한 음수 체크 해주신 부분 너무 좋았습니다👍

validation DB 요청 전에 request 생성자에서도 하여 DB 부하를 줄일 수 있을 것 같아요😀

```java
    public ProductRequest {
        if (price <= 0) {
            throw new IllegalArgumentException("Price must be positive.");
        }
    }
```

2024-06-29 02:50 UTC, hocaron commented on src/test/java/gift/application/ProductServiceTest.java
> +    }
서비스 테스트 너무 좋습니다👍

`assertThatThrownBy` 를 사용하여 실패하는 테스트 케이스를 추가해볼 수도 있을 것 같습니다😎

2024-06-29 02:50 UTC, hocaron commented on src/main/java/gift/dao/ProductDao.java
> +    }
현재 ID 가 DB 에서 채번한 값을 사용하고 있어서 파라미터로 들어온 Product 의 id 값과 실제로 DB 에 저장되는 id 가 다른 경우가 있는 것 같아요.

`GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();` 를 사용하여 실제 저장된 id 값 또는 객체를 클라이언트에세 반환하면 좋을 것 같아요!

2024-06-29 16:50 UTC, hocaron requested changes
수환님, 안녕하세요👋
이번 step 을 함께할 호선우입니다!

요구사항 및 로직에 대한 validation 처리가 완벽한 것 같습니다. 코드의 흐름도 읽기가 편해서 리뷰하기 편했습니다.👍
함께 작업하는 입장에서 반영하면 좋을 리뷰를 남겼는데, 궁금한 점이나 의문이 생기면 편하게 코멘트나 DM 주세요.

2024-07-01 01:34 UTC, HSHwan commented
질문에 대한 답변을 잘해주셔서 궁금증을 해결할 수 있었습니다.
그리고 특정 부분에서 간과하고 있던 부분을 피드백해주셔서 정말 감사합니다!
앞으로도 잘 부탁드립니다!

2024-07-01 05:29 UTC, hocaron approved these changes
고생 많으셨습니다👍

2024-07-01 09:52 UTC, merged