경북대 BE_박준석_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #112
Opened 2024-06-27 12:23 UTC by Lucerna00

스프링이 익숙하지 않아 실습 강의 토대로 model과 controller만을 만들어 진행하였습니다.

Q. 스프링에는 Controller, Service, Repository, Domain 계층이 있는 것으로 아는데, 지금은 이러한 계층 구조로 개발하지 않아도 되는 지, 그리고 앞으로의 강의나 과제에서 다룰 내용인지 궁금합니다.

Q. 이번 1단계에서 model에 해당하는 Product를 class로 작성하는 것과 record로 작성하는 것이 차이가 있는지, 있다면 어느 것이 더  적합한지 궁금합니다.

2024-06-29 17:44 UTC, gongdongho12 requested changes
안녕하세요 이번에 BE멘토로 함께하게 될 강동호입니다
과제 목표치를 달성하시느라 고생 많으셨습니다

> Q. 스프링에는 Controller, Service, Repository, Domain 계층이 있는 것으로 아는데, 지금은 이러한 계층 구조로 개발하지 않아도 되는 지, 그리고 앞으로의 강의나 과제에서 다룰 내용인지 궁금합니다.

지금처럼 간단한 구조일 때는 큰 차이를 느끼지 못하겠지만, 나중에 로그인을 구현하려면 인증 서비스와 멤버 서비스를 같이 사용하는 부분도 존재할 겁니다
이때, 멤버 컨트롤러에서 사용되는 멤버 서비스가 있다면 두번 동작을 구현하지 않아도 되겠죠?
그래서 동작과 실제 엔드포인트 연결, 레포지토리 등으로 레이어를 구성해서 개발하는 방식을 사용하고 있습니다
직접 프로젝트 진행하면서 얻어가시는게 있으실거에요 💪🏼 

> Q. 이번 1단계에서 model에 해당하는 Product를 class로 작성하는 것과 record로 작성하는 것이 차이가 있는지, 있다면 어느 것이 더 적합한지 궁금합니다.

record는 Java 14에서 생긴 compact 클래스인데요, 이것도 클래스이긴 합니다!
다만 나중에 DTO간에 Join을 걸어준다던가 각종 메서드가 포함된다면 좀 더 세부적으로 사용할 수 있는 class가 구현하기에 용이하겠죠?
관련해서는 record 제약사항에 대해 문서 찾아보면 좋을 것 같습니다

> Q. 나름대로 service, repository 계층을 만들어 진행하였는데, 개선해야 할 점이 궁금합니다.
리뷰에 남겨드렸지만 service에서 repository를 호출하는 부분은 좋지만 repository가 실제 DB에 업데이트 하지 않고 있습니다
동작을 잘 하고 있다고 보여졌을 것 같은데 실제 연동 관련해서 테스트코드 작성해보시면 확연히 이해하실 수 있을 것 같습니다

> Q. 테이블 먼저 생성하고자 테이블 생성 메서드에 @PostConstruct를 추가하였습니다. 혹시 또 다른 방법이 있는지 궁금합니다.

코드 사용부에 답변드렸습니다

> Q. 현재는 record로 만든 DTO가 모든 과정을 수행하고 있습니다. 좋지 않은 방법인 거 같은데, product라는 클래스를 만들어 어디에 어떻게 적용해야 할 지 잘 모르겠습니다.

현재는 record로 만든 범위를 그대로 사용하고 있어서 큰 문제는 없습니다.
다만 클래스에 상속받아서 생성일 수정일 등을 구현한다던가 했을 때 record의 제약이 생긴다면 그때 변경을 고려해보면 좋을 것 같아요
위에 말씀드린 것처럼 제약사항을 이해하고 사용하신다면 현재 사용에는 이슈가 없습니다

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/api/products")
api와 admin을 도메인으로 분리하신 부분 👍🏼

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    }
ResponseEntity를 사용하는 곳과 아닌 곳이 있는데요
쓸거면 다 같이 사용하고 사용하지 않을거면 다 빼는게 좋지 않을까요?

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/java/gift/repository/H2Repository.java
> +    }
schema.sql과 data.sql이 있을 때 자동으로 인식될 수 있도록 제공하고 있습니다
이렇게 문자열로 쿼리 관리하지 않아도 되는데 [문서](https://engineerinsight.tistory.com/77#%E2%9C%94%C2%A0schema.sql%2C%C2%A0data.sql%20%ED%8C%8C%EC%9D%BC%EC%9D%98%20%EC%8B%A4%ED%96%89%20%EC%88%9C%EC%84%9C-1) 한번 확인해 보시면 좋을 것 같습니다

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/java/gift/repository/MemoryRepository.java
> +    }
정상적으로 처리된 것과 처리되지 않음을 구분하시는 방법이 어떻게 될까요?
위와 같이 구성하게 되면 실제 DB가 아닌 단순 로컬 메모리에서만 사라지지 않을까요?

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/resources/static/js/main.js
> +}
기능 단위로 구분해둔 js 코드 👍🏼

2024-06-29 17:44 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    }
정상일땐 OK 아닐땐 BAD_REQUEST를 주고 있는 방식이 전부 공통적인데 ControllerAdvice를 찾아보시면 좋을 것 같습니다

2024-06-29 17:50 UTC, gongdongho12 commented on src/main/java/gift/repository/H2Repository.java
> +    }
SimpleJdbcInsert 같은 기능을 사용해보시면 좋을 것 같습니다

2024-06-29 17:53 UTC, gongdongho12 commented on src/main/java/gift/repository/H2Repository.java
> +    }
공통 Mapper 사용 👍🏼

2024-06-29 17:54 UTC, gongdongho12 commented on src/main/java/gift/repository/H2Repository.java
> +    }
ProductDTO에 id도 포함되어 있는데 id를 따로 구분하지 않아도 되지 않았을까요?

2024-06-30 16:36 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/api/products")
감사합니다 😊

2024-06-30 16:36 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +    }
모든 곳에 ResponseEntity를 사용하도록 수정하였습니다

2024-06-30 16:38 UTC, Lucerna00 commented on src/main/java/gift/repository/H2Repository.java
> +    }
알려주신 덕분에 schema.sql로 테이블 생성을 대체하였고 data.sql로 더미 데이터를 추가하였습니다

2024-06-30 16:39 UTC, Lucerna00 commented on src/main/java/gift/repository/MemoryRepository.java
> +    }
네, 사용하지 않는 MemoryRepository와 service에서의 코드를 삭제하였습니다

2024-06-30 16:39 UTC, Lucerna00 commented on src/main/resources/static/js/main.js
> +}
감사합니다!

2024-06-30 16:41 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +    }
하나의 controller만 에러 처리가 필요하기에 ExceptionHandler를 사용해 보았습니다

2024-06-30 16:42 UTC, Lucerna00 commented on src/main/java/gift/repository/H2Repository.java
> +    }
insert문을 SimpleJdbcInsert로 수정하였습니다

2024-06-30 16:42 UTC, Lucerna00 commented on src/main/java/gift/repository/H2Repository.java
> +    }
감사합니다 😁

2024-06-30 16:53 UTC, Lucerna00 commented on src/main/java/gift/repository/H2Repository.java
> +    }
pathvalue인 id와 name, price, imageUrl이 담긴 DTO로 service에서 새로운 DTO를 만들어 repository에 넘기는 방식으로 수정하였습니다

이 과정을 수행하면서 한 가지 의문점이 들었는데,
데이터 추가나 업데이트 시 확인을 위해 무엇을 어떻게 반환하는지 궁금합니다
(저는 추가나 업데이트가 된 객체를 service에서 반환하도록 만들었습니다 (repository는 void))

2024-07-01 13:18 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +}
:+1

2024-07-01 13:18 UTC, gongdongho12 commented on src/main/java/gift/repository/H2Repository.java
> +    }
에러가 발생하면 exception을 주기도 하고, 없는데이터 변경은 boolean 으로 리턴하기도 하는데 어떤 상황이냐에 따라 처리를 다르게 할 것 같습니다

2024-07-01 13:19 UTC, gongdongho12 approved these changes
고생많으셨습니다 👍🏼

2024-07-01 13:19 UTC, merged