경북대 BE_유승욱_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #114
Opened 2024-06-27 13:04 UTC by yso8296

코드 작성시 어려웠던 점

강의에서 강사님께 지금까지 배운 것만을 토대로 구현하시라고 하셔서 평소 사용하던 mvc 패턴을 사용하지 않고 구현을 해보았는데, mvc 패턴에 익숙해지다보니 구현하는데 어색함과 어려움이 있었던 것 같습니다.

리뷰 받고싶은 부분

모든 상품 조회 url을 "/api/products"라고 작성했는데, 여러 개의 데이터를 조회하는 경우 products처럼 복수형으로 작성하면 되는지 궁금합니다.

DTO를 선언할 때 record를 이용해보았는데, record의 필요성에 대해 아직 와닿지 않는 것 같습니다. record를 사용하는 가장 큰 이유가 보일러 플레이트 코드를 제거하기 위함인 것 같은데 이는 롬복으로 대체 가능하기 때문에 큰 차이를 못 느끼겠는데 record를 사용하면 좋은게 맞는지 궁금합니다.

productRequstDTO 안에 toEntity 메서드, Product 안에 toDTO 메서드를 만들어서 서로간의 변환이 용이하게 했는데 이렇게 해도 되는지 궁금합니다. 혹은 더 좋은 방법이 있는지 궁금합니다.

전체적인 코드에 대한 평가를 받고싶습니다.

2024-06-30 15:25 UTC, khj68 commented
안녕하세요, 앞으로 리뷰를 담당할 준 멘토입니다.
전반적으로 깔끔하게 배운 내용을 바탕으로 코드를 잘 짜주셨습니다.
구체적으로 받고 싶은 내용도 자세히 적어주셔서 감사합니다.
앞으로 잘 부탁드립니다.

2024-06-30 15:29 UTC, khj68 requested changes
안녕하세요, 앞으로 리뷰를 담당할 준 멘토입니다.
전반적으로 깔끔하게 배운 내용을 바탕으로 코드를 잘 짜주셨습니다.
구체적으로 받고 싶은 내용도 자세히 적어주셔서 감사합니다.
앞으로 잘 부탁드립니다.

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +    @Autowired
@Autowired는 실무에서 지양하는 편입니다.
테스트 작성, 의존 불변성 보장 어려움, 명시적인 관리, 순환 의존성 컴파일 시 감지 불가 등 다양한 부분에서 단점을 가지고 있습니다.
생성자 주입을 통해 의존성을 관리하는 방법을 살펴보시고 습관으로 가져가시는 것을 추천드리겠습니다 :)

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/api/products")
list 반환에 대해서 복수형으로 표현하는 것은 RESTful API 원칙을 지키는 좋은 명명법입니다 :)

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +        return product.toDTO();
Dao 부분에서 반환형을 DTO로 가져가는 것을 추천드립니다.
컨트롤러에서는 최소한의 로직을 가져가는 것이 좋습니다.
엔티티를 컨트롤러까지 가져올 경우 추후 트래픽, 트랜잭션 등 엔티티와 관련된 문제가 발생할 가능성이 있습니다.

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/model/ProductResponse.java
> +public record ProductResponse(Long id, String name, int price, String imageUrl) {
record 객체의 경우 기본적으로 불변성을 보장하기 때문에 단순히 보일러플레이트 코드를 줄이는 것 외에도 일관성 있는 코드를 제공합니다.
또한 프로젝트 규모가 작을 때에는 단순히 롬복이 편해보일 수 있지만, 협업자가 많아지고 프로젝트 규모가 커질수록 무의미한 어노테이션이 덕지덕지 붙을 가능성이 있습니다.
불변 객체일 떄에는 record를 적극적으로 활용해주시는 것을 추천드립니다.

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/model/ProductDao.java
> +        if (!store.containsKey(id)) {
기본적인 예외처리 좋습니다.

2024-06-30 15:29 UTC, khj68 commented on src/main/java/gift/model/ProductDao.java
> +    public void delete(Long id) {
update, save, delete 등 write 로직에는 @Transactional 을 달아주는 습관도 좋습니다.
 (현재 강의 진도에 해당하지는 않는 것 같습니다.)

2024-06-30 15:47 UTC, khj68 commented
> productRequstDTO 안에 toEntity 메서드, Product 안에 toDTO 메서드를 만들어서 서로간의 변환이 용이하게 했는데 이렇게 해도 되는지 궁금합니다. 혹은 더 좋은 방법이 있는지 궁금합니다.

패키지 구조가 복잡하지 않은 현재 상황에서는 적합한 방법입니다.
추후 패키지 구조가 복잡해져, 올바른 방향으로의 참조가 일어나지 않을 때에는 고민이 필요한 부분입니다.

예를 들어 entity에서는 controller의 response나 request관련 dto를 알 필요가 없겠지요?

2024-07-01 00:49 UTC, yso8296 commented on src/main/java/gift/controller/ProductController.java
> +        return product.toDTO();
피드백 감사합니다! 멘토님 말씀은 controller에서는 아예 엔티티가 노출되지 않게 DTO만 이용해서 처리해야된다고 이해했는데 제가 이해한게 맞을까요?

2024-07-01 06:41 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +        return product.toDTO();
네 최대한 dto로 클래스 간 이동을 해주는 것을 추천드립니다 :)

2024-07-01 10:13 UTC, yso8296 commented on src/main/java/gift/controller/ProductController.java
> +        return product.toDTO();
감사합니다!

2024-07-02 03:07 UTC, merged