충남대 BE_송민주_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #116
Opened 2024-06-27 13:32 UTC by mingjuu

2024-06-29 09:45 UTC, asebn1 requested changes
3단계도 고생 많으셨습니다
1, 2단계와 겹치는 리뷰내용은 생략했습니다 :)

2024-06-29 09:45 UTC, asebn1 commented on src/main/java/gift/config/DatabaseConfig.java
> +    }
h2 데이터베이스 빈 등록 후 `JdbcTemplate`에서 사용해 주었군요 👍

2024-06-29 09:45 UTC, asebn1 commented on src/main/java/gift/repository/ProductRepository.java
> +    }
생성자 의존주입을 사용해 주셨네요 👍 
또 어떤 의존주입 방법이 있을까요?

2024-06-29 09:45 UTC, asebn1 commented on src/main/java/gift/config/DatabaseInitializer.java
> +}
`@PostConstruct`도 사용해주셨군요! 👍 👍

2024-06-29 09:45 UTC, asebn1 commented on src/main/java/gift/repository/ProductRepository.java
> +    }
잘 작성해주셨네요~
해당 기능의 테스트 코드를 구현해보는건 어떨까요?

2024-07-03 17:25 UTC, asebn1 approved these changes
민주님 안녕하세요~
과제 진행하시는데 어려움이 느껴지실까요? 지금까지 진행된 내용까지 난이도가 어땠는지 궁금하네요
이전에 리뷰드렸던 코멘트 내용에도 답변을 주시면 서로 티키타카 하며 성장에 도움이 될 것 같아요~
1주차 과제는 우선 현재까지 진행된 내용으로 이만 머지하겠습니다.
추가 리팩토링 부분은 2주차 과제에 함께 올려주세요 
남은 기간도 화이팅해요! 🔥🔥🔥

2024-07-03 17:27 UTC, asebn1 requested changes
머지하려고 보니 PR 브랜치가 잘못 바라보고 있어요 😱
수정해주시면 머지진행하겠습니다~

2024-07-04 00:21 UTC, mingjuu commented
> 머지하려고 보니 PR 브랜치가 잘못 바라보고 있어요 😱 수정해주시면 머지진행하겠습니다~
-- 수정하겠습니다! 감사합니다. (이전에 주신 피드백을 바탕으로 이전 과제를 수정하여 commit을 남겼습니다! )

2024-07-05 05:43 UTC, asebn1 approved these changes
확인했습니다~ 1주차는 이만 머지할게요!

2024-07-05 05:44 UTC, merged