경북대 BE_도기헌_1주차 과제 (1단계, 2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #118
Opened 2024-06-27 13:54 UTC by Dockerel

# 1단계
### 코드 작성시 어려웠던 점
프레임워크의 사용 보다도 여전히 구조를 짜는 것이 더 어려웠던 것 같습니다. 어떤식으로 객체를 구성할지, post로는 어떤 형태의 객체를 받아올지, id 처리를 어떤 식으로 해야할지 등에 대한 고민이 많았습니다.
### 리뷰 받고싶은 부분
1. post 요청 시 id를 제외한 ProductForm 형태로 받아 새로운 Product 객체를 갱신시켜 추가하는 방식으로 구현하였습니다. 왜냐하면 유저가 all product에서 특정 product를 선택하면 서버에서는 해당 product의 id를 바탕으로 db에서 찾아 product를 리턴해주어야 한다고 생각했기 때문입니다. 하지만 아무리봐도 product에 대한 모델이 2개나 있다는 것이 여전히 비효율적이게 보입니다. 이런 방식으로 구현을 해주는것이 최선일까요?
2. put 요청 시 현재는 만약 name 필드의 값만 바꾸고 싶어도 다음과 같이 모든 필드를 작성하여 전송합니다.
```
{
    "name": "abc",
    "price": 123,
    "imageUrl": "www.test.com",
}
```
혹시 name 필드만 작성하여 부분 업데이트를 처리할 수 있을까요? 제가 찾아본 방식으로는 if 분기로 필드에 대해 다 처리하는 방식으로 구현하는 방식이 있었는데 다른 방식이 있는지 궁금합니다.
3. 그 외에 코드의 전반적인 흐름이나 구조에 대해 리뷰를 받고 싶습니다.
# 2단계
### 코드 작성시 어려웠던 점
본격적으로 공식문서와 구글을 찾아가며 하게 된 과제인 것 같습니다. 그리고 thymeleaf로 프론트와 백을 섞으며 코드가 잘 동작하는것도 고려해야 하고 구조도 깔끔하게 유지하려하다보니 굉장히 헷갈렸고 처음부터 구조적으로 잘 설계해야 함을 다시한번 느꼈다.
### 리뷰 받고싶은 부분
전체적으로 수정하거나 개선할 부분에 대해 리뷰를 받고 싶습니다.

사실 백으로만 처리의 한계를 느껴 js를 같이 사용하여 구현을 했는데 백엔드 트랙인 만큼 백으로만 구현이 가능한 방법이 있는지 그리고 실제로도 thymeleaf를 사용하여 admin page를 구현하는지가 궁금합니다.
# 3단계
### 코드 작성시 어려웠던 점
수업 시간에 배운 부분을 굉장히 많이 벗어나서 엄청난 범위의 스프링을 공부하고 겨우 해결하였다. 그래도 최대한 구조적으로 잘 설계하려고 신경을 처음부터 써서 설계하여 그런지 마지막에 인터페이스에 대해 구현을 하기만 해도 전체적으로 잘 구현되어서 뿌듯했다.
### 리뷰 받고싶은 부분
최대한 객체지향적으로 코드를 구성해보려 했는데 잘 설계 되었는지가 궁금합니다. 그 외에 전반적으로 수정하거나 개선할 부분이 있을지 리뷰를 받고 싶습니다.

감사합니다.

2024-06-29 17:16 UTC, gongdongho12 requested changes
안녕하세요 저는 BE 멘토 강동호입니다
앞으로 좋은 코드 만들어가봐요!

테스트까지 작성해주시구 고생하셨습니다

> 1. post 요청 시 id를 제외한 ProductForm 형태로 받아 새로운 Product 객체를 갱신시켜 추가하는 방식으로 구현하였습니다. 왜냐하면 유저가 all product에서 특정 product를 선택하면 서버에서는 해당 product의 id를 바탕으로 db에서 찾아 product를 리턴해주어야 한다고 생각했기 때문입니다. 하지만 아무리봐도 product에 대한 모델이 2개나 있다는 것이 여전히 비효율적이게 보입니다. 이런 방식으로 구현을 해주는것이 최선일까요?

지금처럼 구조가 간단하다면 크게 차이가 나지 않지만 엔티티에 join이나 각종 기능들이 포함되게 되면 toString에 연결된 데이터들이 고구마줄기처럼 나올 수 있고, 엔티티에 있는 password가 노출되면 안되는데 노출될 수 있는 상황이 생길 수 있습니다
그래서 되도록이면 실제 처리하는 객체인 DAO와 전송하는 개체 DTO를 구분해서 사용하고 있습니다
만약 이 방식이 조금 번거롭다면 DTO와 DAO간에 전환을 메서드로 구현해 두는 것도 손쉬운 방법이지 않을까 생각됩니다

> 2. put 요청 시 현재는 만약 name 필드의 값만 바꾸고 싶어도 다음과 같이 모든 필드를 작성하여 전송합니다. 혹시 name 필드만 작성하여 부분 업데이트를 처리할 수 있을까요? 제가 찾아본 방식으로는 if 분기로 필드에 대해 다 처리하는 방식으로 구현하는 방식이 있었는데 다른 방식이 있는지 궁금합니다.

이부분은 프론트쪽 코드이다 보니 현재는 모든 값을 미리 세팅해서 변경하고 있는데요
javascript를 활용해서 변경을 시킨 칼럼들만 json으로 object를 만들어서 전달하고, 보내진 칼럼만 업데이트 시킬 수 있도록 json의 키를 하나씩 가져와 필요한 메서드를 실행하는 방법으로 적용할 수 있습니다
ex) 상품의 이름만 수정하면 실제 웹 동작은 name만 업데이트 될 거구 `{ "product_name": "변경" }` 형식으로 되면 스프링에선 이 json의 key만 뽑아서 DAO에서 변경하고 트랜잭션을 반영하게 합니다

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/SpringConfig.java
> +    }
생성자로 주입이면 Autowired가 필요한지 한번 확인해보면 좋을 것 같습니다

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/SpringConfig.java
> +    }
ProductRepository에 @Repository를 달지 않고 datasource를 직접 넣어주신 이유가 있을까요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/SpringConfig.java
> +    }
PostConstruct로 실행시에 init을 하는데요, 만약 다른 config의 @PostConstruct로 warmup 기능을 만든다면
db를 먼저 조회하는 경우에 문제가 생길 수 있지 않을까요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/controller/AdminController.java
> +    @GetMapping("")
비었으면 `("")` 제거하면 어떨까요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/model/Product.java
> +    }
DB에 적재되는 아이디는 항상 0으로만 만들 수 있는데 생성할때 아이디를 기입하면 더 편리하지 않을까요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/model/ProductForm.java
> +    }
이부분은 전체 코멘트에 답변을 남겼는데요
질문의 의도가 맞는지 한번 더 답변주시면 좋을 것 같아요!

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        jdbcInsert.withTableName("product").usingGeneratedKeyColumns("id");
SimpleJdbcInsert로 깔끔하게 반영해주셨네요

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        return result.stream().findFirst().orElse(null);
nullable 데이터를 명시해주기 위해 Optional 타입을 사용해보면 어떨까요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +    }
공통 mapper의 분리 👍🏼

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/java/gift/repository/MemoryProductRepository.java
> +        product.setId(++id);
++id로는 DB가 mysql 처럼 실제 적재되는 저장소일 경우에 항상 다시 0부터 시작하게 되면 덮어씨워질 수 있을 것 같은데
db의 auto_increment 사용하지 않는 이유가 있으신가요?

2024-06-29 17:16 UTC, gongdongho12 commented on src/test/java/gift/repository/MemoryProductRepositoryTest.java
> +    }
테스트 작성해서 기본적인 에러 검증은 가능할 것 같아요
다만 오류가 날 수 있는 db의 칼럼 사이즈 초과 등의 예시도 assertThrow 등으로 검증해주면 실제 오류상황을 더 정확하게 검증할 수 있을 것 같아요

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/resources/templates/adminProductDetail.html
> +      };
이 javascript를 그대로 만들지 말고 form에서 이벤트리스너를 달아서 변경된 input의 name만 json으로 만들어주면 첫번째 질문은 해소 가능할 것 같습니다 👍🏼

2024-06-29 17:16 UTC, gongdongho12 commented on src/main/resources/templates/adminProductDetail.html
> +      })
fetch를 사용할 때 `http://localhost:8080/api`의 주소는 거의 고정으로 실행될것 같은데요
나중에 배포될 때에는 전부 url을 바꿔줘야 할 것 같은데 공통 변수로 만들어두면 좋지 않을까요?

2024-07-01 10:10 UTC, Dockerel commented on src/main/java/gift/SpringConfig.java
> +    }
생성자가 하나이니까 @Autowired가 생략될 수 있다는 말씀이신 것 같아 @Autowired를 생략함으로써 해결하였습니다!

2024-07-01 10:16 UTC, Dockerel commented on src/main/java/gift/controller/AdminController.java
> +    @GetMapping("")
빈 route들에 대해 모두 수정하였습니다!

2024-07-01 10:17 UTC, Dockerel commented on src/main/java/gift/controller/ErrorController.java
> +}
감사합니다 ☺️

2024-07-01 10:21 UTC, Dockerel commented on src/main/java/gift/controller/ProductController.java
> +    }
ControllerAdvice 적용 완료했습니다. 다만 각 코드마다
```
@GetMapping("/{id}")
    public ResponseEntity<ProductDAO> getProduct(@PathVariable("id") Long id) {
        ProductDAO result = repository.findById(id);
        if (result == null) throw new ResourceNotFoundException("Product not found with id: " + id);
        return ResponseEntity.status(HttpStatus.OK).body(result);
    }
```
위와 같은 방식으로 적용하였는데 이전보다 깔끔해졌다는 느낌이 크게 받지 못하였습니다. 혹시 제가 ControllerAdvice를 잘못 사용하고 있는지 더 나은 적용 방식이 있는지 궁금합니다.

2024-07-01 11:40 UTC, Dockerel commented on src/main/java/gift/model/Product.java
> +    }
```
public ProductDAO(Long id) {
        this.id = id;
    }
```
말씀해주신 대로 위 생성자를 추가하여
```
ProductDAO product = ProductUtility.productDTOToDAO(new ProductDAO((Long) key), productDTO);
```
repository 코드 수정 개선하였습니다!

2024-07-01 11:42 UTC, Dockerel commented on src/main/java/gift/model/ProductForm.java
> +    }
넵! 답변해주신 코멘트와 실시간 강의에서 배운 PUT과 PATCH의 차이점을 바탕으로 해당 코드에서는 전체 필드를 넘겨주는 것이 맞고 말씀해주신 방법으로도 나중에 구현해보도록 하겠습니다. 감사합니다!

2024-07-01 11:42 UTC, Dockerel commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        jdbcInsert.withTableName("product").usingGeneratedKeyColumns("id");
감사합니다! 😊

2024-07-01 11:44 UTC, Dockerel commented on src/main/java/gift/repository/JdbcProductRepository.java
> +        return result.stream().findFirst().orElse(null);
Optional로 개선해 보는 것을 추천해주셨는데 findById 메서드의 반환값을 Optional로 변경하고 리팩터링을 실시하다보니 점점 코드가 산으로 가는 것 같아 Optional을 적용하지 못하였습니다. NullPointerException을 방지하지 위해 Optional을 사용한다는 것은 이해하였습니다. 그런데 제가 작성한 코드의 경우 null이 나올만한 케이스를 다 분기로 잡아 처리해주고 있는데 혹시 Optional을 사용하는 다른 이유가 있는지 궁금합니다!

2024-07-01 11:44 UTC, Dockerel commented on src/main/java/gift/repository/JdbcProductRepository.java
> +    }
👍👍👍

2024-07-01 11:46 UTC, Dockerel commented on src/main/java/gift/repository/MemoryProductRepository.java
> +        product.setId(++id);
해당 코드는 로컬환경에서 HashMap으로 구현한 db라 auto_increment를 사용한 쿼리가 적용되지 않아 임의로 만든 id 값입니다! 혹시 해당 로컬 환경에서도 auto_increment를 사용하는 방법이 있을까요?

2024-07-01 11:47 UTC, Dockerel commented on src/test/java/gift/repository/MemoryProductRepositoryTest.java
> +    }
넵! name field에 대해 최대 글자수를 넘는 이름을 추가하는 테스트 케이스를 추가하여 검증해보았습니다!

2024-07-01 11:54 UTC, Dockerel commented on src/main/resources/templates/adminProductDetail.html
> +      };
아하 넵!
```javascript
form.addEventListener('input', (e) => {
    const e = e.target;
    if (target.name) {
        changedFields[target.name] = target.value;
    }
});
```
위와 같은 방식으로 구현해보겠습니다 👍

2024-07-01 11:56 UTC, Dockerel commented on src/main/resources/templates/adminProductDetail.html
> +      })
넵! static/js 디렉터리에 var.js로 관리해보려 했는데 결국 오류를 해결하지 못해 각 js 파일에 공통 변수를 만듦으로써 해결하였습니다!

2024-07-01 12:45 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    }
컨트롤러에서 레포지토리를 바로 쓰지말고 서비스 하나 구성해서 아래같은 메서드를 전부 대체하면 에러처리는 자동으로 ControllerAdvice에서 하지 않을까요?
```java
ProductDAO result = repository.findById(id);
if (result == null) throw new ResourceNotFoundException("Product not found with id: " + id);
return result
```

2024-07-01 12:46 UTC, gongdongho12 approved these changes
조금 더 손볼 부분이 있지만 차차 고쳐나가봅시다
고생하셨습니다

2024-07-01 13:16 UTC, merged