부산대 BE_진서현 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #130
Opened 2024-06-27 19:03 UTC by jinseohyun1228

2024-06-29 03:14 UTC, hocaron requested changes
서현님, 안녕하세요👋
이번 step 을 함께할 호선우입니다!

값 로직 마다 적절한 http status code 가 들어가있어서, 리뷰하는데 도움이 많이 되었습니다👍
함께 작업하는 입장에서 반영하면 좋을 리뷰를 남겼는데, 궁금한 점이나 의문이 생기면 편하게 코멘트나 DM 주세요.

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/MainController.java
> +        return "main";
healthCheck 를 위한 API 좋은 것 같습니다👍

/heath 로 시작하는 api path 명도 좋을 것 같아요😀

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/controller/ProductController.java
> +    @GetMapping("/product")
RESTful 하게 많은 리소스들 중에서 해당 id 값을 찾는 다는 의미로 아래 PATH 로 변경해보는 것은 어떨까요?!
```suggestion
@GetMapping("/products/{id}")
```

fyi; [RESTful API 관련 문서](https://meetup.nhncloud.com/posts/92)

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/controller/ProductController.java
> +    @PostMapping("/product")
위와 마찬가지로 복수의 path 도 좋을 것 같습니다!

```suggestion
    @PostMapping("/products")
```

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/controller/ProductController.java
> +        System.out.println("producstRepository.get(id) = " + producstRepository.get(id));
디버깅을 위한 코드로 보여 제거해도 좋을 것 같습니다😎

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/controller/ProductController.java
> +    private final AtomicLong idGenerator = new AtomicLong();
ThreadSafe 한 PK 생성기 사용 좋습니다👍

Product 가 외부로 부터 ID 값을 받는 것보다는 Product 내부에 생성기를 두는 것은 어떨가요?!

1.	캡슐화 강화: ID 생성 로직을 Product 클래스 내부에 두면, 객체 생성 시 ID 관리가 외부로 노출되지 않으므로 데이터 무결성을 유지할 수 있습니다.
2.	일관성 유지: 객체가 생성될 때마다 고유한 ID가 자동으로 할당되므로, 일관된 ID 정책을 유지할 수 있습니다.
3.	단순화: 외부 코드에서 ID를 관리할 필요가 없으므로, 객체 생성 과정이 단순해집니다.

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/dto/ProductRequest.java
> +        Objects.requireNonNull(imageUrl);
validation 체크 좋습니다💯

2024-06-29 03:14 UTC, hocaron commented on src/main/java/gift/main/controller/ProductController.java
> +    private final Map<Long, Product> producstRepository = new HashMap<>();
[지금 반영하지 않으셔도 됩니다😀]
동시 요청 하는 경우를 위한, ConcurrentHashMap 을 사용할 수도 있을 것 같아요!

fyi; [hashmap 스레드 관련 글](https://stackoverflow.com/questions/2688629/is-a-hashmap-thread-safe-for-different-keys)

2024-07-03 03:18 UTC, hocaron commented
@jinseohyun1228 서현님, 안녕하세요! 리뷰가 분산되어서 4단계로 모두 머지 후에 리뷰 반영이 필요한 부분이 있다면 추가로 작업하는 방향이 좋을 것 같습니다😀

4단계에서 반영해주시거나 2주차 과제에 리뷰 반영 요청드립니다👍

2024-07-03 03:19 UTC, merged

2024-07-05 16:01 UTC, jinseohyun1228 commented on src/main/java/gift/main/MainController.java
> +        return "main";
제가 깃으로 리뷰 받는 것이 처음이라... 이걸 확인을 제대로 못한것같습니다.. !!

`healthCheck `가 무엇인지 몰랐는데, 검색을 통해 컨테이너 내부의 프로세스가 정상적으로 동작하는지 확인하는 것이군요..!!

리뷰를 받으면서 좋은 지식들을 많이 쌓아가는 것 같습니다..!

`healthCheck`를 하고 싶다면 해당 페이지를 따로 두는 것이 좋을까요?
* 2주차 3단계를 끝낸 지금 로그인 후 "/"페이지로 이동하여 홈화면으로 사용중이라  질문드립니다