충남대BE_신성희_1주차 과제
kakao-tech-campus-2nd-step2/spring-gift-product pull request #131
Opened 2024-06-27 19:15 UTC by Shsin9797

[1주차] 클론코딩 주차별 과제
----------------
[1단계]
어려웠던점: 
1)롬복을 사용하지 말라고 말씀하셨던 것 같아서, 쓰지 않았고, 장황해졌습니다.. 
2)스트림 사용에 능숙하지 않아서,, 코드가 길어졌습니다.. 

중점리뷰:
1) 결과값을 List 형태가 아니라 Map<>형태로 반환해도 괜찮은지 궁금합니다.  

----------------
[2단계]
어려웠던점:
 
중점리뷰: 

----------------
[3단계]
어려웠던점:
 
중점리뷰:

2024-06-29 10:27 UTC, asebn1 requested changes
안녕하세요 성희님~
6주간 코드리뷰어를 맡은 공재호입니다. 잘부탁드려요.
코드를 보니 service, repository 계층 사용 및 DTO 사용까지 꽤 학습하신 내용이 있는 것 같아요👍 
리뷰 확인해주시고 궁금한 점 코멘트로 남겨주세요 (DM도 좋아요)

---
3단계는 아직 미완성인 것 같아 현재까지 구현된 내용으로 리뷰 했습니다.

> 1. 롬복을 사용하지 말라고 말씀하셨던 것 같아서, 쓰지 않아보니 장황해졌는데 어떤부분을 개선하면 롬복없이도 더 깔끔하게 작성 가능한지궁금합니다.

롬복 제거 후 코드가 길어져서 장황해졌다라고 이해하면 될까요~? 롬복사용으로 반복적인 것을 줄여주어 코드를 보다 단순하게 구현할 수 있다고 생각해요. 하지만 롬복 없이도 가능 구현에 규칙을 따르고 반복적인 부분을 개선하면 깔끔하게 작성 가능하다고 생각해요.

> 스트림 사용에 능숙하지 않아서,, 코드가 길어졌는데 스트림을 사용하지 않고도 코드를깔끔하게작성할수있는 방법이 있나요 ?

코드가 길어지는 것이 꼭 나쁜것만은 아니라고 생각해요. 메서드 분리를 잘하고 코드 관리가 잘 된다면 문제 없다고 생각합니다. 또한 스트림은 오히려 주의해서 사용해야합니다. 
참고: [item 45. 스트림은 주의해서 사용하라](https://jake-seo-dev.tistory.com/452)

> 3. 결과값을 List 형태가 아니라 Map<>형태로 반환해도 괜찮은지 궁금합니다.

controller에서 response로 map 반환을 말씀하시는 건가요? 
성희님은 어떻게 생각하시나요?

2024-06-29 10:27 UTC, asebn1 commented on src/main/java/gift/repository/CollectionDB.java
> +
```java
private final Map<Long, Product> products = new HashMap<>();
```
위와 같은 사용을 질문주신걸까요? 
final은 언제 사용해야 할까요?

2024-06-29 10:27 UTC, asebn1 commented on src/main/java/gift/repository/CollectionDB.java
> +    }
기본 생성자로 아이스아메리카노를 만들고있군요 ㅎㅎ

2024-06-29 10:27 UTC, asebn1 commented on src/main/java/gift/entity/Product.java
> +    }
[객체지향 생활체조 원칙: 규칙 9번 제한사항](https://tmd8633.tistory.com/16)을 사용하고있어요
어떻게 변경해야할까요?

2024-06-29 10:27 UTC, asebn1 commented on src/main/java/gift/repository/CollectionDB.java
> +public class CollectionDB {
`@Repositiory`의 클래스 명이 `CollectionDB`네요. 
더 좋은 네이밍을 고려해보면 좋을 것 같아요.

2024-06-29 10:27 UTC, asebn1 commented on src/main/java/gift/dto/CreateProduct.java
> +    }
전반적으로 불필요한 줄바꿈이 많네요..!

2024-06-30 09:44 UTC, Shsin9797 commented on README.md
> +2. 타임리프 연결하여 정보 뿌려주기
공재호 멘토님 안녕하세요~!! 만나서 반갑습니다 👍🏻 한달반 정도 잘부탁드립니다!! 
그리고 이번 코드리뷰 감사합니다!! 제가 step2 에서 막혀서 step1까지만 하고 조금전에 step2 해결해서 업로드 했습니다!!

2024-06-30 09:45 UTC, Shsin9797 commented on src/main/java/gift/controller/ProductController.java
> +import org.springframework.web.bind.annotation.*;
말씀해주신 부분 바탕으로 코드 수정해보겠습니다! !

2024-07-03 08:43 UTC, Shsin9797 commented on README.md
> +2. 타임리프 연결하여 정보 뿌려주기
step3까지 구현완료하였습니다!!

2024-07-03 08:53 UTC, Shsin9797 commented on src/main/java/gift/controller/ProductController.java
> +import org.springframework.web.bind.annotation.*;
annotation 의 경우  * 를 없애니까 코드가 좀 많이 길어지는 느낌이 있는데, 그래도  [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)기반이라면  다 풀어서 쓰는게 맞나요?

2024-07-03 17:08 UTC, asebn1 approved these changes
성희님 안녕하세요~
코드와 작성해주신 내용을 다시한번 읽어보니 성희님께서 지금 매우 어렵다고 느껴지시는 것 같아요.
지금 보충하고 가야할 부분이 있다고 느껴지는데, 멘토링 시간에 다시한번 이야기 나누어보아요
step3를 완성하셨다고 하는데, 아직 구현이 안된 부분이 꽤 있는 것 같아요
우선 다음 주차 과제를 위해 머지하겠습니다~

2024-07-03 17:08 UTC, merged

2024-07-03 23:21 UTC, Shsin9797 commented on src/main/java/gift/controller/ProductController.java
> +import org.springframework.web.bind.annotation.*;
수정해보았는데 이렇게 여러개를 import 하게 되더라구요 그래도 * 안쓰고 계속 써도 이상하지 않은지 궁금합니다! 
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;

2024-07-03 23:24 UTC, Shsin9797 commented on src/main/java/gift/controller/ProductController.java
> +    }
수정하였습니다!

2024-07-03 23:25 UTC, Shsin9797 commented on src/main/java/gift/controller/ProductController.java
> +    }
@RestController("/api/products")
이렇게 따로 빼보았습니다.!!

2024-07-03 23:25 UTC, Shsin9797 commented on src/main/java/gift/dto/CreateProduct.java
> +        private String imageUrl;
넵 수정하였습니다!

2024-07-03 23:29 UTC, Shsin9797 commented on src/main/java/gift/repository/CollectionDB.java
> +    }
당시에는 insert 를 작성하기 전이라 해당코드를 넣었던것 같아요!!
지금은 삭제하였습니다!!

2024-07-03 23:31 UTC, Shsin9797 commented on src/main/java/gift/repository/CollectionDB.java
> +
final 은 값이 처음 생성되고 변하면 안되는 값에 넣어야할것 같습니다 . 그래서 일단 final 을 제외하여 작성했습니다. 

질문 드린 이유는 제가 참고한 영상에서 final 을 이용해서 Map 객체를 생성해서 그랬던것 같습니다.