경북대 BE_이상희_1주차 과제
kakao-tech-campus-2nd-step2/spring-gift-product pull request #133
Opened 2024-06-27 19:32 UTC by sanghee0820

### 코드 작성 시 어려웠던점.

1. Layered Architecture에 너무 익숙해져있어서 MVC로 짜기 조금 어려웠던 것 같다.
2. 직접 String으로 쿼리를 짜고, 디버깅하는 과정이 어려웠다.
3. DI를 하는 과정에서, 그동안 너무 롬복에 의존적이었다는 생각이 들었다.
4. 논리 삭제를 처음 해봤는데, 의문점이 많이 생겼다.

### 코드리뷰 부분 + 질문사항
1. 논리삭제 시 Delete를 어떠한 방식으로 해야 하나요?
논리삭제를 사용하였는데, 논리 삭제 시 Delete 매서드에서 곧바로 해당 엔티티를  update를 해주는 것이 좋은방법일까요?
아니면 find를 통해 반환된 엔티티를 서비스에서 필드 값을 변경하고 저장해 주는것이 좋을까요?

2. 논리 삭제 시 Select는 어떻게 해야 하나요?
논리 삭제 시 findAll과 find(id) 매서드를 통해 Product를 반환한 후 filtering을 통해 삭제되지 않은 값만 반환해야할까요?
아니면 Query에 Where절을 통해 필터링해야할까요?

3. MVC패턴에서의 도메인 로직 호출
Layered Architecture에서는 Service에서 Domain을 호출하면 되는데, MVC에서는 어디에서 호출을 해야할 지 잘 모르겠습니다. Controller에서 호출해도 될까요?

4. Response의 변환은 어디에서 이루어져야 하나요?
Layered Architecture에서 Service = Domain이라 생각했고, Domain로직은 외부 영향에 최소한의 영향을 받아야 된다고 알고있어, ResponseDTO를 Controller에서 변환을 해왔습니다. 그리고  MVC패턴에서도 동일하게 적용했습니다.
여기서 Service는 Domain이 맞는가에 대한 의문과 Domain이 맞다면, Domain이 Controller에 반환되는 것을 막기위해 어떻게 해야하는가가 궁금합니다.

[코드]
1. 코드에 가독성이 좋지 않은 부분이 있다면 어떤부분에서 늘릴 수 있는지 궁금합니다.
2. 매서드 네이밍이 적절한지 궁금합니다.
3. 클래스가 적절한 책임을 갖고있는지 궁금합니다.
4. 기타 개선할 부분이있는지 궁금합니다.

감사합니다!!

2024-06-30 16:46 UTC, khj68 commented
> 코드리뷰 부분 + 질문사항
> 논리삭제 시 Delete를 어떠한 방식으로 해야 하나요?
> 논리삭제를 사용하였는데, 논리 삭제 시 Delete 매서드에서 곧바로 해당 엔티티를 update를 해주는 것이 좋은방법일까요?
> 아니면 find를 통해 반환된 엔티티를 서비스에서 필드 값을 변경하고 저장해 주는것이 좋을까요?
도메인 지향적으로 엔티티 내의 메소드를 통해 필드 값을 변경하고 변경사항을 저장해주는 것을 추천드립니다.
entity.delete() 를 통해 필드 값을 변경해주는 로직 좋습니다.
> 논리 삭제 시 Select는 어떻게 해야 하나요?
> 논리 삭제 시 findAll과 find(id) 매서드를 통해 Product를 반환한 후 filtering을 통해 삭제되지 않은 값만 반환해야할까요?
> 아니면 Query에 Where절을 통해 필터링해야할까요?
두 가지 전부 가능한 방법입니다.
추가 적으로 엔티티 리스너를 통해 필터링을 적용하는 방법도 있습니다.
엔티티와 접촉하는 가장 첫 단계인 쿼리에서부터 필터링이 적용되는 것이 가장 깔끔해보입니다.
> MVC패턴에서의 도메인 로직 호출
> Layered Architecture에서는 Service에서 Domain을 호출하면 되는데, MVC에서는 어디에서 호출을 해야할 지 잘 모르겠습니다. Controller에서 호출해도 될까요?
꼭 service가 아니더라도 domain 관련 로직을 담당하는 component를 생성해 해주는 것도 좋습니다.
컨트롤러는 요청과 응답 관련된 부분만을 다루고, 비즈니스 로직은 다른 곳에서 분리하여 적용해주는 것을 추천드립니다.
> Response의 변환은 어디에서 이루어져야 하나요?
> Layered Architecture에서 Service = Domain이라 생각했고, Domain로직은 외부 영향에 최소한의 영향을 받아야 된다고 알고있어, ResponseDTO를 Controller에서 변환을 해왔습니다. 그리고 MVC패턴에서도 동일하게 적용했습니다.
> 여기서 Service는 Domain이 맞는가에 대한 의문과 Domain이 맞다면, Domain이 Controller에 반환되는 것을 막기위해 어떻게 해야하는가가 궁금합니다.
layerd에서는 controller -> service -> repository (domain) 의 순서로 층이 진행됩니다.
mvc에서도 비슷하게 별도 컴포넌트를 통해 domain이 컨트롤러에 등장하는 것을 방지할 수 있습니다.
그것은 facade일 수도 있고 helper와 같은 component일 수도 있습니다.
다만 강의 진도 상 layerd를 지양해야 한다면, query를 통해 꺼내오는 로직에서 dto를 적용할 수도 있습니다.
엔티티를 꺼내올 때는 dto로, 컨트롤러에서는 dto 값을 받아 response로 변환하는 식의 분리도 좋습니다.
> CUD의 경우 Test코드를 어떻게 짜야하는지 궁금합니다!
@RepositoryTest를 통해 실제로 write 작업이 이루어지는지를 테스트할 수 있습니다. 
> [코드]
> 
> 코드에 가독성이 좋지 않은 부분이 있다면 어떤부분에서 늘릴 수 있는지 궁금합니다.
사용하지 않는 주석은 지워주시고, 무의미한 줄바꿈도 함께 챙겨주세요.
한 메소드의 파라미터에는 최대한 변수가 들어가는 것이 좋습니다.
그 안에 또 다른 로직이 들어가게 되면 가독성이 떨어집니다.
단축어는 패키지명이더라도 지양하는 것이 좋습니다. (req, res)
줄바꿈 하나하나가 로직을 의미할 때도 있습니다.
> 매서드 네이밍이 적절한지 궁금합니다.
전반적으로 직관적이고 좋습니다.
bean 을 설정하는 메소드명 조금 더 신경써주세요.
> 클래스가 적절한 책임을 갖고있는지 궁금합니다.
클래스는 적절한 책임을 가지고 분리가 잘되어 있는 것으로 보입니다.
> 기타 개선할 부분이있는지 궁금합니다.
항상 주석이나 줄바꿈, Import 등 디테일한 부분까지 신경쓰는 습관을 가지는 것이 좋습니다 :)

2024-06-30 16:46 UTC, khj68 requested changes
고생 많으셨습니다 :)

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/common/exception/ProductException.java
> +public class ProductException extends RuntimeException{
별도 에러 클래스 정의 좋습니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/config/RepositoryConfig.java
> +//    @Bean
사용하지 않는 주석은 지워주세요!

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/config/RepositoryConfig.java
> +    public ProductRepository products(JdbcTemplate jdbcTemplate) {
bean 등록이기에 ProductRepository productRepository 를 추천드립니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/AdminController.java
> +
줄바꿈 디테일 챙겨주세요!

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +
줄바꿈 디테일 챙겨주세요~

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("")
개인적으로 ("") 는 지우는 것을 추천드립니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +                .body(foundProduct.stream().map(ProductResponse::fromModel).toList());
코드 가독성을 위해 foundProduct.stream().map(ProductResponse::fromModel).toList() 는 변수로 추출하는 것을 추천드립니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +        List<Product> foundProduct = productRepository.findAll();
여기서 stream()을 바로 적용해도 좋고요.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/ProductController.java
> +                .body("Product deleted");
유의미한 엔티티나 dto가 반환되지 않는다면 ok 상태코드만 내려주어도 좋을 것 같습니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/res/ProductResponse.java
> +
줄바꿈 디테일 챙겨주세요~

2024-06-30 16:46 UTC, khj68 commented on src/test/java/gift/controller/ProductControllerTest.java
> +    @DisplayName("모든 Product 반환 테스트")
테스트 좋습니다.
given,when,then 템플릿 적용도 아주 좋습니다.

2024-06-30 16:46 UTC, khj68 commented on src/main/java/gift/controller/req/ProductRequest.java
> +package gift.controller.req;
단축어는 최대한 지양하는 것을 추천드립니다.
req와 res를 합쳐서 dto 패키지 내에서 관리하는 방법도 자주 사용합니다.

2024-07-01 04:48 UTC, sanghee0820 commented on src/main/java/gift/config/RepositoryConfig.java
> +//    @Bean
이 부분에서 Step 1~3까지 구현한 내용이 Config에서 바꿀 수 있다는 것을 나타내고 싶었습니다.
지우도록 하겠습니다!

2024-07-01 04:58 UTC, sanghee0820 commented on src/main/java/gift/config/RepositoryConfig.java
> +    public ProductRepository products(JdbcTemplate jdbcTemplate) {
변경하였습니다!

2024-07-01 05:34 UTC, sanghee0820 commented on src/main/java/gift/controller/res/ProductResponse.java
> +
혹시 줄바꿈이 중괄호 뒤 빈줄이 추가되어있기 때문인가요?

일단 그렇게 수정하였습니다!

2024-07-01 05:34 UTC, sanghee0820 commented on src/main/java/gift/controller/ProductController.java
> +
수정하였습니다.

2024-07-01 05:34 UTC, sanghee0820 commented on src/main/java/gift/controller/AdminController.java
> +
수정하였습니다.

2024-07-01 05:38 UTC, sanghee0820 commented on src/main/java/gift/controller/req/ProductRequest.java
> +package gift.controller.req;
dto 내부에 request와 response 클래스들이 모두 담겨져 있나요?

request, response로 변경하였습니다!

2024-07-01 05:44 UTC, sanghee0820 commented on src/main/java/gift/controller/ProductController.java
> +                .body("Product deleted");
감사합니다! @ResponseStatus를 활용해 수정하였습니다.

2024-07-01 06:46 UTC, khj68 commented on src/main/java/gift/config/RepositoryConfig.java
> +//    @Bean
의도하신 바가 있으시다면 남겨두셔도 좋습니다 :)

2024-07-01 06:46 UTC, khj68 commented on src/main/java/gift/controller/res/ProductResponse.java
> +
넵 맞습니다 :)

2024-07-01 06:47 UTC, khj68 commented on src/main/java/gift/controller/req/ProductRequest.java
> +package gift.controller.req;
넵 dto 클래스 내부에 함께 담아두기도 합니다.
이 부분은 취향에 따라 다를 것 같습니다 :)

2024-07-01 06:47 UTC, merged