전남대 BE_서지우 1주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #134
Opened 2024-06-27 20:19 UTC by seojiu

서로 다른 파일들끼리 기능들이 깊게 얽혀있어서 어떤 기준으로 커밋을 해야하는지 헷갈리는 경우가 많았습니다.

상품이 추가 될 때 마다 id가 자동으로 1씩 증가하도록 구현했는데, 지금 와서 생각해보니 id까지 사용자가 입력할 수 있도록 만들었어야 됐는지 궁금합니다.
또, 상품 imageUrl을 string으로 화면에 띄워놨는데 이미지로 변환해서 띄웠어야 했는지 궁금합니다.

2024-06-29 07:59 UTC, pkeugine requested changes
step 2 도 잘 만들어주셨네요!
리뷰 남겨보았으니 step1 쪽 리뷰와 함께 봐주세요 :)
반영은 step3 PR 에 일괄적용해주셔도 괜찮습니다.

2024-06-29 07:59 UTC, pkeugine commented on README.md
> +![img_2.png](img_2.png)
해당 이미지는 어떤 이유로 추가해주셨나요?

2024-06-29 07:59 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        return "redirect:/api/products";//상품 추가 끝나면 메인페이지로~
이전 스텝에서 리뷰로 남겼지만 이런 주석은 코드로 다 이해 가능해요!
그런데 주석이 재밌네요 ㅋㅋㅋ

2024-06-29 07:59 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +    private long currentId = 1;
이전 스텝에서 제가 리뷰로 남겼던 부분이 이 step 에 반영되었군요!!

> 상품이 추가 될 때 마다 id가 자동으로 1씩 증가하도록 구현했는데, 지금 와서 생각해보니 id까지 사용자가 입력할 수 있도록 만들었어야 됐는지 궁금합니다.

고민을 한 번 해볼까요?
사용자는 상품을 추가할 때 어떻게 다음 id 를 알고 입력할 수 있을까요?
만약 사용자가 한 명이 아닌 1000000 명이라고 생각해보죠.
그 많은 사용자들이 상품을 추가한다면 id 값은 빠르게 증가할거예요.
그렇다면 사용자는 현재 id 값을 알 수 있을까요?

2024-06-29 07:59 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +    }
새로운 collection 을 만들어서 반환해주시는 이유가 궁금해요!

2024-06-29 07:59 UTC, pkeugine commented on src/main/java/gift/ProductService.java
> +        product.setId(id);
앞서 setter 를 지양해보자는 리뷰를 남겼었죠!
그렇다면 이 부분은 어떻게 바뀌면 좋을까요?
(참고로 다양한 방식으로 바뀔 수 있으니 지우님이 원하시는 방식으로 해주셔도 괜찮아요)

2024-06-29 07:59 UTC, pkeugine commented on src/main/resources/templates/index.html
> +</html>
empty line 관련 반영사항은 frontend 쪽 코드에도 적용해주세요!

2024-07-01 14:33 UTC, pkeugine commented
step 1 을 머지하고 나니
conflict 가 발생하여 merge 되지 않는 상태네요!
해당 부분 확인해주시고, 해결되면 merge 진행하도록 할게요.
step 3 에 대해서도 한 번 같이 확인해주세요 :)

다음 미션 때는 step 1 작업 후, 그 브랜치를 기반으로 step 2 를
그리고 step 2 를 기반으로 step 3 작업을 해주시면 conflict 를 예방할 수 있을거예요.
앞으로 (커리어 평생...) git 을 활용하여 개발을 하실테니 이 기회에 한 번 연습해보도록 하죠!

2024-07-02 12:14 UTC, pkeugine approved these changes
다음 미션으로 넘어갔으니 해당 PR 은 머지하도록 하겠습니다.
이번 주 미션에서 해당 PR 에 있는 리뷰를 함께 적용해주세요!

2024-07-02 12:14 UTC, merged

2024-07-12 11:29 UTC, seojiu commented on src/main/java/gift/ProductService.java
> +    private long currentId = 1;
알기 힘들 것 같습니다. 역시 서버에서 id값을 지정해주는게 정답이었군요!!

2024-07-12 11:32 UTC, seojiu commented on README.md
> +![img_2.png](img_2.png)
관리자 페이지 예시를 들기 위해 추가했습니다!!

2024-07-12 11:32 UTC, seojiu commented on src/main/java/gift/ProductService.java
> +        product.setId(id);
모두 반영했습니다!

2024-07-12 11:40 UTC, seojiu commented on src/main/java/gift/ProductService.java
> +    }
products.values()를 그대로 반환하기 보단 ArrayList를 만들어 복사하는게 더 안전할 것 같다는 생각을 했던 것 같습니다. 지금보니 크게 의미는 없네요...