경북대 BE_정수현_1주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #137
Opened 2024-06-28 00:25 UTC by suhyeon7497

느낀점
thymeleaf부터 Spring사용까지 아는 게 너무 없어 과제를 진행하는데 삽질만 하는 느낌이 났었습니다. 너무 급하게 하느라 UI 부분은 신경을 쓰지 못했습니다. 주말동안 더 열심히 공부해서 뒤쳐지지 않도록 노력하겠습니다.

-thymeleaf를 사용해보면서 공부를 해보았는데, thymeleaf는 Delete와 Put 요청을 받지 않는다고 하는데 그 이유가 궁금합니다.
-제 코드에서는 Controller나 Dao에서 메서드 이름을 마음대로 작성하였던 것 같은데, 정형화된 메서드 이름이 있는지 궁금합니다.
-가독성이 떨어지는 부분을 알려주시면 step3때 refactoring 하겠습니다.

2024-06-30 10:20 UTC, sang5c requested changes
2단계도 고생하셨습니다!  
1단계에서 리뷰에 작성한 내용이 2단계에도 동일하게 있어서 Request change를 드립니다. :)  

> thymeleaf를 사용해보면서 공부를 해보았는데, thymeleaf는 Delete와 Put 요청을 받지 않는다고 하는데 그 이유가 궁금합니다.

정확히는 타임리프는 템플릿 엔진으로, 동적으로 HTML을 만들어주는 역할을 수행합니다.  HTML form에서 GET과 POST만 지원합니다.  
지원하지 않는 이유에 대한 공식 입장은 없습니다만, 여러 주장들이 있으니 아래 글을 한 번 읽어보시면 좋겠네요.  
https://softwareengineering.stackexchange.com/questions/114156/why-are-there-no-put-and-delete-methods-on-html-forms

>  코드에서는 Controller나 Dao에서 메서드 이름을 마음대로 작성하였던 것 같은데, 정형화된 메서드 이름이 있는지 궁금합니다.

코드를 많이 보다보면 겹치는 이름을 갖게되는 경우가 많긴 하나, `이렇게 작성해야 한다` 라는 규칙은 존재하지 않습니다.  
`이름은 역할을 명확히 나타내기 위해 잘 작성해야 한다` 라는 목표를 두고 수행하기 위해 노력했다면, 어떤 이름이되어도 문제 없다고 생각합니다. 수현님이 생각하시기에 정보 전달에 있어서 적절한 이름이면 괜찮습니다!

2024-07-01 06:09 UTC, suhyeon7497 commented on src/main/java/gift/model/ProductDao.java
> +public class ProductDao {
Controller에서 DB에 저장하는 로직이 존재하면 부하가 커진다고 생각했습니다.

2024-07-01 06:15 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
> +    private ProductDao productDao;
넵 변경될 일이 없는 것 같습니다!

2024-07-01 06:15 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("")
넵!

2024-07-01 06:27 UTC, suhyeon7497 commented on src/main/java/gift/model/Product.java
> +    public Product(Long id, String name, int price, String imageUrl) {
가장 처음에 JacksonLibrary에서 dataBinding될 때의 방식이  둘 중 하나일 것이라고 생각했습니다. 기본 생성자 + setter 이거나 AllArgConstructor일 것으로 생각하였습니다. 제대로된 학습이 부족하여 둘 다 함께 사용한 것 같습니다.

2024-07-01 06:28 UTC, suhyeon7497 commented on src/main/java/gift/model/Product.java
> +    public Product(Long id, String name, int price, String imageUrl) {
지금 다시 확인해보니 setter가 없어도 제대로 작동하는 것으로 보입니다. 기본 constructor 와 setter는 지우도록 하는 것이 좋아보입니다! 좋은 지적 감사합니다.

2024-07-01 13:28 UTC, sang5c commented
코드의 분리는 부하와는 관련이 없습니다 :)  
각각의 클래스에 역할과 책임을 주고, 유지보수에 도움을 주기 위해 코드를 분리하는 편이에요.  

혹시 추가 질문이 있으시면 편하게 말씀해주세요!  

3단계에서 통합 머지를 위해 close 처리합니다.

2024-07-01 13:28 UTC, closed without merging