충남대 BE_윤정훈_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #14
Opened 2024-06-25 07:49 UTC by yunjunghun0116

1주차 과제(1단계) 수행 과정
1. README.md 를 작성하고 상품 추가, 수정, 조회, 삭제 기능을 구현할 것을 정리한다.
2. 한 함수는 오직 하나의 기능을 수행할 수 있도록 하기 위해 계층을 분리한다.
3. 새로 알게된 record를 DTO에 적용하여 코드를 개선한다.
4. 리팩토링 중 메소드 추출 기법을 사용하여 예외를 한곳에서 처리할 수 있도록 한다.

궁금한 부분
1. 기존 저의 생각은 DTO는 클라이언트가 서버에게 요청을 보내기 위한 객체, ENTITY는 데이터베이스에 저장되고, 서버에서는 저장된 온전한 객체를 바탕으로 여러가지 작업을 수행하며 이 결과(엔티티가 될 수도 있고, 엔티티를 갖는 컬렉션이 될 수 도있다고 생각)를 그대로 반환한다고 생각을 했는데, 서버에서 클라이언트에게 엔티티를 온전히 보내는것이 아닌, 엔티티를 다시 DTO로 변환하여 전송하여야 하는지?
2. 모든 요청에 대해서 응답결과를 한번 더 감싸서 statusCode, data(수행 결과), message(에러 발생시 해당 에러 메세지를 보내기 위함) 와 같은 필드를 갖는 ResultResponse 같은 객체로 한번더 감싸서 보내는것이 좋을지, ResponseEntity에 객체를 담아 리턴하는것이 좋을지?

2024-06-29 11:12 UTC, asebn1 requested changes
안녕하세요 정훈님~
6주간 코드리뷰어를 맡게된 공재호라고합니다. 잘부탁드려요.
코드를 보니 전반적으로 스프링에 대한 이해도가 높으신 분으로 보여요. 
계층분리, dto사용, 에러처리, 추가기능구현까지 잘 구현해주셨네요 💯💯 
부족한 부분은 없으나 몇 가지 코멘트 드렸습니다.
리뷰 확인해주시고 궁금한 점 코멘트로 남겨주세요 (DM도 좋아요)

2024-06-29 11:12 UTC, asebn1 commented on src/main/java/gift/model/Product.java
> +    }
[객체지향 생활체조 원칙: 규칙 9번 제한사항](https://tmd8633.tistory.com/16)을 사용하고있어요
어떻게 변경해야할까요?

2024-06-29 11:12 UTC, asebn1 commented on src/main/java/gift/repository/ProductMemoryRepository.java
> +    Long sequentialId = 1L;
`private`를 추가하는게 좋아보아요

2024-06-29 11:12 UTC, asebn1 commented on src/main/java/gift/repository/ProductMemoryRepository.java
> +    }
`private`으로 수정해주세요!

2024-06-29 11:12 UTC, asebn1 commented on src/main/java/gift/repository/ProductOptionRepository.java
> +}
인터페이스를 구현해주셨네요!
어떤 이점이 있을까요?

2024-06-29 11:12 UTC, asebn1 commented on src/main/resources/schema.sql
> +);
스키마 관리 👍

2024-06-29 11:12 UTC, asebn1 commented on src/test/java/gift/service/ProductOptionServiceTest.java
> +    }
실패케이스, 성공케이스 모두 잘 작성해주셨군요! 👍 👍

2024-06-29 11:12 UTC, asebn1 commented on src/main/java/gift/controller/AdminController.java
> +import org.springframework.web.bind.annotation.*;
현재 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)를 기반으로 하고 있습니다.
No wildcard imports 부분 참고해주세요~

2024-06-30 07:33 UTC, yunjunghun0116 commented on src/main/java/gift/controller/AdminController.java
> +    }
생성자 주입 말고는 @Autowired를 사용하는 필드주입, Setter 를 사용한 수정자 주입, init()과 같이 일반 메서드를 사용하여 주입하는 방법이 있습니다. 😁

또한 생성자 주입과 다른 방식의 가장 큰 차이점은 의존관계가 설정된 객체에 대해서 final을 적용할 수 있느냐 없느냐의 차이라고 생각하고, 객체의 불변성을 보장하고자 생성자 주입으로 위 코드를 구현하였습니다! 감사합니다 :)

2024-06-30 07:34 UTC, yunjunghun0116 commented on src/main/java/gift/controller/AdminController.java
> +import org.springframework.web.bind.annotation.*;
감사합니다! 기존에는 단순히 wildcard를 사용해서 import를 하면 코드도 줄어들고 편하지 않을까? 라는 생각을 갖고있었는데 잘못된 생각을 바로잡을 수 있었습니다! :)

2024-06-30 07:41 UTC, yunjunghun0116 commented on src/main/java/gift/controller/AdminController.java
> +    }
기존 상품 정보에 대한 완전 대체 작업을 수행중이므로 PutMapping으로 변경해야겠네요! 감사합니다 :)

2024-06-30 07:56 UTC, yunjunghun0116 commented on src/main/java/gift/controller/ProductController.java
> +    }
1. 적절한 HTTP Method는 PUT이라고 생각합니다. 이유는 상품 추가의 경우 새로운 리소스를 생성하기 때문에 기존 리소스 중 일부 필드를 변경하는 PATCH 메소드와는 적절하지 않다고 생각합니다.
또한 상품 수정의 로직도 일부 필드의 수정이 아닌, 상품 정보에 대한 완전한 대체를 통한 수정이 이루어지기 때문에 PUT메소드가 적절하고, 상품의 이름 혹은 가격 만을 수정하는 경우에 PATCH 메소드가 사용되어야 할것같다 생각합니다.

2. DTO에 대해서는 계속 생각을 해보고 있는데 현재까지 정리해본 내용을 바탕으로 답변을 말씀드리면 요청과 응답 부분에서 모두 DTO를 사용해야 할 필요가 있다 생각합니다.
DTO는 필요한 정보를 전송하기 위한 객체이고, 클라이언트와 서버와의 소통에 있어 불필요한 정보는 제외하고, 필요한 정보만을 담아 전송하기 위해 사용됩니다.
따라서 클라이언트로부터 요청을 받을때 request dto를 사용하고, 응답을 할때 역시 서버에서 클라이언트에게 필요한 정보를 전송하기 위한 객체로서 response dto를 사용하여 불필요한 정보는 담지 않고, 필요한 정보만을 담아 전송하기 위해서 response도 dto로 반환할 필요가 있다고 생각합니다.

RESPONSE DTO를 만들어 반환할때 사용해주어야겠네요!!

2024-06-30 08:22 UTC, yunjunghun0116 commented on src/main/java/gift/controller/ProductController.java
> +    }
HTTP 요청과 응답에 해당하는 HttpEntity를 상속받은 클래스로, HttpRequest에 대한 응답 데이터를 포함하는 클래스입니다. 또한 이 클래스는 빌더패턴을 사용해서 다양하게 header, status code, body(data) 등을 담아 전송할 수 있습니다.

저는 요청에 대해서 성공했을경우 200번대 응답만 보내주면 되겠지? 라고 생각을 하고 있었는데, 덕분에 더 공부해보며 ok, created, no-content 등 200번대 응답에서도 경우에 따라 사용되는 응답코드가 다르다는 것을 알게 되었습니다. 감사합니다 :)

2024-06-30 09:55 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductMemoryRepository.java
> +    Long sequentialId = 1L;
넵 확인했습니다!
외부에서 sequentialId에 접근할 수 없도록 private로 타입을 변경하는게 좋아보이네요 저도!

2024-06-30 09:56 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductMemoryRepository.java
> +    }
내부 로직에서만 값을 validation 하기때문에 이 메소드 역시 private으로 수정하는게 맞아보이네요!
수정했습니다 :)

2024-06-30 09:58 UTC, yunjunghun0116 commented on src/main/java/gift/repository/ProductOptionRepository.java
> +}
현재는 JDBC Repository를 사용하여 서비스가 구현되어있는데, 추후 JPA Repository나 MemoryRepository 등 다양한 레포지토리로 변경을 하게 되더라도 Service계층에서의 코드 수정 없이 Configuration에서만 갈아끼워넣어주면 되기에 각 계층은 다른 계층의 구현체에 의존하지 않고, 추상체에 의존하게 됩니다!

2024-06-30 09:58 UTC, yunjunghun0116 commented on src/test/java/gift/service/ProductOptionServiceTest.java
> +    }
감사합니다 :)

2024-06-30 11:24 UTC, yunjunghun0116 commented on src/main/java/gift/model/Product.java
> +    }
setter의 남용을 피하고, 각 계층에서 생성자를 통한 인스턴스를 생성하기 보다는 상품 클래스 내부에 from, of 등과 같은 메소드를 사용하여 구현해야 합니다. 이를 통해 객체의 정보를 외부에서 수정할 수 없도록 합니다.

궁금한 점
1. 위 내용을 바탕으로 fromDto, updateFromDto를 통해 내부의 로직은 외부에서 알 수 없고, 입력을 바탕으로 결과를 내주는 함수를 만들었는데 현업에서는 객체의 캡슐화를 위해 생성자, getter를 제외한 위와같은 함수를 따로 만들어 자주 사용하는지?
2. repository에서 생성된 id를 바탕으로 객체를 생성해서 service로 만들어 내보내주는데 위와 같이 사용해도 되는지?
궁금한 이유 : repository는 객체를 저장만하고, 그에대한 결과만을 반환해야지 객체를 새로 만들어서 반환하는건 단일책임원칙에 위배되는것은 아닌가? 라는 생각이 들어서 생긴 궁금한점입니다.

2024-06-30 14:45 UTC, asebn1 commented on src/main/java/gift/model/Product.java
> +    }
> 1. 위 내용을 바탕으로 fromDto, updateFromDto를 통해 내부의 로직은 외부에서 알 수 없고, 입력을 바탕으로 결과를 내주는 함수를 만들었는데 현업에서는 객체의 캡슐화를 위해 생성자, getter를 제외한 위와같은 함수를 따로 만들어 자주 사용하는지?

네 기본적으로 캡슐화를 지키며 개발되고 있어요.
dto의 사용범위는 어떻게 될까요? 읽어보면 좋은 내용 공유드려요
- https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/
- https://umbum.dev/1206

> 2. repository에서 생성된 id를 바탕으로 객체를 생성해서 service로 만들어 내보내주는데 위와 같이 사용해도 되는지?
궁금한 이유 : repository는 객체를 저장만하고, 그에대한 결과만을 반환해야지 객체를 새로 만들어서 반환하는건 단일책임원칙에 위배되는것은 아닌가? 라는 생각이 들어서 생긴 궁금한점입니다.

좋은 질문입니다! 단일책임원칙을 지키는건 중요합니다. repository에서 객체를 새로 만들어서 반환하면 해당 원칙을 위배할 수 있어요
정훈님이 생각하는 repository, service 계층의 각 역할은 무엇일까요? 그리고 코드부분이 단일책임원칙에 위배된다고 생각하시나요?

2024-06-30 14:47 UTC, asebn1 commented
1주차 과제 수고하셨습니다. 
질문 주신 코멘트는 답변을 드렸어요. 추가로 질문 있으시다면 다음 PR로 작성해주세요~ (DM도 좋습니다)
이번 주차는 이만 머지하겠습니다.

2024-06-30 14:48 UTC, asebn1 approved these changes

2024-06-30 14:48 UTC, merged

2024-07-01 06:24 UTC, yunjunghun0116 commented on src/main/java/gift/model/Product.java
> +    }
제가 생각했을때 
Repository는 DB에 접근하여 리소스에 접근하여 저장, 조회, 수정, 삭제의 작업을 수행하고 그에 해당하는 결과를 반환하는 역할을 하고
Service는 요청에 대한 비즈니스로직에 대한 처리와 도메인 모델(상품, 상품옵션 등)의 인스턴스 처리 역할을 수행한다고 생각합니다.

그렇기 때문에 도메인 모델에 관련한 작업을 수행하는 계층은 Service 계층이라고 생각합니다.

기존 코드 부분은 레포지토리에서 저장을 수행하고, 저장에 따른 결과(id)와 입력인자를 바탕으로 객체를 생성해서 반환하는 작업을 수행하기에 단일책임원칙에 위배된다고 생각합니다.
그렇기때문에 이를 Repository는 저장에 대한 결과(id)만을 반환하고, 이를 바탕으로 객체를 생성하는 작업은 service로 옮겨보았습니다.