전남대 BE_서영우_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #145
Opened 2024-06-28 04:01 UTC by westzeroright

2024-06-29 05:51 UTC, pkeugine requested changes
안녕하세요 영우님! 반갑습니다 😄 
미션 잘 진행해주셨는데요! 애플리케이션이 현재 실행 가능한 상태가 아니라서,
해당 버그 수정해주시면 될 것 같아요.

그 외에도 간단한 리뷰와 질문 남겨보았으니
적용해보거나 답변 댓글로 남겨주시면 나중에 확인해보겠습니다.

주말 잘 보내시고, 같이 파이팅해봐요!! 🔥 🔥 🔥

2024-06-29 05:51 UTC, pkeugine commented on README.md
> +# spring-gift-product
commit 을 깔끔하게 나눠주셔서 리뷰하기 좋네요! 💯 💯 💯 

그런데 이미 다 구현을 해주신 뒤 커밋을 쌓아가셔서 그런지
어떤 커밋은 checkout 하면 실행되는 상태가 아닐 때가 있어요.
예를 들어 controller 를 구현하는 commit 이후에 dto commit 이 들어가는 경우가 있네요.
commit 을 잘 쌓아주시니까 다음엔 이런 부분도 한 번 고려해서 쌓아보는건 어떨까요? :)

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +    }
setter 를 사용하지 않고 생성자를 활용해서 정보를 넣어보는건 어떨까요?
이왕이면 setter 를 최대한 지양하며 로직을 만들어보면 좋을 것 같아요.

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +public class ProductController {
`@RequestMapping` 을 사용해서 공통적인 uri 경로를 잘 묶어주셨네요 👍 
그런데 `/api` 말고도 조금 더 묶어볼 수 있을 것 같아요!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    private final ProductDAO productDAO;
패키지명, 변수명, 상수명, 그리고 메서드명 등등....
[꽤 많은 개발자분들이 따르는 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)이 있는데 한 번 읽어보고 적용해보면 좋을 것 같아요.
`productDAO` 의 경우엔 `productDao`, 그리고 클래스명 `ProductDAO` 는 `ProductDao` 가 되겠군요!

이 외에도 해당 컨벤션은 시간날 때 쭉 읽어보고, 네이밍 외 다른 컨벤션 어떤 것들이 있는지 알아보면 도움이 많이 돼요!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        productDAO.createProductTable();
생성자에 DB 관련 로직을 넣으셨군요!
이렇게 만드신 이유가 궁금해요.
`schema.sql` 도 있어서요!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +        }
예외처리 꼼꼼하네요!!! 👍 👍 👍

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/Product.java
> +    }
해당 생성자는 어떤 이유로 존재하나요?

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    public ProductController(ProductDAO productDAO) {
현재 애플리케이션이 제대로 실행되지 않는 것 같아요.
왜 실행되지 않는지 로그를 확인해보고, 실행될 수 있도록 수정해보는건 어떨까요?

PR 을 남기기 전에 컴파일, 실행이 잘 되는지 확인해보는 습관을 들이면 좋아요!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    // 모든 상품 조회
메서드명으로 충분히 어떤 로직인지 파악 가능하네요! (이름을 잘 지으셨습니다 ㅋㅋㅋ)
그러니 이 주석은 불필요하므로 제거해보죠!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductDAO.java
> +        var sql = """
controller 와는 다르게 repository 에서는 `var` 을 사용하시네요!
이 선택을 하신 이유가 궁금해요.

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductDAO.java
> +                        //resultSet.getLong("id"),
사용하지 않는 코드는 제거해주세요!

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductDAO.java
> +        var sql = "insert into product (id, name, price, url) values (?, ?, ?, ?)";
multi line string 과 줄바꿈을 사용해서 쿼리를 보기 좋게 나타내보는건 어떨까요?

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductRequestDTO.java
> +}
record 를 사용해주셨군요!
dto 에 record 를 사용하신 이유가 있나요?

2024-06-29 05:51 UTC, pkeugine commented on src/main/resources/schema.sql
> +)
파일의 끝부분에 empty line 을 추가해주면 좋을 것 같아요.
그 줄이 왜 필요한지도 한 번 알아보도록 하죠!

intelliJ 에는 빈 줄을 자동으로 추가해주는 옵션이 있는데요,
이를 활성화해주면 코드를 관리하기 더 수월해져요 :)
<img width="1094" alt="Screenshot 2024-06-08 at 2 05 28 PM" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/48251668/069e78fc-a521-48cf-afe1-86bb3ea72edd">

2024-06-29 05:51 UTC, pkeugine commented on src/main/java/gift/ProductDAO.java
> +package gift;
매의 눈으로 불필요한 공백을 하나 찾아냈습니다 🦅  👀

2024-06-29 14:46 UTC, westzeroright commented on src/main/java/gift/ProductController.java
> +        productDAO.createProductTable();
강의를 들을 때 GET 기능 속에 `createProductTable()` 메서드가 있었는데 강의 때 정리한 내용을 기반으로 과제를 수행하며 

GET 요청이 들어올 때마다 테이블이 생성되면 안 된다고 생각하여 생성자 속에 넣었습니다. 이후 `schema.sql` 을 추가하고 수정하지 못 한 것 같습니다.

2024-06-29 14:46 UTC, westzeroright commented on src/main/java/gift/Product.java
> +    }
삭제하겠습니다..!

2024-06-29 15:07 UTC, westzeroright commented on src/main/resources/schema.sql
> +)
좋은 조언 감사합니다!

https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/
파일의 끝부분에 개행이 필요한 이유에 대해서 이 블로그를 참고하여 알아보았는데
1. POSIX에서 파일의 끝을 개행으로 정의했고
2. 파일을 구분하기 위함
으로 이해하였습니다.

2024-06-29 15:13 UTC, westzeroright commented on src/main/java/gift/ProductRequestDTO.java
> +}
요청과 응답으로 들어오는 데이터는 불변성 특징을 가진다고 생각하여 DTO 클래스에 record를 사용하였습니다.

2024-06-29 15:23 UTC, westzeroright commented on src/main/java/gift/ProductDAO.java
> +        var sql = """
강의 때 강사님 따라서 사용하였습니다.

var 타입에 대해 컴파일 시점에 타입을 추론하고 장점으로는 코드가 간결해지고 단점으로는 유지 보수 시 문제가 생길 수 있다고 알고 있습니다.
var 타입에 대해 아직 잘 몰라서 추가적인 조언 주시면 감사드리겠습니다!

2024-06-30 14:55 UTC, pkeugine commented
안녕하세요 영우님!
리뷰어로 저를 등록해주셔서 혹시나해서 리뷰요청한 것인지 확인차 다녀갑니다!
아직 작업해주고 계신 것 같네요 :)
파이팅입니다!!

2024-06-30 15:01 UTC, westzeroright commented
작업 완료했습니다!

2024-06-30 15:33 UTC, pkeugine commented
<img width="1298" alt="Screenshot 2024-07-01 at 12 33 24 AM" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/48251668/b79ee9ea-ca4b-46e3-b4bc-fca93d0c35fc">

한 번 더 확인해보시길 바랍니다 :)

2024-06-30 16:27 UTC, westzeroright commented
안녕하세요 코치님!

제 노트북에서는 오류가 뜨지 않고 정상 실행되어 파일을 올렸습니다. 올려진 파일과 로컬과 비교했을 때도 같고
혹시 코치님 화면에 뜨는 오류 내역이나 제가 할 수 있는 다른 방안을 말씀해주실 수 있으실까요?

<img width="1439" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/124443419/f3b7f4d6-c84d-48c2-927f-504edacc1bc8">

2024-06-30 17:46 UTC, pkeugine commented
안녕하세요 영우님,
올려진 파일과 로컬이 같지는 않은 것 같습니다.
캡쳐해주신 화면을 보니 dto 쪽에 변경사항을 적용해주셨는데,
commit 을 이나 push 를 하지 않은 상태로 보여요.
controller 관련 로직만 된 것 같네요.
`schema.sql` 파일이나 `application.properties` 도 탭이 파란색으로 되어있는걸 보니 아직 commit & push 가 되어있지 않은 것 같습니다.
한 번 확인해주세요!

2024-07-01 03:52 UTC, westzeroright commented
확인해보니 변경사항이 있었네요ㅠㅠ 번거롭게 해드려서 죄송합니다

모두 커밋했으니 리뷰 부탁드릴게요!

2024-07-01 13:55 UTC, pkeugine approved these changes
안녕하세요 영우님,
다음 단계에서 리뷰 요청 주신 것을 확인해서,
이 PR 은 이만 머지하도록 할게요.
앞으로 한 달 넘게 함께하게 될텐데 잘 부탁드립니다 🙇 
추가 리뷰는 다음 스텝 작업과 함께 그 쪽에서 진행할게요!

2024-07-01 13:55 UTC, merged