강원대 BE_이강욱_1주차 과제 STEP 1
kakao-tech-campus-2nd-step2/spring-gift-product pull request #15
Opened 2024-06-25 07:57 UTC by kanguk01

#  코드 작성하면서 어려웠던 점

과제 시작 전 이렇게 다짐했었습니다. 

> 지금까지 내가 했던 매우 얕은 지식의 웹 개발 지식은 모두 잊자!
> 

그 개념을 기반으로, 기존 알고 있던 서비스, 레포지토리, 컨트롤러, 모델 형식의 구조가 아닌, 단순 모델-컨트롤러 구조로 구현하였는데, 이렇게 구현해도 잘 작동이 되는 것이 또 새로웠던 것 같습니다. 

어렵던 부분은 테스트부분이였습니다. 
테스트코드를 작성하다가 다음과 같은 방식을 보게 되었습니다.

```java
public void testGetAllProducts() throws Exception {
      mockMvc.perform(get("/api/products"))
              .andExpect(status().isOk())
              .andExpect(content().contentType(MediaType.APPLICATION_JSON))
              .andExpect(jsonPath("$[0].name").value("아이스 카페 아메리카노 T"))
              .andExpect(jsonPath("$[0].price").value(4500))
              .andExpect(jsonPath("$[0].imageUrl").value("https://st.kakaocdn.net/product/gift/product/20231010111814_9a667f9eccc943648797925498bdd8a3.jpg"));
  }
```

이런 방식으로 작성하는 방법도 있던데, 이게 통합테스트인건지 궁금합니다. 맞다면 이런 방법은 어느 상황에 작성하는지 궁금합니다. 제가 진행하는것처럼 TDD를 작성할때 이런 테스트코드를 작성해도 괜찮은건지, 아니면 개발을 마치고 전체적인 테스트를 진행할 때만 작성하는건지, 무슨 상황에 어떤 테스트코드를 작성해야하는지 아직 미숙한 부분이 많은 것 같습니다.

# 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
위에 작성한대로, 일단 테스트를 잘 작성했는지 봐주시면 감사하겠습니다. 그리고 기본적인 규칙을 최대한 지키며 코드를 작성 했다고 생각하는데, 부족한 부분이 있는지도 궁금합니다. 
그리고 커밋을 찍을 때, 제가 한 것처럼 하나하나 다 찍는 것이 옳은 것인지도 궁금합니다. 너무 작게 나눠서 찍는 경향이 있는 것 같다고 생각이 들었습니다 .

그리고 이후에 배우겠지만, 그렇다면 왜 `서비스, 레포지토리, 컨트롤러, 모델` 구조가 널리 알려지고 잘 사용되는지 궁금하기도 합니다. 솔직히 지금까지 배운 내용으로 컨트롤러 하나에 작성하니까 코드 작성도 편하고 헷갈리는 부분도 덜 해서 좋다고 생각하는데, 왜 그런 복잡한 구조를 사용하는 것인지 궁금합니다..

또한 제가 `TDD` 방식으로 이번 과제를 구현하였는데, 제가 잘 진행한 것인지, 그리고 솔직히 더 오래걸리기만 하는 것 같고 이점을 못느끼겠는데 그래도 이게 좋은 습관이 맞는 것인지도 궁금합니다. 실제 실무에서도 이런 방식을 사용하는지 궁금합니다…

2024-06-29 12:40 UTC, pci2676 commented
> # 코드 작성하면서 어려웠던 점
> 과제 시작 전 이렇게 다짐했었습니다.
> 
> > 지금까지 내가 했던 매우 얕은 지식의 웹 개발 지식은 모두 잊자!
> 
> 그 개념을 기반으로, 기존 알고 있던 서비스, 레포지토리, 컨트롤러, 모델 형식의 구조가 아닌, 단순 모델-컨트롤러 구조로 구현하였는데, 이렇게 구현해도 잘 작동이 되는 것이 또 새로웠던 것 같습니다.
> 
> 어렵던 부분은 테스트부분이였습니다. 테스트코드를 작성하다가 다음과 같은 방식을 보게 되었습니다.
> 
> ```java
> public void testGetAllProducts() throws Exception {
>       mockMvc.perform(get("/api/products"))
>               .andExpect(status().isOk())
>               .andExpect(content().contentType(MediaType.APPLICATION_JSON))
>               .andExpect(jsonPath("$[0].name").value("아이스 카페 아메리카노 T"))
>               .andExpect(jsonPath("$[0].price").value(4500))
>               .andExpect(jsonPath("$[0].imageUrl").value("https://st.kakaocdn.net/product/gift/product/20231010111814_9a667f9eccc943648797925498bdd8a3.jpg"));
>   }
> ```
> 
> 이런 방식으로 작성하는 방법도 있던데, 이게 통합테스트인건지 궁금합니다. 맞다면 이런 방법은 어느 상황에 작성하는지 궁금합니다. 제가 진행하는것처럼 TDD를 작성할때 이런 테스트코드를 작성해도 괜찮은건지, 아니면 개발을 마치고 전체적인 테스트를 진행할 때만 작성하는건지, 무슨 상황에 어떤 테스트코드를 작성해야하는지 아직 미숙한 부분이 많은 것 같습니다.

보통의 경우 통합테스트는 애플리케이션에서 동작하는, 상호작용하는 구성요소들을 실제 구현체를 활용하는 경우를 말합니다. (다만 일부분은 대체하곤 합니다. 외부 API 등..) 지금의 경우 애플리케이션에서 사용하는 DB를 사용하여 테스트하는 코드이기 때문에 통합테스트라고 불러도 문제 없을것 같습니다.

2024-06-29 12:45 UTC, pci2676 commented
> # 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
> 위에 작성한대로, 일단 테스트를 잘 작성했는지 봐주시면 감사하겠습니다. 그리고 기본적인 규칙을 최대한 지키며 코드를 작성 했다고 생각하는데, 부족한 부분이 있는지도 궁금합니다. 그리고 커밋을 찍을 때, 제가 한 것처럼 하나하나 다 찍는 것이 옳은 것인지도 궁금합니다. 너무 작게 나눠서 찍는 경향이 있는 것 같다고 생각이 들었습니다 .

본문에 적어주신 글을 먼저 읽고 답변드리고 있어서 작성하신 코드와 커밋에 대해서는 추후 코멘트로 남겨드리겠습니다. 😄 

> 그리고 이후에 배우겠지만, 그렇다면 왜 `서비스, 레포지토리, 컨트롤러, 모델` 구조가 널리 알려지고 잘 사용되는지 궁금하기도 합니다. 솔직히 지금까지 배운 내용으로 컨트롤러 하나에 작성하니까 코드 작성도 편하고 헷갈리는 부분도 덜 해서 좋다고 생각하는데, 왜 그런 복잡한 구조를 사용하는 것인지 궁금합니다..

단일 책임 원칙에 대해 아실까요? 아신다면 각자(service, repository, controller, model)의 역할과 책임이 다르다고 생각해보신적 있으실까요?  
 
> 또한 제가 `TDD` 방식으로 이번 과제를 구현하였는데, 제가 잘 진행한 것인지, 그리고 솔직히 더 오래걸리기만 하는 것 같고 이점을 못느끼겠는데 그래도 이게 좋은 습관이 맞는 것인지도 궁금합니다. 실제 실무에서도 이런 방식을 사용하는지 궁금합니다…

TDD는 이름에서 알 수 있듯 하나의 개발방법론입니다. 무조건 정답이라고 볼 수는 없지만 하나의 좋은 방법론이라고 받아들이시면 좋을것 같습니다.

추가로 TDD의 장점을 느끼지 못하신것 같은데요. TDD의 첫번째 사이클에 해당하는 테스트 코드를 작성하는 부분에서 테스트 코드를 통해 우리가 얻을 수 있는 장점은 무엇이라고 생각하시나요? TDD는 테스트를 작성하면서 시작하는 사이클이라 테스트를 작성하게 하는데 이는 곧 테스트 코드의 장점이 TDD에 녹아들어 있다고 볼 수 있지 않을까요?

실무에서도 항상 TDD를 이용한 개발을 하지는 않고 가능한 상황에서는 사용할 때가 있습니다. 😄

2024-06-29 12:50 UTC, pci2676 commented
> # step2
> 직접 타임리프를 이용하여 템플릿을 짜고 AJAX 방식을 이용하여 구현했는데, 이러한 방법이 후에 백엔드와 프론트엔드가 연동하는 방식이랑 비슷한 것인지 궁금합니다. 

프론트 엔드측의 코드를 질문 주신것이라면 제 답변의 범위를 조금 넘어설 것 같습니다. 다만 제가 경험한 현업에서는 타임리프를 활용하는 코드는 그다지 선호되는 편이 아니었습니다. 하지만 ajax와 같은 통신 라이브러리는 사용하곤 합니다. 😄   
보통의 경우 백엔드 개발자가 프론트 엔드 영역의 코드를 작성할 일은 거의 없고 어드민 정도의 페이지를 작성할 수 있는데 이러한 경우에도 타임리프가 아닌 vue 혹은 react등 다른 프론트엔드 측 프레임워크를 활용합니다.

> 기존 api 컨트롤러 외에 ViewController를 따로 구현하였는데, 이것도 없이 그냥 연결하는 방법은 어떤 것이 있는지 궁금합니다!

제가 알기로 할수는 있는데요.. 일부러 그렇게 하는 경우는 잘 보지 못한것 같습니다.

view 전용 컨트롤러를 없애려 하시는 이유는 무엇일까요? 꼭 그래야만 하는 이유가 있을까요?

2024-06-29 12:55 UTC, pci2676 commented
> # step3
> 힌트에
> 
> > JdbcTemplate, SimpleJdbcinsert 및 JdbcClient와 같은 도구를 사용할 수 있다.
> 
> 라고 쓰여있어서 코드를 다 작성한 후 알아보게 되었는데 `JdbcClient` 가 더 현대적이고 간결하다는 것을 보게 되었습니다. 당연히 저는 `JdbcTemplate` 로 진행을 한지라 뒤늦게 찾아보고 살짝 아쉬웠는데, 성능이나 규칙? 같은 부분에서 큰 차이가 있는 것인지 궁금합니다. 만약 JdbcClient를 이용하여
> 
> ```java
> public void insertProduct(Product product) {
>     String sql = "INSERT INTO product (name, price, image_url) VALUES (?, ?, ?)";
>     jdbcTemplate.update(sql, product.getName(), product.getPrice(), product.getImageUrl());
> }
> ```
> 
> 이 코드를 바꾼다 가정하면
> 
> ```java
> public void insertProduct(Product product) {
>     String sql = "INSERT INTO product (name, price, image_url) VALUES (?, ?, ?)";
>     jdbcClient.sql(sql)
>               .param(product.getName())
>               .param(product.getPrice())
>               .param(product.getImageUrl())
>               .update();
> }
> ```
> 
> 이런 식으로 되는 것 같은데, 방법이 맞는지, 그리고 기존 JdbcTemplate와 비교했을때 차이가 큰지 궁금합니다.

성능적인 부분에서 유의미한 차이는 있지 않은것으로 알고 있습니다.

다만 파라미터를 바인딩하는 방식에 변화가 있는것으로 알고 있습니다.

param 메서드를 이용할시 값만 입력하는 것이 아닌 파라미터의 이름을 함께 입력하여 순서에 구애받지 않고 param을 build할 수 있는것으로 알고 있습니다.

아래 글을 읽어보시면 차이를 쉽게 보실 수 있을것 같습니다.

https://www.baeldung.com/spring-6-jdbcclient-api

2024-06-29 13:09 UTC, pci2676 requested changes
반갑습니다 🤠 

조금 질문에 대한 답변과 조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

모든 요구사항을 한번에 개선하시기 어렵다면 코멘트를 남겨주시고 할 수 있는 부분부터 점진적으로 적용해주시면 됩니다. 다음 단계로 넘어가면서 조금씩 개선하셔도 좋습니다.

2024-06-29 13:09 UTC, pci2676 commented on src/test/java/gift/ProductControllerTest.java
> +    private ProductController productController;
Mock을 사용하신 이유가 있을까요? 이러한 테스트의 장단점에 대해 알고 계실까요?

+jdbcTemplate는 사용하지 않는 것 같네요. 😄

2024-06-29 13:09 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +@RequestMapping("/api/products")
전체적으로 api uri의 설계와 네이밍이 잘 되어있는것 같네요 👍

2024-06-29 13:09 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    }
이번에는 controller에 모든 구현을 하셨는데요.

이렇게 작성한 코드는 단일책임원칙을 잘 지키고 있다고 볼 수 있을까요?

controller의 역할과 책임은 무엇이라고 생각하실까요?

비단 addProduct 메서드만을 보고 말씀드리는 것은 아니고 다른 controller 메서드도 비즈니스 로직을 구현해두신것 같습니다.

객체지향적으로 작성하는것에 대해 고민해보시면 큰 도움이 될 것 같습니다. 😄

2024-06-29 13:09 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        }
null을 반환하는 이유가 있었을까요?

exception을 발생시키는 것에 대해 고려해보셨을까요?

2024-06-29 13:09 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public Product addProduct(@RequestBody Map<String, Object> productData) {
Product는 DB에 저장하는 데이터 모델로도 사용되고 응답용 객체로도 사용되는것 같아보입니다.

두가지 용도로 사용된다면 이 또한 SRP를 위반하는 것으로 보입니다.

이러한 경우 발생할 수 있는 문제점이 무엇이 있을까요? 고민해보시고 개선해보시면 좋을것 같습니다. 😄

2024-07-01 03:49 UTC, kanguk01 commented on src/main/java/gift/ProductController.java
> +        }
예외 처리에 관하여 이번주차에 리팩토링 진행하도록 하겠습니다! 😊

2024-07-01 03:49 UTC, kanguk01 commented on src/main/java/gift/ProductController.java
> +@RequestMapping("/api/products")
감사합니다!!😆

2024-07-01 03:52 UTC, kanguk01 commented on src/test/java/gift/ProductControllerTest.java
> +    }
블로그 글 참고하였습니다. 각 테스트마다 독립적으로 실행되도록 하며 테스트의 구성 요소들을 해당 테스트 내부에 작성하도록 하여 수정하도록 하겠습니다!

2024-07-01 06:09 UTC, kanguk01 commented on src/test/java/gift/ProductControllerTest.java
> +    private ProductController productController;
### Mock?

<aside>
❗ 실제 객체의 동작을 모방하여 테스트할 때 사용하는 가짜 객체

</aside>

```java
@Mock
private ProductDao productDao;
```

`@Mock` 을 설정하면 productDao는 실제 객체가 아닌 Mock 객체로 초기화된다. `Mockito` 가 생성한 가짜 객체로, `ProductDao`를 모방한다.

```java
@BeforeEach
public void setUp() {
    MockitoAnnotations.openMocks(this);
}
```

`MockitoAnnotations.openMocks(this)` 는 모든 `@Mock` 이 붙은 객체를 초기화하는 것이다. 

결국 테스트 클래스의 Mock 객체를 주입하는 과정이다.

**장점**

- **독립성** - 테스트가 `ProductDao` 의 실제 구현에 의존하지 않아서 컨트롤러를 독립적으로 테스트할 수 있다.
- **속도** - 실제 DB를 사용하는것이 아니므로 테스트 속도를 단축시킬 수 있다.

**단점**

- **실제 동작과의 괴리** - Mock 이기 때문에 실제 ProductDao를 완벽하게 모방하지는 못할 수 있다. 그래서 예기치 못한 문제가 발생할 수도 있다.
- 테스트 코드의 유지보수 - Mock 설정이 많아질수록 테스트 코드의 복잡성이 증가한다.

**요약**

Mock 을 활용한 테스트는 빠르고 독립적인 테스트를 가능하게 한다. 하지만 실제 시스템 동작을 완벽하게 구현하지는 못하므로 신뢰성을 검증하는 것이 중요하다.

---
라고 정리해보았습니다. 단위테스트 부분이기 때문에 Mock을 활용해도 괜찮을 것이라고 생각하여 적용했습니다!!

+JdbcTemplate은 생각없이 추가해놓고 확인을 못했습니다 ㅠ

2024-07-01 06:12 UTC, kanguk01 commented on src/main/java/gift/ProductController.java
> +    }
해당 부분은 2주차에 리팩토링 예정입니다! 감사합니다 😆

2024-07-01 06:19 UTC, kanguk01 commented on src/main/java/gift/ProductController.java
> +    public Product addProduct(@RequestBody Map<String, Object> productData) {
DB에 처리하는 Product 객체와 응답용 객체인 ProductDTO를 구별해서 처리하면 해결된다고 생각합니다! 

문제점으로는, DB에 저장되는 요소들과 받을 때와 반환하는 속성들이 다른 경우에, 이 두 가지 용도를 모두 고려해야한다는 단점이 있고, 응답용 객체가 바뀔 때, 데이터 모델에도 영향이 간다는 문제도 있다고 생각이 듭니다..!

해당 부분도 이번 주차에 리팩토링 진행하도록 하겠습니다!

2024-07-01 08:12 UTC, pci2676 approved these changes
수고하셨습니다. 🚀

2024-07-01 08:13 UTC, merged