경북대 BE_이지호_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #152
Opened 2024-06-28 05:10 UTC by GitJIHO

> step2까지의 과정을 step3 브렌치에 pull하여 진행하였습니다.
> [DOCS: 3단계 README 추가] 커밋부터 step3 입니다.

**코드 작성하면서 어려웠던 점**
---

- 구조적으로 리팩토링하는 과정이 익숙치 않았습니다

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분**
---

- step2까지의 코드와는 다르게 디렉구조를 세부적으로 분할하여 진행하였는데, 해당 분할방법이 맞는지 궁금합니다.
- 예외 처리를 추가적으로 해야하는 부분이 있는지, 또한 해당 예외처리를 controller단에서 직접적으로 진행하였는데 다른 적절한 방법을 알고 싶습니다.
- else나 switch문 대신 if단에 return을 넣어 해당 예약어의 기능을 간접적으로 구현하였는데, 해당 방식도 적절하지 않은지 궁금합니다.

2024-06-28 15:45 UTC, sang5c requested changes
3단계까지 고생 많으셨습니다!  

먼저 꼭 드리고 싶은 말은 `주어진 요구사항을 모두 만족했는가` 를 최우선으로 고민해보시면 좋을 것 같습니다.  
요구사항을 만족하기 위해서 최선을 다해보고, 모두 만족한 다음에 다른 고민들을 해보시면 좋을 것 같아요!  
1, 2단계 리뷰에서 남겨드린 내용에 대해 동일하게 적용이 필요하니 꼭 적용해주시고 아래 답변들 읽어주세요 :) 
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/28#pullrequestreview-2148064822
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/99#pullrequestreview-2148204460

리팩터링은 시간과 경험이 필요한 과정이라 천천히 익숙해져도 괜찮습니다. 시작하는 단계이니 여러 도전들을 해보시면 좋을 것 같아요.

---

> step2까지의 코드와는 다르게 디렉구조를 세부적으로 분할하여 진행하였는데, 해당 분할방법이 맞는지 궁금합니다.  

👍👍  이 부분은 step2에서 드린 답변을 참고해주세요!  
  
질문 주실 때 어떤 고민을 통해 이런 결과를 만들었는지 질문 배경을 저에게 좀 더 알려주시면 더 좋은 답변을 드릴 수 있습니다 🙇

> 예외 처리를 추가적으로 해야하는 부분이 있는지, 또한 해당 예외처리를 controller단에서 직접적으로 진행하였는데 다른 적절한 방법을 알고 싶습니다.  

좋은 고민입니다만, 차주에 진행하게 될 내용입니다 👍  

> else나 switch문 대신 if단에 return을 넣어 해당 예약어의 기능을 간접적으로 구현하였는데, 해당 방식도 적절하지 않은지 궁금합니다.  

if문 내에서 return하는게 프로그래밍 요구사항에서 의도한 바가 맞습니다! 
`힌트: if 조건절에서 값을 return하는 방식으로 구현하면 else를 사용하지 않아도 된다.
`

2024-06-28 15:45 UTC, sang5c commented on src/main/java/gift/dao/ProductDAO.java
> +public class ProductDAO {
DAO는 어떤 이유로 나누게 되었고, 어떤 역할을 하면 좋을까요?

2024-06-28 15:45 UTC, sang5c commented on src/main/java/gift/dao/ProductDAO.java
> +    private final RowMapper<Product> rowMapper = new BeanPropertyRowMapper<>(Product.class);
필드는 생성자보다 위에 위치해야 합니다!

2024-06-28 15:45 UTC, sang5c commented on src/main/java/gift/dto/Product.java
> +    public String toString() {
toString 메서드가 사용되지 않는데 구현한 이유가 있을까요?

2024-06-28 15:45 UTC, sang5c commented on src/main/java/gift/dto/Product.java
> +    }
개행이 빠졌네요!

2024-06-28 15:45 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +public class ProductService {
서비스는 어떤 이유로 분리했고 어떤 책임을 가지면 좋을까요?  
컨트롤러에 있는 코드는 어떤 이유로 남겨지고 일부만 서비스가 되었나요?

2024-06-30 12:17 UTC, GitJIHO commented on src/main/java/gift/dao/ProductDAO.java
> +public class ProductDAO {
DAO는 실시간 수업 과정 중에 강사님과 함께 진행한 DB 연동 실습 과정에서 DAO를 사용했던 내용을 토대로 진행중인 코드에도 적용해 보았습니다.

DB에 데이터를 access하기 위해 필요한 메소드 작성이나, JDBC 의존성 주입 등의 역할을 수행하는 것을 목적으로 하였습니다.

혹시 제가 잘못 이해한 부분이 있을까요? 이번에 DAO 분리를 처음 해봐서 익숙하지 않았습니다,,

2024-06-30 12:18 UTC, GitJIHO commented on src/main/java/gift/dao/ProductDAO.java
> +    private final RowMapper<Product> rowMapper = new BeanPropertyRowMapper<>(Product.class);
네 주의하겠습니다!

2024-06-30 12:21 UTC, GitJIHO commented on src/main/java/gift/dto/Product.java
> +    public String toString() {
처음에 추가할때는 혹시 나중에 객체 정보를 IDE console에 출력해 확인할 상황이 생기지 않을까싶어 만들었지만, 정작 사용하지 않았고 삭제를 까먹었습니다.
혹시 다른 상황에서도 toString 메서드를 사용하는 경우가 있나요?

2024-06-30 12:24 UTC, GitJIHO commented on src/main/java/gift/dto/Product.java
> +    }
네 추가했습니다!

2024-06-30 12:29 UTC, GitJIHO commented on src/main/java/gift/dto/Product.java
> +    }
혹시 코드 제일 마지막 부분에 개행을 말씀해주신게 맞으신가요?

혹시 맞다면 지금도 개행이 없다고 뜨는지 궁금합니다.
지금 인텔리제이에서는 [remove: 사용하지 않는 메서드 삭제](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/152/commits/032fb0d0529c90cce3d0917392839985661bf532) 해당 커밋 이후에 53행까지 존재하는데 github에서는 52행까지만 존재하는 것처럼 보이는 것 같습니다..

2024-06-30 12:38 UTC, GitJIHO commented on src/main/java/gift/service/ProductService.java
> +public class ProductService {
>서비스는 어떤 이유로 분리했고 어떤 책임을 가지면 좋을까요?

의도는 DAO를 주입받아 이를 활용한 비즈니스 로직을 구현하기 위해서 service를 따로 분리하였습니다. controller단에서 모두 진행할 수는 있지만 일반적인 스프링 웹 패키지 구조가 service단을 분리한 구조가 많아보여서 한번 시도해보았습니다..!

controller단에서 중복적으로 사용되는 비즈니스 로직 관련 코드들을 좀 더 간단하게 표현하기 위한 목적도 있었습니다.

>컨트롤러에 있는 코드는 어떤 이유로 남겨지고 일부만 서비스가 되었나요?

말씀주신 내용을 잘 이해하지 못했습니다 ㅠ
컨트롤러에서 서비스코드가 사용되지 않고 직접적으로 product의 id를 조절하는 수정 메서드 부분을 말씀하시는건가요?

2024-07-01 13:01 UTC, sang5c approved these changes
1주차 미션 고생 많으셨습니다 👏  

추가로 코멘트 남겼으니 읽어보시고 궁금한 내용 언제든 질문주세요!  
다음 미션에서 수정되지 않으면 동일한 리뷰를 드릴 예정입니다 😉
2주차도 파이팅입니다 💪

2024-07-01 13:02 UTC, merged