충남대 BE_김해경_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #157
Opened 2024-06-28 06:00 UTC by HaegyeongKim01

코드 리뷰 부탁드립니다.  감사합니다.
Controller와 Dao에서 동일한 기능을 수행하는 각 메소드의 이름을 지정할 때, 메소드 이름을 기능에 맞게 일관성 있게 유지하는 것이 좋을지, 아니면 클래스의 특성에 맞게 지정하는 것이 좋을지 궁금합니다.
예를 들어, Controller에서 addProduct라고 했을 경우, Dao에서는 데이터베이스와 관련이 깊은 클래스이므로 insertProduct처럼 각 클래스 특성에 맞게 다른 이름을 사용하는 것이 좋을지, 아니면 addProduct로 일관성 있게 이름을 동일하게 유지하는 것이 더 일반적인지 알고 싶습니다. 

Mapper를 RowMapper를 상속 받아 override로 구현해주었는데 이렇게 하면 Mapper 하려는 객체의 필드명이 수정되거나 삭제 혹은 추가 되는 경우에 변경해주어야 하는 번거로움이 있을 것 같은데 예를 들어, ModelMapper 같은 라이브러리를 사용하는 것이 더 나은 것인지 궁금합니다.

2024-06-29 14:34 UTC, Hyeon9mak requested changes
안녕하세요 해경님~ 미션을 함께할 최현구입니다 🙇‍♂️
1주차 과제 잘 진행해주셨어요.

> Controller와 Dao에서 동일한 기능을 수행하는 각 메소드의 이름을 지정할 때, 메소드 이름을 기능에 맞게 일관성 있게 유지하는 것이 좋을지, 아니면 클래스의 특성에 맞게 지정하는 것이 좋을지 궁금합니다.

결국 저희가 코드 네이밍을 고민하는 이유는 먼 미래에 다른 사람이 해경님의 코드를 읽게 되었을 때
최대한 쉽게, 최대한 빠르게 코드의 의도를 이해하도록 하기 위함이겠죠.
때문에 업계에서 고정적으로 사용되는 고유명사, 네이밍 등이 존재하는데요,
(이것들은 차차 알아가게 되실 것이니 급하게 생각하지 않으셔도 됩니다.)
어차피 클래스 파일 명칭으로 계층을 드러내줄 수 있으므로
조금 더 기능에 집중한 명칭을 사용해주는게 좋다고~ 저는 생각합니다 😄 

간단한 코멘트 몇 가지 남겼습니다.
궁금하신 점 언제든지 질문 남겨주세요~

2024-06-29 14:34 UTC, Hyeon9mak commented on README.md
> +
요구사항을 체크박스를 통해 잘 정리해주셨군요~ 👍 
요런 사소한 습관이 나중에 큰 결과를 만든다고 생각합니다.

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/controller/ProductController.java
> +
layered architecture 에서 controller 계층은 http 통신과 java 코드간 변환을 담당하는 계층이에요!
즉, 표현(presentation)을 다루는 것에만 집중합니다.

현재는 http 통신과 java 코드간 변환, 영속(persistence) 관련 내용에도 관여하는 걸로 보이는데요,
ProductDao 와 ProductController 사이 중간 소통을 담당하는 클래스를 하나 더 만드는 건 어떨까요? 😉

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
`@Controller` 와 `@RestController` 의 차이는 무엇일까요?

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/controller/ProductController.java
> +    }
`@GetMapping()`, `@PostMapping("")` 사이 일관성이 없어보이네요.
일관성은 가독성을 높이고, 가독성은 유지보수성과 생산성을 높이는 중요한 포인트입니다.
코드 작성 방식을 통일해주세요!

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/controller/ProductController.java
> +
언제 사용되는 메서드일까요?

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/dao/ProductMapper.java
> +    }
> Mapper를 RowMapper를 상속 받아 override로 구현해주었는데 이렇게 하면 Mapper 하려는 객체의 필드명이 수정되거나 삭제 혹은 추가 되는 경우에 변경해주어야 하는 번거로움이 있을 것 같은데 예를 들어, ModelMapper 같은 라이브러리를 사용하는 것이 더 나은 것인지 궁금합니다.

구현 상황과 방식, 코드 관리 주체에 따라 다를 것 같네요.
현재와 같은 경우 컬럼 개수가 많지 않기 때문에 큰 불편함이 없었을 것 같은데, 해경님은 어떻게 느끼셨나요?

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/dao/ProductMapper.java
> +    }
또 row mapper 를 꼭 별도 클래스파일로 분리하지 않고도 아래와 같은 방법으로 활용해볼 수 있겠어요.

```java
(rs, rowNum) -> new Product(
                rs.getLong("id"),
                rs.getString("name"),
                rs.getInt("price"),
                rs.getString("imageUrl"));
```

이러면 `ProductDao` 의 멤버변수로도 활용할 수 있겠죠!

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/dao/ProductMapper.java
> +}
https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/ 😉

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/vo/Product.java
> +    public Product() { }
기본 생성자를 둔 이유가 있을까요?

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/vo/Product.java
> +    }
생성자 체이닝을 활용해보아도 좋겠네요!

```suggestion
    public Product(String name, int price, String imageUrl) {
        this(null, name, price, imageUrl);
    }

    public Product(Long id, String name, int price, String imageUrl) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.imageUrl = imageUrl;
    }
```

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/java/gift/vo/Product.java
> +    // getter
꼭 setter 가 필요했을까요? setter 대신 생성자를 적극 활용해보는 것도 좋을거 같아요 😉 👍

2024-06-29 14:34 UTC, Hyeon9mak commented on src/main/resources/application.properties
> +logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
로깅 레벨을 debug 로 변경한 이유가 있을까요?

2024-07-03 08:05 UTC, HaegyeongKim01 commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
@Controller는 주로 View를 반환하는데 사용되며 @RestController는 JSON 객체 반환에 사용됩니다...!

2024-07-03 08:06 UTC, HaegyeongKim01 commented on src/main/java/gift/controller/ProductController.java
> +
코드를 수정 하여 필요 없어진 메소드인데 삭제하는 것을 잊어버렸습니다...하핳

2024-07-03 08:09 UTC, HaegyeongKim01 commented on src/main/java/gift/vo/Product.java
> +    public Product() { }
음...필요 없는 것 같습니다

2024-07-03 08:10 UTC, HaegyeongKim01 commented on src/main/resources/application.properties
> +logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
오류 해결 중 debug해보기 위해서 사용했었습니다! 다음 단계에서 삭제 했습니다!

2024-07-03 08:10 UTC, HaegyeongKim01 commented on src/main/java/gift/vo/Product.java
> +    // getter
아하! 넵! ProductMapper에서 setter를 사용하였는데 다음 단계에서 생성자로 생성하도록 변경하여 setter를 없애주었습니다.

2024-07-03 10:32 UTC, Hyeon9mak approved these changes
피드백 모두 반영해주신것 같네요! 😄 
2주차 진행을 위해 approve 하겠습니다!
2주차 과제 PR 에서 만나요~

2024-07-03 10:32 UTC, merged