충남대 BE_김유겸_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #159
Opened 2024-06-28 06:06 UTC by rladbrua0207

2024-06-29 14:16 UTC, Hyeon9mak requested changes
안녕하세요 유겸님~ 미션을 함께할 최현구입니다 🙇‍♂️
1주차 과제 잘 진행해주셨어요!
이미 스프링에 대한 이해가 어느정도 있으신걸로 보이네요~

> 커밋 단위를 설정하는 것과 관련하여 질문이 있습니다. 구현하다 보면 간단한 기능들은 중간에 끊기가 어려워서 주로 책임 영역별로 커밋을 하고 있습니다. 기능 단위로 커밋하는 것이 더 나을까요, 아니면 현재 방식이 괜찮을까요?

커밋은 결국 버전관리의 한 단위이죠. 문제점이 생겼을 때 롤백지점을 선택하기 용이한 것이 기준입니다.
게임을 한참 진행하다가 저장을 깜빡해서 초기로 돌아갔을 때의 허망함을 겪는 것처럼
커밋을 너무 큰 단위로 만들면 업무에 차질이 생길수도 있겠죠?
이를 위해서라면 가능하면 작은 단위, 기능 단위로 커밋을 하는게 좋을거 같아요.

> 아키텍처 구조를 설계하거나 메서드 패턴을 적용할 때 어떤 기준을 사용하는 것이 좋을지 조언을 구하고 싶습니다.

잘 아시겠지만 구조, 패턴 등은 모두 유지보수성, 생산성을 향상 시키기는 것이 목적입니다.
프로젝트에 대한 이해, 도메인에 대한 이해, 팀에 대한 이해가 높아야 하죠.
즉 개발 기술에만 관심을 갖는게 아니라 회사와 업무에 대한 관심이 전반적으로 높아야합니다.
그럼 자연스럽게 "우리 팀은 이렇게 하는게 더 좋은 것 같네!" 라는 기준이 설립되실거 같아요.
과제를 진행하는 동안에는 특정 상황 속에서 일하고 있다고 가정하고 아키텍처를 선택해보시는 것도 좋겠네요.

> Controller에서의 테스트 코드를 작성하는 방법에 대해서도 조언을 얻고 싶습니다. 
> Service 계층과 Domain 계층에 대해서만 테스트 코드를 작성해도 괜찮을까요? 

무얼 테스트 하고 싶으신 걸까요? 왜 테스트를 해야하나요?
이에 대해 먼저 설명을 해주시면 자세한 답변을 드릴 수 있을 것 같아요 😄 

간단한 코멘트 몇 가지 남겼습니다.
궁금하신 점 언제든지 질문 남겨주세요~

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/application/ProductService.java
> +    }
`@Autowired` 어노테이션을 사용하여 의존성을 주입 받는 것과 생성자를 통해 주입 받는 것의 차이는 무엇일까요?
그리고 생성자를 통한 의존성 주입에 `@Autowired` 가 꼭 필요할까요? 🤔

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductJDBCRepository.java
> +    }
중복해서 사용되기 쉬운 row mapper 를 메서드로 분리해주셨군요!
이를 멤버변수로 갖도록 하는 것은 어떨까요? 어떤 차이가 있을까요?

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductJDBCRepository.java
> +    }
simple jdbc insert 에 대해 알아보고 이를 활용해보는 것도 좋을 것 같아요 😄

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductMemoryRepository.java
> +
id(key) 와 value 를 다루는 구조에는 list 대신 map 도 잘 어울릴 것 같은데, 어떻게 생각하시나요? 😉 
조회 속도도 획기적으로 높아질거 같아요!

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductMemoryRepository.java
> +    }
동시성 이슈가 발생할 수도 있으므로, 원자성을 보장해주는 `AtomicLong` 등을 사용해보아도 좋겠네요!

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductRepository.java
> +}
인터페이스로 명세만 하고, 실 구현체를 나누어 선택해주셨군요~ 👍

2024-06-29 14:16 UTC, Hyeon9mak commented on src/main/java/gift/product/presentation/ProductController.java
> +    }
상품 컨트롤러만 접근제한자를 기본(package-default)로 채택하신 이유가 있을까요?

2024-06-29 14:16 UTC, Hyeon9mak commented on src/test/java/gift/product/application/ProductServiceTest.java
> +    }
테스트 코드도 단단히 잘 작성해주셨네요! 👍

2024-06-29 14:37 UTC, rladbrua0207 commented on src/main/java/gift/product/application/ProductService.java
> +    }
첫 번째 줄에서 말씀하신 것이 필드로 의존성 주입을 받는것을 말씀하신 거로 이해했는데 맞을까요? 필드주입으로 코드를 작성하였을 때 경고로 스프링 특정 버전부터 권장되지 않는 방법이라는 경고메시지가 나타나 생성자 주입으로 변경했습니다. 하나하나 고쳐가며 해결하느라 왜 그런지 깊게 생각해보지 못했네요..!

인터넷 검색을 통해 다음과 같은 이유를 알았습니다!
1. 테스트의 어려움: 객체를 직접 생성하며 의존성을 주입하는 생성자 주입을 사용하면 테스트가 더 용이하다. (필드주입은 스프링 컨테이너가 필요하다)
2. 의존성이 변경될 수 있다:  필드주입을 사용하면 객체가 생성된 후에도 의존성이 변경될 수 있다.
3. 순환 참조 문제가 발생할 가능성이 있다: 

하지만 명확한 예제가 없어 좀 더 공부해봐야 할 거 같습니다!


또한 생성자를 통한 의존성 주입에 @Autowired 어노테이션이 꼭 필요하지 않는거로 알고있습니다. 생성자가 하나만 있는 경우에는 생략할 수 있다고 알고 있습니다. 하지만, 의존성을 주입받았다는 것을 명시하기 위해 작성한 것 같습니다.

2024-06-29 15:10 UTC, rladbrua0207 commented
> 안녕하세요 유겸님~ 미션을 함께할 최현구입니다 🙇‍♂️ 1주차 과제 잘 진행해주셨어요! 이미 스프링에 대한 이해가 어느정도 있으신걸로 보이네요~
> 
> > 커밋 단위를 설정하는 것과 관련하여 질문이 있습니다. 구현하다 보면 간단한 기능들은 중간에 끊기가 어려워서 주로 책임 영역별로 커밋을 하고 있습니다. 기능 단위로 커밋하는 것이 더 나을까요, 아니면 현재 방식이 괜찮을까요?
> 
> 커밋은 결국 버전관리의 한 단위이죠. 문제점이 생겼을 때 롤백지점을 선택하기 용이한 것이 기준입니다. 게임을 한참 진행하다가 저장을 깜빡해서 초기로 돌아갔을 때의 허망함을 겪는 것처럼 커밋을 너무 큰 단위로 만들면 업무에 차질이 생길수도 있겠죠? 이를 위해서라면 가능하면 작은 단위, 기능 단위로 커밋을 하는게 좋을거 같아요.
> 
> > 아키텍처 구조를 설계하거나 메서드 패턴을 적용할 때 어떤 기준을 사용하는 것이 좋을지 조언을 구하고 싶습니다.
> 
> 잘 아시겠지만 구조, 패턴 등은 모두 유지보수성, 생산성을 향상 시키기는 것이 목적입니다. 프로젝트에 대한 이해, 도메인에 대한 이해, 팀에 대한 이해가 높아야 하죠. 즉 개발 기술에만 관심을 갖는게 아니라 회사와 업무에 대한 관심이 전반적으로 높아야합니다. 그럼 자연스럽게 "우리 팀은 이렇게 하는게 더 좋은 것 같네!" 라는 기준이 설립되실거 같아요. 과제를 진행하는 동안에는 특정 상황 속에서 일하고 있다고 가정하고 아키텍처를 선택해보시는 것도 좋겠네요.
> 
> > Controller에서의 테스트 코드를 작성하는 방법에 대해서도 조언을 얻고 싶습니다.
> > Service 계층과 Domain 계층에 대해서만 테스트 코드를 작성해도 괜찮을까요?
> 
> 무얼 테스트 하고 싶으신 걸까요? 왜 테스트를 해야하나요? 이에 대해 먼저 설명을 해주시면 자세한 답변을 드릴 수 있을 것 같아요 😄
> 
> 간단한 코멘트 몇 가지 남겼습니다. 궁금하신 점 언제든지 질문 남겨주세요~

답변 정말 감사합니다! 이해됐습니다!

Controller는 클라이언트의 요청을 처리하기위해 비즈니스 로직(service)을 호출한뒤 그 결과를가지고 클라이언트에게 적절한 응답을 주는것으로 알고있습니다. 또한 비즈니스 로직 처리는 주로 서비스 계층에서 이루어지며, Controller는 서비스 계층의 결과를 받아와 HTTP 응답으로 변환하여 클라이언트에게 반환해주는 역할밖에 안한다고 알고있어서 어떤 검증 로직을 해야하지? 라는 의문이 있어서 질문드렸었는데, 헤더검증 및 HTTP 상태코드, 인증 및 권한 검증이 있다는걸 알게됐습니다. 아직 어떻게 테스트해야 할 지는 잘 모르지만 인터넷에 찾아보니 MockMvc과 같은 컨트롤러 검증 도구가 있어서 공부해보고 적용해 볼 예정입니다!

2024-07-01 09:38 UTC, Hyeon9mak approved these changes
안녕하세요 유겸님~ 피드백 반영 잘 해주셨어요~
질문 코멘트에 대한 답변이 몇 가지 누락된걸로 보여요.
유겸님께서 학습한 내용을 답변 코멘트로 남겨주시는건 어떨까요? 😉 

몇 가지 간단한 코멘트 추가로 남겼으니, 확인 후 2주차 과제 진행에 참고해주세요~
(merge 전 target branch 를 제가 임의로 유겸님 branch 로 변경했어요~ 이것도 참고해주세요~)

2024-07-01 09:38 UTC, Hyeon9mak commented on src/main/java/gift/product/application/ProductService.java
> +    }
> 생성자를 통한 의존성 주입에 `@Autowired` 어노테이션이 꼭 필요하지 않는거로 알고있습니다. 생성자가 하나만 있는 경우에는 생략할 수 있다고 알고 있습니다. 하지만, 의존성을 주입받았다는 것을 명시하기 위해 작성한 것 같습니다.

넵, 생성자 위 어노테이션 제거를 유도드리기 위한 코멘트였어요 😄

2024-07-01 09:38 UTC, Hyeon9mak commented on src/main/java/gift/product/domain/ProductMemoryRepository.java
> +
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/159#discussion_r1659835635

list 대신 map 을 사용해도 좋을거 같아요 😉

2024-07-01 09:39 UTC, merged

2024-07-01 09:55 UTC, rladbrua0207 commented on src/main/java/gift/product/presentation/ProductViewController.java
> +
제가 comment를 달아본게 처음이어서 Submit을 하기전에 제 comment가 전송이 안되는지 몰라서 제가 남긴 코멘트가 멘토님께 안보였나보네요... 지금이나마 Submit했습니다..!

@Autowired 어노테이션은 더 신경쓰겠습니다!

리뷰 감사합니다 ㅎㅎ