경북대 BE_박한솔_1주차 과제(1~3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #164
Opened 2024-06-28 06:32 UTC by pjhcsols

JdbcProductRepository 클래스를 추가하여 Spring의 JdbcTemplate을 활용해 데이터베이스와 상호작용하는 기능을 구현했습니다.

 추가로 RowMapper를 람다식으로 사용하여 제품 객체와 데이터베이스 레코드를 매핑했습니다.

예외 처리 전략에 대한 리뷰를 부탁드립니다.
코드의 확장성과 유연성을 개선할 수 있는 방안에 대한 피드백도 환영합니다.

2024-06-28 16:08 UTC, lsm7179 requested changes
안녕하세요~ 한솔님!
리뷰를 함께 할 닉키라고합니다.
기능구현하느라 고생하셨어요 👍

몇가지 코멘트 드렸는데 확인부탁드립니다.🙏

2024-06-28 16:08 UTC, lsm7179 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +            return Optional.empty();
적절하게 Optional을 사용했네요👍
Optional은 주의하며 사용해야합니다.
https://dev-coco.tistory.com/178

2024-06-28 16:08 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +public class ProductService {
Service 계층 👍

2024-06-28 16:08 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +    private void validateProduct(Product product) {
product가 null일때 npe가 생길거같아요.😨

2024-06-28 16:08 UTC, lsm7179 commented on src/main/resources/schema.sql
> +);
적절하게 잘 만들어주셨네요👍

2024-06-28 16:08 UTC, lsm7179 commented on src/main/java/gift/util/ImageStorageUtil.java
> +        System.out.println("Attempting to delete image at path: " + imagePath);
System.out.println은 가급적 자제해야됩니다.
왜 그럴까요?🤔
https://hudi.blog/do-not-use-system-out-println-for-logging/
내용을 보고 수정해보아요.😃

2024-06-28 16:15 UTC, lsm7179 commented
> JdbcProductRepository 클래스를 추가하여 Spring의 JdbcTemplate을 활용해 데이터베이스와 상호작용하는 기능을 구현했습니다.
> 
> 추가로 RowMapper를 람다식으로 사용하여 제품 객체와 데이터베이스 레코드를 매핑했습니다.
> 
> 예외 처리 전략에 대한 리뷰를 부탁드립니다. 코드의 확장성과 유연성을 개선할 수 있는 방안에 대한 피드백도 환영합니다.

충분히 예외처리 잘 처리해주신거 같아요 😁

그러나 더 고민하고 공부할만한 예외처리에 레퍼런스를 한번 참고해주세요~😁
checked와 unchecked exception을 구분하고 / 공통 예외처리를 통하여 클라이언트에게 일관된 결과값을 주는게 좋습니다.
https://jojoldu.tistory.com/734
https://cheese10yun.github.io/spring-guide-exception/#null
https://steady-coding.tistory.com/583

2024-07-01 05:24 UTC, pjhcsols commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<List<Product>> getAllProducts() {
예외나 오류 상황 뿐만 아니라 여러 요청을 유연하게 처리할려고 사용하게 되었습니다.

2024-07-01 11:38 UTC, pjhcsols commented
넵 감사합니다! 요구사항을 정리하여 두번째 과제의 step0에 반영하였습니다. 리뷰 부탁드립니다

2024-07-01 11:47 UTC, pjhcsols commented on src/main/java/gift/util/ImageStorageUtil.java
> +        System.out.println("Attempting to delete image at path: " + imagePath);
감사합니다 2단계 step0에 수정하였습니다

2024-07-01 11:48 UTC, pjhcsols commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
자바 버전을 17로 기존에 학습하고 있어서 21을 사용하지 않았습니다. 2단계 step0에 반영하여 PR 보냈습니다.

2024-07-01 12:02 UTC, lsm7179 commented
> 넵 감사합니다! 요구사항을 정리하여 두번째 과제의 step0에 반영하였습니다. 리뷰 부탁드립니다

네 다음과제에서 뵙겠습니다. 해당과제 머지할테니 다음과제에서 반영해주세요.🔥

2024-07-01 12:02 UTC, merged