경북대 BE_정수현_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #167
Opened 2024-06-28 06:53 UTC by suhyeon7497

1. Entity는 DB에 1대1로 맵핑 되는 것으로 DB 저장에 사용되는 것이고, DTO는 View와 Controller 사이에서 이동되는 데이터의 형식이라고 보면 되는 것일까요?
ex) ProductDTO, Product (Product class의 인스턴스 하나하나가 Entity라고 생각해도 되는 것일까요?)
2. 그렇다면 ProductDTO에서 Product를 생성하여 ProductDao가 Product 인스턴스(Entity?)를 DB에 저장한다고 보면 될까요?
3. repository와 dao의 기능이 조금 겹친다고 생각하는데 어떤 점이 다른가요? (관점의 차이 인가요? 소프트웨어 공학적 관점... 이런 느낌? )
4. refactoring 할 부분도 알려주시면 좋을 것 같습니다!

감사합니다.

2024-06-30 10:56 UTC, sang5c requested changes
질문 주신내용을 읽어봤는데 이후에 차차 배울 내용이니 너무 조급해 마시고, 강의 듣고도 해결되지 않으시면 다시 질문해주세요!  

단, 강의를 듣기 전에 고민하셔야 되는 포인트가 있습니다.  
코드에서 DAO, DTO, Entity 용어를 사용하셨는데 수현님은 이 용어들을 뭐라고 정의했고, 왜 사용했는지 되돌아보시고, 강의 듣고 다시 말씀해주시면 제가 더 좋은 답변을 드릴 수 있을 것 같습니다.  

지금 별도의 리팩터링이 필요한 포인트는 없습니다. :)  

프로그래밍 요구사항, 과제 요구사항, 기능 요구사항을 모두 만족했는지 먼저 확인하시길 추천드립니다!

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
JdbcTemplate은 접근제어자가 필요하지 않을까요?  
기본적으로 최소한의 범위를 여는 것을 권장합니다.

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/controller/AdminController.java
> +        List<ProductResponseDto> productList = productDao.selectAllProduct()
stream 활용 👍

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/controller/DTO/ProductRequestDto.java
> +package gift.controller.DTO;
패키지 네이밍 컨벤션 위반입니다!  
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/controller/DTO/ProductRequestDto.java
> +public class ProductRequestDto {
DTO는 어떤 이유로 나누게 되었고, 어떤 역할을 수행하나요?  
Product와 ProductRequestDto는 어떤 차이가 있고 왜 하나로 존재해선 안되나요?

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/Application.java
> +public class Application implements CommandLineRunner {
해당 클래스가 다음 컨벤션을 만족하는지 확인해주세요.  
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html#1852

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/controller/DTO/ProductResponseDto.java
> +    public ProductResponseDto(Long id, String name, int price, String imageUrl) {
생성자들 사이에도 개행이 필요합니다.

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/model/ProductQuery.java
> +public enum ProductQuery {
ProductQuery는 어떤 이유로 enum이 되었나요?  
예를 들어 DAO 내에 아래와 같은 코드를 사용했을때와 어떻게 다를까요?
```java
private static final String SELECT_ALL_PRODUCT = "select id, name, price, image_url from products";
private static final String SELECT_PRODUCT_BY_ID = "select id, name, price, image_url from products where id=?";
// ...
```

2024-06-30 10:56 UTC, sang5c commented on src/main/java/gift/model/ProductDao.java
> +package gift.model;
DAO는 model일까요? 🤔

2024-07-01 01:58 UTC, suhyeon7497 commented on src/main/java/gift/controller/DTO/ProductRequestDto.java
> +package gift.controller.DTO;
넵! 소문자로 변경하겠습니다!

2024-07-01 02:01 UTC, suhyeon7497 commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
넵! 시정하겠습니다!

2024-07-01 02:08 UTC, suhyeon7497 commented on src/main/java/gift/controller/DTO/ProductRequestDto.java
> +public class ProductRequestDto {
Product와 ProductResponseDto를 나눈 이유는 클라이언트에게 DB에서 나오는 모든 정보를 제공하는 것은 보안상으로 좋지 않을 것이기 때문에 중간에 데이터를 정제하기 위해 만들었습니다. 
 위 부분을 분리하면서, ProductReqeustDto도 함께 분리한 것 같은데 ProductRequestDto를 분리한 명확한 이유는 없는 것 같습니다. 조금 더 공부를 해보고 다시 말씀드리겠습니다.

2024-07-01 02:09 UTC, suhyeon7497 commented on src/main/java/gift/controller/DTO/ProductResponseDto.java
> +    public ProductResponseDto(Long id, String name, int price, String imageUrl) {
넵! 시정하겠습니다!

2024-07-01 02:15 UTC, suhyeon7497 commented on src/main/java/gift/model/ProductDao.java
> +package gift.model;
MVC 패턴에서 model은 데이터베이스와 관련된 로직을 관리한다고 배웠습니다. 그런고로, dao는 database에 save, update, delete 등의 기능을 수행하기 때문에 model package에 들어가야 한다고 생각했습니다. snag5c님은 어떻게 생각하시나요?

2024-07-01 05:37 UTC, suhyeon7497 commented on src/main/java/gift/Application.java
> +public class Application implements CommandLineRunner {
새로운 DataBaseUtil에 분리하였습니다!

2024-07-01 10:19 UTC, suhyeon7497 commented on src/main/java/gift/controller/DTO/ProductRequestDto.java
> +public class ProductRequestDto {
ProductRequestDto를 통해 데이터 검증을 미리 진행할 수 있다는 점에 이점이 있다고 생각합니다. 뒷 단에 넘겨서 데이터 검증을 진행하면 중간과정을 계속 거쳐야하는 오버헤드가 발생할 것 같습니다.

2024-07-01 14:07 UTC, sang5c commented on src/main/resources/templates/product-form.html
> +</html>
no newline at a end of file!
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/91#discussion_r1660102660

2024-07-01 14:08 UTC, sang5c commented on src/main/java/gift/utility/DataBaseUtil.java
> +    @Autowired
여기도 생략할 수 있겠네요.

2024-07-01 14:13 UTC, merged

2024-07-01 14:18 UTC, sang5c commented
참고로 resolve는 제가 할 수 있도록 해주시면 감사하겠습니다 👍  
1단계 - https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/91
2단계 - https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/137

2024-07-06 07:56 UTC, suhyeon7497 commented on src/main/java/gift/model/ProductQuery.java
> +public enum ProductQuery {
query문이 많아질 염려를 해서 가독성 때문에 enum으로 작성했었습니다. 현재는 id로만 select를 진행하지만, where구문에 들어갈 다른 필드들을 위해 method를 만들어 처리한 후 query문을 넘겨줄 수 있지 않을까요?