경북대 BE_신성민_1주차 과제
kakao-tech-campus-2nd-step2/spring-gift-product pull request #17
Opened 2024-06-25 09:01 UTC by anaconda77

안녕하세요 경북대 BE 신성민 학생입니다. 1주차 과제 제출드립니다.

## 과제 수행 중에 궁금했던 점
### 1단계
- 이전에 스프링 강의를 학습할때 주로 GET, POST만 다루었었는데, 실무에서 PUT, PATCH, DELETE와 같은 메서드들도 자주 사용하는지 궁금합니다.

- 찾고자 하는 상품이 존재하지 않음, 상품 등록에 실패함 등 예외 상황에 대한 예외 처리 기능은 따로 구현하지 않았는데 과제의 의도에 부합하는지 궁금합니다.

- 상품 수정/삭제 메서드는 아무 것도 반환하지 않게 void형으로 작성하였는데, 과제 의도에 맞게 하였는지 궁금합니다.
### 2단계
- 실무에서 대부분의 경우에는 뷰 렌더링 작업을 프론트에서 담당하지만, 상황에 따라 서버에서 JSP나 타임리프와 같은 뷰-템플릿 엔진을 사용하여 렌더링을 한다는 얘기를 들었습니다. 
이것이 서비스의 특성에 따라 갈리는 건지 아니면 서비스 내에서 정적-뷰나 구성이 복잡하지 않은 뷰에 한해서 서버에서 렌더링을 하는건지... 어떠한 경우에 서버에서 렌더링을 하는지 궁금합니다. 

- 제품 정보 삭제 요청 시 GET 방식으로 URI에 상품 id을 경로 변수나 쿼리 파라미터로 노출 및 전달하는게 보안 상 좋지 않은 방식이라는 생각이 들었습니다. 따라서 대신 html 폼에 상품 관련 정보를 넣어 전송하는게 적절한 해결책이라 생각되어 POST 방식으로 메서드를 수정하였는데, 제 생각이 맞는지 궁금합니다.

### 3단계
- 스프링에서 JdbcTemplate/JPA 등 데이터 엑세스 기술을 사용하면 DateAccessException 하위 타입의 런타임-예외로 자동 변환해주는 기능이 있다는 내용을 학습하였습니다. 그런데 복구가 가능한 예외의 경우 
  #### 1. 체크-예외로 바꾸어서 처리를 의무화
  #### 2. 메소드에 throws를 명시하여 해당 예외가 발생할 수 있음에 대한 주의를 주어 상위 계층에서 예외를 처리하도록 유도
   두 가지의 처리 방식이 있다고 하는데, 실무에서는 둘 중 어느 방식을 사용하는지 궁금합니다. 

전반적으로 예외 처리나 테스팅에 대한 의무 사항은 없어서 해당 작업들은 별도로 하지 않았습니다.
과제 피드백 해주셔서 감사드립니다:)

2024-06-28 15:03 UTC, lsm7179 requested changes
안녕하세요~ 성민님!
리뷰를 함께 할 닉키라고합니다.
기능구현하느라 고생하셨어요. 👍

몇가지 간단한 코멘트 드렸는데 금방 반영 하실수 있을거에요.👍
PR을 main이 아니라 깃허브id로 바꿔서 올려주세요.

2024-06-28 15:03 UTC, lsm7179 commented on src/main/resources/templates/addForm.html
> +<head>
html을 열심히 만들어주셨네요👍

2024-06-28 15:32 UTC, lsm7179 commented
> 안녕하세요 경북대 BE 신성민 학생입니다. 1주차 과제 제출드립니다.
> 
> ## 과제 수행 중에 궁금했던 점
> ### 1단계
> * 이전에 스프링 강의를 학습할때 주로 GET, POST만 다루었었는데, 실무에서 PUT, PATCH, DELETE와 같은 메서드들도 자주 사용하는지 궁금합니다.
> * 찾고자 하는 상품이 존재하지 않음, 상품 등록에 실패함 등 예외 상황에 대한 예외 처리 기능은 따로 구현하지 않았는데 과제의 의도에 부합하는지 궁금합니다.
> * 상품 수정/삭제 메서드는 아무 것도 반환하지 않게 void형으로 작성하였는데, 과제 의도에 맞게 하였는지 궁금합니다.
> 
> ### 2단계
> * 실무에서 대부분의 경우에는 뷰 렌더링 작업을 프론트에서 담당하지만, 상황에 따라 서버에서 JSP나 타임리프와 같은 뷰-템플릿 엔진을 사용하여 렌더링을 한다는 얘기를 들었습니다.
>   이것이 서비스의 특성에 따라 갈리는 건지 아니면 서비스 내에서 정적-뷰나 구성이 복잡하지 않은 뷰에 한해서 서버에서 렌더링을 하는건지... 어떠한 경우에 서버에서 렌더링을 하는지 궁금합니다.
> * 제품 정보 삭제 요청 시 GET 방식으로 URI에 상품 id을 경로 변수나 쿼리 파라미터로 노출 및 전달하는게 보안 상 좋지 않은 방식이라는 생각이 들었습니다. 따라서 대신 html 폼에 상품 관련 정보를 넣어 전송하는게 적절한 해결책이라 생각되어 POST 방식으로 메서드를 수정하였는데, 제 생각이 맞는지 궁금합니다.
> 
> ### 3단계
> * 스프링에서 JdbcTemplate/JPA 등 데이터 엑세스 기술을 사용하면 DateAccessException 하위 타입의 런타임-예외로 자동 변환해주는 기능이 있다는 내용을 학습하였습니다. 그런데 복구가 가능한 예외의 경우
>   #### 1. 체크-예외로 바꾸어서 처리를 의무화
>   #### 2. 메소드에 throws를 명시하여 해당 예외가 발생할 수 있음에 대한 주의를 주어 상위 계층에서 예외를 처리하도록 유도
>   두 가지의 처리 방식이 있다고 하는데, 실무에서는 둘 중 어느 방식을 사용하는지 궁금합니다.
> 
> 전반적으로 예외 처리나 테스팅에 대한 의무 사항은 없어서 해당 작업들은 별도로 하지 않았습니다. 과제 피드백 해주셔서 감사드립니다:)

1단계 
* 실무에서는 다양한 html 메서드를 사용합니다. options도 알게 모르게 많이 사용합니다. 😁https://jaeyeong951.medium.com/options-%EC%9A%94%EC%B2%AD%EC%9D%80-%EC%B2%98%EC%9D%8C-%EB%B3%B4%EB%8A%94%EB%8D%B0%EC%9A%94-sop-cors-398f780601bb
* 해당과제에는 예외처리에 대한 내용은 없는거 같아요:) 다만 실무에서는 당연히 처리해야합니다.
* 수정/삭제에서 서버에서 내려줄 콘텐츠가 없으니 void로 잘 구현해주신거 같아요. 다만 HttpStatus코드도 같이 수정하면 더 좋을거 같네요.https://developer.mozilla.org/ko/docs/Web/HTTP/Status/204

2단계
* 실무에서는 상황에 따라 다릅니다.🤔 서비스 특성, 엔지니어 리소스, 프로젝트 기한 등등 다양한 변수가 있어서 특정하기 어렵습니다.
admin이나 관리페이지는 서버엔지니어가 할때도 많습니다.😁
* 클라이언트에서 get, post등으로 바꿔도 막을수 없습니다. 즉 post로 바꿔서 url path가 안보인다고 한들 개발자도구로 확인가능합니다.
그렇다면 어떻게 해야될까요?... 인증과 권한으로 해당 리소스를 삭제, 수정 할 수 있는지 판단합니다.(또는 테이블에 userId값이 있어서 해당유저가 아니면 못하게 한다던가 부가적인 작업이 필요합니다.)

3단계
* 이것도 케이스별로 다를거 같은데요. 반드시 처리해야되는경우 예를 들어 입금처리는 예외 처리를 의무화 할수 있을거 같네요. 아니면 배치를 통해서 후처리를 한다던가. 복구트랜잭션을 통해서 처리한다던가 할거 같아요. 반드시처리해야되는게 아니라면 api까지 상위로 예외를 올려서 로그나 모니터링을 통해 확인가능하게 합니다.

2024-06-30 08:09 UTC, anaconda77 commented on src/main/resources/schema.sql
> +)
앗 기본적인 것을 놓치고 있었네요..수정하겠습니다!

2024-06-30 08:09 UTC, anaconda77 commented on src/main/java/gift/controller/ProductController.java
> +    private ProductDao productDao;
롬복에 익숙해져서 당연히 생성자 주입으로 되는줄 알고 있었습니다..중요한 피드백 감사합니다!

2024-06-30 08:10 UTC, anaconda77 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<List<ProductResponseDto>> getAllProducts() {
Dto를 그대로 반환하는 대신 ResponseEntity<>에 감싸서 반환하면 헤더나 http 상태 코드 등을 설정할 수 있기 때문에, REST API 방식에 적합하다고 판단되어 사용하였습니다.

2024-06-30 08:10 UTC, anaconda77 commented on src/main/java/gift/controller/ProductController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
404 상태코드의 뜻을 잘못 이해하고 있었습니다
서버에서 페이지가 정상적으로 리턴되었고, 0개의 결과 값을 정상적으로 반환한 것이므로 200 상태코드로 수정하겠습니다!

2024-06-30 08:10 UTC, anaconda77 commented on src/main/java/gift/controller/ProductController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
위와 동일하게 수정하겠습니다

2024-06-30 08:10 UTC, anaconda77 commented on src/main/java/gift/dto/ProductResponseDto.java
> +public record ProductResponseDto(Long id, String name, int price, String imageUrl) {
이번주차 강의때 우연히 record 클래스에 대해 알게 되었는데, getter와 같이 기본 메서드들을 자동으로 생성해주어서 코드 작성의 번거로움도 덜하고 DTO에 적용해도 큰 문제가 없겠다는 생각이 들어서 한번 사용해보았습니다.

2024-06-30 08:10 UTC, anaconda77 commented on src/main/java/gift/model/Product.java
> +    }
도메인 객체는 변경되는 경우가 매우 적으므로 의존 시의 변경 파급력이 적은 반면, DTO는 클라이언트의 요구 사항 등에 의해 변경이 매우 잦아 의존 시의 변경 파급력이 클 것 같습니다. 
DTO의 각 인스턴스들을 파라미터로 받는 형태로 수정해보겠습니다

2024-06-30 08:11 UTC, anaconda77 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
노트북에 자바 11,17 버전만 설치되어 있어 버전을 낮추었습니다!

2024-07-01 11:26 UTC, lsm7179 commented on src/main/java/gift/controller/ProductController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
조회의 경우엔 빈값을 내려주고 200코드를 사용합니다.😃
`collections.emptylist()` 를 body에 넣어서 사용합니다. 
204인경우엔 말그대로 무엇인가 내려줄게 없는 경우 사용합니다.

2024-07-01 11:52 UTC, lsm7179 approved these changes
안녕하세요. 성민님~
피드백 반영 잘 해주셨습니다.
다음과제에도 화이팅입니다🔥

2024-07-01 11:52 UTC, lsm7179 commented on src/main/java/gift/controller/ProductViewController.java
> +    }
Spring Framework 4.3 이후 부턴 한개의 생성자만 있고 생성자주입일땐 Autowired annotaion은 생략가능합니다~
https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html

2024-07-01 11:52 UTC, lsm7179 commented on src/main/resources/schema.sql
> +  name VARCHAR(255) NOT NULL,
👍

2024-07-01 11:52 UTC, lsm7179 commented on src/main/java/gift/dto/ProductResponseDto.java
> +    }
👍

2024-07-01 11:53 UTC, merged