경북대 BE_주보경_1주차 과제_2단계
kakao-tech-campus-2nd-step2/spring-gift-product pull request #178
Opened 2024-06-28 07:56 UTC by jupyter471

타입리프와 SSR이 익숙하지가 않아 시간이 오래 걸렸습니다.

controller가 현재 화면을 return 하는 컨트롤러 파일과 서버 내부 로직 처리하는 컨트롤러 분리했는데 맞는지 궁금합니다.

화면 리턴 컨트롤러 <-> html <-> 로직 처리 컨트롤러 간의 호출에서 아직 에러가 발생하는데 API 경로를 명확하게 다시 짜서 추후 수정하겠습니다.

2024-06-30 12:08 UTC, sang5c requested changes
안녕하세요 보경님! 리뷰를 맡은 박상오입니다 잘 부탁드려요 💪💪  

인터페이스 사용, dto 분리 등 여러 방식으로 다양한 시도를 해보신게 보이네요!  
아쉽지만 현재 요구사항을 모두 만족하지 못한 것으로 보여 Request Change를 드립니다.  
혼자 해결하기 어려운 막힌 부분이 있다면 질문 남겨주세요!  

몇 가지 리뷰 남겼으니 확인해보시고 다시 리뷰 요청 진행해주세요~!

2024-06-30 12:08 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +     */
주석의 의미에 대해 고민해봐야 합니다.  
해당 주석은 누구에게 어떤 정보를 전달하기 위해 작성되었고, 없으면 어떻게 되나요?  
다른 코드에 주석이 없는데 여기만 있는 이유는 무엇인가요?

2024-06-30 12:20 UTC, sang5c requested changes
누락된 리뷰가 있어서 추가했습니다 :)

2024-06-30 12:20 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +public class ProductController {
마지막으로 현재 컨트롤러에 작성된 API가 REST와 거리가 있네요. 자료를 참고해서 다시 작성해주세요!  
https://mannhowie.com/rest-api

2024-07-01 05:27 UTC, jupyter471 commented on src/main/java/gift/Application.java
> +//        jdbcTemplate.execute("DROP TABLE product IF EXISTS");
안녕하세요! 우선 꼼꼼하고 정성스러운 리뷰 정말 감사드립니다! 아직 많이 부족하지만 잘 부탁드립니다.

우선 해당 코드는 수요일 클론코딩 강의를 들으면서 강사님이 올려주시는 
<img width="907" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/87298145/ccee0347-05fe-412e-9f11-fb0198b0e4fc">
해당 코드를 따라 쳤었습니다. 그리고 과제 설명부분에서 테이블은 schema.sql 로 생성을 하라고 하셔서 schema 부분만 뺐었습니다. 
<img width="409" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/87298145/fbb0ef22-dc73-42ca-a85e-29128896366c">

그렇게 하니깐 생성한 product 테이블이 해당 구문때문에 먼저 drop이 되길래 주석 처리하였습니다.

application 코드가 먼저 실행되고 properties에 정의한 경로에 있는 schema.sql 코드가 실행되는 줄 알았는데 순서가 반대라는 것을 알게 되었습니다.

주석 처리만 해두고 push할 때 코드를 수정하는 걸 잊었었는데 수정해두겠습니다!

2024-07-02 11:18 UTC, sang5c approved these changes
고생많으셨습니다 보경님! 👏👏

나머지 부분에 대해 이야기를 이어가는 것은 2주차 과제에서 함께 하겠습니다 :)  
이번 주도 파이팅입니다 💪

2024-07-02 11:18 UTC, merged