전남대 BE_서지우 1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #179
Opened 2024-06-28 07:58 UTC by seojiu

ResultSet을 객체로 매핑하고 싶어서 특강에서 알려주신 RowMapper를 사용해봤는데 만들 땐 어려웠지만 재사용 할 수 있어서 굉장히 편리했습니다. 

마지막에 ProductRepository 클래스와 ProductController 클래스가 직접적으로 연결되도록 productService 클래스를 삭제하고 리펙토링했는데 멘토님이 보시기엔 리펙토링 전후 중 어떤 코드가 더 좋은지 궁금합니다.

2024-06-29 08:28 UTC, pkeugine requested changes
안녕하세요 지우님, 3 개의 pr 에 걸쳐 리뷰 남겨보았으니 다 확인해보시고,
해당 PR 에 적용해보시면 좋을 것 같아요.
소소한 부분부터 생각해볼 것들까지 남겨보았으니
시간을 가지고 생각해보신 다음, 추가로 알아볼 내용도 학습한 뒤 적용해보시면 좋겠네요!
함께 파이팅 해보죠 😄 😄 😄

2024-06-29 08:28 UTC, pkeugine commented on README.md
> +### 스키마 및 데이터 스크립트의 위치는 각각 spring.sql.init.schema-locations 및 spring.sql.init.data-locations를 사용하여 사용자 지정할 수 있다.
readme 를 꾸준히 업데이트하시는 모습 좋네요! 💯 💯 💯

2024-06-29 08:28 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    }
`Model` 을 사용하시게 된 이유가 궁금해요! 😄

2024-06-29 08:28 UTC, pkeugine commented on src/main/java/gift/ProductRepository.java
> +    private final SimpleJdbcInsert jdbcInsert;
`SimpleJdbcInsert` 를 사용해주셨군요!
`JdbcTemplate` 과는 어떤 차이가 있나요?

2024-06-29 08:28 UTC, pkeugine commented on src/main/java/gift/ProductRepository.java
> +    };
> ResultSet을 객체로 매핑하고 싶어서 특강에서 알려주신 RowMapper를 사용해봤는데 만들 땐 어려웠지만 재사용 할 수 있어서 굉장히 편리했습니다.

정말 잘 만들어주셨습니다.
이왕이면 `rs`, `rowNum` 이라는 표현보다 줄임말이 없는 단어를 사용해보면 어떨까요?

2024-06-29 08:28 UTC, pkeugine commented on src/main/java/gift/ProductRepository.java
> +        parameters.put("imageUrl", product.getImageUrl());
Java 의 거의 최신버전을 사용하니 다양한 Java api 를 활용해볼 수 있어요.
`Map.of()` 에 대해 한 번 알아보고 적용해보면 좋을 것 같네요.

2024-06-29 08:28 UTC, pkeugine commented on src/main/resources/application.properties
> +spring.sql.init.data-locations=classpath:data.sql
각각의 설정이 어떤 역할을 하나요?
저는 이 중 필요없는 것들도 있다고 생각해서, 하나씩 어떤 용도인지 알아보고 필요한 것들만 남겨보면 좋을 것 같아요.

2024-06-29 08:28 UTC, pkeugine commented on src/main/resources/data.sql
> +
불필요한 공백...!

2024-06-30 15:07 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +    }
추가적으로 `PUT`, `DELETE`, `PATCH` 와 같은 http method 를 알아봐도 좋을 것 같아요!

2024-07-02 12:21 UTC, pkeugine approved these changes
깃 컨플릭트 해결하느라 고생 많으셨습니다.
이번주 미션에서 조만간 다시 뵙도록 할게요!

2024-07-02 12:21 UTC, pkeugine commented on src/main/java/gift/ProductController.java
> +
import 문에 와일드카드를 사용했을 경우의 장단점을 한 번 알아보면 좋을 것 같아요.
그리고 불필요한 공백은 제거해주세요!

2024-07-02 12:21 UTC, merged

2024-07-12 11:41 UTC, seojiu commented on src/main/java/gift/ProductController.java
> +
1주차 step1 리뷰에 와일드카드에 대한 코멘트 남겨놨습니다!!

2024-07-12 11:42 UTC, seojiu commented on src/main/java/gift/ProductController.java
> +    }
참고하겠습니다!!

2024-07-12 11:42 UTC, seojiu commented on src/main/java/gift/ProductRepository.java
> +    };
반영했습니다!!

2024-07-12 11:43 UTC, seojiu commented on src/main/java/gift/ProductRepository.java
> +        parameters.put("imageUrl", product.getImageUrl());
마지막에 Map.of()로 수정했습니다!