경북대 BE_김은선_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #180
Opened 2024-06-28 08:00 UTC by eunsoni

데이타베이스를 설정하는 것에 능숙하지 않아서 헷갈리는 부분들이 많았습니다.

데이타베이스가 있을 때 데이타 유지 기간은 서버 실행중일 때만인지 궁금합니다.

2024-06-29 16:48 UTC, gongdongho12 requested changes
안녕하세요 BE 리뷰어 강동호입니다
앞으로 좋은 프로젝트 같이 만들어가봐요!

질문에 대한 답변을 드리면
>데이타베이스를 설정하는 것에 능숙하지 않아서 헷갈리는 부분들이 많았습니다.
데이타베이스가 있을 때 데이타 유지 기간은 서버 실행중일 때만인지 궁금합니다.
H2 DB를 사용해주시고 있는데 현재설정에 보면
```
spring.datasource.url=jdbc:h2:mem:testdb
```
로 인메모리 상태로 지정되어 있어서 서버 실행중일떄 같이 실행되서 init되는 구조로 지정되어 있어서요
이부분은 설정을 어떻게 하느냐에 따라 사용방식이 달라질 수 있습니다

2024-06-29 16:48 UTC, gongdongho12 commented on build.gradle
> +group = 'com.example'
gift 프로젝트를 만드는건데 실제 서비스 도메인의 역순으로 패키지를 작성하는 편인 것 같은데 샘플 프로젝트의 패키지명인 것 같아요

추후 변경하려면 코드 꼬일 수 있어서 초기에 잡아두시는게 좋은 것 같습니다

2024-06-29 16:48 UTC, gongdongho12 commented on src/main/java/gift/ProductController.java
> +    }
GET과 Post를 사용하는 부분에는 잘 작성해 주셨는데요
삭제와 수정 기능에는 다른 HTTP Method를 사용해주는게 명확한 표현이 되지 않을까요?

2024-06-29 16:48 UTC, gongdongho12 commented on src/main/java/gift/ProductService.java
> +                .usingGeneratedKeyColumns("id");
SimpleJdbcInsert 사용으로 깔끔하게 표현주셨네요 👍🏼

2024-06-29 16:48 UTC, gongdongho12 commented on src/main/resources/schema.sql
> +    image_url VARCHAR(255)
필요한 부분과 사이즈를 잘 지정해주셨네요!

2024-07-01 13:14 UTC, gongdongho12 approved these changes

2024-07-01 13:20 UTC, gongdongho12 commented
@eunsoni conflict 해소 부탁드려요!

2024-07-02 15:10 UTC, eunsoni commented on build.gradle
> +group = 'com.example'
리뷰 감사드립니다! 그런데 리뷰 내용이 잘 이해되지않는 것 같습니다.. "샘플 프로젝트의 패키지명인 것 같아요" 이건 어떤 의미일까요?

2024-07-02 15:23 UTC, gongdongho12 commented on build.gradle
> +group = 'com.example'
일반적으로 패키지명은 네이버쇼핑이면 shopping.naver.com
이렇게 도메인의 역순으로 쓰는데요

진행하는 프로젝트가 카카오 선물하기니까
gift.kakao.com 정도로 해보면 어떨까 하는 의견이었어요

지금은 com.example이라서요

2024-07-06 10:58 UTC, gongdongho12 commented
@eunsoni 각 코드들에 순서가 섞여서 conflict가 발생하네요

2025-08-12 11:14 UTC, closed without merging