경북대 BE_배준호_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #185
Opened 2024-06-28 08:14 UTC by BaeJunH0

2024-06-28 13:56 UTC, lsm7179 requested changes
안녕하세요~ 준호님!
리뷰를 함께 할 닉키라고합니다.
기능구현하느라 고생하셨어요. 👍
전체적으로 기능구현도 잘되어 있고 고민한 포인트들이 엿보이네요. 

몇가지 간단한 코멘트 드렸는데 금방 작업 하실수 있을거에요.👍

2024-06-28 13:56 UTC, lsm7179 commented on README.md
> +  3. Create -> INSERT / Update -> UPDATE 등, 매칭되는 DB 쿼리문을 사용
👍 각 단계별 요구사항이 잘 정리되어 있네요!

2024-06-28 13:56 UTC, lsm7179 commented on src/main/java/gift/Application.java
> +    }
CommandLineRunner 이용해서 초기화를 잘 이용했습니다.👍💯
spring과 springboot 에서 다양하게 초기화 할 수 있는 방법이 있습니다.
https://sgc109.github.io/2020/07/09/spring-running-startup-logic/#Spring-Boot-%EC%9D%98-CommandLineRunner

2024-06-28 13:56 UTC, lsm7179 commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
@Autowired 의존성주입과 생성자 주입에 차이에 대해서 한번 고민해보아요🙂
https://dev-coco.tistory.com/70

2024-06-28 13:56 UTC, lsm7179 commented on src/main/java/gift/Application.java
> +    }
상품에 가격과 이름이 없을 수 있나요?🤔

2024-06-28 13:56 UTC, lsm7179 commented on src/main/java/gift/DTO/Product.java
> +package gift.DTO;
nit(꼭 수정하지 않아도 됩니다): Product는 DTO 계층일까요?
다음 수업시간에 계층형에 대해 배울텐데 고민해보아요😃

2024-06-28 13:56 UTC, lsm7179 commented on src/main/java/gift/Application.java
> +    }
고민포인트가 있었을거 같은데 잘 정리해주셨네요.
다만 실무에서는 HiddenHttpMethodFilter 를 잘 사용하지 않습니다.🥹
https://haah.kr/2017/05/23/rest-http-method-in-html-form/

2024-06-28 13:56 UTC, lsm7179 commented on src/test/java/gift/ProductControllerTest.java
> +}
(선택)4단계 E2E 테스트를 하려다 만 거 같은데 지금 구조로는 하기 어렵습니다.
rest api를 만들고 화면에서 api call(이를테면 ajax를 이용한)을 통해서 crud가 이뤄지면 각 api에 E2E 테스트를 해볼수 있을거 같아요.😁

2024-06-28 13:56 UTC, lsm7179 commented on src/test/java/gift/ProductTest.java
> +        Assertions.assertTrue(tf);
지금은 어떤 단계에서 검증 실패가 났는지 확인하기 어렵네요.😅

각 검증별로 메소드를 만들어서 검증해보아요🤗

2024-07-02 03:16 UTC, BaeJunH0 commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
해당 사항 공부하여 Service 클래스에서는 final 제한자를 사용해서 생성자 주입의 이점을 살리는 식으로 바꾸었습니다.
Application 클래스는 static이라 생성자가 없으니 필드 주입하는 것 같은데, 이외의 방법은 없을까요?

2024-07-02 03:18 UTC, BaeJunH0 commented on src/main/java/gift/Application.java
> +    }
Form 형식 사용하지 않고 API와 View를 분리하여 View에서 API를 요청하는 식으로 변경하였습니다!
위의 다른 부분 포함하여 2주차 과제에 PR 생성했으니 확인 부탁드립니다 👍

2024-07-02 13:54 UTC, lsm7179 approved these changes
준호님~
2주차 과제에서 확인해보겠습니다. 수고하셨습니다~

2024-07-02 13:54 UTC, merged