강원대 BE_이의찬_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #19
Opened 2024-06-25 11:01 UTC by ana-raka

# 1주차 과제 수행한 결과입니다.
## 궁금한 점 정리 입니다.
1. 메서드 명을 정할 때 좋은 작명의 기준이 있는지 궁금합니다. 예를 들어 처음 상품 등록의 경우 저는 setproduct로 하였는데 이러한 메서드 이름이 최선이 아니란 생각이 들어 질문 드립니다.
2. 입력으로 들어오는 객체가 객체 선언시 설정한 도메인과 맞지 않을 경우 예외처리를 Product 클래스에서 진행해야 하는 지 궁금합니다. 
4. 중간에 업데이트 하는 메소드에서 업데이트 성공 시와 실패 시 다른 타입을 리턴하게 설정하였는데 저런 식의 코드 작성은 괜찮은 건지 궁금합니다. 

## 감사합니다 !

2024-06-29 13:49 UTC, pci2676 commented
> ## 궁금한 점 정리 입니다.
> 1. 메서드 명을 정할 때 좋은 작명의 기준이 있는지 궁금합니다. 예를 들어 처음 상품 등록의 경우 저는 setproduct로 하였는데 이러한 메서드 이름이 최선이 아니란 생각이 들어 질문 드립니다.

set이라는 이름에 등록이라는 의미가 명확하게 드러난다고 보셨을까요? 메서드 이름은 메서드의 행위를 명확하고 간결하게 드러낼 수 있도록 작성해주시면 좋을것 같습니다. set은 너무 추상적이지 않을까 싶습니다. :)

> 2. 입력으로 들어오는 객체가 객체 선언시 설정한 도메인과 맞지 않을 경우 예외처리를 Product 클래스에서 진행해야 하는 지 궁금합니다.

도메인 객체가 검증할 수 있고 검증해야하는 영역이라면 도메인 객체에서 하는것이 맞습니다.

가령 양수를 나타내는 `PositiveNumber`가 있을때

`new PositiveNumber(-1);` 와 같이 생성자를 호출하는 경우 생성자의 구현부에서 exception을 발생시키는 경우가 있을것 같습니다.

> 3. 중간에 업데이트 하는 메소드에서 업데이트 성공 시와 실패 시 다른 타입을 리턴하게 설정하였는데 저런 식의 코드 작성은 괜찮은 건지 궁금합니다.

다른타입이라고 하셨는데 아마 ResponseEntity의 내용물이 다른경우를 말씀하시는 것 이겠지요?

이렇게 작성하는 경우도 있어 어색하다고 할 순 없지만 가능한 단순하게 반환하고 정상적으로 수행되지 않거나 수행할 수 없는 경우 exception을 발생시키는 경우도 많이 있습니다.

2024-06-29 13:52 UTC, pci2676 commented
> * 기능은 정상적으로 작동하는데 제가 작성한 코드가 올바른 코드인지 잘모르겠습니다.

질문이 너무 추상적입니다! 

조금 더 구체적으로 어떠한 부분에서 고민을 하셨는지 알려주시면 제가 더 도움을 드리기 쉬울것 같습니다.

제가 다니고 있는 회사에는 다음과 같은 말이 있습니다. `만드는 사람이 수고로우면 쓰는 사람이 편하고, 만드는 사람이 편하면 쓰는 사람이 수고롭다.`

좋은 질문은 좋은 답변을 만들어 낼 수 있으니 조금 더 구체적으로 질문해주세요. 이러한 경우 comment기능을 활용해서 고민하신 부분에 대해 알려주시면 더 좋습니다 😄 

> * HTML과 연동하면서 코드를 작성하려니 커밋 단위를 생각보다 나누지 못하겠어서 너무 큰 단위로 한 것 같습니다. 이런 경우 어느 식으로 커밋 단위를 잡으면 좋을지 궁금합니다.

커밋을 너무 작게 잡으면 맥락을 파악하기 힘들어질 수 있습니다. 반대로 너무 크게 단위를 잡아도 마찬가지로 맥락을 파악하기 힘듭니다.

의찬님이 생각하시기에 '이 정도 크기의 커밋이라면 커밋만 보고 맥락을 파악할 수 있겠다!' 싶은 수준으로 커밋을 잡는 연습을 계속해서 해보시면 좋을것 같습니다.

2024-06-29 14:04 UTC, pci2676 commented
> # Step3 과제 수행한 결과입니다.
> * 특정 메서드를 수행할 때 동작에 대한 처리를 서버 사이드에서 수행하는 것이 좋은 지 클라이언트 측에서 수행하는 게 좋은지 궁금합니다.
> * ex) 물건 구매 처리시 자바스크립트로 구매가 가능한지 체크하는 것과 서버 컨트롤러가 체크하는 것

비즈니스 로직의 경우 가능한 서버 사이드에서 해결하는 것이 좋습니다.

그러나! 양쪽 모두 체크하는것이 가장 좋습니다. 😄

2024-06-29 14:04 UTC, pci2676 requested changes
반갑습니다 🤠 

조금 질문에 대한 답변과 조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

모든 요구사항을 한번에 개선하시기 어렵다면 코멘트를 남겨주시고 할 수 있는 부분부터 점진적으로 적용해주시면 됩니다. 다음 단계로 넘어가면서 조금씩 개선하셔도 좋습니다.

2024-06-29 14:04 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public String getproductList(Model model) {
다른 부분은 잘 지켜주셨는데 이 부분은 camel case로 작성하는 것을 놓치신것 같군요!

2024-06-29 14:04 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +    public String movtoAddProduct(Model model) {
사용하지 않는 파라미터는 제거해주세요.

2024-06-29 14:04 UTC, pci2676 commented on src/main/java/gift/ProductController.java
> +        Product product = productDao.selectProduct(id);
찾는 product가 없는 경우 대응할 수 있어야 할 것 같습니다.

2024-07-02 09:31 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +    public String movtoAddProduct(Model model) {
수정 완료하였습니다.

2024-07-02 09:32 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +public class ProductDao {
Step3까지 진행하면서 Test 진행을 누락한 것 같습니다.. 2주차 과제 진행하면서 추가하도록 하겠습니다..!

2024-07-02 09:34 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +        }
아직 정확히 컨트롤러의 역할과 애플리케이션이 진행되는 과정에서 각 역할을 명확히 구분하고 있지 못한 것 같아 좀 더 학습을 진행하도록 하겠습니다 !

2024-07-02 09:34 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +        }
수정 완료하였습니다.

2024-07-02 09:34 UTC, ana-raka commented on src/main/java/gift/ProductController.java
> +    //private final Map<Long, Product> products = new HashMap<>();
수정 하였습니다.

2024-07-02 09:36 UTC, ana-raka commented
수정 가능한 부분은 최대한 수정 진행하려 하였는데 아직 부족함이 많아 전부 다 반영하지 못하였습니다.. 특히 Spring boot관련하여 테스트 코드를 작성하려니까 오류가 많이 발생하여 막히는 부분이 많았습니다. 과제 진행이 너무 늦어질 것 같아 2주차 과제를 진행하면서 부족한 부분과 테스트 코드 작성도 병행하도록 하겠습니다 ! 
피드백 감사합니다 !

2024-07-02 11:34 UTC, pci2676 approved these changes
수고하셨습니다. 🚀

2024-07-02 11:34 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +    }
.sql 파일을 이용하는 방법도 있으니 참고해주세요~

2024-07-02 11:34 UTC, pci2676 commented on src/main/java/gift/ProductDao.java
> +    public void updateProduct(Product product){
메서드 간의 간격이 존재하지 않는것 같아보이네요.

공백도 코드를 읽는데 중요한 요소가 되니 적절한 공백을 이용하시는 것이 좋습니다.

2024-07-02 11:34 UTC, merged

2024-07-02 12:11 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +    }
넵 2주차 과제를 진행하면서 적용해보겠습니다.

2024-07-02 12:12 UTC, ana-raka commented on src/main/java/gift/ProductDao.java
> +    public void updateProduct(Product product){
넵 확인하였습니다 ! 감사합니다.