경북대 BE_탁정민_1주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #194
Opened 2024-06-28 08:52 UTC by xkrwjdals

#질문
## 질문1
> Task :processResources UP-TO-DATE
> Task :classes
Note: /Users/takjungmin/spring-gift-product/src/main/java/gift/ProductOperation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

스프링 어플리케이션을 실행시켰을 때 위와 같은 경고가 뜹니다. 검색을 해봐도 잘 이해가 되지 않아서 혹시 설명해주실 수 있으실까요?

## 질문2
product-edit.html 을 구현하다가 `update` 버튼을 누르면 error가 발생하는데 그 이유를 잘 모르겠습니다... 제대로 AdminController.java에서 POST request에 대한 처리를 한 것 같은데 제출 시간이 가까워져 일단 제출하고 질문드립니다 ㅠㅠ

2024-06-29 13:19 UTC, jadie0319 requested changes
미션 진행하시느라 고생하셨습니다!
좀 더 개선 또는 고민하면 좋을 것들에 대해 메모해놨어요!
피드백 반영하시다 궁금한게 있으시면 남겨주세요!

2024-06-29 13:19 UTC, jadie0319 commented on src/main/java/gift/ProductController.java
> +    public ResponseEntity<Product> createProduct(@RequestBody Product product) {
api 요청 객체로 도메인 객체인 Product 를 사용하고 있어요.
만약에 api를 사용하는 측에서 API 요청시 필드 이름 변경 또는 필드 변수를 추가 하고 싶다는 요청이 생기면 어떤 문제가 발생할 수 있을까요?

2024-06-29 13:19 UTC, jadie0319 commented on src/main/java/gift/ProductOperation.java
> +package gift;
현재 한 패키지에 모든 클래스가 같이 있어요. 
모든 클래스가 한 패키지에 있으면 나중에 클래스를 찾기 어려워 질 것 같아요. 
클래스를 찾기 쉬운 구조로 변경해볼까요?

아래 링크를 참고하면 좋을 것 같아요 :)
https://velog.io/@sunil1369/Spring-boot-%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B5%AC%EC%A1%B0

2024-06-29 15:52 UTC, jadie0319 commented
안녕하세요! 카카오테크 캠퍼스 2기 백엔드 과정의 멘토링을 맡게된 멘토 제이디 입니다. 
부족하지만 앞으로 6주간 좋은 시간이 되게 노력하겠습니다. 잘부탁드립니다~!
그리고 질문은 많으면 많을수록 좋습니다. 많이 질문해주세요! 
이번 PR 에서 질문해주신 부분에 대해서 아래 정리했습니다.
 앞선 두개의 PR 에 대한 답변도 이번 PR 에서 답변드리겠습니다. 다음주엔 하나의 PR로 주시면 될 것 같아요~

### 첫번째 PR 에 있는 Autowired 질문 답변

클래스간 의존성을 배우실때 봤던 코드가 Service 클래스에서  DAO 객체를 **직접 생성**하여 메서드를 호출했으면 스프링 의존성 주입을 사용하지 않은 것 입니다 (의존성 주입은 직접 생성하는게 아닌 생성되어 있는 객체를 주입 받습니다). 그래서 Autowired 사용 없이 코드가 동작했을 겁니다. 

스프링을 사용한다고 해서 반드시 어노테이션을 사용해야 하는 것은 아닙니다. 스프링에서도 위의 예시와 같이 DAO 객체를 직접 생성하면 Autowired 를 사용하지 않아도 됩니다. 다만 DAO 객체를 만들기 위한 코드를 직접 작성해야 하죠. 그러니 DAO 객체를 직접 생성하지 않고 이미 만들어져 있는 객체(스프링 빈)를 주입받기 위해서 Autowired 를 사용합니다! 

여기서 어떻게 객체가 만들어져 있을 수 있을까요? 이건 스프링 빈과 의존성 주입에 대해서 좀 더 공부해보시면 아실 수 있을 것 같습니다!

추가로 스프링 빈으로 등록된 객체를 사용하기 위해선 스프링 빈을 주입받아야 합니다. 주입 방식으로는 

- 필드 주입 방식
- 생성자 주입 방식
- 수정자 주입 방식

이렇게 3가지 방식이 있습니다. Autowired 어노테이션을 사용해서 주입하는 방식은 필드 주입 방식, 수정자 주입 방식 입니다. Autowired 어노테이션이 반드시 필요합니다.

하지만 생성자 주입 방식은 필요하지 않습니다. 옛날 스프링 버전에서는 Autowired 어노테이션을 생성자 위에 붙여줘야 했지만 최신 스프링 버전에서는 어노테이션 사용없이 생성자를 통해 의존성 주입이 가능합니다.

아래 링크를 참고하시면 도움이 될 것 같습니다! 참고로 저도 이 블로그에 나온 내용과 같은 이유로 생성자 주입 방식을 선호합니다~
https://velog.io/@think2wice/Spring-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85DI%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC
https://velog.io/@minji/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B9%88Bean-%EC%97%90-%EB%8C%80%ED%95%9C-%EC%9D%B4%ED%95%B4


### 첫번째 PR 에 있는 hashmap 질문

상품의 id 를 api 요청으로 받는게 아니라 curId 라는 변수를 만들고 자체적으로 관리해도 되는지에 대한 질문으로 이해를 했습니다. 의도하신 질문이 맞을까요? 
상품 ID 를 외부(API 호출자) 에서 관리하는게 아닌 ProductOperation 클래스에서 관리하려면 말씀하신 방식으로 구현해도 됩니다. 해당 변수가 나중에 DB 를 사용할 때의 AUTO_INCREMENT 와 같은 역할을 하겠네요. :)


### 두번째 PR 질문

많은 고민이 들게 하는 질문이네요 ㅎ 이 질문은 나중에 일을 하면서도 많이 고민하실 질문 주제인 것 같아요. 

과연 꼼수(?) 를 써서라도 미션을 완료한게 중요할까요? 아니면 꼼수를 사용하지 않고 미션에 실패하는게 중요할까요?

대개 꼼수(?)는 현재의 문제를 좀더 손쉽게 해결하기 위해 사용한다고 생각해요. 그러면 좀 더 빠르게 문제를 해결하겠지만 그 꼼수로 인해 미래에 더 복잡한 문제를 마주하게 될 가능성이 있습니다. (상상하신 것보다 크고 거대하고 복잡한 문제일 수 있습니다 ㅎ) 그래서 꼼수에 대한 인식이 안좋고 최대한 지양하려고 합니다.

하지만 꼼수(?)가 무조건 나쁜것이냐? 라고 물어보신다면 그건 또 아니라고 생각합니다. 꼼수도 어떻게 보면 문제를 해결하기 위한 아이디어 중에 하나가 될 수 있다고 생각해요. 이러한 생각도 할 수 있다는 점에서 선택의 폭을 넓히는 훈련이 될 수도 있다고 생각합니다.

다만! 공부를 할 땐 꼼수 보다는 문제를 정확하게 해결하고, 모르는 것은 질문하며 확실하게 알고 넘어가는게 중요할 것 같아요 :)


### 세번째 PR 질문 1

경고가 발생했을 당시의 코드를 봐야 정확하게 알 수 있을 것 같아요.  일단은 컴파일 당시 deprecated 된 코드가 포함되어 있어서 발생한 것으로 추정 됩니다.
관련 링크 : https://stackoverflow.com/questions/31762417/java-uses-or-overrides-a-deprecated-api-error


### 세번째 PR 질문 2

html, javascript 는 경험이 없어 정확한 답변은 드리기 어려울 것 같습니다ㅠ 대신에 좀 찾아봤는데 아래 링크와 같은 방법도 있다고 합니다 :)
https://donggu1105.tistory.com/61
https://bestinu.tistory.com/63

2024-06-30 08:35 UTC, xkrwjdals commented on src/main/java/gift/ProductController.java
> +    @PutMapping("edit/{id}")
관리자 페이지(product-list.html 템플릿)에서 리스트에 저장된 `Product` 객체들을 보여줄 때, edit 하이퍼링크를 누르면 필드값을 수정할 수 있는 페이지(product-edit.html 템플릿)으로 넘어갈 수 있도록 했습니다. 이때 해당 페이지의 주소가 `/admin/product/edit/{id}` 로 넘어가기 때문에 `PUT` 요청시에도 일관성 있게 `api/products/edit/{id}' 로 URL 엔드포인트를 정의했습니다. 

그런데 생각해보니 `@PutMapping` 을 사용했으니 굳이 사용하지 않아도 될 것 같습니다! 현업 시에는 URL 엔드포인트를 좀 더 단순하게 정의하는 것이 더 중요할까요?

2024-06-30 09:46 UTC, xkrwjdals commented on src/main/java/gift/ProductController.java
> +    public ResponseEntity<Product> createProduct(@RequestBody Product product) {
DTO 클래스를 새로 정의한 뒤, 컨트롤러에서 DTO 클래스의 객체를 이용하여 클라이언트와 서버 간의 데이터 전송을 처리할 수 있을 것 같습니다. 그럼 API 사용하는 측에서 필드 변수명 변경이나 필드 변수를 추가하고 싶다는 요청이 생기면 DTO 클래스에서 변경하거나 추가하면 되는 것일까요? 그렇다면 DTO 클래스는 도메인 객체인 `Product` 클래스를 보호하기 위해 존재하는 것인가요? 

예를 들어 지금 과제에서 현재 `gift` 프로젝트에서 `ProductDTO.java` 라는 새로운 DTO 모델 클래스를 정의하면, 필드 값들은 `Product.java`와 동일(도메인 객체의 필드 값과 동일)할 것입니다. 그렇기에 API를 사용하는 측에서 필드 이름 변경이나 필드 변수를 추가하고 싶다는 요청이 생기면, `ProductDTO` 클래스의 필드 변수명이나 필드 변수들을 추가하는 식으로 수정하게 될 것 같습니다. 그럼 결국 데이터를 담는 모델 클래스에 수정을 하게 되는 것인데 이것이 도메인 객체의 필드 변수를 수정하는 것과 DTO 객체의 필드 변수를 수정하는 것에 어떤 차이가 있는 지 궁금합니다. 혹은 결국 필드 변수들을 수정하게 된다는 점에서는 차이가 없으나 `Product` 객체(도메인 객체)의 수정을 피하게 되어 객체 지향 측면에서 다양한 이득을 볼 수 있다는 건가요?

2024-06-30 10:02 UTC, xkrwjdals commented on src/main/java/gift/ProductController.java
> +        Product product = productOperation.getProductById(id);
굳이 product라는 이름의 Product 객체를 생성하여 productOperation 객체의 getProductById 메서드를 호출하기 보단 그냥 
```java
productOperation.getProductById(id);
``` 
로 수정하라는 말씀이시죠? 동일한 문제가 `ProductController.java`의 @PutMapping 에도 있어서 수정했습니다!

2024-06-30 10:35 UTC, xkrwjdals commented on src/main/java/gift/Product.java
> +    public void setImageUrl(String imageUrl) {
인텔리제이에서 사용하지 않는 메서드라고 뜨는 메서드를 삭제했더니 
localhost:8080/admin/product/add 에서 **Save 버튼** 을 누르니까 500 에러가 발생했습니다!

2024-06-30 10:48 UTC, xkrwjdals commented
안녕하세요! 경북대 BE 과정을 하고 있는 탁정민입니다! 우선 코드리뷰와 질문에 대한 답변 모두 감사합니다! 첨부해주신 링크를 통해 의존성 주입에 대한 내용이 어느정도 감이 잡힌 것 같습니다. 또한 코드 리뷰에서 DTO 모델을 왜 사용해야 하는 지도 다시 한번 생각할 수 있어 정말 도움이 되었습니다! 

세번째 PR 질문 1에 대한 내용은 @Autowired를 그대로 표기해서 나타난 에러였던 것 같습니다. 생성자 주입 방식으로 코드를 수정하니 해당 경고가 발생하지 않게되었습니다! 감사합니다. 

현재 코드 리뷰를 보면서 대부분의 변경 요구 사항을 반영하여 push 하였는데, 인텔리제이에서 사용하지 않는 메서드라고 표시되는 Setter 메서드를 삭제하니 해당 conversation에 댓글로 말씀드린 문제가 발생합니다. 이에 대한 피드백이 필요할 것 같습니다!

또한 getter/setter를 쓰지 않는 것이 좋다고 **[프로그래밍 요구 사항]-[객체  지향 생활 체조 원칙]**에 명시되어 있어서, 1단계 ~ 2단계 과제때만 하여도 record로 `Product.java`를 작성했었습니다. 하지만 Jdvc Template를 사용하게 되면서 getter, setter가 필요하여 정의하게 되어 Product 클래스를 record에서 class로 변경했습니다. 그런데 지금 DTO 클래스를 새롭게 정의하여 사용하고 있는 상황이라 혹시 `Product.java` 는 record 타입으로 정의하여도 문제가 없을까요?

또한 getter/setter를 쓰지 않는 것이 좋다고 하였는데 Jdvc Template를 사용하게 되면 필연적으로 사용하게 되지 않나요? 이를 해결할 수 있는 방법은 어떤 것이 있는지 궁금합니다!

2024-07-01 02:53 UTC, jadie0319 commented on src/main/java/gift/Product.java
> +    public void setImageUrl(String imageUrl) {
/admin/product/add 화면에서 호출하는 api 가 
ProductController#createProduct() 인줄 알았는데 AdminController#addProduct() 였네요.

500 에러가 발생한 이유는 ProductDto 에 값이 null 이 들어가서 입니다.

- ProductController#createProduct() 메서드는의 @RequestBody 는 set 메서드가 없어도 ProductDTO 객체에 값이 바인딩되어 정상적으로 호출이 됩니다.
- AdminController#addProduct() 메서드의 @ModelAttribute 는 set 메서드가  없으면 api 요청시 입력한 값이  ProductDTO 객체에 값이 바인딩되지 않아 객체의 값이 null 입니다. 값이 null 이라 DB에 저장하다가 ID가 NULL 이라 에러가 발생했습니다.

AdminController#addProduct() 를 사용하실거면 set 메서드를 남겨두시고
ProductController#createProduct() 를 사용하실거면 set 메서드를 지우셔도 됩니다.

@RequestBody 와 @ModelAttribute 의 차이는 아래 링크에 잘 나와있으니 참고 바랍니다 :)
https://tecoble.techcourse.co.kr/post/2021-05-11-requestbody-modelattribute/

2024-07-01 03:24 UTC, jadie0319 commented on src/main/java/gift/ProductController.java
> +    @PutMapping("edit/{id}")
화면에 보여주는 페이지 API(/admin/product/edit/{id}) 는 edit 가 라는 단어가 있어도 상관없다고 생각합니다. 

하지만 Rest API (api/products) 의 URL 은 자원을 나타내야 합니다. 
행위는 HTTP METHOD 로 표현이 가능하죠. 굳이 자원을 표현하는 URL 에서 중복된 표현을 할 필요는 없다고 생각해요.

REST API 설계 라는 키워드로 구글링하시면 많은 자료가 나올겁니다 :)

2024-07-01 03:35 UTC, jadie0319 commented on src/main/java/gift/ProductController.java
> +        Product product = productOperation.getProductById(id);
```java
productOperation.getProductById(id)
```

위 코드가 ProductController 에 2개 존재합니다. productOperation#getProductById(id)를 사용하는 코드를 한개로 줄여보라는 말씀이었어요 ㅎ 

```java
private Product getProduct(Long id) {
  return productOperation.getProductById(id);
}
```
이러한 메서드를 만들고 ProductController 에서는 이 메서드만 호출하면 됩니다. 그러면 ProductController 입장에서 ProductOperation#getProductById() 메서드를 호출하는 곳이 한곳이 됩니다.

이렇게 바꾸면 어떤점이 좋을까요? 변경과 영향도 라는 키워드에 집중하여 고민해보시면 좋을것 같아요! :)

2024-07-01 06:58 UTC, xkrwjdals commented
@jadie0319 일단 2주차 과제를 진행해야 해서 conflict를 reslove했습니다! 어제 보낸 push를 마지막으로 피드백을 새로 반영하고 있는 부분은 없습니다! 아직 반영하지 못한 피드백은 2주차 과제를 진행하면서 계속 고민하며 같이 반영할 것 같습니다! 감사합니당

2024-07-01 07:13 UTC, merged