경북대BE_안용진_1주차 과제
kakao-tech-campus-2nd-step2/spring-gift-product pull request #197
Opened 2024-06-28 08:55 UTC by sapsalian

## 어려웠던 점
Spring 프레임워크 자체를 처음 접하다 보니, 공부하면서 과제를 진행해 나가는 부분이 조금 벅찬 느낌이 있었습니다. 또한 프레임워크나 라이브러리에서 발생할 수 있는 예외들을 어디까지 처리해주어야 하는지, 어떻게 처리해주어야 하는지가 어려웠고, 테스트를 어떤식으로 진행해야할지 고민하는 과정에서 시간을 많이 썼던 것 같습니다.

## 궁금한 점
- 현업에서는 외부 라이브러리를 가져다 쓸 때, throws로 정의되어 있는 발생할 수 있는 예외를 모두 처리해주나요? 아니면 치명적으로 작용할 수 있는 몇몇 예외들만 처리해주나요?

2024-06-28 10:50 UTC, leaf-upper commented on src/main/java/gift/Application.java
> +    public void run(String... args) throws Exception {
👍👍 애플리케이션이 시작할때 Inmemory 스키마를 정의해주는 코드네요~
잘 작성해주신것 같아요~ 
번외로 스프링부트에서, 작성된 스키마 파일을 기반으로 애플리케이션 동작시에  자동으로 해당 스키마 파일을 실행시켜주는 기능이 있는데 해당 기능을 사용해보셔도 좋을것 같아요~

2024-06-28 11:02 UTC, leaf-upper requested changes
안녕하세요 안용진님 
6주간 코드리뷰어를 맡게되었습니다. 잘부탁드려요!
Spring을 처음 사용해보신다고 하셨지만 너무 코드를 잘 작성해주셨습니다.
몇가지 코멘트를 남겨드렸는데요~ 확인해주시면 주말기간에 Approve 드리도록 하겠습니다.
1주차 고생많으셨습니다~!!

2024-06-28 11:02 UTC, leaf-upper commented on src/main/java/gift/repository/ProductDAO.java
> +    private long idTraker = 1;
데이터베이스 스키마를 AUTO INCREMENT로 설정하면 애플리케이션에서 굳이 ID 발번하지 않아도 괜찮아요~
ID는 애플리케이션에서 생성하기보다는 데이터베이스가 직접 생성해주는게 좋을것 같습니다!

2024-06-29 10:25 UTC, sapsalian commented on src/main/java/gift/Application.java
> +    public void run(String... args) throws Exception {
아하 감사합니다!!ㅎㅎㅎㅎ 안 그래도 과제 힌트에 있던 SQL script에 대해 찾아보았는데, 위 코드 처럼 스키마를 정의해주는 부분은 schema.sql에 정의해주면 되는 것이 맞을까요?? 좀 더 공부해보고 바로 적용해보도록 하겠습니다!!

2024-06-30 08:14 UTC, leaf-upper approved these changes
1주차 고생많으셨습니다~

2024-06-30 08:14 UTC, leaf-upper commented on src/main/java/gift/Application.java
> +    public void run(String... args) throws Exception {
넵넵 다른부분들은 잘 적용되어서, 어프로브 드리고 머지해두겠습니다~!

2024-06-30 08:14 UTC, merged