경북대 BE 김민주A
kakao-tech-campus-2nd-step2/spring-gift-product pull request #198
Opened 2024-06-28 08:56 UTC by minju26

2024-06-29 09:24 UTC, gongdongho12 requested changes
> 매 주 모든 테스트 코드를 써야할지도 고민입니다. 실제로는 어떤 단위로 테스트코드를 작성하는지 궁금합니다.

이번에 동작적인 측면이 delete update 그리고 초기에 insert 되는 1건이 있는데요
이런 동작이 정상적으로 이루어지는지에 대한 테스트가 있으면 직접 빌드하지 않고서라도 확인이 가능해서 적용되면 좋을 것 같습니다

2024-06-29 09:24 UTC, gongdongho12 commented on src/main/java/gift/ProductManageController.java
> +    }
이부분도 위와 같은 코멘트인데요!
다른 메서드 타입 한번 체크 부탁드려요

2024-06-29 09:24 UTC, gongdongho12 commented on src/main/resources/db/schema.sql
> +    imageUrl VARCHAR(255)
H2 db에서 대소문자 구분을 정상적으로 하는지 테스트 해보셨을까요?

2024-06-29 09:24 UTC, gongdongho12 commented on src/main/resources/templates/product-addition-form.html
> +<a th:href="@{/api/manage/products}">Cancel</a>
edit기능이랑 add 기능이 비슷한 것 같은데 이 부분을 추후에는 템플릿 조각같은거로 공통 부분을 하나로 사용해보시면 좋을 것 같습니다

2024-06-29 15:51 UTC, gongdongho12 commented on src/main/java/gift/Product.java
> +    }
빈 생성자를 둘 필요가 있었는지 궁금합니다

2024-06-29 15:51 UTC, gongdongho12 commented on src/main/java/gift/ProductController.java
> +    }
Put과 Delete 메서드 사용해주셨네요 👍🏼

2024-06-29 15:51 UTC, gongdongho12 commented on src/main/java/gift/ProductDao.java
> +    }
쿼리이다 보니 중간에 칼럼이 추가될 수 있는데요 ?로 표기하는 방식의 구조면 IDE에서 체킹이 어려울 수 있을 것 같아요
이부분 SimpleJdbcTemplate를 한번 고려해보면 어떨까요?

2024-07-01 05:26 UTC, minju26 commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
시간 분배 실패로 급하게 하느라.. 시도 했는데 처음 보는 오류가 나서 그대로 둬버렸습니다🥹
다시 한번 시도해보겠습니다 :)

2024-07-01 05:30 UTC, minju26 commented on src/main/java/gift/ProductManageController.java
> +    }
`ProductController` 에서는 DELETE 메소드를 사용했지만,
HTML 폼에서는 method 속성으로 POST와 GET만 지원한다고 해서 `ProductManageController`에서만 모든 메소드를 post와 get으로 적용했습니다!
혹시 다른 방법이 있을까요?

2024-07-01 05:32 UTC, minju26 commented on src/main/java/gift/ProductDao.java
> +    }
넵 한번 적용 해보겠습니다!

2024-07-01 05:34 UTC, minju26 commented on src/main/resources/db/schema.sql
> +    imageUrl VARCHAR(255)
imageUrl 과 imageurl 을 구분할 수 있는지를 말씀하시는 걸까요, 아니면 값으로 들어오는 문자열을 말씀하시는 걸까요?

2024-07-01 05:35 UTC, minju26 commented
> > 매 주 모든 테스트 코드를 써야할지도 고민입니다. 실제로는 어떤 단위로 테스트코드를 작성하는지 궁금합니다.
> 
> 이번에 동작적인 측면이 delete update 그리고 초기에 insert 되는 1건이 있는데요 이런 동작이 정상적으로 이루어지는지에 대한 테스트가 있으면 직접 빌드하지 않고서라도 확인이 가능해서 적용되면 좋을 것 같습니다

넵 한번 해보겠습니다.
예외처리에 대한 질문에도 의견이 궁금합니다..!

2024-07-01 05:53 UTC, minju26 commented on src/main/java/gift/ProductService.java
> +    }
아하 그렇군요..! 
`addNewProduct`메소드를 똑같이 사용하도록 수정하겠습니다 :)

2024-07-01 13:05 UTC, gongdongho12 commented on src/main/java/gift/ProductManageController.java
> +    }
HTML Form 말고 javascript의 fetch 메서드를 사용해보시면 좋을 것 같습니다

2024-07-01 13:08 UTC, gongdongho12 approved these changes
> 일단 happy path에 맞춰 기능 구현을 한 후에 다시 예외 처리를 하는 것이 좋은지, 기능 구현 중에 떠올릴 수 있는 예외는 그때그때 처리해두는 것이 좋을지 궁금합니다.

나중에 보면 Exception에 따라서 예외를 공통처리하는 ControllerAdvice 같은게 생겨서 에러 타입에 따른 메시지를 적용할 수 있을거에요

지금 구성하는것도 좋지만 어느정도 예외상황을 정리하고 가도 좋을 것 같습니다
ControllerAdvice 관해서 한번 찾아보시고 추후 방향을 잡아주세요!

고생 많으셨습니다 :)

2024-07-01 13:08 UTC, merged

2024-07-01 14:54 UTC, minju26 commented on src/main/resources/db/schema.sql
> +    imageUrl VARCHAR(255)
넵 구분 확인했습니다!

2024-07-01 14:56 UTC, minju26 commented on src/main/java/gift/Product.java
> +    }
`ProductManageController` 의 `addProductForm`에서 빈 product 객체를 생성하여 model을 통하여 뷰로 전달하고 있습니다!