경북대 BE_장우석_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #25
Opened 2024-06-25 14:24 UTC by us4c0d3

1. 과제를 진행하며 상태 코드를 적용하고 싶어 ResponseEntity<> 객체를 추가하였는데, 예외 발생 시 에러 메시지를 어떤 방식으로 클라이언트 측으로 보내면 좋을까요? Exception을 throw할 때 에러 메시지를 작성하였습니다.
2. 기본적으로 제공되는 Exception을 사용해 대부분의 예외 상황에 `IllegalArgumentException`으로 처리하였는데 enum으로 예외 상황을 정리하여 추가하는 것이 더 좋을지 궁금합니다.

2024-06-28 17:31 UTC, sang5c requested changes
안녕하세요 우석님! 리뷰를 맡은 박상오입니다. 잘 부탁드립니다 💪💪
커밋 분리, README 작성까지 열심히 노력하신 부분이 보이네요 👍

예외 관련된 질문에 대해서는 앞으로 배울 내용이라, 강의를 듣고 다시 고민해보신 다음 질문해주시면 다시 답변 드릴게요!

> Step2 과제를 진행하다가 thymeleaf에 빈 객체 전달을 위한 id가 nullable하도록 수정했습니다. -> 빈 객체를 보내기 위해 id가 null인지 검증하는 부분이 record 객체에서 빼도록 했는데 이 부분을 어떤 방식으로 처리하면 좋을지 모르겠습니다. 그냥 model에서는 검증하지 않고 DB 스키마로 검증해도 괜찮은가요? 아니면 또 다른 방안이 어떤 것이 있는지 궁금합니다.  

좋은 고민입니다만, 앞으로 배우게 될 내용이라 지금 답변 드리기 어렵네요! 지금은 주어진 요구사항을 만족했는지 먼저 확인해보면 좋을 것 같습니다 :) 

> thymeleaf에서 form을 통해 request를 할 때 HiddenHttpMethodFilter를 주입하여 GET, POST가 아닌 다른 method를 요청하도록 처리했는데, html에서 get과 post가 아닌 다른 method의 요청을 보내는 방법은 JS의 ajax와 fetch를 통해 요청하는 방법밖에 없는 것인가요?

말씀하신 내용이 맞습니다 :)

> 개발을 진행하긴 했으나 익숙하지 않아 요구사항이었던 json을 통해 주고받으라는 것이 정상적으로 작동하는지 모르겠습니다. 테스트를 위해 cli에서 curl을 통해 header에 Content-Type: application/json으로 요청을 보냈을 때는 정상 작동을 했으나 이 외의 타입(예를 들어 text 타입)에 대한 처리 구조를 잘 모르겠습니다.

확인하는 방법은 여러가지가 있는데요, 테스트 코드로도 가능하고, curl처럼 HTTP REQUEST를 보내주는 Intellij 내에 내장된 [http client](https://jojoldu.tistory.com/266)도 있고, GUI 도구인 [POSTMAN](https://www.postman.com/) 등이 있으니 참고하시면 좋을 것 같아요.  

Content-Type 헤더는 내가 보내는 데이터의 형식이 어떻게 생겼지 알려주는 헤더입니다. 만약 알려주지 않는다면 서버는 어떤 형식으로 왔는지 검사하는 과정을 거쳐야 합니다.  
예) 파일인지 확인 -> JSON인지 확인 -> 기타 다른 형식인지 확인 -> 일반 텍스트임을 확인
이런 과정과 다른 형식으로 오해하는 상황을 방지하기 위해 보내주는 헤더라고 생각하시면 될 것 같아요.  
혹시 다른게 궁금하셨다면 댓글 남겨주세요!

2024-06-29 16:38 UTC, us4c0d3 commented on src/main/java/gift/Product.java
> +public record Product(Long id, String name, Integer price, String imageUrl) {
클론코딩 강의 시간에 강사님께서 record를 쓰셔서 적용해보고자 했습니다.

2024-06-29 16:38 UTC, us4c0d3 commented on src/main/java/gift/Product.java
> +        // 빈 객체 전달을 위한 검증 임시 주석처리
DTO객체에 id 필드가 필요하며 null을 가지지 못하는 이유는 결국 DB에서 기본키로 사용하기 위함이라고 생각합니다. 그래서 검증을 위한 방법으로 몇 가지 생각을 해봤습니다.
1. 애초에 프론트단에서 검증 로직을 넣어 검증되지 않은 데이터가 서버로 넘어오지 않게 하기
2. id를 유저가 입력하지 않고 서버에서 자동으로 부여하는 방식(incremental 등)

둘 다 사용하는 것이 좋다고 생각합니다만 다른 방법도 있는지 궁금합니다

2024-06-29 17:07 UTC, us4c0d3 reviewed
각 파일별로 수정을 진행할 때 refactor와 fix를 사용해야될 것 같은데 이러한 커밋도 기능단위로 하는 것이 좋을까요? 아니면 상황에 따라 특정 파일을 리팩토링만 했을 때 refactor 커밋 하나만 쓰는 경우도 있나요?

2024-06-29 17:07 UTC, us4c0d3 commented on src/main/java/gift/ProductService.java
> +public class ProductService {
Service와 Controller를 분리하여 Controller에는 데이터 추출 및 연결, Service에는 비즈니스 로직만 수행하도록 하였습니다. 이는 Service에서 수행하는 비즈니스 로직들을 필요한 부분이 생겼을 때 재사용할 수 있고, 로직 자체만 독립적으로 테스트할 수 있다는 장점이 있습니다. 

Controller에 남은 코드들은 클라이언트의 요청에 대하여 Service의 메서드를 호출하고, 그 결과를 ResponseEntity를 통해 상태코드와 함께 클라이언트에게 응답하는 역할을 합니다.

2024-06-29 17:07 UTC, us4c0d3 commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
넵 JdbcTemplate에 대해 아직 완전히 이해된 것이 아니라 예시 코드를 대부분 참조하여 작성하여 그 부분이 부족한 것 같습니다.

2024-06-29 17:07 UTC, us4c0d3 commented on src/main/java/gift/Application.java
> +            + " price INT, imageUrl VARCHAR(255),"
전부 개행을 하다가 누락된 것 같습니다! 수정하겠습니다.

2024-06-29 17:07 UTC, us4c0d3 commented on src/main/resources/application.properties
> +# h2-console ??? ??
넵 알겠습니다.

2024-06-29 17:07 UTC, us4c0d3 commented on src/test/java/gift/ProductServiceTest.java
> +class ProductServiceTest {
다시 수정하여 커밋하겠습니다!

2024-06-29 17:07 UTC, us4c0d3 commented on src/test/java/gift/ProductServiceTest.java
> +    @DisplayName("getAllProducts empty test")
Empty는 객체는 존재하지만 비어있는 것이고 Null은 객체 자체가 없다는 뜻인가요?

2024-06-29 17:07 UTC, us4c0d3 commented on src/test/java/gift/ProductServiceTest.java
> +    void getAllProductsTest() throws Exception {
수정하겠습니다.

2024-06-30 16:21 UTC, us4c0d3 commented
로그, 테스트 부분 외에 코드 수정 완료했습니다!

2024-07-01 11:33 UTC, sang5c approved these changes
1주차 미션 고생하셨습니다 👍  
더 고민해볼 부분들 댓글 남겼으니 확인해주세요!  

추가로 질문에 답변을 드리자면, 

> 각 파일별로 수정을 진행할 때 refactor와 fix를 사용해야될 것 같은데 이러한 커밋도 기능단위로 하는 것이 좋을까요? 아니면 상황에 따라 특정 파일을 리팩토링만 했을 때 refactor 커밋 하나만 쓰는 경우도 있나요? 

fix는 코드를 수정했다는 의미가 아닌, 버그를 수정했다는 의미입니다 :)  

커밋을 나누는 이유는 미래의 나 혹은 리뷰(협업)하는 동료들에게 코드를 수정한 이유에 대해 명확하게 전달하기 위함입니다.  
리팩터링과 수정을 하나의 커밋으로 합치기보다는 각각을 커밋을 나눠 나타내면 좀 더 명확하지 않을까요?

파일을 단위로 커밋을 고려하지 않습니다.  
하나의 기능이 커밋의 기준이 되고, 커밋의 크기는 가능한 작게를 권장하구요. 커밋에는 한 줄만 포함될 수도 있고, 여러 파일에 걸쳐 여러 줄이 포함될 수도 있습니다.

2024-07-01 11:33 UTC, sang5c commented on src/main/java/gift/ProductService.java
> +    public Product getProductById(long id) {
그렇다면 파라미터가 많아지면 어떻게 될까요?  
만약 getProductxxxxx() 메서드 내에서 다른 메서드를 호출하면 어떻게될까요?
```java
public Product getProductByIdAndNameAndValuesAndData(long id, String name, String Values, String Data) {
    getInfoByIdAndNameAndValuesAndData(long id, String name, String Values, String Data);
}
```

위 코드는 좋은 코드일까요?  

메서드를 읽을 땐 반환형, 메서드명, 파라미터를 같이 읽어야 합니다.  
메서드 오버로딩을 활용하는 것도 고려해주세요!

2024-07-01 11:33 UTC, sang5c commented on src/test/java/gift/ProductServiceTest.java
> +class ProductServiceTest {
우석님의 테스트 코드에서는 ProductService에 JdbcTemplate 의존성을 주입해주고있지 않아서 발생하는 문제입니다.  
`의존성 주입`이라는 개념이 어려우신거라면 이 부분에 대해 다시 질문해주시면 답변드릴게요!

2024-07-01 11:33 UTC, sang5c commented on src/main/resources/templates/product_add_form.html
> +</html>
<img width="127" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/28697758/1a0c9438-a50f-4087-9575-1b806cc4e0f1">


다른 파일들도 동일한 경고가 발생하고 있습니다!  
상단의 File changed 탭으로 들어와서 보시면 경고가 보이니 나머지 부분도 수정해주세요~  
<img width="743" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/28697758/75cb9def-8f2a-408e-a53d-938bbeb67f9f">

2024-07-01 11:33 UTC, sang5c commented on src/main/java/gift/Application.java
> +    JdbcTemplate jdbcTemplate;
JdbcTemplate 사용법이 리뷰의 핵심이 아닙니다!  
1. 접근제어자가 적절하게 지정되었는지
2. 해당 클래스가 다음 컨벤션을 만족하고 있는지(생성자, 필드, 메서드 순서가 올바른지) 확인해주세요.  
    - https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html#1852

2024-07-01 11:33 UTC, sang5c commented on src/main/resources/application.properties
> +# h2-console 사용
해당 주석이 없으면 어떤 일이 생기나요? 다음 줄을 해석했을때 주석과 어떤 차이가 있을까요?
```
spring.h2.console.enabled=true
```

2024-07-01 11:33 UTC, sang5c commented on src/main/resources/application.properties
> +# db url
이 주석도 동일합니다.  
누구에게 어떤 정보를 전달하기 위해 주석을 달았는지, 없으면 어떻게 되는지 고민이 필요합니다.

2024-07-01 11:35 UTC, merged

2024-07-01 12:05 UTC, us4c0d3 commented on src/main/resources/application.properties
> +# h2-console 사용
이에 대하여 코드에 주석을 남기는 이유에 대하여 처음부터 다시 생각해봤습니다.

주석은 코드에 대한 추가적인 설명을 남길 수 있지만 결국 부가적인 것이고, 코드만으로 의도를 명확히 표현한다면 굳이 주석이 필요없는 것 같습니다. application.properties의 내부 속성들의 이름들은 `spring.h2.console.enabled`, `spring.datasource.url`과 같이 명확하고 이에 따라 기존 주석은 삭제해도 좋을 것 같습니다. 다만 h2 url이 테스트환경에서 주로 사용하는 In-memory모드라는 것을 
```
spring.datasource.url=spring.datasource.url=jdbc:h2:mem:test # 테스트환경 In-Memory mode
```
와 같이 남기거나 config에 관한 수정커밋을 할 때 커밋 메시지로 남길 필요가 있을 것 같습니다.