강원대 BE_김병수_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #29
Opened 2024-06-25 15:19 UTC by GamJaDo

질문

6/24 클론 강의를 할 때 강사님께서 lombok을 사용하지 말라고 하셨는데 왜 사용하지 말아야 하나요?
이유를 찾아보니 IDE 지원, JDK 변경 후에 깨질 수 있는 비표준적 접근법, 사용시 모든 계층이 롬복에 의존하게되는 이유들을 보았는데, 이것 말고도 다른 이유들이 있나요?

2024-06-27 15:37 UTC, jaymarystella requested changes
안녕하세요 병수님
리뷰어 제이입니다. 만나서 반갑습니다.
피드백 몇가지 남겼는데 확인주시고 반영해주시면 좋을거같아요. 질문주신부분은 코멘트 따로 남겨두었습니다.
특별히 받고싶은 피드백이 있으면 말씀주세요.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        if(product == null) {
style guide를 잘 지켜볼까요? 다른부분들도 마찬가지입니다.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Product> addProduct(@RequestBody Product product) {
ResponseEntity를 사용하신 이유가 있을까요? 어떤 점이 좋게느껴지신지 남겨주시면 좋을거같아요.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        }
delete를 했을때의 응답값이 boolean형태군요. update하실때는 없는 상품에 대해서는 null을 반환하고 delete하실때는 false를 반환하네요. 통일성있게 바꿔보면 어떨까요?

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        }
참고로 null반환은 지양해주세요.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +	public void setId(Long id) {
사소할수있어도 style guide를 꼭 따라주세요.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +        products.put(updatedProduct.getId(), updatedProduct);
업데이트인데 기존 id의 엔티티를 삭제하고 새로만들고있네요. id가 바뀌는게 맞을까요?

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +    private Map<Long, Product> products = new HashMap<>();
인메모리로 다뤘을때 문제가 발생할 수 있는 부분이 있을까요?

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +	public String getName() {
> 6/24 클론 강의를 할 때 강사님께서 lombok을 사용하지 말라고 하셨는데 왜 사용하지 말아야 하나요?
> 이유를 찾아보니 IDE 지원, JDK 변경 후에 깨질 수 있는 비표준적 접근법, 사용시 모든 계층이 롬복에 의존하게되는 이유들을 보았는데, 이것 말고도 다른 이유들이 있나요?

단점을 이야기하자면 코드가독성저하나 주로사용되는 생성자관련 애노테이션에서 문제가 발생할 소지가 있습니다. 보통 필드순서에따라 실수가 일어나곤하는데요, 실제로는 lombok config에 위험성이 있는 애노테이션은 아예 사용하지 못하도록 설정을해두고씁니다.

2024-06-27 15:37 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +	public String getName() {
다만 강사님께서 사용하지 말라고하셨던 이유는 현재 실무적인 이유보다는 자동생성되는 코드에 대해서 모르고 넘어가는것을 방지하기위함이라고 생각됩니다. 도구의 원리를 이해하고 사용하는것과 그렇지 않은것은 차이가 있기 때문입니다.

2024-06-28 08:52 UTC, GamJaDo commented on src/main/java/gift/controller/ProductController.java
> +        if(product == null) {
메서드 작성시 camelCase 형식으로 하고 동사 형태로 명명 해야합니다.
답변해주신것 처럼 변경하였습니다.

2024-06-28 08:52 UTC, GamJaDo commented on src/main/java/gift/model/Product.java
> +	public void setId(Long id) {
메서드와 메서드 사이에 빈 line으로 구분을 해야합니다.
답변해주신것 처럼 변경하였습니다.

2024-06-28 08:54 UTC, GamJaDo commented on src/main/java/gift/service/ProductService.java
> +        products.put(updatedProduct.getId(), updatedProduct);
id가 1, 2, 3, ... 순차적으로 진행되지 않고, 예시에서는 id가 8146027로 지정되어 있어서 id도 변경되어야 하는 줄 알았습니다.
primary key 의도에 맞게 바뀌지 않도록 변경하였습니다.

2024-06-28 08:55 UTC, GamJaDo commented on src/main/java/gift/service/ProductService.java
> +    private Map<Long, Product> products = new HashMap<>();
서버가 재시작 되었을 때 데이터가 손실됩니다. (휘발성)

2024-06-28 08:56 UTC, GamJaDo commented on src/main/java/gift/controller/ProductController.java
> +        }
일관성 있게 변경하였습니다.

2024-06-28 08:58 UTC, GamJaDo commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Product> addProduct(@RequestBody Product product) {
ResponseEntity를 사용하면 상태 코드를 따로 설정할 수 있어서 쓰고는 있습니다.
굳이 ResponseEntity를 사용하지 않고

@PostMapping
public Product addProduct(@RequestBody Product product) {
    // 
    return product;
}
이런식으로 할 수도 있을것 같습니다.

2024-06-30 12:29 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +        products.put(updatedProduct.getId(), updatedProduct);
id가 순서대로 만들어질수도, 그렇지 않을수도있습니다. 다만 update는 key가 바뀌지는 않기 때문에 그부분만 신경써주시면 될거같아요.

2024-06-30 12:33 UTC, jaymarystella requested changes
안녕하세요 병수님.
1주차 미션 고생많으셨어요.
main branch에는 머지를 할 수 없어서 target branch를 remote의 본인 브랜치로 해주셔야 될거에요. 
그리고 다시 요청주시면 merge할수 있도록 하겠습니다.

2024-06-30 12:33 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +    public String addProduct(@ModelAttribute Product product) {
url mapping 컨벤션도 한번 찾아보시면 좋을거같아요.

2024-06-30 12:33 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +    private JdbcTemplate jdbcTemplate;
jdbcTemplate을 사용하면서 어떤 장/단점들을 느껴보셨을까요?

2024-06-30 15:24 UTC, GamJaDo commented on src/main/java/gift/service/ProductService.java
> +    private JdbcTemplate jdbcTemplate;
장단점으로는 SQL문을 직접 작성해야한다고 느꼈습니다.
왜냐하면 JdbcTemplate은 SQL문을 직접 다루어야 하는 부담이 있지만, 이를 통해 더 높은 성능과 특정 데이터베이스 기능을 활용할 수 있는 융통성이 있다고 생각합니다.

2024-06-30 15:26 UTC, GamJaDo commented
본인 브랜치로 변경하였습니다.

2024-07-01 14:41 UTC, jaymarystella approved these changes
안녕하세요 병수님
첫번째 미션 PR 브랜치수정해주셨네요~
이만 머지할게요.

2024-07-01 14:41 UTC, merged