경북대 BE_정성훈_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #3
Opened 2024-06-24 13:23 UTC by zzoe2346

## 코드 작성하면서 어려웠던 점
- 제가 작명한 컨트롤러의 메서드명이 해당 메서드의 기능을 잘 표현하는지 확신이 없습니다. 이름이 조금 이상해도 **주석**으로 커버쳐도 되는 부분일까요?
- 예외상황 처리를 이런 restAPI에서는 어떻게 처리하면 좋을까요? 

## 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
- 제가 정한 변수명, 메서드명에 개선점이 있을지 궁금합니다. 항상 코딩할때 작명하는게 제일 고민이 됩니다.
- String을 반환함으로써 제대로 요청 처리가 되었는지 확인하게 구현해보았는데, 더 나은 방법이 혹시 있을지 궁급합니다.

감사합니다!

2024-06-30 08:02 UTC, sang5c requested changes
안녕하세요 성훈님! 리뷰를 맡은 박상오입니다. 잘 부탁드려요 💪💪

PR에 대해서는 컨벤션이 지켜지지 않아, Request Change를 드립니다.  
예외처리에 대해서는 앞으로 배울 내용이라, 차주 강의 들어보시고 다시 질문해주시면 답변드릴게요!  

interface를 사용한 코드가 인상적이었습니다. 다방면으로 노력해보신 것 같아서 멋지네요 👍  
대신 interface가 왜 필요한지, 어떻게 활용하면 좋을지에 대해서는 고민이 조금 더 필요해보입니다. 작성하신 코드에서 interface가 없었으면 어땠고, 있으면 어떤 장점이 생기는지도 생각해보시면 좋을 것 같아요!  

> 제가 정한 변수명, 메서드명에 개선점이 있을지 궁금합니다. 항상 코딩할때 작명하는게 제일 고민이 됩니다.  

아직까지는 이해가 가지 않는 메서드명은 없었습니다. 앞으로 리뷰하면서 중점적으로 고민해볼게요 :)  
저는 애매한 포인트를 만나면 글을 작성한다는 생각으로 한글로 쓰고 -> 영어로 번역하고 -> 메서드명으로 더 좋은 방법은 없을지 고민하는 식으로 작업하는 편이에요.

> rest api에서 String메세지를 반환함으로써 제대로 요청 처리가 되었는지 확인하게 구현해보았는데, 더 나은 방법이 혹시 있을지 궁금합니다.  

이 부분 리뷰 남겼으니 확인해주세요! 요구사항에 JSON을 통해 요청과 응답을 보낸다 라는 부분이 있습니다.

> MethodArgumentNotValidException 같은 예외를 처리하기 위해 GlobalExceptionHandler클래스를 이용하였고, Controller 클래스에서 try-catch로도 예외를 처리했는데 이렇게 작성하니 좀 코드가 지저분한거같은 느낌이 들어 고민입니다.

예외처리는 이후에 배울 내용이라 여기선 답변드리지 않을게요! 다음 주 과제를 진행하면서 다시 한 번 고민해보시고 리뷰 요청 주시면 다시 말씀드리겠습니다. 

> Interface를 처음 응용해서 사용해보았는데, 아직 익숙치 않아 제대로 사용한건지 확신이 안들었습니다.  

다양한 노력을 해보시는게 좋다고 생각해요.  
단, 여기서는 기본 요구사항을 높은 우선순위로 수행하신 다음, 그 외 작업들에 신경써주시면 저도 더 좋은 답변을 드리기 위해 노력하겠습니다 💪

> chatGPT의 도움을 받아 테스트 코드를 작성해보았습니다.(어떤식으로 동작하는 테스트 코드인지 학습)  

GPT를 사용하신 코드라고 말씀하셔서 따로 리뷰하지 않았는데요, 직접 고민하고 작성한 코드였으면 하는 바램이 있습니다.  
리뷰와 멘토링의 효과를 보기 위해서 잘못된 테스트 코드를 하나라도 직접 작성하고 어떤 부분에서 막혔는지, 어떤 고민을 했는지 알려주시면 좋을 것 같아요.

2024-06-30 09:42 UTC, zzoe2346 commented on src/main/resources/templates/version-SSR/add-error.html
> +</html>
이런 경고가 있는지 몰랐는데 알려주셔서 감사합니다! 멘토님의 경고를 무시하지 않아야 된다는말씀 명심하겠습니다.

2024-06-30 09:46 UTC, zzoe2346 commented on src/main/java/gift/controller/GlobalExceptionHandler.java
> +    //MethodArgumentNotValidException이 Controller 메서드 단계에서 안잡혀서 @ControllerAdvice를 이용해보았습니다.
넵 다음 PR 부터 그렇게 하겠습니다!

2024-06-30 09:47 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductController.java
> +    //@Qualifier("MEMORY DATABASE") //memoryDB(Map<Long, Product>>) 원하면 주석 풀고 아래 H2를 주석화 시킬 것
네 멘토님. 사실 주석은 별 생각없이 사용했었는데 이렇게 말씀해주시니 너무 생각없이 쓴거 아닌가 하는 생각이듭니다. 한번 고민해보겠습니다.

2024-06-30 09:57 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductController.java
> +    ProductDB productDB;
오직 ProductController에서 사용되도록 private를 지정하였습니다. ProductController에서 의존성을 주입한 productDB에 외부의 접근을 제한하여 객체의 무결성을 유지하도록 하였습니다.

2024-06-30 10:11 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +        }catch (Exception e) {
네 수정하였습니다!

2024-06-30 10:14 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +    //Create
넵 개행추가 하였습니다

2024-06-30 10:14 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +import gift.db.ProductDB;
정리하였습니다. 감사합니다.

2024-06-30 10:18 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +    public String updateProduct(@PathVariable("id") Long id, @RequestBody Product product) {
아 Product를 받기때문에 불필요한거 같습니다. 삭제하였습니다. 감사합니다!

2024-06-30 10:22 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +    ProductMemoryDB productDB;
ProductDB 인터페이스를 사용하도록 변경하였고 private 를 붙였습니다. 

ProductMemoryDB를 사용한 이유는 기존에 코드를 미처 변경못한것 같습니다. 이제는 인터페이스를 활용하도록 변경완료하였습니다!

2024-06-30 10:40 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +    public ProductH2DB(JdbcTemplate jdbcTemplate) {
너무 강의의 코드를 생각 없이 복사 붙여넣기 한것 같습니다. 이유 없이 한거라 부끄럽습니다. 다른 코드들 처럼 필드 주입방식으로 통일시키겠습니다.

감사합니다!

2024-06-30 10:42 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +@Qualifier("H2 DATABASE")
미처 스프링 빈의 네이밍 컨벤션은 생각지 못하였습니다. 문서를 참고하여 수정하겠습니다.

2024-06-30 10:44 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +
수정하였습니다

2024-06-30 10:48 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +    public void addProduct(Product product) throws Exception {
MethodArgumentNotValidException을 해결해보려고 테스트해볼때 붙이고 깜밖하고 제거를 하지 않은것 같습니다. 

바로 삭제하겠습니다. 감사합니다.

2024-06-30 12:15 UTC, zzoe2346 commented on src/main/java/gift/controller/ProductRestController.java
> +            return "상품 추가 성공!";
수정 완료했습니다. 감사합니다!

2024-07-01 12:28 UTC, sang5c approved these changes
1주차 미션 고생하셨습니다 💪  

다음 미션 진행을 위해 approve를 드리나, 남긴 리뷰를 확인해주세요!  
수정되지 않으면 다음 미션에서도 동일한 리뷰를 드릴 예정입니다 :)  

추가로, 리뷰에 대한 resolve 처리는 제가 할 수 있도록 남겨주시면 감사하겠습니다 😉

2024-07-01 12:28 UTC, sang5c commented on src/main/java/gift/controller/ProductRestController.java
> +    public ResponseEntity<Map<String, String>> updateProduct(@RequestBody Product product) {
id를 받지 않아야 한다는 의견이 아니었습니다 😅  
이 부분은 이번 주에 배우는 내용을 참고해서 고쳐보시면 좋을 것 같네요.

2024-07-01 12:28 UTC, sang5c commented on src/main/java/gift/db/ProductH2DB.java
> +    private JdbcTemplate jdbcTemplate;
필드 주입을 의도한 리뷰가 아닙니다.  
다음 글을 읽어보시고, 생성자 주입 형태로 변경해주세요.  
다른 클래스에서 사용된 @autowired도 변경해주세요!  
https://mangkyu.tistory.com/125

2024-07-01 12:28 UTC, merged

2024-07-01 12:46 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +@Qualifier("h2Database")
네 감사합니다!

2024-07-01 12:47 UTC, zzoe2346 commented on src/main/java/gift/db/ProductH2DB.java
> +    private JdbcTemplate jdbcTemplate;
감사합니다. 공부하고 변경하겠습니다.