강원대 BE_고명준_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #30
Opened 2024-06-25 15:57 UTC by noojmogstel

### 코드 작성하면서 어려웠던 점
- Test코드 작성이 익숙치 않아 관련 자료를 참고하여 진행했습니다. 부족한 점이 많은 코드라고 생각합니다. 코드리뷰 부탁드립니다!!
- 생성,수정,삭제하는 과정에서 유효성 검증이 필요하다고 생각했습니다.(id값이 없는 객체의 생성,수정,삭제) 따로 클래스를 분리해서 하고싶었는데 부득이하게 Products 클래스에서 진행했습니다. 구조를 어떤식으로 짜는것이 더 좋았을지 궁금합니다.

### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- 처음엔 Post,Patch,Delete 매핑을 처리하는 메서드의 반환값을 String으로 지정했었습니다. 하지만 테스트 코드를 작성하며 너무 모호하고 테스트작성시에 불편함을 느껴 ResponseEntity를 사용하여 진행했습니다. 작성한 부분이 맞게 되었는지, 실무에서나 보통은 어떻게 작업하는지 궁금합니다.
- 위에서 말씀드린 유효성 검증을 간단하게 진행하는 메서드의 반환값이 boolean으로 작성하였는데 이것도 같은 맥락으로 궁금합니다.
- 이미 다른사람이 짜놓은 프로젝트의 구조를 참고하기보다는 제가 생각한 방식으로 구현하고 리팩토링을 거쳤습니다. 부족한 점이 많을거라 생각하고 말씀해주시는 내용최 대한 수용해보겠습니다. 감사합니다!

2024-06-27 17:22 UTC, cheol-95 requested changes
안녕하세요~
코드를 보니 공부하시면서 많이 고민하신게 느껴지네요!

전반적으로 잘 작성하셨고 코멘트를 따라 한번 더 다듬으면 좋을 것 같습니다.
고생하셨어요 👍

---
테스트 코드 관련
- 테스트 코드 작성은 익숙해지기까지 시간이 걸릴 수 있습니다. 좋은 자료로는 JUnit, Mockito 등의 프레임워크에 대한 공식 문서와 예제 코드를 참고하는 것이 좋습니다. 테스트 코드는 코드 품질을 높이고 버그를 줄이는 데 중요한 역할을 합니다. 작은 단위의 테스트부터 시작하여 점차 통합 테스트로 확장해 나가는 방식으로 진행해 보세요.

유효성 검증을 위한 클래스 분리
- 효성 검증을 별도의 클래스로 분리하는 것은 좋은 접근입니다. Service 레이어를 도입하여 비즈니스 로직과 데이터 접근 로직을 분리하는 것이 좋습니다. 이렇게 하면 코드의 가독성과 유지보수성이 향상됩니다. 예를 들어, ProductValidator 클래스를 만들어 유효성 검증을 담당하게 하고, Products 클래스는 순수한 데이터 저장소 역할만 하도록 할 수 있습니다.

ResponseEntity 사용
- ResponseEntity를 사용하는 것은 매우 적절한 선택입니다. 이는 HTTP 상태 코드와 응답 본문을 명확하게 반환할 수 있어 클라이언트와의 통신을 더 명확하게 합니다. 실무에서도 자주 사용되는 방법입니다. 응답이 단순 문자열이 아닌 경우, 상태 코드와 함께 필요한 데이터를 반환하는 것이 좋습니다.

유효성 검증 메서드의 반환값(boolean)
- 효성 검증 메서드의 반환값을 boolean으로 사용하는 것도 하나의 방법이지만, 예외를 던지는 방식으로 처리하는 것이 더 명확하고 관리하기 좋습니다. 예외를 통해 에러 상황을 처리하면, 에러 발생 시점과 원인을 더 쉽게 파악할 수 있습니다. 예외 클래스도 세분화하여 특정 오류를 명확히 나타내는 것이 좋습니다.

2024-06-27 17:22 UTC, cheol-95 commented on src/main/java/gift/domain/Products.java
> +}
synchronized 키워드를 추가하여 싱글턴 인스턴스의 초기화가 스레드 안전하게 되도록 만들어주세요.
추가로, 공백등을 신경써서 style guide 를 지켜주세요.
```java
public static synchronized Products getInstance() {
    if (products == null) {
        products = new Products();
    }
    return products;
}
```

2024-06-27 17:22 UTC, cheol-95 commented on src/main/java/gift/domain/Products.java
> +    }
HashMap은 스레드 안전하지 않으므로 멀티스레드 환경에서 사용하면 데이터 일관성이 깨질 수 있습니다.
멀티스레드 환경에서도 안전하게 사용할 수 있는 데이터 구조인 ConcurrentHashMap을 사용하는 것이 좋습니다.

2024-06-27 17:22 UTC, cheol-95 commented on src/main/java/gift/domain/Products.java
> +    }
현재 상태에서는 에러 처리를 해당 위치에서 처리하는것도 좋아보입니다.
```java
        if (product.getId() == null) {
            throw new ProductOperationException("Product ID cannot be null");
        }
        productsList.put(product.getId(), product);
```

2024-06-27 17:22 UTC, cheol-95 commented on src/main/java/gift/domain/Products.java
> +    }
위 로직에서 input으로 받은 id와 product객체의 id 값은 동일해야 합니다.
그렇지 않으면 엉뚱한 객체를 삭제하고 새로운 product 객체를 넣을 수도 있어요.

검증 로직이 있으면 좋을 것 같습니다.

2024-06-27 17:22 UTC, cheol-95 commented on src/test/java/gift/ProductControllerTest.java
> +    private MockMvc mvc;
MockMvc 은 무엇인지 한번 더 알아보면 좋을 것 같습니다.

2024-06-27 17:22 UTC, cheol-95 commented on src/test/java/gift/ProductControllerTest.java
> +@WebMvcTest(ProductController.class)
WebMvcTest 은 어떤 역할을 할까요?

2024-06-27 17:22 UTC, cheol-95 commented on src/test/java/gift/ProductControllerTest.java
> +    }
테스트 메서드 내의 각 단계를 명확히 분리하여 가독성을 높이는게 좋아보입니다.
이를 위해 주석을 추가하거나, Given-When-Then 패턴을 사용 수 있습니다.

2024-06-28 05:13 UTC, noojmogstel commented on src/main/java/gift/controller/AdminController.java
> +    Products products = Products.getInstance();
이 부분은 Step3에 리팩토링 하였습니다! 감사합니다!

2024-06-28 05:28 UTC, noojmogstel commented on src/main/java/gift/controller/AdminController.java
> +
상품 로직이라기보다는 상품 추가 화면을 보여주는 Controller라 @RestController가 아닌 @Controller를 선언해서 추가했습니다.

2024-06-28 05:29 UTC, noojmogstel commented on src/main/java/gift/controller/AdminController.java
> +    }
이 부분도 상품 관리화면인 product-manage.html을 보여주는 용도로 사용하였습니다. 혹시 ProductController로 합치는게 좋을까요?

2024-06-28 05:29 UTC, noojmogstel commented on src/main/java/gift/controller/ProductController.java
> +    @PatchMapping("/edit/{id}")
수정하였습니다. 감사합니다:)

2024-06-28 05:30 UTC, noojmogstel commented on src/main/java/gift/controller/ProductController.java
> +    @DeleteMapping("/delete/{id}")
수정하였습니다. 감사합니다:)

2024-06-28 05:37 UTC, noojmogstel commented on src/main/java/gift/domain/Product.java
> +    public Product(){}
product-add.html에서 POST메서드의 바디 부분에서 json으로 변환하는 과정에서 빈 생성자가 없으면 오류가 발생하여 추가했습니다!

2024-06-28 05:43 UTC, noojmogstel commented on src/main/java/gift/domain/Products.java
> +    }
이 부분은 생각 못했었습니다! 수정해서 올려보도록 하겠습니다!

2024-06-30 11:30 UTC, noojmogstel commented on src/test/java/gift/ProductControllerTest.java
> +    }
테스트코드를 전체적으로 리팩토링하였습니다. 감사합니다!

2024-06-30 15:17 UTC, cheol-95 commented on src/main/java/gift/controller/AdminController.java
> +    }
해당 컨트롤러가 단순히 뷰를 보여주기 위한 컨트롤러라면 그대로 두셔도 좋습니다.

2024-07-03 04:05 UTC, cheol-95 approved these changes

2024-07-03 05:48 UTC, merged