부산대 BE_강수민_1주차 과제(1단계, 2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #32
Opened 2024-06-25 17:15 UTC by wvssm

## 리뷰 받고 싶은 부분

### step 1 
1. 등록되지 않은 id로 조회할 때, ProductNotFoundException 클래스를 만들어 throw했습니다. 이러한 방식으로 예외 처리해도 괜찮은지 궁금합니다.

2. controller에서 addProduct, deleteProduct가 일반적으로 어떤 값을 반환하는지 궁금합니다. 

3. 상품 정보 변경 api를 만들 때, 보통 하나의 정보(ex. 가격)을 수정하기 위한 api를 각각 따로 만드는지 아니면 여러 정보를 한 번에 변경하는  api를 만드는지 궁금합니다. 

4. controller에서 deleteProduct는 하나의 상품을 다루니 api path를 api/products보다 api/product를 사용하는 것이 적절한지 궁금합니다. 

5. 기능 단위의 커밋을 진행할 때, 만약 상품 등록 기능을 구현한다면 상품 등록에 관련된 controller, service를 한 번에 커밋해야 하는지 아니면 상품 조회에 관련한 controller, service를 따로 커밋해야 하는지 궁금합니다.

6. DTO를 생성했을 경우, 커밋할 때 어떤 tag name을 사용해야 하는 지 궁금합니다. (저의 경우 feat를 사용했습니다.)

7. 일관된 인터페이스를 가진 api를 작성하기 위해서 현재 코드에서 어떠한 점을 보완해야 하는 지  궁금합니다.

### step 3
1. jdbc를 이용하여 데이터를 저장할 때에는 Entity가 id를 포함한 생성자를 가지거나, setId라는 setter()가 필요할 수 밖에 없나요? 어떤 상황에서 Entity의 생성자에 id가 포함되면 안되는지 궁금합니다.

2024-06-29 06:00 UTC, jadie0319 requested changes

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/dto/ProductRequestDto.java
> +    }
Dto 객체를 Entity 로 변환시키는 메서드가 Dto 클래스에 위치하는게 적절할까요?

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/dto/ProductRequestDto.java
> +    }
미사용 코드는 삭제 해주시는게 좋아요 :)

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/dto/ProductResponseDto.java
> +    }
미사용 코드는 삭제 해주시는게 좋아요 :)

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/repository/ProductRepository.java
> +public interface ProductRepository {
인터페이스 작성 Good! 💯

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/exception/ProductNotFoundException.java
> +public class ProductNotFoundException extends RuntimeException{
어떤 Exception이 발생했는지 바로 알 수 있겠네요! 적절한 이름으로 잘 만들었습니다! 👍

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/repository/impls/ProductRepositoryH2Impl.java
> +    }
입력으로 받은 id 를 그대로 반환해주고 있는데 반환값이 필요할까요?

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +@Transactional(readOnly = true)
클래스에 Transactional(readOnly = true) 를 붙이신 이유가 있을까요?

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id)
productRepository.findById 메서드가 여러곳에서 사용되고 있어요. 중복된 코드를 줄일 수 있을 것 같습니다~

2024-06-29 06:00 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +                .orElseThrow(()-> new ProductNotFoundException("ID가 " + id + "인 상품이 존재하지 않습니다."))
똑같은 문자열이 중복으로 사용되고 있어요.  아래와 같은 코드는 어떻게 생각하시는지 궁금합니다
```java
private final String NOT_FOUND_PRODUCT_MESSAGE="ID가 %d 인 상품이 존재하지 않습니다.";
public ProductResponseDto findById(Long id){
    return productRepository.findById(id)
            .orElseThrow(()-> new ProductNotFoundException(NOT_FOUND_PRODUCT_MESSAGE.formatted(id)))
            .toDto();
    }
```

2024-06-29 06:15 UTC, jadie0319 reviewed
전반적으로 많이 고민하며 코딩하셨다는게 느껴지는 좋은 코드였어요 :)
좀더 고민했으면 좋을만한 부분이 보여 피드백 남겨놨습니다!

2024-06-29 06:37 UTC, jadie0319 commented
안녕하세요! 카카오테크 캠퍼스 2기 백엔드 과정의 멘토링을 맡게된 멘토 제이디 입니다. 
부족하지만 앞으로 6주간 좋은 시간이 되게 노력하겠습니다.  잘부탁드립니다~! 
그리고 질문은 많으면 많을수록 좋습니다. 많이 질문해주세요! 
이번 PR 에서 질문해주신 부분에 대해서 아래 정리했습니다.

등록되지 않은 id로 조회할 때, ProductNotFoundException 클래스를 만들어 throw했습니다. 이러한 방식으로 예외 처리해도 괜찮은지 궁금합니다.
```text
괜찮습니다. 어떤 예외가 발생했는지 Exception 클래스 이름에서부터 알 수 있어 좋네요.
직접 Exception 생성하는 방법 외에 공통 Exception 클래스를 만들고 에러 메시지만 다르게 하는 방법도 있어요. 
```

controller에서 addProduct, deleteProduct가 일반적으로 어떤 값을 반환하는지 궁금합니다.
```text
API 를 사용하는 측에서 어떤 값을 원하는지에 따라 반환하는 값이 달라질 것 같아요. 
구현하신 것처럼 product 의 id 정도를 반환해주기도 하고 아무 값도 반환하지 않기도 합니다.
```

상품 정보 변경 api를 만들 때, 보통 하나의 정보(ex. 가격)을 수정하기 위한 api를 각각 따로 만드는지 아니면 여러 정보를 한 번에 변경하는 api를 만드는지 궁금합니다.

```text
하나의 정보를 수정하는 API 를 여러개 구현 VS 모든 정보를 변경할 수 있는 하나의 API 

이런 관점에서 질문하신게 맞으실까요? 맞다면 두가지 구현 방법에 각자 장단점이 있는 것 같아요. 

각각 구현 API
- 기능이 명확하고 단순하다.
- 이 코드의 변경은 하나의 이유로만 변경이 된다.
- API의 개수가 많다.

한번에 변경 API
- API 개수가 적어 관리가 쉽다.
- 이 코드는 여러 이유로 변경이 될 수 있어 코드가 복잡해질 수 있다. 

보통 하나의 정보를 수정하기 위한 API를 각각 만듭니다. 
여러 정보를 한번에 변경하는 API 의 코드를 상상해보시면 도움이 되실 것 같아요. 
```

controller에서 deleteProduct는 하나의 상품을 다루니 api path를 api/products보다 api/product를 사용하는 것이 적절한지 궁금합니다.

```text
보통 API 에서 resource 를 지칭할 땐 일관성을 위해 복수를 많이 사용합니다. 
API URL을 봤을 때 /api/products/{id} 이니 특정 ID의 상품만 삭제한다는 의미가 잘 전달되는 것 같아요!
```

기능 단위의 커밋을 진행할 때, 만약 상품 등록 기능을 구현한다면 상품 등록에 관련된 controller, service를 한 번에 커밋해야 하는지 아니면 상품 조회에 관련한 controller, service를 따로 커밋해야 하는지 궁금합니다.

```text
이번 과정을 진행하면서는 controller, service 따로 커밋해주시는게 좋을 것 같아요.
하지만 의미 있는 커밋 단위가 무엇인지는 고민해보셔도 좋은 주제 같아요. 
```

DTO를 생성했을 경우, 커밋할 때 어떤 tag name을 사용해야 하는 지 궁금합니다. (저의 경우 feat를 사용했습니다.)

```text
 feat 로 사용하시면 됩니다. 
```

일관된 인터페이스를 가진 api를 작성하기 위해서 현재 코드에서 어떠한 점을 보완해야 하는 지 궁금합니다.

```text
현재 미션에 필요한 인터페이스와 구현 클래스 잘 구현하셨습니다! 
```

jdbc를 이용하여 데이터를 저장할 때에는 Entity가 id를 포함한 생성자를 가지거나, setId라는 setter()가 필요할 수 밖에 없나요? 어떤 상황에서 Entity의 생성자에 id가 포함되면 안되는지 궁금합니다.

```text
db에 데이터를 저장할 때 id 를 직접 저장해야 한다면 생성자나 setter 를 통해 id 를 전달해줘야 해요. 
하지만 db 에서 자동으로 id를 생성하는 경우(db auto_increment 사용)라면 id 를 전달안해줘도 되겠네요
```

2024-06-29 12:37 UTC, jadie0319 requested changes

2024-06-29 12:37 UTC, jadie0319 commented on src/main/java/gift/controller/ProductController.java
> +    @Autowired
현재 스프링 버전에서는 생성자에 Autowired 안붙이셔도 됩니다 :)

2024-06-29 12:37 UTC, jadie0319 commented on src/main/java/gift/controller/ProductRestController.java
> +public class ProductRestController {
Controller 와 RestController 를 나눠서 구현하니 각 클래스의 역할이 더 명확하게 보이네요 ㅎ

2024-07-01 05:16 UTC, wvssm commented on src/main/java/gift/controller/ProductRestController.java
> +    public ResponseEntity<?> getProduct(@PathVariable Long id){
오 유용한 단축키네요! 잘 활용해서 코드 정리하겠습니다! 감사합니다☺️

2024-07-01 05:26 UTC, wvssm commented on src/main/java/gift/domain/Product.java
> +    }
안됩니다. 도메인에 객체를 dto로 변환시키는 메서드를 작성한다면, dto를 변경할 시 도메인까지 수정해야합니다.
그러므로 DTO가 도메인을 의존하도록 코드를 수정해보겠습니다!

2024-07-01 06:13 UTC, wvssm commented on src/main/java/gift/dto/ProductRequestDto.java
> +    }
Dto와 Entity 중 좀 더 자주 변경될 수 있는 곳이 저는 Dto라고 생각했습니다.
그래서 Dto 객체를 Entity로 변환시키는 메서드를 Dto 클래스에 위치시켰습니다.
변경의 빈도 말고 제가 고려해야할 사항이 또 있을 지 궁금합니다!

2024-07-01 06:17 UTC, wvssm commented on src/main/java/gift/repository/impls/ProductRepositoryH2Impl.java
> +    }
반드시 필요하지는 않다고 생각합니다!
사용자 요구에 따라 id를 반환하거나 아무것도 반환하지 않으면 될 것 같습니다!

2024-07-01 06:29 UTC, wvssm commented on src/main/java/gift/service/ProductService.java
> +@Transactional(readOnly = true)
findById 나 findAll 같이 조회를 담당하는 메서드에 바로 적용하기 위해 class에 일단 붙였습니다.
조회라는 메서드의 작업을 명확하게 알리기 위해서는 메서드 위에 붙이는 게 좀 더 나은 방법인 것 같습니다!

2024-07-01 06:30 UTC, wvssm commented on src/main/java/gift/service/ProductService.java
> +                .orElseThrow(()-> new ProductNotFoundException("ID가 " + id + "인 상품이 존재하지 않습니다."))
중복되는 코드를 줄일 수 있어서 좋은 방법인 것 같습니다!

2024-07-01 06:58 UTC, wvssm commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id)
함수로 따로 빼서 중복을 줄였습니다! 피드백 감사합니다 🥇

2024-07-01 07:14 UTC, merged