충남대 BE 박상우 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #34
Opened 2024-06-25 17:41 UTC by pswaao88

코드를 작성하면서 어려웠던 점
우선 제가 스프링이라는 것을 처음 접했습니다. 월요일에 라이브 강의에서 간단한 맛보기 실습을 진행한뒤에 과제를 진행을 하게 되었는데 스프링에 대해서 아무것도 모르는 상태에서 과제를 보니 어떻게 시작을 해야하고, 어떤 부분을 공부를 해야 하며, 패스트 캠퍼스에 있는 강의 같은 경우에는 너무 광범위하게 강의를 나가 어떤 강의를 듣고 해야할지 몰라서 굉장히 답답하고 힘들었습니다. 계속 구글링과 패스트 캠퍼스의 일부 강의를 통해서 postman의 사용법을 알게 됐고 이를 통해서 과제에서 요구한 Get, Put, Delete, Post를 구현을 했습니다. 앞으로 강의를 진행할 텐데 어떤 부분을 공부를 해야 이 내용을 따라 갈 수 있을지 걱정이됩니다.

리뷰 받고 싶은 부분
1. 제가 스프링을 처음 다루다 보니 지금처럼 코드를 짜는게 맞는 건지 궁금합니다.
2. 제가 단순하게 생성, 삭제 가져오기만 구현했는데 제한사항 (예를 들면 상품을 가져올때 해당되는 id의 상품이 없다)을 나누어서 코드를 짜야하는지 궁금합니다.
3. 테스트 코드를 한번 짜볼려고 했으나 메소드의 리턴값이 제가 생각했던것과 다르게 나와서 테스트 메소드를 어떤 식으로 작성해야하는지 궁금합니다.
4. 지금 제 상태가 어떤 것을 모르는지 모르는 상태인것 같습니다. 이번주의 과제를 해내기 위해서 어떤 강의를 듣고 어떤 부분을 공부를 해야하는지 알고 싶습니다.
5. 지금도 어찌저찌 이해하지 않고 해낸거 같은 기분이 듭니다. 앞으로의 과제 및 공부를 위해서 어떻게 진행을 해야할지 감이 잡히지 않습니다.

2024-06-29 15:04 UTC, Hyeon9mak requested changes
안녕하세요 상우님~ 미션을 함께할 최현구입니다 🙇‍♂️
1주차 과제 잘 진행해주셨어요.

> 제가 스프링을 처음 다루다 보니 지금처럼 코드를 짜는게 맞는 건지 궁금합니다.

잘 작성해주신 것도 있고, 당연히 아닌 것들도 있습니다~
과제를 진행하면서 차차 학습을 해나가시면 되니 너무 마음 급하게 생각하시지 않아도 될거 같아요.

> step1에서 GET, POST, PUT, DELETE에서 동일한 주소로 작성했는데 각각의 주소를 다르게 하는게 좋은지 궁금합니다.

http 통신규약에서 GET, POST, PUT, DELETE 는 method 를 나타냅니다.
주소를 어떻게 선정하는게 좋은가에 대해서는 아래 아티클을 공유드릴게요 😄 
https://meetup.nhncloud.com/posts/92

> 커밋 같은 경우 처음 접하고 만드는 것에 집중을 하여 큰 단위로 커밋을 진행한 것 같습니다. 메소드를 구현하는 단위로 커밋을 진행하는편이 좋은 지 궁금합니다.

커밋은 결국 버전관리의 한 단위이죠. 문제점이 생겼을 때 롤백지점을 선택하기 용이한 것이 기준입니다.
게임을 한참 진행하다가 저장을 깜빡해서 초기로 돌아갔을 때의 허망함을 겪는 것처럼
커밋을 너무 큰 단위로 만들면 업무에 차질이 생길수도 있겠죠?
이를 위해서라면 가능하면 작은 단위, 기능 단위로 커밋을 하는게 좋을거 같아요~

> spring 공부법이 궁금합니다

가장 좋은 건 역시 공식문서입니다~~ 만 처음부터 다 읽으려면 오랜 시간이 걸리실거에요.
우선 현재 상우님께서 프로그램을 통해 만들고자 하는 가치가 무엇인지에 집중하시고,
거기에 필요한 것들이 있을 때마다 공식 문서를 부분적으로 참고하면서 공부해보시면 좋겠네요!
(e.g. "외부 API 를 연동하고 싶은데, best practice 는 뭐지? 공식문서를 찾아봐야겠다.")

간단한 코멘트 몇 가지 남겼습니다.
궁금하신 점 언제든지 질문 남겨주세요~

2024-06-30 10:38 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
> +public class ProductController {
@Controller은 요청을 View로 반환을 하기 위해 사용합니다. 
@Controller를 사용할 때 데이터를 반환 해야하는 경우 @ResponseBody 를 사용하여 HTTP응답으로 들어온 객체를 반환을 해줍니다.
위의 과정을 한번에 포함을 한것이 @RestController입니다.

제가 @Controller을 사용한 이유는 과제를 진행하는 도중 오류가 발생하여 @RestController 대신 @Controller를 사용해 오류를 해결했습니다. 
또한 처음 배우는 사용하는 Spring이어서 @Controller이 무엇인지 @RestController가 무엇인지에 대해 이해를 하지 않고 적용을 했습니다.

2024-06-30 10:52 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
> +}
글을 읽고 파일 끝에 개행이 필요하다라는 것을 알게 되었습니다. 덕분에 인텔리제이에서 설정도 마무리하고 관련하여 한번 더 공부를 진행 하도록 하겠습니다!

2024-06-30 10:54 UTC, pswaao88 commented on src/main/java/gift/Model/Product.java
> +    }
ProductController클래스의 newProductForm메소드에서 model.addAttribute의 파마미터로 기본 생성자가 필요하다고 생각을 하여 기본생성자를 만들었습니다

2024-06-30 10:56 UTC, pswaao88 commented on src/main/java/gift/Model/Product.java
> +    }
step1, step2 과제를 진행을 하였을 때 setter메소드를 사용을 하여 만들어 두었다가 step3를 만들면서 setter가 필요가 없어졌습니다. 과제를 완성을 하고 제출하는데에 집중을 하게 되어 이부분을 놓치게 된거 같습니다.

2024-06-30 11:03 UTC, pswaao88 commented on src/main/java/gift/Repository/ProductRepository.java
> +    private final RowMapper<Product> rowMapper = new BeanPropertyRowMapper<>(Product.class);
step2와 step3에서 Thymeleaf와 JBDC를 이용하기 위해서 실습을 진행했던 내용을 토대로 과제를 진행하였으나 계속 저의 코드에서는 오류가 뜨고 오류를 해결할 방법을 찾아도 해결을 진행하지 못했습니다.
 구글링을 하여 코드를 비교하며 찾아보았지만 제생각에는 코드가 똑같다고 생각을 하지만 막상 400에러와 500에러를 지속적으로 발생이 되어서 JDBC를 이용하는 많은 블로그들을 참고하여 파일 전체를 다시 재구성을 해 사용을 했습니다.
오류를 해결하는 과정에서 JDBC에 대해 제대로 이해를 하지 못하고 그냥 이러한 구조를 가지고 있고 천천히 다시 공부를 해야겠다는 생각으로 적용을 시켰습니다. 코드리뷰를 해주신 내용에 대해 공부를 다시 하면서 조금씩 이해가 되는 것 같습니다. BeanPropertyRowMapper에 대해서도 공부를 진행하겠습니다!!!

2024-06-30 11:35 UTC, pswaao88 commented on src/main/java/gift/Service/ProductService.java
> +    }
궁금한게 생겨서 질문드립니다!
다름이 아니라 save에서 직관적으로 바꾸기 위해서 add와 update로 분리를 하려고 시도를 하였습니다. 
add 메소드인 경우에는 if문의 productRepository.add(product); //(save 도 add로 변경하였습니다.)
update 메소드인 경우에는  productRepository.update(product);로 따로 분리를 시켰습니다.
이렇게 변경을 한 후 테스트를 하니 모든 값이 null값으로 들어가는 것을 확인을 해 다시 원상태로 복구를 한뒤 테스트를 하니 똑같이 null 값만 들어가고 있습니다. 이런경우에 어떤 문제가 발생을 해서 원래 코드를 되돌려고 null값이 계속 들어가는지 궁금합니다!!

2024-06-30 12:49 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
> +    }
우선 step3의 과제를 진행을 하면서 과제 제출에 중점을 두어서 자세한 내용에 대해 공부를 하지 못하고 이렇게 되면 이런 결과가 나오는구나 정도의 이해를 한뒤에 과제를 진행을 하였습니다. 
제가 공부하고 이해한 바가 맞는지 궁금합니다.
@Autowired 어노테이션을 사용을 할 때에는 생성자에 의존성을 주입을 할 때에는 2개 이상의 생성자가 필요한 경우 
필드와 setter에 의존성을 주입해 사용하는 경우에 @Autowired 어노테이션이 필요한 것으로 알고 있습니다.
따라서 생성자를 통해 의존성을 주입을 받을 때 1개의 생성자일때는 생략이 가능하고 2개 이상일 때만 @Autowired 어노테이션을 사용해야 한다. 그리고 필드와 setter로 의존성을 주입할 때는 @Autowired 이 필요하다 라고 이해했는데 맞는지 궁금합니다.

2024-07-01 10:06 UTC, Hyeon9mak requested changes
안녕하세요 상우님~ 궁금한 내용이 많으셨군요!
답변 코멘트 남겨드렸으니 확인 후 피드백 반영을 진행해주세요 😄 
궁금하신 점 언제든지 추가로 질문주세요~

2024-07-01 10:06 UTC, Hyeon9mak commented on src/main/java/gift/Controller/ProductController.java
> +    }
API 명칭은 상품을 더한다인데, GET method 를 사용하고 있네요.
요 API 에 대한 부가 설명이 필요해요 😢

2024-07-01 10:06 UTC, Hyeon9mak commented on src/main/java/gift/Model/Product.java
> +    }
해당 API 에서 비어있는 Product 가 꼭 필요한가요? 🤔

2024-07-01 10:06 UTC, Hyeon9mak commented on src/main/java/gift/Service/ProductService.java
> +    }
공식문서를 참고해보니 `BeanPropertyRowMapper` 에서 setter 메서드를 필요로 하네요.
`BeanPropertyRowMapper` 대신 직접 row mapper 를 구현하거나,
setter 메서드를 다시 추가하는 방식 중 하나를 채택하면 되겠어요.

```java
private final RowMapper<Product> rowMapper = (rs, rowNum) ->
                new Product(
                        rs.getLong(ID),
                        // ...
                );
```

이 둘 중 어느 것이 더 유지보수에 좋은 방식일까요?

2024-07-01 10:49 UTC, pswaao88 commented on src/main/java/gift/Model/Product.java
> +    }
post.html에서 id가 null값일 때와 아닐때로 나뉘어서 기본 생성자가 필요하다고 생각했습니다. 다시 살펴보니 기본생성자 없이 초기값을 0또는 ""으로 주어지면 필요없을 거 같아 기본생성자를 없애고 new Product("",0,"")로 바꾸었습니다!

2024-07-01 11:09 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
> +    }
제가 이해를 했던 부분이 처음에 add 버튼을 누르면GET /api/products/add로 요청을 보내 newProductForm이 실행이 되고 리턴 값으로 "post"가 되어 post.html파일에 불러옵니다.
=> add의 경우 불러온 파일에서  id는 null값이므로 데이터를 입력을 받아 product에 저장한 후 POST /api/products 을 요청해  postMapping메소드를 실행한다. => createProduct에서 DB에 저장을 한다. => 다시 GET /api/products를 요청하여 index.html파일을 가져와 데이터 목록을 표시한다.
위의 일련의 과정으로 이해를 하고있습니다. 혹시 틀린 부분이 있는 지 궁금합니다.

다른 방법으로는 어떤 방법을 쓸 수 있는지 도 궁금합니다!

2024-07-02 11:21 UTC, pswaao88 commented on src/main/java/gift/Service/ProductService.java
> +    }
우선 기존의 코드를 크게 건드리고 싶지 않아서 setter를 추가하는 방향으로 진행을 했습니다.
제생각은 setter의 경우 객체의 값을 바꿀 수 있어서 row mapper를 직접 구현하는 것이 유지보수에 더 좋은 방식이라고 생각합니다!

2024-07-03 17:16 UTC, Hyeon9mak approved these changes
안녕하세요 상우님!

http 통신규약에는 GET, POST, PUT, PATCH, DELETE 메서드는 각각의 용도가 나뉘어져있죠.
'규약'이라는 것은 상호간의 약속이므로, 보편적으로 사용되는 방식을 이해하는 것이 중요할거 같아요 😄 

가장 좋은 방법은 post.html 페이지를 반환하는 요청과,
상품을 생성하는 요청을 명시적으로 분리하는 것이라 생각되어요.

피드백 잘 반영해주셔서 우선 approve 합니다!
2주차 과제 PR에서 뵈어요 😄

2024-07-03 17:16 UTC, merged