부산대 BE_박민재_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #37
Opened 2024-06-25 19:40 UTC by minjae4650

Spring이 완전 처음이라 과제를 이해하고 시작하는 것조차 많은 시간이 걸렸던 과제였던 것 같습니다.

궁금한 점.
1. POST를 통해 상품을 추가할 때, ID를 부여해야되는데 이때 ID를 원래 어떤 식으로 할당하는지 궁금합니다.
2. Entity에서 생성자, Setter 가 반드시 필요한가요?
3. Delete를 하는 경우 요청한 ID가 존재하지 않는 경우, 현재 구현에서는 어차피 지워질 데이터이므로 에러를 띄우거나 알리지 않고 있는데 사용자에게 알려주는 것이 필요할까요?
4. Test 코드 작성 시에 추가적으로 필요한 부분이 더 존재하는지 궁금합니다.

수정할 부분이 꽤나 많을 것 같은데 많은 피드백 부탁드립니다!

2024-06-27 20:16 UTC, minjae4650 commented
2단계를 진행하기 전에 Thymeleaf를 처음 사용해보아서 시작하기 앞서 공부할 것이 정말 많았던 과제였습니다.

궁금한 점은 다음과 같습니다:
1. 처음부터 전체적인 틀을 잡고 하나씩 구현하는 것이 맞는지, 또는 기초적인 것 먼저 구현을 진행한 후에 필요한 기능들을 추가해가는 것이 맞는 것인지 궁금합니다.
2. Postman 같이 다른 곳에서 데이터를 추가, 수정, 삭제를 하게 된다면 F5를 눌러서 업데이트 하지 않는 한 원래 화면에 반영되지 않습니다. 이를 해결하기 위해서는 어떻게 하는 것이 올바른지 궁금합니다.

코드 봐주셔서 감사합니다!

2024-06-28 07:49 UTC, minjae4650 commented
현재 DB가 jdbc:h2:mem:~~ 이므로 h2-console을 통해서 Application이 실행될 때, 초기화 되는 것을 확인하였습니다.

궁금한 점은 다음과 같습니다:
1. price 같은 경우 0보다 작은 음수로 들어오면 안 될 것 같은데, 이는 어느 계층에서 처리하는 것이 가장 좋은 방법인가요?
2. 잘못된 값이 들어왔음을 어떻게 사용자에게 알려주면 좋을까요?

감사합니다.

2024-06-30 06:34 UTC, azjaehyun requested changes
안녕하세요. 박민재님.  양재현 멘토 입니다.
코드 리뷰하면서 정말 생각도 많이하고 고생한 흔적도 많아 보입니다.
스프링을 프레임워크를 익히면서 프레임워크도 학습해야하지 개발 코드도 공부해야하지
참 학습할게 많습니다. 그래도 지금 처럼 꾸준히 하신다면 분명히 좋은 개발자가 되실겁니다.
문의 주신것에 대해서 피드백 드립니다.
1. POST를 통해 상품을 추가할 때, ID를 부여해야되는데 이때 ID를 원래 어떤 식으로 할당하는지 궁금합니다.
> 보통은 id는 데이터베이스에서 시퀀스 id 즉 자동으로 생성해서 아이디를 부여합니다. 아니면 id를 만드는 원칙이 회사에 있다면 id를 생성하는 로직을 만들어서 상품을 추가할때 id 생성로직을 태워서 id 값을 넣어서 할당합니다. 구현하신것도 좋아보입니다.

2. Entity에서 생성자, Setter 가 반드시 필요한가요?
> 네 생성자는 필요하며 셋터는 모든 필드가 다 필요하진 않습니다. 필요한 필드만 세터를 구현할수도 있습니다.

3. Delete를 하는 경우 요청한 ID가 존재하지 않는 경우, 현재 구현에서는 어차피 지워질 데이터이므로 에러를 띄우거나 알리지 않고 있는데 사용자에게 알려주는 것이 필요할까요?
> 네 보통은 해당 아이디가 없다고 리턴값을 주는 경우가 좋습니다.
 return ResponseEntity.status(HttpStatus.NOT_FOUND).build(); // 404 Not Found 이런식으로 구현할것 같아요.

4. Test 코드 작성 시에 추가적으로 필요한 부분이 더 존재하는지 궁금합니다.
수정할 부분이 꽤나 많을 것 같은데 많은 피드백 부탁드립니다!
> 리뷰로 가이드 드렸습니다.

다음주도 화이팅입니다. 감사합니다.

2024-06-30 06:34 UTC, azjaehyun commented on src/main/java/gift/repository/ProductRepositoryImpl.java
> +    public void save(Product product) {
void로 그냥 로직을 끝내는것보다
  int result = jdbcTemplate.update 이하 생략.. 
이 처럼 업데이트가 성공했을시 result 값을 받을수 있습니다. 성공하면 1이 리턴이 되며 실패시 0이 반환됩니다.
```
        int result = jdbcTemplate.update(sql, product.getName(), product.getPrice(), product.getImageUrl(), product.getId());
        return result > 0; // 업데이트된 행이 1개 이상이면 true 반환
``` 
이런식으로 결과값에 대해서 정확히 피드백을 사용자에게 주는게 더 좋습니다.
따라서 컨트롤러 단에서도 
```
        boolean isSaved = productService.saveProduct(product);
        if (isSaved) {
            return ResponseEntity.status(HttpStatus.CREATED).body("Product created successfully.");
        } else {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to create product.");
        }
```
이런식으로 수정할수 있겠습니다.

2024-06-30 06:34 UTC, azjaehyun commented on src/test/java/gift/service/ProductServiceImplTest.java
> +    @Autowired
이런 방법도 있지만,
@Mock 이라는 방법을 써서 구현하는게 일반적입니다.
build.gradle 추가 후 진행.
```
    // Mockito Core
    testImplementation 'org.mockito:mockito-core:3.12.4'

    // Mockito JUnit Jupiter
    testImplementation 'org.mockito:mockito-junit-jupiter:3.12.4'
```
해당 부분 아래와 같이 변경
```
    @Mock
    private ProductRepository productRepository;

    @InjectMocks
    private ProductServiceImpl productService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

```

2024-06-30 06:34 UTC, azjaehyun commented on src/test/java/gift/service/ProductServiceImplTest.java
> +
product 아이디가 존재하지 않을 케이스도 작성
```
    @Test
    @DisplayName("ID로 특정 제품 조회 - 존재하지 않는 경우")
    void testGetProductById_NotFound() {
        when(productRepository.findById(999L)).thenReturn(Optional.empty());

        ProductNotFoundException exception = assertThrows(ProductNotFoundException.class, () -> {
            productService.getProductById(999L);
        });

        assertEquals("Product not found with id: 999", exception.getMessage());
    }
```

2024-06-30 06:34 UTC, azjaehyun commented on src/test/java/gift/service/ProductServiceImplTest.java
> +
ProductNotFoundException 클래스도 구현하는게 좋습니다.
```
package gift.exception;
public class ProductNotFoundException extends RuntimeException {
    public ProductNotFoundException(String message) {
        super(message);
    }
}
```

2024-06-30 06:34 UTC, azjaehyun commented on src/main/resources/static/js/product-management.js
> +$(document).ready(function() {
프론트에 대해서도 학습 하시고 열정에 감탄하고 갑니다 👍 
저도 백엔드 , 프론트 , 인프라 , 클라우드 등등 많은 분야를 하면서 풀스택 역량을 가지고 있지만
여러분야에서 이렇게 호기심을 가지고 공부한다는건 정말 보기 좋습니다.

2024-07-04 02:53 UTC, minjae4650 commented
피드백 참고하여 수정하였습니다!

2024-07-05 05:56 UTC, merged