경북대 BE_이도훈_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #44
Opened 2024-06-26 04:16 UTC by 2iedo

### 코드 구현 시 고민했던 점

- HashMap의 경우 <Key, Data>값이 이미 있을 경우 같은 Key값에 입력하면 자동으로 늦게 입력한 값으로 변경되는데, 이는 업데이트 기능과 동일한데 어떻게 해야 할지 궁금합니다.(제출한 파일에는 HashMap이 아닐 경우도 가정하여 Update는 따로 구현하여 제출하였습니다.)
- 업데이트 기능의 어노테이션 중 @PostMapping과 @PutMapping 두 가지가 있었는데 , 이 두가지의 차이점을 잘 모르겠습니다.
- 데이터를 담는 DTO인 Product 클래스는 커밋 메시지 작성 시 어떤 태그로 작성해야할 지 고민입니다. 이것도 기능 추가(feat)로 봐야 할까요??  

### 그 외의 궁금한 점
- 구현한 기능이 제대로 작동하는 지 확인하기 위해 cmd의 curl 커맨드를 사용했는데, 이것 이외에 응답 방식을 확인할 수 있는 프로그램이 있나요??

2024-06-30 15:51 UTC, khj68 commented
> ### 코드 구현 시 고민했던 점
> * HashMap의 경우 <Key, Data>값이 이미 있을 경우 같은 Key값에 입력하면 자동으로 늦게 입력한 값으로 변경되는데, 이는 업데이트 기능과 동일한데 어떻게 해야 할지 궁금합니다.(제출한 파일에는 HashMap이 아닐 경우도 가정하여 Update는 따로 구현하여 제출하였습니다.)
의도하신 비즈니스 로직이, 이미 존재할 때 저장이 안되도록 하려면 해당 상황에 에러처리를 해주시면 되겠습니다.
> * 업데이트 기능의 어노테이션 중 @PostMapping과 @PutMapping 두 가지가 있었는데 , 이 두가지의 차이점을 잘 모르겠습니다.
post는 새로 등록하는 경우, put은 이미 존재하는 것을 수정하는 경우입니다.
> * 데이터를 담는 DTO인 Product 클래스는 커밋 메시지 작성 시 어떤 태그로 작성해야할 지 고민입니다. 이것도 기능 추가(feat)로 봐야 할까요??
feat으로 봐주시면 되겠습니다. dto도 중요한 기능 중 하나입니다.
> * 예시 이미지에는 추가, 삭제, 선택 등의 버튼이 나타나 있는데, 이것들 또한 구현해야 하는지 궁금합니다!(일단은 목록 보여주기만 구현했습니다.)
이는 프로젝트 진행 관련으로 주최 측에 질문주시면 감사하겠습니다 :)
> 
> ### 그 외의 궁금한 점
> * 구현한 기능이 제대로 작동하는 지 확인하기 위해 cmd의 curl 커맨드를 사용했는데, 이것 이외에 응답 방식을 확인할 수 있는 프로그램이 있나요??
저는 실무에서 postman을 편리하게 사용하고 있습니다.

2024-06-30 15:56 UTC, khj68 requested changes
전반적으로 클래스 분리도 잘되어있고 깔끔한 코드입니다.
다만 try/catch 와 같이 보일러플레이트처럼 반복되는 부분은 global하게 관리하는 방법을 고려해주세요.
고생하셨습니다.

2024-06-30 15:56 UTC, khj68 commented on src/main/java/gift/Application.java
> +    public static Connection getConnection() throws Exception {
이 함수는 어디서 사용하고 있나요?

2024-06-30 15:56 UTC, khj68 commented on src/main/java/gift/Controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("제거 실패");
모든 컨트롤러 메소드에서 try/catch 를 하는 것보다 global exception handler 도입을 추천드립니다.

2024-07-01 00:58 UTC, 2iedo commented on src/main/java/gift/Application.java
> +    public static Connection getConnection() throws Exception {
아 저번 클론코딩 때 한 코드 참고하여 작성하다 잘못 넣은 것 같습니다. 제거했습니다!

2024-07-01 00:58 UTC, 2iedo commented on src/main/java/gift/Controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("제거 실패");
넵 알겠습니다!

2024-07-02 03:08 UTC, khj68 commented
도훈님 conflict resolve 부탁드립니다!

2024-07-02 04:50 UTC, 2iedo commented
> 도훈님 conflict resolve 부탁드립니다!

넵 해결했습니다!

2024-11-05 04:25 UTC, closed without merging