경북대 BE_신형진 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #46
Opened 2024-06-26 04:41 UTC by hjinshin

### 1. 코드 작성하면서 어려웠던 점
저장소에 상품 정보를 저장하는 product 객체를 record로 생성하는게 옳은지 궁금합니다.
기능 요구사항에도 나와있듯 데이터의 수정 기능이 필요한데, record는 불변 객체이다보니 데이터의 수정이 아닌 새로운 객체를 생성하여 대체하는 방법으로 구현할 수 밖에 없었습니다. 또 record의 목적인 데이터의 전달을 초과하는 역할인 것 같습니다. 그래서 r이 경우에는 record를 사용하지 않는 것이 좋아보이는데 제 생각이 맞는지 알고 싶습니다.

### 2. 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
* 클래스들이 역할에 맞게 잘 나뉘었는지 확인해 주셨으면 좋겠습니다.
* 개선하면 좋겠다고 생각되는 부분을 말씀해주시면 감사하겠습니다.

2024-06-28 00:58 UTC, leaf-upper requested changes
안녕하세요. 형진님
6주간 코드리뷰어를 맡게되었습니다. 잘부탁드려요.
코드를 보니 형진님도 Spring을 잘 사용하시는분인것 같아요.
부족한 부분은 없지만 몇가지 코멘트를 드렸습니다!

2024-06-28 00:58 UTC, leaf-upper commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
자바버전을 21에서 17로 변경하셨는데요,
혹시 이유가 있을까요?

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +public class AdminController {
👍 굉장히 깔끔하게 AdminController 코드 작성해주신것 같아요
다만 HTTP Method를 좀더 잘 사용해주시면 훨씬더 좋은 코드가 될것 같습니다.
POST와 GET만 사용하더라도 주어진 요구사항을 만족하는데는 크게 문제가 되지 않지만~
다양한 기능과 HTTP 명세를 공부 해보시면서 개발해보시면 훨씬 실력이 빠르게 늘 수 있습니다.

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    public String updateProduct(@PathVariable("id") Long id, Model model) {
id값이 0, 음수, 혹은 null등 생각지 못한 값이 들어왔을때의 방어코드가 있으면 좋을것 같아요~

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    public String newProduct(@ModelAttribute ProductRequest request) {
HTTP Post Method는 기본적으로 데이터에 대한 생성의 의미를 담기도 하여서 꼭 new를 API Path에 붙이시지 않으셔도 괜찮을것 같습니다~ RESTful 이라는 용어를 기억해두시면 좋을것 같아요!

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    public String updateProduct(@PathVariable("id") Long id,
상품을 업데이트하는건 POST보다는 PUT 혹은 PATCH HTTP Method가 좋을것 같아요. 또한 이런 메서드를 쓰게 되면 update한다는 의미를 담기 때문에 API Path도 간단해질것 같습니다!

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/AdminController.java
> +    public String delete(@PathVariable("id") Long id) {
삭제하는 HTTP Method는 DELETE가 있어요! 위 코멘트와 동일합니다.

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Void> deleteProduct(@PathVariable("id") long id) {
데이터를 삭제할때도 삭제한 데이터에 대해 잘 삭제되었는지 확인하기 위해
noContent보다는 기본적인 값을 내려주셔도 좋을것 같아요~

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(id);
👍 201에 대해서 알고 계시네요 좋은것 같습니다.

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Product> getProduct(@PathVariable("id") long id) {
위 코멘트에서 말씀드린것처럼 여기서도 id값에 대해서 기본적인 Validation이 수행되면 좋을것 같아요~

2024-06-28 00:58 UTC, leaf-upper commented on src/main/java/gift/model/Product.java
> +public record Product(Long id, String name, int price, String imageUrl) {
Product는 아마도 이후에 영속화된 데이터를 저장하게 될것 같기도하고, 요런 도메인 객체는 비지니스 로직을 가지게 되는 경우가 
많아 record로 사용하기 보다는 class를 사용해보시는게 좋을것 같아요~

2024-06-30 07:35 UTC, hjinshin commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(17)
별다른 이유는 없습니다. 단지 제 로컬에 자바 17이 있어서 그렇게 했습니다.

2024-06-30 08:12 UTC, leaf-upper commented
3단계만 머지할게요~

2024-06-30 08:12 UTC, closed without merging