부산대 BE_신예준_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #47
Opened 2024-06-26 05:09 UTC by pnuece

2024-06-29 14:18 UTC, yoo-jaein requested changes
예준님 안녕하세요 😊
앞으로 6주간 step2를 함께 할 유재인입니다.

몇 가지 코멘트와 질문을 남겨드렸으니 확인 부탁드립니다!

2024-06-29 14:18 UTC, yoo-jaein commented on src/main/java/gift/controller/ProductController.java
> +package gift.controller;
기능을 구현하기 전 README.md에 구현할 기능 목록을 작성하는 것은 어떨까요?
작성한 항목을 바탕으로 커밋도 세부적으로 나누는 것을 추천합니다!
- [AngularJS Git Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153) 참고

커밋을 효과적으로 잘 나누는 경우 다음과 같은 장점이 있어요.
1. 작은 단위의 커밋은 각 변경 사항의 목적과 영향을 쉽게 파악할 수 있습니다.
2. 버그가 발생한 경우 롤백이 쉽습니다.
3. 다른 개발자와 함께 작업할 때 코드 충돌 가능성을 줄여줍니다.

2024-07-03 08:26 UTC, pnuece commented on src/main/java/gift/product/ProductRequest.java
> +public record ProductRequest(
DTO를 불변 객체로 유지하고 생성자 접근자 등을 자동으로 생성해주는 record를 사용하는게 효율적인 것 같아 사용하였습니다

2024-07-03 08:26 UTC, pnuece commented on src/main/java/gift/service/ProductService.java
> +}
수정하였습니다!

2024-07-03 08:29 UTC, pnuece commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Product> createProduct(@RequestBody ProductRequest productRequest) {
신규 리소스를 생성하는 API라 HTTP 상태 코드를 201로 반환하고자 ResponseEntity를 사용하였습니다!

2024-07-03 08:31 UTC, pnuece commented on src/main/java/gift/service/ProductService.java
> +    public List<Product> readProduct() {
메서드 이름을 더 명확히 구분할 수 있도록 수정하였습니다!

2024-07-03 22:50 UTC, yoo-jaein approved these changes
1주차 과제 고생 많으셨어요!! 👏👏
우선 머지하고 2주차에서 함께 리뷰드릴게요!
다음 과제도 화이팅입니다 :)

2024-07-03 22:51 UTC, merged