전남대 BE_조현 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #49
Opened 2024-06-26 05:26 UTC by hxunsc

### 코드 작성하면서 어려웠던 점
- id 값 처리하는 부분 및 다른 변수 처리에서 임의로 설정값을 주었는데, 초기 변수 값을 어떻게 처리해두어야 할 지 잘 모르겠습니다.

### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
- 전체적으로 아직 Spring의 이해도가 낮아서 제대로 수행했는지 모르겠습니다.. 전반적으로 확인해주시면 감사하겠습니다!

2024-06-29 12:03 UTC, seungy0 requested changes
현서님 코드 작성하시면서 이런저런 고민하셨을게 느껴졌습니다.
너무 잘하고 계시고, 몇가지 코멘트 남겼으니 참고해주세요~
궁금하신점은 대댓글, 또는 슬랙으로 문의부탁드립니다😊

2024-06-29 12:03 UTC, seungy0 commented on src/main/java/gift/ProductController.java
> +            return ResponseEntity.notFound().build();
https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/PUT
404 NOT FOUND보단 204 No Content가 좀 더 적합합니다~

2024-07-01 06:17 UTC, hxunsc commented on src/main/java/gift/ProductController.java
> +    private long counter = 8146027;
아니요.. 따로 주어진 조건과 값이 없어서 어떻게 처리해두어야 할지 고민했었습니다!

2024-07-01 06:20 UTC, hxunsc commented on src/main/java/gift/ProductController.java
> +    }
감사합니다. 참고해서 수정하겠습니다!

2025-06-29 12:47 UTC, closed without merging