충남대 BE_이은경 1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #50
Opened 2024-06-26 05:29 UTC by pkyung

## 과제 질문 ʕ •ᴥ•ʔ
이번 1단계 과제에서 응답 값에 http 상태 코드가 함께 반환된 것을 보고 ResponseEntity를 사용했는데 이를 이렇게 사용하는 것이 맞는지 궁금합니다. 또한, mapping을 통한 메서드 구현은 어떻게 test 코드를 짜야하는 지 궁금합니다.

2024-06-29 06:08 UTC, ksy90101 approved these changes
고생많으셨습니다~
질문이 있다면 언제든 DM주세요~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/Product.java
> +    private String imageUrl;
대부분 순서를 필드를 먼저 작성하고 생성자를 두긴 합니다.

```suggestion
    private Long id;
    private String name;
    private int price;
    private String imageUrl;
    
        public Product() {}
    public Product(Long id, String name, int price, String imageUrl) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.imageUrl = imageUrl;
    }
```

이런식으로 말이죠~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +        return new ResponseEntity(HttpStatus.CONFLICT);
부정보단 긍정을 쓰는 편 입니다.

```suggestion
        if (product == null) {
                 return new ResponseEntity(HttpStatus.CONFLICT);
        }
        
        return new ResponseEntity(HttpStatus.CREATED);
```

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    public ResponseEntity deleteProduct(@PathVariable("id") Long id) {
PathVariable의 value는 변수와 동일하면 생략해도 됩니다~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductDao.java
> +@Repository
```suggestion
import java.util.List;

@Repository
```

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductDao.java
> +    private RowMapper<Product> productRowMapper() {
👍

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductDao.java
> +    public Product select(Long id) {
select라는건 여러개가 나올수 있을거 같아서, find와 같은 단어를 쓰기도 합니다~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductService.java
> +    public Product makeProduct(ProductRequestDto requestDto) {
Service와 Controller간의 통신에서 DTO로 하는게 훨씬 더 좋을거 같습니다~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductService.java
> +        Product getProduct = productDao.select(requestDto.getId());
makeProduct와 Put에 대해서 나눠둔다면 굳이 getId가 없어도 되지 않을까요?

ID를 생성하는것은 DB에서 하기 떄문이죠..

아니면 차라리 requestDto.getId가 null이 아니라면 에러를 발생시키는게 더 좋을거 같긴합니다~

2024-06-29 06:08 UTC, ksy90101 commented on src/main/java/gift/ProductService.java
> +        return null;
여기도 product가 존재하지 않는다면 null보단 예외를 발생시키는게 더 좋을거 같습니다~

2024-06-29 11:45 UTC, ksy90101 commented
> 이번 1단계 과제에서 응답 값에 http 상태 코드가 함께 반환된 것을 보고 ResponseEntity를 사용했는데 이를 이렇게 사용하는 것이 맞는지 궁금합니다.

네 잘 사용해주셨어요~ 그러나 200 OK status에도 어떻게 쓸수 있는지 찾아보시면 좋을거 같습니다~

> mapping을 통한 메서드 구현은 어떻게 test 코드를 짜야 하는 지 궁금합니다.

이부분에 대해서 이핼를 못했습니다 mapping 메서드를 어떤걸 말하시는건가요?

> jpa만을 사용해보다 jdbc를 처음 사용해보았습니다. 무분별한 setter의 사용은 하지 않는 것이 좋은 것으로 알고 있는데 DAO의 rowMapper를 만들다보니 모든 필드의 setter를 열게 되었습니다. rowMapper는 이렇게 만드는 것이 맞나요? 아니면 builder를 사용할 수도 있을까요?

생성자로 하면 setter를 사용할 필요 없지 않을까요~?

> 전체적으로 제가 올바르게 코드를 짰는지 궁금합니다.
이건 전반적으로 리뷰를 남겼어요~

2024-07-01 01:02 UTC, pkyung commented on src/main/java/gift/ProductService.java
> +        return null;
이 null을 발생시킨 이유는 controller에서 null로 판단하여 httpStatus를 나눠주기 위해서 한 것인데 예외는 어떤식으로 구현을 해야하나요?

2024-07-01 01:20 UTC, pkyung commented
mapping은 getMapping, PostMapping으로 Post 요청 시에 이 로직이 돌아가는데 이것을 어떻게 test 코드를 짤 수 있는지 궁금합니다.

2024-07-01 07:27 UTC, ksy90101 requested changes

2024-07-02 05:53 UTC, pkyung commented
멘토님께서 주신 글을 읽고 exception을 만들어 처리해보았습니다. 맞는지 확인해주실 수 있나요? 감사합니다!!

2024-07-02 06:06 UTC, ksy90101 approved these changes
1주차 미션 고생많으셧어요~
2주차에도 이어지니 간단한 피드백 남긴건 2주차 1단계에서 진행해주시면 될거 같습니다~
언제든 질문이 있다면 DM주세요!

2024-07-02 06:06 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    }
<img width="805" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/53366407/b8acd503-2f6c-4fdb-9365-55ed745d21d4">
이런식으로 Authwired를 생략해보면 어떨까요?

2024-07-02 06:06 UTC, merged