충남대 BE_박서현_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #53
Opened 2024-06-26 05:46 UTC by sseooh

2024-06-28 14:52 UTC, jjongwa requested changes
안녕하세요! 이번 step2 리뷰어를 맡은 디노입니다 🦖 

전체적으로 요구사항에 맞게 잘 구현해 주셨어요! 👍👍 

리뷰 확인 후 다시 요청해 주세요~!

2024-06-28 14:52 UTC, jjongwa commented on README.md
기능 구현 목록 정리 👍 
진행한 단계에 따른 구현 목록 정리 잘 해주셨네요!

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +    }
생성자 주입 방식을 이용할 땐 `@Autowired` 어노테이션이 없어도 동작합니다! (service와 dao의 생성자 부분도 동일!)

+ 클래스에 생성자를 정의하지 않고 다음과 같이 의존성을 주입하는 방식도 있는데요, 각각 어떤 차이가 있을까요?

```
public class ProductController {
    
    @Autowired
    private ProductService productService;
```

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/api/products")
중복되는 prefix는 RequestMapping으로 묶어 주었네요! 👍

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +        return "redirect:/api/products";
redirect url을 string으로 중복해서 리턴하고 있는데, 
중복되는 문자열을 상수화 시켜 놓으면 나중에 변경이 발생했을 때 손쉽게 대처할 수 있습니다~!

```
public class ProductController {

    private static final String REDIRECT_URL = "redirect:/api/products";

private final ProductService productService;

...

@PostMapping
    public String addProduct(@ModelAttribute Product product) {
        productService.addProduct(product);

        return REDIRECT_URL;  // 새로운 상품 추가 후 상품 조회 화면으로 리다이렉트
    }

...

@PostMapping("/{id}")
    public String EditProduct(@PathVariable("id") Long id, @ModelAttribute Product product) {
        // 상품 정보 수정
        productService.updateProduct(id, product);

        return REDIRECT_URL;
    }

...

}
```

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +    public String EditProduct(@PathVariable("id") Long id, @ModelAttribute Product product) {
메서드가 대문자로 시작하네요!

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +        // 요청받은 id를 가진 상품을 삭제
README에 적어놓은 기능 요구사항에선 HTTP Method가 수정은 PUT, 삭제는 DELETE였는데, 
각각 PostMapping과 GetMapping을 쓰고 있네요! 이유가 있을까요?

2024-06-28 14:52 UTC, jjongwa commented on README.md
> +    - URL: /api/products/{id}
PUT, PATCH, POST는 각각 어떤 차이가 있고 어떠한 경우에 사용하나요?
(PUT 사용이 틀렸다는건 아닙니다!)

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +    }
서비스 계층을 만들어 주셨는데요, 지금 보면 해당 클래스에서 하는 일이 전달 이외엔 없는 것 같아요!

다시 말하면, 현재 로직 상에선 컨트롤러에서 다음과 같이 DAO 메서드를 직접 호출해도 아무 문제가 없는데요

```
@PostMapping
    public String addProduct(@ModelAttribute Product product) {
        productDAO.save(product);

        return REDIRECT_URL;  // 새로운 상품 추가 후 상품 조회 화면으로 리다이렉트
    }
```

서비스 계층은 어떤 역할을 맡아야 할까요?

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/dao/ProductDAO.java
JdbcTemplate 사용 잘 해주셨어요! 👍

2024-06-28 14:52 UTC, jjongwa commented on src/main/java/gift/dto/Product.java
> +    private String imageUrl;
Product 클래스를 dto로 칭해 주셨는데요! dto란 무엇이고 어떤 역할을 할까요?

mvc 패턴 또는 domain 이라는 용어를 들어보셨다면 dto와 이들을 비교하고 정리해 보는 것도 좋을 것 같습니다!

+위 키워드에 대해 잘 모른다 or 개념이 아직은 와닿지 않는다 싶으면 우선 **setter가 있다면 dto라고 부를 수 있는가?** 부터 먼저 접근해 보는걸 추천합니다!

2024-06-28 14:52 UTC, jjongwa commented on src/test/java/gift/ProductControllerTest.java
테스트 작성 잘 해주셨어요! 👍 

하지만 지금 테스트틀 각각 돌리면 모두 통과하지만 전체를 한꺼번에 돌리면 실패하는 경우가 발생하는데요..!
어떤 부분 때문에 문제가 발생하는지, 이를 해결하려면 어떤 방식들이 있을지 고민해 볼까요~?
<img width="614" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/77482065/526c0190-4f03-458c-b45d-1069887013a2">

2024-07-04 11:19 UTC, sseooh commented on src/test/java/gift/ProductControllerTest.java
각 테스트들끼리 서로 DB에 영향을 주는 것 같아서 @Transactional을 추가하여 각 테스트가 끝난 후 DB 상태를 원래대로 롤백할 수 있도록 변경했습니다!

2024-07-04 11:23 UTC, sseooh commented on src/main/java/gift/controller/ProductController.java
> +    }
생성자 주입 방식은 단위 테스트를 할 때 Mock 객체를 주입하기 쉽지만 의존성이 많아지는 경우에는 생성자 매개변수도 많아지기 때문에 코드가 복잡해지는 단점이 있습니다. 그리고 필드 주입 방식은 초기 설정은 간단하지만 단위 테스트를 할 때 의존성을 주입하는 것이 어렵다고 알고 있습니다..!

2024-07-04 11:25 UTC, sseooh commented on README.md
> +    - URL: /api/products/{id}
<img width="494" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/105717406/71618d60-1f49-4df1-9c3b-8c7fd8a4fa17">

이렇게 정리해봤습니다!

2024-07-04 14:55 UTC, jjongwa approved these changes
우선 1주차 과제는 머지할께요! 나머지는 2주차 리뷰에서 이어가겠습니다~!

2024-07-04 14:55 UTC, merged