[전남대 BE 김보민][1단계 - 상품 API]
kakao-tech-campus-2nd-step2/spring-gift-product pull request #56
Opened 2024-06-26 06:01 UTC by KBM05haruin30

1단계에 있는 문서들을 읽어보면서 헷갈리는 부분은 검색도 하고 찾아가며 코드를 작성했습니다. 처음 접하는 것들이라 많이 어려웠습니다. 첫 강의 때 입력을 쿼리 스트링으로 한 것을 보고 과제도 쿼리 스트링이 되게 만들었었습니다. 오늘 모각코 시간에서 팀원들과 이야기하며 응답과 요청은 JSON 형태인 것을 깨닫고 코드를 알맞게 수정하게 되었습니다.

궁금한 점
- postman으로 API를 테스트 했는데 쿼리 스트링은 param으로 입력받고 json은 body로 입력 받는 것을 확인했습니다. json을 사용하는 이유가 더 편리해서 사용하는 것인지 궁금합니다.
- 작성한 코드는 아직 테스트 코드를 작성하지 않았습니다. 미니 과제 때처럼 테스트 코드를 작성하면 되는지 궁금합니다.
- 에외 처리 관련해서 질문이 있습니다. HTTP API를 테스트하던 중 JSON의 입력이 만든 Product의 필드 수와 일치하지 않으면 HttpMessageNotReadableException이 발생하는데 그러면 위의 예외로 처리해야 하는지, 입력이 잘못되었으니 illegalArgumentException처럼 해야하는지 궁금합니다.

2024-06-29 12:08 UTC, Hongdonggeon requested changes

2024-06-29 12:08 UTC, Hongdonggeon commented on src/main/resources/templates/add_product_form.html
> +  </div>
상품추가 화면에서 ID를 받게한 이유가 궁금해요. ID 의 목적이 어떤거냐에 따라 달라질 수 있을 것 같은데, 제가 이해한바로는 현재 ID 의 역할이 상품 정보의 속성이 아닌 데이터 식별의 역할만 해주고 있는 것 같은데요. 사용자한테 id값을 받는게 아닌 DB auto_increment 기능을 사용해주면 어떨까 싶습니다

2024-06-29 12:08 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute Product product, Model model) {
이 리뷰는 반영보다는 참고해주시면 좋을 것 같아요
현재 상품 정보를 Product 객체로 바인딩하고 있는데요. 
Product 객체는 도메인 (엔티티)로 사용되고 있는데, 컨트롤러의 요청과 응답의 객체로 사용되면 어떤 단점이 있을지 고민해보면 좋을 것 같아요
참고할 문서도 공유드릴게요 https://tecoble.techcourse.co.kr/post/2020-08-31-dto-vs-entity/

2024-06-29 12:08 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +            return "add_product_form";
요청값으로 id를 받지 않게 된다면, 이러한 검증도 제외시킬 수 있을 것 같아요 (DB에 데이터가 추가될 때 id값을 알아서 넣어주기 때문에, 겹칠일이 없어지죠!)

2024-06-29 12:23 UTC, Hongdonggeon commented
안녕하세요 리뷰를 맡게된 카카오테크 캠퍼스 2기 BE 멘토 홍동건이라고 합니다! 
- postman으로 API를 테스트 했는데 쿼리 스트링은 param으로 입력받고 json은 body로 입력 받는 것을 확인했습니다. json을 사용하는 이유가 더 편리해서 사용하는 것인지 궁금합니다.
> 

- 작성한 코드는 아직 테스트 코드를 작성하지 않았습니다. 미니 과제 때처럼 테스트 코드를 작성하면 되는지 궁금합니다.
> 저는 개인적으로 테스트 코드가 정말 중요하다고 생각합니다. 현재는 구현 요구사항이 작기 때문에 테스트 해보기가 쉬운데요. 요구사항이 더 많아지게 된다면, 테스트해보기가 쉽지 않을거예요. 테스트하기 어려운 상황에서 기능별로 테스트하기에 가장 피드백이 빠르고 쉬운 방법이 테스트 코드라고 생각해요. 테스트 코드를 습관화하시면 좋을 것 같아요!

- 에외 처리 관련해서 질문이 있습니다. HTTP API를 테스트하던 중 JSON의 입력이 만든 Product의 필드 수와 일치하지 않으면 HttpMessageNotReadableException이 발생하는데 그러면 위의 예외로 처리해야 하는지, 입력이 잘못되었으니 illegalArgumentException처럼 해야하는지 궁금합니다.

- Get과 Post가 아닌 Delete와 Put을 사용하기 위해서 HiddenHttpMethodFilter를 사용했는데 사용하지 않고 코드를 작성하는 방법이 있는지 궁금합니다.
> HTML Form은 GET과 POST 방식의 methods 만 지원하기 때문에, HiddenHttpMethodFIlter를 빈으로 등록하면서 해결하신 것 같은데, 잘 해결하신 것 같아요 
일단 HTML Form이 Get과 Post 방식의 Methods만 지원하는지에 대해서 궁금하시다면 https://haah.kr/2017/05/23/rest-http-method-in-html-form/ 이 블로그를 읽어보면 좋을 것 같아요 


- 기능 별로 코드가 잘 나뉘어 졌는지 부족한 기능은 없는지 궁금합니다.

- 제대로 코드를 작성했는지 궁금합니다. 특히 데이터베이스를 사용하는 부분이 잘 작성되었는지 궁금합니다.

- 추가로 중복된 로직이 더 없는지 확인해주셨으면 합니다.

- 업데이트도 SimpleJdbcInsert를 사용할 수 있을 것 같은데 정말 안되는지 궁금합니다.

2024-06-29 13:11 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +import java.util.*;
넵 알겠습니다! 와일드카드를 제거했고 사용하지 않은 import문은 제거했습니다.

2024-06-29 13:32 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    private ProductRepository productRepository;
넵! 알겠습니다. 필드 주입이 아닌 생성자 주입으로 수정하였습니다. 제가 알아온 내용이 맞는지 궁금합니다. @Autowired(필드 주입)는 간결하고 편리하지만 테스트가 어렵고, 순환 의존성 문제가 발생합니다. 생성자 주입은 명시적이고 테스트가 용이하며 순환 의존성을 해결할 수 있지만 코드 양이 증가하고 복잡성이 증가합니다. 생성자 주입과 필드 주입 중 생성자 주입을 권장하는 이유는 명시성과 가독성, 테스트 용이성, 순환 의존성 문제 해결이 가능하기 때문입니다.

2024-06-29 13:38 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductController.java
> +    private final Map<Long, Product> products = new HashMap<>();
넵 알겠습니다! 1단계가 지난 후 2단계부터 새로운 컨트롤러인 AdminController를 만들어 사용하다 보니 깜빡했던 것 같습니다.

2024-06-29 13:40 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductController.java
> +    private final Map<Long, Product> products = new HashMap<>();
수정 완료했습니다!

2024-06-29 13:41 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductController.java
> +    @GetMapping("/all")
넵 알겠습니다! 전체 조회는 /api/products , 단일 조회는 /api/products/{id}로 할 수 있도록 수정하였습니다.

2024-06-29 13:52 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/ProductController.java
> +        products.put(updatedProduct.id(), updatedProduct);
단순하게 지우고 새로 만드는 것이 빠를 것 같아 이렇게 작성했었습니다. 현재는 DB를 사용하도록 코드가 바뀌어 있습니다.

2024-06-29 13:55 UTC, KBM05haruin30 commented on src/main/java/gift/Repository/ProductRepository.java
> +    public List<Product> checkProductsAll() {
저도 작성하면서 check말고 더 좋은 동사가 있을 것 같다고 생각했었습니다. 하지만 단어가 생각이 나지 않아서 check로 작성했는데 조언해주신 동사들 중 find가 가장 적합한 것 같습니다! 감사합니다!

2024-06-29 13:58 UTC, KBM05haruin30 commented on src/main/java/gift/Repository/ProductRepository.java
> +        return products.isEmpty() ? null : products.get(0);
Optional 반환 타입에 대해 더 공부하고 수정하겠습니다!

2024-06-29 13:59 UTC, KBM05haruin30 commented on src/main/java/gift/Repository/ProductRepository.java
> +    }*/
넵 알겠습니다! 주석을 남겨뒀던 이유는 2가지 방식으로 구현했던 것을 기억하고 싶어서 남겼었습니다.

2024-06-29 14:10 UTC, KBM05haruin30 commented on src/main/java/gift/Repository/ProductRepository.java
> +            .withTableName("products");
확실히 상수로 따로 관리하는 것이 필드명을 잘못 입력하는 실수를 줄일 수 있을 것 같습니다! 감사합니다!

2024-06-29 14:13 UTC, KBM05haruin30 commented on src/main/resources/templates/add_product_form.html
> +  </div>
제가 정확히 이해를 못했던 것 같습니다. 추가할 때 ID도 입력 받고 수정도 가능해야 한다고 생각해서 이렇게 작성했습니다. 사용자한테 id값을 받는게 아닌 DB auto_increment 기능을 사용해서 전체적으로 수정하겠습니다!

2024-06-29 14:45 UTC, KBM05haruin30 commented on src/main/resources/templates/add_product_form.html
> +  </div>
수정을 하려고 보니 record 클래스로 만든 Product를 일반 클래스로 변경해야 하는 것 같습니다. 혹시 record 클래스를 유지한 채 위와 같은 기능을 할 수 있는 방법이 있을까요?

2024-06-29 15:23 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    public String addProduct(@ModelAttribute Product product, Model model) {
바로 윗 단계의 코드 리뷰와 연관된 질문입니다. record를 사용하여 Product를 만들었고 id, name, price, imageUrl의 필드가 있습니다. DTO를 새로 만들어서 사용할 때 record로 만든 Product처럼 ProductDTO도 똑같이 4개의 필드를 가져도 되나요?

2024-07-01 12:02 UTC, Hongdonggeon commented on src/main/java/gift/Controller/AdminController.java
> +    private ProductRepository productRepository;
좋아요 잘 학습하신 것 같네요!! ProductRepository의 jdbcTemplate도 생성자 주입으로 처리해주세요!

2024-07-01 12:57 UTC, KBM05haruin30 commented on src/main/java/gift/Controller/AdminController.java
> +    private ProductRepository productRepository;
넵 변경하여 2주차 과제에 적용하였습니다. https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/28

2024-07-08 16:49 UTC, Hongdonggeon approved these changes
2주차 과제 진행하시면서 코멘트도 다 반영하셔서 1주차 과제는 머지할게요

2024-07-08 16:49 UTC, merged

2024-07-08 16:53 UTC, KBM05haruin30 commented
넵! 감사합니다!