부산대 BE_김태윤_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #6
Opened 2024-06-25 03:06 UTC by pykido

# 1주차 1단계 과제 진행 중 궁금했던 것들을 정리해보았습니다!
1. 이전에 Step 1에서 진행했던 과제들에 비해, nextstep 과제들은 기능 수행의 정도가 좀 더 유연하다고 느껴졌습니다. 예를 들어 이번 1단계 과제는 상품 정보를 CRUD하는 API를 구현하는 것이었는데, 수업 시간에 배운 내용만을 바탕으로 HTTP 요청과 응답 방식에 중점을 두어 구현할지, 수업 시간에 배운 내용은 아니지만 service, repository, dto 등을 추가적으로 구현할 지 고민되었습니다. 왜냐하면 두 방식 모두 과제에서 요구하는 기능 요구 사항을 만족하기 때문입니다.
- 이와 관련하여 두 가지 접근 방식 중 어느 것이 더 효과적일지 고민하고 있습니다.
(1) 최대한 여러 기능을 구현해보기: 아직 배우지 않았기에 퀄리티가 조금 떨어지더라도 할 수 있는 최대한 많은 기능을 구현해 보는 방법.
(2) 핵심 내용을 깊게 공부하기: 과제의 핵심 내용을 더 깊게 공부하고 이해하는 데 집중하여 할 수 있는 최선의 기능을 구현하는 방법.

2. 단위 테스트 시 중점을 둬야하는 부분이 궁금합니다.
- CRUD API 구현 후 Postman을 통해 동작을 확인해보았지만 자세한 검증을 위해 junit을 활용한 테스트 코드를 추가적으로 구현하여 테스트해보았습니다. 이때, 좋은 테스트 코드를 구현하기 위해 중점적으로 테스트해볼 부분이 어떤 것인지 궁금합니다.
- 이와 관련하여 제가 중점을 둬야할 거 같은 부분을 몇 가지 정리해보았습니다.
(1) API 주요 기능 : 각 기능이 기대했던 것과 동일하게 동작하는지 확인
(2) 유효성 검증 : 잘못된 입력 값이나 존재하지 않는 리소스 요청 등 예외 상황에서 적절한 오류 메시지와 상태 코드가 반환되는지 확인
(3) 상태 코드 확인 : 반환되는 상태 코드값이 올바른지 확인

3. 라이브 강의에서 배운 객체 지향 생활 체조 원칙에 따르면 getter & setter를 사용하지 않아야한다고 합니다. getter & setter을 가급적이면 사용하지 않아야하는 이유가 궁금합니다. 또한 필드값에 접근할 때 getter & setter를 활용하는 것 이외의 다른 방법이 있는지 궁금합니다.

2024-06-30 01:29 UTC, azjaehyun requested changes
안녕하세요. 양재현 멘토입니다.
수업시간에 배운 내용과 본인이 코드를 개선하기 위해 노력한 모습이 곳곳에서 많이 보입니다.
고민도 많이 하신 흔적도 많이 보여서 코드 리뷰를 하면서 예전의 저의 모습이 떠올랐습니다.
전반적으로 코드가 가독성도 좋고 테스트코드 까지 짜주신 모습이 감명 깊었습니다.

고민하고 계신 질문에 대한 답변만 첨언 하겠습니다.
1.  테스트 코드를 구현하기 위해 중점적으로 테스트 해야할것
   -> 현업에서는 코드 커버리지 검사를 돌려서 최소 80% 이상 나오게 테스트 코드에 적용합니다.
    (쉽게 말해서 코드에서 나올수 있는 경우의 수의 80% 이상을 테스트 코드에 구현 목표 )
    코드 커버리지 관련 내용은 구글에서 스프링 코드 커버리지 라고 치면 나올거에요.
    참고 사이트 : https://yinq.tistory.com/211
 2. 어떤 방식으로 의존성 주입(DI)하는 것이 바람직한지 알고 싶습니다! 
     지금 해주신대로 생성자 주입으로 해주시는게 좋습니다. 이유는 불변성 보장.
     테스트 코드 작성시 유리.
     - 불변성 보장 안되는 코드
       @Autowired
       private ProductService productService;  
     - 불변성 보장 코드 (final) 
     private final ProductService productService;
     @Autowired
    public ProductController(ProductService productService) {
        this.productService = productService;
    }
    - 테스트 코드 작성시
    private ProductService productService = Mockito.mock(ProductService.class);
    private ProductController productController = new 
    ProductController(productService);  
지금 처럼 해주시면 됩니다. GooD!
3. hymeleaf를 사용해 서버 사이드 렌더링(SSR)으로 구현하였는데, 현업에서도 주로 CSR이 아닌 SSR을 통해 구현하는지 궁금합니다! 
현업에서는 hymeleaf를 거의 잘 사용안하는 추세이고 react로 구현하는 추세입니다.
hymeleaf 나 react나  SSR 을 무조건적으로 구현하지 않습니다. 모든지 개발에서는 정답이 없으며
최대한 적소적소에 기술을 넣어서 개발하는게 중요합니다. SSR 로만 구현하게된다면 , 서버에 무리가
많이 가기때문에 절절하게 아키텍처를 잡고 설계해야합니다.
Static Site Generation (SSG) , Incremental Static Regeneration (ISR) 개념도 한번 파악해보시는걸 추천드립니다.

수고 많으셨습니다. 응원합니다 👍

2024-06-30 01:29 UTC, azjaehyun commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/delete/{id}")
DeleteMapping을 사용해보는건 어떨까요?

2024-06-30 01:29 UTC, azjaehyun commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
@ControllerAdvice 을  사용해서 예외처리 Good!

2024-07-01 06:27 UTC, pykido commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +@ControllerAdvice
감사합니다! 오늘 라이브 강의에서 problemdetail 또한 학습하여 exceptionhandler 부분의 기능들을 추가해줄 예정입니다 ㅎ

2024-07-01 07:49 UTC, pykido commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/delete/{id}")
감사합니다! deletmapping으로 수정하였습니다. 수정 중에 에러가 발생하였지만 다음 블로그를 통해 해결하였습니다! 
[블로그 바로가기](https://kth990303.tistory.com/51)

2024-07-01 16:10 UTC, pykido commented
안녕하세요 코치님 정말 좋은 리뷰 감사드립니다. 이번 카테캠 step2를 진행하며 기능 구현에만 매몰되지 않고 '왜 이렇게 개발해야하는거지?'라는 질문을 끊임 없이 하고 있습니다! 덕분에 성취감과 동기부여라는 원동력으로 꾸준한 성장을 이루고 있는 듯합니다! 
  앞으로 6주동안 잘 부탁드립니다! 매주 꾸준히, 또 가파르게 성장하는 제 모습을 보여드리겠습니다!

2024-07-05 05:28 UTC, merged