경북대 BE_윤재용_1주차 과제
kakao-tech-campus-2nd-step2/spring-gift-product pull request #60
Opened 2024-06-26 06:30 UTC by yooonwodyd

# spring-gift-product

## 기능 요구 사항
상품을 조회, 추가, 수정, 삭제할 수 있는 간단한 HTTP API를 구현한다.

HTTP 요청과 응답은 JSON 형식으로 주고받는다.
현재는 별도의 데이터베이스가 없으므로 적절한 자바 컬렉션 프레임워크를 사용하여 메모리에 저장한다.

## 구현할 기능 목록 V1.
### 상품
- [x] 상품 Id
- [x] 상품 이름
- [x] 상품 가격
- [x] 상품 이미지 URL

### 상품 컨트롤러
- [x] 상품 In MemoryRepository 를 필드로 가진다. Status 200을 반환한다.
- [x] 상품 추가 메서드. Response DTO를 반환한다.
- [x] 상품 조회 메서드. 상품 Response DTO를 반환한다.
- [x] 상품 전체 조회 메서드. 상품 Response DTO를 리스트로 반환한다.
- [x] 상품 수정 메서드, Id를 통해 받은 상품의 ResponseDto를 반환한다
- [x] 상품 삭제 메서드, 200을 반환한다.

## 구현할 기능 목록 V2.
### 어드민 페이지
- [x] 어드민페이지로 이동하는 메서드를 추가한다. 현재 요구사항에서 InmemoryDB를 Controller의 필드에 있는 관계로, 분리하지 않는다.
- [x] adminPage의 html 파일을 구현한다. JS의 reload를 통해 원래 페이지로 돌아오고, 기존의 CRUD는 유지하도록 한다.
- [x] html에 테일윈드를 적용한다. 재사용성이 안좋은 만큼, 추후 변경이 필요하다.

2024-06-30 15:43 UTC, khj68 commented
Error로 통일하다보면, 추후 클라이언트단과 에러상황에 따른 응답코드를 커스텀하여 정의하거나,
다양한 에러 관련 비즈니스 로직을 처리하는 데에 어려움이 있을 수 있습니다.

프로젝트 초반에는 그런 회의감이 드실 수 있지만,
실무에 가서는 필수적으로 필요한 것들을 미리 학습하는 중이라고 생각해주시면 되겠습니다.

실무에서는 상상하지 못할 엣지케이스와 유저액션으로 인해 다양한 에러가 발생학 때문에,
미리 정의할 수 있는 에러를 정의하여 추후 이슈 파악과 유지보수에 용이할 수 있습니다.

2024-06-30 15:49 UTC, khj68 requested changes
전반적으로 깔끔한 코드입니다.
주석, 인덴트 등 조금 디테일한 부분을 더 신경 써주시면 좋을 것 같습니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/contoller/ProductController.java
> +	private ProductService productService;
@Autowired는 실무에서 지양하는 편입니다.
테스트 작성, 의존 불변성 보장 어려움, 명시적인 관리, 순환 의존성 컴파일 시 감지 불가 등 다양한 부분에서 단점을 가지고 있습니다.
생성자 주입을 통해 의존성을 관리하는 방법을 살펴보시고 습관으로 가져가시는 것을 추천드리겠습니다 :)

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/contoller/ProductController.java
> +public class ProductController {
하나의 컨트롤러에서 뷰를 반환하는 메소드와, 서버응답을 반환하는 메소드가 혼용되고 있습니다.
view controller와 api controller 분리를 추천드립니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/contoller/ProductController.java
> +	@GetMapping("/api/product/{id}")
api에는 /api/v1 과 같이 버전도 명시해주는 습관이 좋을 것 같습니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/domain/Product.java
> +	//of
주석의 의미가 크게 없는 듯 보입니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/dto/ProductRequestDto.java
> +	//toEntity
주석의 의미가 크게 없어 보입니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler(DuplicateProductIdException.class)
이렇게 exception 별로 필요한 에러 처리가 다를 수 있습니다.
따라서 에러를 커스텀처리 하는 것은 유의미한 과정이 됩니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/resources/schema.sql
> +                                        name VARCHAR(255) NOT NULL,
이런 사소한 정렬도 맞춰주면 좋습니다.

2024-06-30 15:49 UTC, khj68 commented on src/main/java/gift/Application.java
> +		SpringApplication.run(Application.class, args);
실무에서 인덴트는 두 칸 정도로 사용하고 있습니다.

2024-07-01 05:36 UTC, yooonwodyd commented on src/main/java/gift/contoller/ProductController.java
> +	private ProductService productService;
넵 변경했습니다 : )

2024-07-01 05:37 UTC, yooonwodyd commented on src/main/java/gift/contoller/ProductController.java
> +public class ProductController {
넵 감사합니다! 변경했습니다!

2024-07-01 05:38 UTC, yooonwodyd commented on src/main/java/gift/contoller/ProductController.java
> +	@GetMapping("/api/product/{id}")
헉 감사합니다. 놓치고 있었네요 v1으로 명시해 두었습니다!

2024-07-01 05:38 UTC, yooonwodyd commented on src/main/java/gift/domain/Product.java
> +	//of
넵!!

2024-07-01 05:38 UTC, yooonwodyd commented on src/main/java/gift/dto/ProductRequestDto.java
> +	//toEntity
변경했습니다!!

2024-07-01 05:38 UTC, yooonwodyd commented on src/main/java/gift/Application.java
> +		SpringApplication.run(Application.class, args);
넵 변경했습니다. 감사합니다 : )

2024-07-01 05:40 UTC, yooonwodyd commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler(DuplicateProductIdException.class)
넵 감사합니다. 복잡한 개발을 한 적 없다보니 에러처리에 소홀했는데, 배워가겠습니다 : )

2024-07-01 06:44 UTC, merged