충남대BE_정현서_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #62
Opened 2024-06-26 06:32 UTC by hynseoj

안녕하세요. 멘토님 :)
1주차 1단계 과제 제출합니다.

스프링을 사용해서 프로젝트를 진행해본 적이 있지만 꾸준히 사용하지 않아 많이 잊기도 했고 최대한 배운 내용 안에서 구현해보려고 했습니다.

## 궁금한 점

1. update를 구현할 때 PUT과 PATCH의 사용 상황의 차이가 무엇인지, 경우에 따라 더 선호하는 방식이 있다면 무엇이고 왜인지 궁금합니다.
 
> PUT 방식은 자원을 전체 교체하고 PATCH는 일부 교체한다고 알고 있는데, 객체 정보 중에서 일부만 수정 가능하게 하고 싶을 때는 PATCH를 사용할 수 있을 것 같습니다. 반대로 모든 정보가 수정 가능할 경우에는 찾아본 바, 보통 PUT을 사용하는 것 같은데 일부 필드가 누락될 경우 초기화될 가능성이 있음에도 굳이 사용자가 수정한 필드만 갱신하지 않고 PUT을 사용하는 이유가 있을까요?

2. 백엔드에서는 사용자 입력에 대한 검증을 어느 정도로 수행해야 하는지 궁금합니다. 그리고 Exception을 던지는 방식과 HTTP 에러 코드를 반환하는 방식 중 어떤 것을 사용하는지도 궁금합니다.

> 과제를 구현할 때 처음에 입력 JSON 필드에 대해 하나하나 null 여부와 타입을 검사하도록 코드를 구현했었는데 이런 기본적인 검증은 프론트엔드에서 해주는 게 더 효율적일 것 같다는 생각이 들어 제외했습니다. 결국 존재하지 않는 자원에 대해 접근하는 경우만 처리하도록 했는데 일반적으로 백엔드에서 입력을 검증하는 범위가 궁금합니다.

감사합니다😁

2024-06-29 11:35 UTC, ksy90101 requested changes
전체적으로 잘 해주셨네요! 고생많으셨습니다!!

2024-06-29 11:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductController.java
> +    private final AtomicLong key = new AtomicLong(1);
이부분은 Dao에 있어야 할거 같습니다~

2024-06-29 11:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductController.java
> +        return updatedProduct.map(value -> "redirect:/products/" + value.getId()).orElse("error");
```suggestion
        return updatedProduct
        .map(value -> "redirect:/products/" + value.getId())
        .orElse("error");
```

혹시 Map을 하신 이유가 있나요?

위에처럼 if문으로 해도 되는데 통일시키면 어떨까요?

2024-06-29 11:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/dao/ProductDao.java
> +        jdbcClient.sql(sql).param(product.getName()).param(product.getPrice()).param(product.getImageUrl())
```suggestion
        jdbcClient.sql(sql)
        .param(product.getName())
        .param(product.getPrice())
        .param(product.getImageUrl())
```
한줄에 하나씩 작성한다면 훨씬 보기 좋을거 같습니다.

2024-06-29 11:35 UTC, ksy90101 commented on src/main/resources/static/js/main.js
> +  var selectAllCheckbox = document.getElementById('selectAll');
document.querySelctor를 쓰면 어떨까요?

2024-06-29 11:35 UTC, ksy90101 commented on src/main/resources/templates/error.html
> +<html lang="en">
```suggestion
<html lang="ko">
```

2024-06-29 11:35 UTC, ksy90101 commented on src/main/resources/templates/error.html
> +  <style>
여기 style도 css파일로 넣으면 어떨까요?

2024-06-29 11:35 UTC, ksy90101 commented on src/test/java/gift/domain/product/dao/ProductDaoTest.java
> +        assertThat(savedProduct.getImageUrl()).isEqualTo(product1.getImageUrl());
assertAll을 알아보고 적용해보시면 어떨까요~?

2024-06-29 11:40 UTC, ksy90101 commented
> update를 구현할 때 PUT과 PATCH의 사용 상황의 차이가 무엇인지, 경우에 따라 더 선호하는 방식이 있다면 무엇이고 왜인지 궁금합니다.

작성해주신대로, 자원전체를 수정할때 PUT, 일부를 수정할때 PATCH를 씁니다.
예를들어 상품의 정보를 변경하는 작업에서는 PUT을 쓰고, 상품을 품절시키는 기능이 필요하다면 상품의 품절시키는 것은 PATCH를 씁니다. 상품에서의 재고 및 상태만을 변경하는것이니깐요. 
이 관점에서 차이점은 멱등성의 차이라고 생각이 들어요.
멱등성이라는 것을 한번 공부해보시면 좋을거 같습니다.

참고글 : https://tecoble.techcourse.co.kr/post/2020-08-17-put-vs-patch/

> 백엔드에서는 사용자 입력에 대한 검증을 어느 정도로 수행해야 하는지 궁금합니다. 그리고 Exception을 던지는 방식과 HTTP 에러 코드를 반환하는 방식 중 어떤 것을 사용하는지도 궁금합니다.

결국 프론트(사용자)가 받은 것은 HTTP stauts code입니다. 따라서 백엔드 내부에서는 Exception을 사용하고 그걸 ExceptionHandler를 사용하여 HTTP Status를 통해 처리하게 됩니다.

사용자의 입력에 대한 검증을 어느정도로 수행하냐에 대해서는 필요한 검증은 모두 해야 한다고 생각합니다. 잘못된 데이터가 들어온다는것이 문제를 많이 일으키기 때문에 필요한 검증은 모두 해야 한다고 생각하고 있습니다~

2024-06-29 14:08 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/ProductController.java
> +    private final AtomicLong key = new AtomicLong(1);
1,2단계 구현 시에 DAO를 작성하지 않고 구현한 부분인데 삭제하는 걸 놓쳤네요 감사합니다!

2024-06-29 14:11 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/ProductController.java
> +        return updatedProduct.map(value -> "redirect:/products/" + value.getId()).orElse("error");
별 다른 이유는 없습니다. IDE에 노란줄이 보기 싫어서 추천해주는 방향으로 수정했습니다..😅
말씀해주신 대로 통일시키는 게 좋을 것 같습니다!!

2024-06-29 14:13 UTC, hynseoj commented on src/main/java/gift/domain/product/dao/ProductDao.java
> +        jdbcClient.sql(sql).param(product.getName()).param(product.getPrice()).param(product.getImageUrl())
메소드 체이닝에서 항상 줄 바꿈을 해야하나 말아야 하나 고민했는데 의견 감사합니다~!

2024-06-29 14:16 UTC, hynseoj commented on src/main/resources/static/js/main.js
> +  var selectAllCheckbox = document.getElementById('selectAll');
넵 제가 html, css, js 사용 경험이 적어서 더 공부해보겠습니다!

2024-06-29 14:40 UTC, hynseoj commented
말씀해주신 내용 모두 잘 읽어보았습니다. 감사합니다!

2024-07-02 01:00 UTC, ksy90101 approved these changes
1주차 진행하시느라 고생많으셨습니다~
추가 간단한 리뷰 남기긴 했는데 2주차 1단계에서 같이 적용해주시면 좋을거 같습니다~
2주차 미션도 계속 이어지기 때문에 진행하면서 더 보는걸로 해도 좋을거 같습니다~
고생 많으셨어요!

2024-07-02 01:00 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductController.java
> +        product.setId(productId);
프론트에서 body에 id를 넣어도 무관하긴 할거 같습니다~
중복으로 두는게 훨씬 더 효율성이 있을땐 중복으로 하기도 해요!

2024-07-02 01:00 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
```suggestion
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }

        return ResponseEntity.noContent()
```
와 같이 빌더 패턴을 쓰는걸 추천드려요!

2024-07-02 01:00 UTC, merged