충남대 BE_이택_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #63
Opened 2024-06-26 06:36 UTC by LeeTaek2T

코치님이라면 step1을 만드실 때 구조를 어떻게 만드셨을지와 테스트코드는 어느정도까지 구현했을지 대략적으로라도 설명해주시면 감사하겠습니다!

2024-06-27 05:14 UTC, LeeTaek2T commented
<STEP2>
1. step2단계를 내용이 처음이여서 인터넷 서칭을 하며 구현을 하였습니다. 지금은 대략적으로 이렇게 움직이는구나!하고 알 뿐이지, 이 경우에는 이런걸 쓰면 좋겠다 다른 경우에는 이런 걸 써야겠다는 생각이 들지가 않습니다. Thymeleaf에 대해서는 어느정도까지 알아두는 것이 좋은지 궁금합니다! 

2. 다른 사람들의 코드를 보고 배우는게 좋다고 들었습니다. 코치님이 생각하시기에 thymleaf에 대해 좋은 코드들을 보여주는 사이트나 자료 추천해주실 수 있을까요,,?

2024-06-27 16:34 UTC, LeeTaek2T commented
Step3
1. 코드를 바꿔 데이터베이스를 적용하였는데, 이때 ProductDao클래스도 Test를 따로 해야하는지 궁금합니다.
2. 관리자 페이지도 데이터베이스와 연동이 되야하는지 궁금합니다. 
3. productDao와 productContoller를 이렇게(제가 짠 코드처럼) 짜는게 맞는지, 아니면 다른 형식으로 접근을 해야하는지 궁금합니다.

2024-06-29 11:17 UTC, ksy90101 requested changes
고생많으셨습니다~
언제든 질문이 있다면 DM주세요!

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/Product.java
> +  private String imageUrl; // 새로 추가된 필드
주석은 제거하면 좋을거 같습니다~

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +@RequestMapping("/products")
URL 👍

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +@RequestMapping("/products")
Admin이라는걸 나타내기 위해
```suggestion
@RequestMapping("admin/products")
```
이렇게 한다면 어드민과 프로덕션과 주소를 보면 분리해볼수 있지 않을까요?

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +    product.setId(id); // Ensure the ID is set to the existing product ID
여기도 사용하지 않은 주석은 제거해도 될거 같습니다~

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +  }
REST API라면 행동을 HTTP Method로 나타낼수 있습니다~
따라서 get, add와 같은 단어는 사용할 필요는 없습니다.

https://meetup.nhncloud.com/posts/92

위 글을 한번 참고해보시면 좋을거 같습니다!

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    Product existingProduct = productDao.selectProduct(id);
product라는 이름을 써도 무관할거 같습니다~

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +  }
한번 DTO를 알아보시고 DTO를 사용해보시면 어떨까요?

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductDao.java
> +    jdbcTemplate.execute(sql);
이런 DDL은 메서드로 만들어두진 않습니다.
따로 schema.sql같은것을 만들어서 맨처음만 실행하게 하기도 합니다!

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductDao.java
> +      ), id
rowMapper를 메서드로 분리해서 작성한다면 아래의 중복코드가 많이 제거될거 같습니다.

2024-06-29 11:17 UTC, ksy90101 commented on src/main/java/gift/ProductService.java
> +public class ProductService {
이부분은 1단계를 하기 위함인가요?

2024-06-29 11:44 UTC, ksy90101 commented
> 코치님이라면 step1을 만드실 때 구조를 어떻게 만드셨을지와 테스트코드는 어느정도까지 구현했을지 대략적으로라도 설명해주시면 감사하겠습니다!

이부분에 대한 질문에 대해서는 잘 이해하지 못했습니다... 혹시 어떤 의도로 어떤 문제를 질문하신건지 좀더 구체적으로 가능할까요?

> step2단계를 내용이 처음이여서 인터넷 서칭을 하며 구현을 하였습니다. 지금은 대략적으로 이렇게 움직이는구나!하고 알 뿐이지, 이 경우에는 이런걸 쓰면 좋겠다 다른 경우에는 이런 걸 써야겠다는 생각이 들지가 않습니다. Thymeleaf에 대해서는 어느정도까지 알아두는 것이 좋은지 궁금합니다!

지금 요구사항에 맞게 구현할수 있을 정도면 충분할거라고 생각했습니다~

> 다른 사람들의 코드를 보고 배우는게 좋다고 들었습니다. 코치님이 생각하시기에 thymleaf에 대해 좋은 코드들을 보여주는 사이트나 자료 추천해주실 수 있을까요,,?

초반에는 공식문서를 많이 참고해서 공부해보시면 좋을거 같습니다~

> 코드를 바꿔 데이터베이스를 적용하였는데, 이때 ProductDao클래스도 Test를 따로 해야하는지 궁금합니다.

시간이 된다면 작성하는게 좋다고 생각이 들어요. 그부분도 결국은 우리가 작성한 코드이기 때문에 작성한 코드에 대해서 안정성을 위해 작성하는게 좋을거 같습니다.

> 관리자 페이지도 데이터베이스와 연동이 되야하는지 궁금합니다.

관리자 페이지를 만드는 이유가 무엇일까요? 해당 서비스의 어드민으로써 기능을 추가하기 위한게 아닐까요? 관리자 페이지에서 특정 행동을 하면 실제 서비스에서도 작동해야 하지 않을까요? 그렇다면 필요할거 같아요~

>productDao와 productContoller를 이렇게(제가 짠 코드처럼) 짜는게 맞는지, 아니면 다른 형식으로 접근을 해야하는지 궁금합니다.

지금 학습의 목표에서는 충분한거 같습니다~ 이후에 좀더 어떻게 계층을 더 할수 있는지 좀더 어떻게 잘 작성할수 있는지 배우는게 준비되어 있다고 생각이 들어요~

2024-07-01 18:53 UTC, LeeTaek2T commented on src/main/java/gift/ProductService.java
> +public class ProductService {
네! 맞습니다. 혹시 몰라 남겨뒀었습니다

2024-07-01 18:58 UTC, LeeTaek2T commented on src/main/java/gift/ProductController.java
> +  }
저는 Product를 DTO라고 생각하고 만들었습니다.
그리고 DTO는 각 계층간 독립성을 유지하기 위한 것이며, DTO로 각 계층끼리 정보를 주고 받는다고 알고 있습니다.
DTO를 적용하여 코드를 바꾸긴 했는데, 이렇게 바꾸는 것이 맞는지 잘 모르겠습니다. 수정된 코드가 계층 간 독립성을 유지하기보다는 단순히 코드만 길어졌다고 생각이 듭니다.

2024-07-01 19:09 UTC, LeeTaek2T commented
<span style="color:yellow">노란 글씨입니다.</span>코치님이라면 이번주 과제를 model-service-repository와 같이 구조를 만드셨을지, 아니면 다른 구조를 이용하셨을지 궁금합니다!

2024-07-01 19:11 UTC, closed without merging

2024-07-02 01:34 UTC, ksy90101 commented
> 코치님이라면 step1을 만드실 때 구조를 어떻게 만드셨을지와 테스트코드는 어느정도까지 구현했을지 대략적으로라도 설명해주시면 감사하겠습니다! 코치님이라면 이번주 과제를 model-service-repository와 같이 구조를 만드셨을지, 아니면 다른 구조를 이용하셨을지 궁금합니다!

기본적으로 Model-Service-Repository와 같은 구조로 만들었을거 같아요~ 차후 확장성을 생각햇을땐 처음부 터 구조를 가져가는게 좋거든요~
그러나 지금은 학습이 목표이기 때문에 너무 멀리 가지 않고 천천히 해주시면 좋을거 같습니다.
2주차 미션에서 한번 Repository == Dao 를 만들어서 처리해보시면 좋을거 같습니다!

2024-07-02 01:41 UTC, ksy90101 approved these changes
고생많으셨습니다~
1주차는 이만 마무리 할게요!
추가 리뷰는 2주차 1단계에서 같이 적용해주시면 좋을거 같습니다~
2주차도 홧팅입니다!
언제든 질문이 있다면 DM주세요!

2024-07-02 01:41 UTC, ksy90101 commented on src/main/java/gift/ProductAdminController.java
> +  }
```suggestion
  private final ProductDao productDao;

  public ProductAdminController(ProductDao productDao) {
    this.productDao = productDao;
  }
```

생성자 주입 방식으로 하면 좋을거 같습니다!

2024-07-02 01:41 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +  private final ProductDao productDao;
앗 제가 답을 잘못남겼네요.
2주차에서는 Service를 한번 도입해보세요~

2024-07-02 01:41 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    productDTO=productDao.selectAllProducts();
```suggestion
    List<Product> productDtos = productDao.selectAllProducts();
```
이런식으로 카멜케이스로 나타내면 좋을거 같습니다~ 아울러 재할당 할 이유가 없어보여요!
마지막으로 Collection은 복수형으로 변수를 지어서 나타내는 편입니다!

2024-07-02 01:41 UTC, ksy90101 commented on src/main/java/gift/ProductController.java
> +    return ResponseEntity.notFound().build();
부정보단 긍정이 더 좋습니다!

```suggestion
    if (product == null) {
      return ResponseEntity.notFound().build();
    }
    return ResponseEntity.ok(product);
```

2024-07-02 01:41 UTC, ksy90101 commented on src/main/resources/templates/product-form.html
> +  <style>
Style을 따로 파일을 빼서 관리하는게 훨씬 더 깔끔할거 같습니다!

2024-07-02 01:41 UTC, ksy90101 commented on src/test/java/gift/ProductControllerTest.java
> +public class ProductControllerTest {
테스트 코드 👍

2024-07-02 01:41 UTC, ksy90101 commented on src/test/java/gift/ProductControllerTest.java
> +@JdbcTest
Controller 테스트이기 때문에 JdbcTest가 아니라 SpringBootTest가 되어야 하지 않을까요?

JbdcTest어노테이션은 어디에 쓰는건지 한번 찾아보시면 좋을거 같습니다~