경북대 BE_김영인_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #64
Opened 2024-06-26 06:42 UTC by Youngini

테스트를 postman에서 진행해서 테스트 코드를 따로 작성하지는 않았는데, 테스트 코드 작성은 현업에서도 필수인지가 궁금합니다!

2024-06-28 10:14 UTC, Youngini reviewed
2단계 과제를 완료하였습니다.
bootstrap을 써서 페이지를 만들 수 는 있지만, thymeleaf 사용법에 익숙치 않아서 많이 헤멘 것 같고, 제대로 동작이 되고있는 것인지도 잘 모르겠습니다. 과제를 제출하고 난 뒤에도 많이 고민하고 공부해야할 것 같습니다.

2024-06-29 16:06 UTC, gongdongho12 requested changes
안녕하세요 이번에 BE멘토를 맡게된 강동호입니다 :)
저도 부족한 부분이 많지만 좋은 프로젝트로 완성해갈 수 있도록 같이 노력해봐요!

> 테스트를 postman에서 진행해서 테스트 코드를 따로 작성하지는 않았는데, 테스트 코드 작성은 현업에서도 필수인지가 궁금합니다!
테스트를 작성하는 이유는 사실 현재의 문제를 대응하는 측면도 있지만 추후에 리팩토링이 일어났을때, 어떤 값이 들어갔을 떄 이 값이 리턴되었다와 같이 변경점이 생기더라도 기존의 동작은 동일하게 적용하기 위해 필요한 부분입니다

ex) 회원가입할때 아이디, 이메일, 비밀번호만 받았는데, 주민번호 칼럼이 추가되면 기존 멤버들의 데이터가 오류가 발생할 수 있겠죠? 그런 것들을 미리 코드화해서 배포하는 github action으로 간단하게 검증할 수 있어서 실제 사용자에게 배포되고 문제가 되는 상황을 사람의 테스트 보다 먼저 확인할 수 있다는 측면에서 시간 절약되는 부분이 크게 작용하기 떄문에 크리티컬한 대상에 우선적으로 적용해 나가는 것이 중요합니다

2024-06-29 16:06 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        }*/
이미 validation이라는 명칭 덕분에 주석을 별도로 포함하지 않더라도 어떤 기능인지 이해할 수 있을 것 같은데 주석을 지우는게 깔끔해 보이지 않을까요?

2024-06-29 16:06 UTC, gongdongho12 commented on src/main/resources/data.sql
> +(5, 'Product 5', 'Description for Product 5', 50, 'https://example.com/product5.jpg');
샘플용 데이터를 쿼리로 활용하신점이 깔끔하네요 👍🏼

2024-06-29 16:11 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    }
각각 전부 } catch (IllegalArgumentException e){ 를 정의해 주셨는데 오류는 결국 대부분 비슷한 리턴 타입인데요
ControllerAdvice 라는 것도 찾아보시면 좋을 것 같습니다

2024-06-29 16:13 UTC, gongdongho12 commented on src/main/java/gift/repository/JdbcProductRepository.java
> +    }
칼럼이 추가되거나 변경되면 ?의 순서가 달라질 수 있는데 SimpleJdbcInsert를 사용해보시면 어떨까요?

2024-06-29 16:16 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +*/
git을 사용하시면 커밋 기록에도 남아서 사용하지 않는 불필요한 주석은 최소화 하는것이 작업하거나 타인이 보기에도 깔끔할 수 있을 것 같아요

2024-06-29 16:50 UTC, gongdongho12 commented on src/main/java/gift/validation/ProductValidation.java
> +    }
기능 구현에도 고생하셨을 건데 Validation 사용하니까 깔끔해졌네요 👑

2024-07-01 13:11 UTC, gongdongho12 approved these changes
기본적인 부분은 완료된거 확인해서 다음 프로젝트에 추가적으로 완성해가봐요 👍🏼

2024-07-01 13:13 UTC, merged