전남대 BE_강명덕_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #67
Opened 2024-06-26 07:33 UTC by Profile-exe

### 코드를 작성하며 어려웠던 점
- 데이터베이스를 사용하지 않다보니 상품을 유일하게 식별할 고유값인 ID를 어떻게 할당해줄지 정하는 것이 어려웠습니다.

### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
- 상품이 아니라 다른 도메인까지 추가된다면 해당 도메인의 고유한 ID가 존재할 텐데, 지금처럼 클래스마다 개별적인 static 변수를 두고 증가시키면서 ID를 할당하는 방식으로 구현해도 괜찮나요?

- 상품을 삭제했을 때 성공 여부를 boolean값으로 반환하기 vs 삭제된 상품 내용 반환하기 둘 중 어느 방법이 괜찮은지 알고 싶습니다.
  - 삭제된 상품 내용을 반환하면 내가 원하는 상품을 삭제했는지 알 수 있지만, 불필요한 정보인 느낌이 들었습니다.
  - boolean값을 반환하면 성공 여부는 알 수 있지만 어떤 상품을 삭제했는지는 알 수 없습니다.
  - 어쩌면 삭제된 상품의 id와 성공 여부를 담아 `{ id: 1, delete: true }` 등으로 반환해야 하는지 궁금합니다.

- Product와 ProductDto간의 변환이 이루어지는게 반복되는 느낌이 들었습니다. 내부적으로 서로 변환하는 메서드를 만들어 호출하는 것이 괜찮은가요?
  - Dto가 많아지면 그만큼 변환 메서드를 추가해야 하고 Dto 또는 Product 내용이 변화되면 각 메서드를 모두 수정해 주어야 하는 비용이 무시하지 못할 것이라 생각합니다.
  - 하지만 메서드가 있다면 변환 과정에서 값을 누락하는 상황을 방지하고 비즈니스 로직을 작성할 때 편리하고 간단하게 작성할 수 있을 것이라 생각하는데
  - 이 둘의 trade-off에서 어떤 선택을 해야 하는지 기준이 있을까요?

2024-06-28 15:00 UTC, hocaron requested changes
명덕님, 안녕하세요👋 
이번 step 을 함께할 호선우입니다.

커밋을 작업별로 세세하게 나눠주셔서, 리뷰하는데 도움이 많이 되었습니다👍
함께 작업하는 입장에서 반영하면 좋을 리뷰를 남겼는데, 궁금한 점이나 의문이 생기면 편하게 코멘트나 DM 주세요.

1. 상품이 아니라 다른 도메인까지 추가된다면 해당 도메인의 고유한 ID가 존재할 텐데, 지금처럼 클래스마다 개별적인 static 변수를 두고 증가시키면서 ID를 할당하는 방식으로 구현해도 괜찮나요?</br>

2. 상품을 삭제했을 때 성공 여부를 boolean값으로 반환하기 vs 삭제된 상품 내용 반환하기 둘 중 어느 방법이 괜찮은지 알고 싶습니다.</br>

3. Product와 ProductDto간의 변환이 이루어지는게 반복되는 느낌이 들었습니다. 내부적으로 서로 변환하는 메서드를 만들어 호출하는 것이 괜찮은가요? </br>
내부에서 반환하는 메서드 만들어주는 것이 좋은 것 같습니다. Dto가 많아지면 변환 메서드를 추가해야 하지만, 변환 로직이 어디에선가는 필요하므로(서비스 로직) 반복되는 것보다는 변환 메서드에서 처리하는 것도 좋을 것 같아요. 오히려 여러곳에서 각각 변환로직을 가지고 있어 여러곳의 코드를 고치는 것보다는 한곳에서 변환메서드를 관리하여 해당 포인트만 고치는게 관리하는 측면에서 수월할 것 같습니다😀

5. window.onload() 방식으로 화면이 새로고침된 경우 상품 목록을 다시 불러와 화면을 갱신하는데, 삭제를 할때마다 페이지를 새로고침해도 괜찮나 고민이 되었습니다. 삭제를 한 경우 JavaScript를 활용해서 테이블 내용만 다시 수정하도록 하는게 적절할까요?</br>
좋은 고민입니다. 불필요한 리소스 소모 방지와 사용자 경험 측면에서 테이블 내용만 다시 수정하도록 해도 좋을 것 같습니다.

6.  insert, update, delete 쿼리를 수행할 때 영향을 받은 row 수를 얻을 수 있었습니다.
이를 이용해 특정 상품에 대한 추가, 수정, 삭제가 정상적으로 이루어졌는지 확인하려고 했습니다.
그래서 ProductController에서 값이 1인 NO_OF_ROWS_AFFECTED 상수와 비교하도록 코드를 작성했는데 적절한 방식인지 궁금합니다.</br>

7. E2E 테스트가 API를 테스트하는 방식으로 이해해도 될까요?</br>
네, 맞습니다. 서비스로직에 대한 세세한 테스트는 할 수 없지만, 저는 배포 나가기 전에 API 가 정상 동작한다는 정도의 테스트 목적으로 사용하고 있습니다.

8.  만약 관리자화면 등의 GUI 구성요소들은 어떤 방식으로 테스트해야되나요?</br>
단위 테스트, 통합 테스트, 그리고 UI(사용자 인터페이스) 테스트가 있을 것 같습니다. 
테스트 코드로는 Jest와 React Testing Library / Supertest와 Jest 등을 사용해서 테스트가 가능할 것 같고, QA 분들께서 테스트 케이스 작성 후에 직접 기능을 사용하면서 테스트도 가능할 것 같습니다.

2024-06-28 16:28 UTC, hocaron commented on src/main/java/gift/product/ProductController.java
> +        );
[반영하지 않으셔도 좋습니다😀]

컨트롤러 클래스에서 validation 및 조회 등의 많은 역할을 하고 있는 것 같아요! 서비스 클래스를 만든 것도 좋아보이는데, 어떻게 생각하실까요?!

2024-06-29 08:03 UTC, Profile-exe commented on src/main/java/gift/product/ProductController.java
> +@RequestMapping("/api")
피드백 감사드립니다!

`URL` 방식으로 버져닝을 하는 경우 `v2` 버전이 추가될 때 `@RequestMapping("/api")`로 수정하고 
`ProductController`의 엔드포인트들은 `@~Mapping("/v1/products")`, `@~Mapping("/v2/products")` 이런식으로 매핑하면 될까요?

2024-06-29 14:43 UTC, hocaron commented on src/main/java/gift/product/ProductController.java
> +@RequestMapping("/api")
맞습니다! 버전업된 API 가 많지 않으면 한개의 클래스 내부에서 v1/v2 로 매팡하여 사용합니다😀

2024-07-01 08:00 UTC, Profile-exe commented on src/main/java/gift/product/ProductController.java
> +        );
이번주(2주차) 목요일에 계층형 아키텍처에 대한 클론코딩 강의가 예정되어있어 해당 부분 학습 후 적용해보도록 하겠습니다!

사용자의 요청에 대한 응답을 하는 책임은 controller
validation 및 조회 등 웹 어플리케이션의 비즈니스 로직을 책임지는 service
database에 접근하여 데이터 CRUD 수행을 책임지는 repository 

각 계층별 책임을 위와 같이 분리한다고 생각해도 괜찮을까요?

2024-07-01 08:59 UTC, hocaron commented on src/main/java/gift/product/ProductController.java
> +        );
넵, 맞습니다! 명덕님! 목요일에 강의가 예정되어 있군요😀

validation 은 RequestDto 에서도 이루어질 수 있는데요, 아래와 같이 나눠볼 수 있을 것 같습니다. 이부분도 취향을 타는 부분이라 참고만 해주시면 좋을 것 같습니다😎

- Request DTO에서 검증을 수행하는 것은 주로 간단하고 기본적인 형식 및 제약 조건을 빠르게 확인하기 위함이며, 이는 코드의 간결성과 재사용성을 높여줍니다.
- Service에서 검증을 수행하는 것은 복잡한 비즈니스 로직 및 상태 기반 검증을 처리하기 위함입니다. 이는 시스템의 일관성과 복잡한 로직을 처리하는 데 도움이 됩니다.

Request DTO에서 Validation이 적절한 경우
1. 간단한 규칙: 필드의 값이 null이 아니어야 한다거나, 특정 값의 범위를 벗어나지 않는 등 간단한 검증 규칙을 적용할 때.
- 예: 이메일 형식 검증, 문자열 길이 검증, 숫자 범위 검증 등.
2. 데이터 형식 검증: JSON 데이터가 올바른 형식인지, 필수 필드가 모두 있는지 확인할 때.
- 예: @NotNull, @Size, @Email 등의 어노테이션을 사용한 검증.
3. 재사용성: 여러 서비스에서 동일한 검증 로직이 필요할 때.
- 예: 여러 서비스에서 동일한 DTO를 사용하여 데이터를 받을 때 공통적인 검증 로직을 DTO에 포함시켜 재사용성을 높임.

Service에서 Validation이 적절한 경우

1. 복잡한 비즈니스 로직 검증: 단순한 형식 검증을 넘어 비즈니스 로직에 따른 복잡한 검증이 필요할 때.
- 예: 데이터베이스 조회를 통한 중복 검사, 사용자 권한 검증 등.
2.	상태 기반 검증: 특정 데이터의 현재 상태나 컨텍스트에 따라 검증이 필요할 때.
- 예: 주문 상태에 따라 업데이트 가능 여부를 검증하는 경우.

2024-07-01 09:15 UTC, Profile-exe commented on src/main/java/gift/product/ProductController.java
> +        );
예시와 함께 상세한 답변 정말 감사드립니다!

검증 로직은 검증 내용과 조건에 따라 여러 부분에서 적용할 수 있다는점 잘 배웠습니다. 추후 학습을 통해 익혀보도록 하겠습니다.
예시로 든 부분은 과제수행시에 적용해보며 공부해보겠습니다!

추가로 이번 피드백을 [2주차 0단계 PR](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/64) 에 코드를 옮기며 적용했으니 이 부분 확인해주시면 감사하겠습니다 ㅎㅎ

2024-07-01 09:37 UTC, merged