부산대 BE_문성재_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #69
Opened 2024-06-26 08:26 UTC by student-p

상품에 대한 crud를 할 때 예외 상황이나 정상 상황에서 ResponseEntity를 사용해서 처리 결과나 메시지와 함께 HTTP상태코드를 반환했는데 이것보다 더 권장하는 방법이 있는지 궁금합니다.

2024-06-28 10:08 UTC, student-p commented
### 과제를 진행하면서 들었던 궁금증

너무 기초적인 질문을 하는 것 같아서 좀 부끄럽지만 그래도 알고 넘어가는 것이 좋을 것 같아서 질문 드립니다.

1. db에 crud를 하다가 오류가 발생한 경우(없는 product를 삭제/수정) 예외 핸들링을 어떻게 할지 잘 모르겠어서 현재는 구현을 하지 않은 상황인데
어떤 방법으로 처리하면 좋을지 방법이나 방향? 이 궁금합니다.

2. db에 crud작업이 성공한 경우에 현재는 필요한 html을 보내주기만 하는데 어떻게 응답해 주는 것이 좀 더 바람직한 방법일지 궁금합니다. 
(만약 삭제에 성공했다면 삭제한 id를 다시 보내줘야 할까요? 그렇다면 왜 그래야 하는지 궁금합니다.)

3. 클라이언트가 보낸 정보를 검증하는 절차가 현재는 없는데 이후에 검증하는 절차를 넣는다면, 검증을 통과하지 못한 경우 클라이언트에게 어떤 응답을 보내야 하는지 궁금합니다.
(만약 price가 부적절하다면 price가 올바르지 않다는 화면을 보내고 끝내는 것이 맞는 걸까요?
보통 어떻게 처리하는지 궁금합니다.)

4. 이전 강의 시간에 책임 별로 나누지 말고 일단 컨트롤러에 전부 구현해보라는 말을 들었던 것 같아서 레포지토리를 제외하고는 일단 컨트롤러에 로직을 전부 넣었습니다.
이것을 감안하고 볼 때 전체적인 코드 스타일이나 로직에서 미흡한 부분이 무엇인지 궁금합니다.

많은 질문 드려서 죄송합니다.
답변을 주신다면 다음주 과제에 충실히 반영하도록 하겠습니다

2024-06-30 05:15 UTC, azjaehyun requested changes
안녕하세요 문성재님. 양재현 멘토 입니다.
코드를 개발하면서 힘든점도 많겠지만 즐겁게 생각하면서 개발에 흥미를 조금씩 가지게되면
점점 실력이 올라가는게 느껴질 겁니다.
한주동안도 수고 많으셨고 다음주에도 화이팅입니다.
궁금한신점은 얼마든지 적어주시면 최대한 답변 드리도록 하겠습니다.
감사합니다 👍

2024-06-30 05:15 UTC, azjaehyun commented on src/main/java/gift/controller/ProductController.java
> +        productjdbcRepository.deleteById(id);
만약에 id가 없다고 가정한다면 exception을 생성하여 구현하는게 좋습니다.

### ProductNotFoundException.java
```
package gift.exception;
public class ProductNotFoundException extends RuntimeException {
    public ProductNotFoundException(String message) {
        super(message);
    }
}
```
 ### GlobalExceptionHandler.java
```
package gift.exception;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(Exception.class)
    public String handleException(Exception e, RedirectAttributes redirectAttributes) {
        redirectAttributes.addFlashAttribute("errorMessage", "Error: " + e.getMessage());
        return "redirect:/api/products";
    }

    @ExceptionHandler(ProductNotFoundException.class)
    public String handleProductNotFoundException(ProductNotFoundException e, RedirectAttributes redirectAttributes) {
        redirectAttributes.addFlashAttribute("errorMessage", "Product not found: " + e.getMessage());
        return "redirect:/api/products";
    }
}
```
--- 
추가후에 해당 로직을 
```
        Product product = productjdbcRepository.findById(id).orElseThrow(() -> new 
        ProductNotFoundException("Product not found"));
        return "redirect:/api/products";
```
이런식으로 짜서 Product not found 라고 값을 넘겨주면 됩니다.
더 자세한 내용은 @ControllerAdvice 관련해서 찾아보셔서 습득해보세요 👍

2024-06-30 05:15 UTC, azjaehyun commented on src/main/java/gift/controller/ProductController.java
> +        return new ResponseEntity<>("Selected products deleted successfully.", HttpStatus.OK);
상품에 대한 crud를 할 때 예외 상황이나 정상 상황에서 ResponseEntity를 사용해서 처리 결과나 메시지와 함께 HTTP상태코드를 반환했는데 이것보다 더 권장하는 방법이 있는지 궁금합니다.

네 보통 ResponseEntity 처리를 사용해서 처리하며 delete 같은 경우는
ResponseEntity.noContent().build(); // 204 No Content 반환 합니다 이유는 보안적인 측면.   
하지만 모든지 무조건 이라는것은 아니며 현업에서 리턴값을 달라고 하는 경우에는 주기도 합니다.

2024-06-30 05:15 UTC, azjaehyun commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/api/products/edit/{id}")
1. @GetMapping
@GetMapping은 HTTP GET 요청을 처리합니다. 주로 리소스를 조회할 때 사용됩니다.
2. @PostMapping
@PostMapping은 HTTP POST 요청을 처리합니다. 주로 새로운 리소스를 생성할 때 사용됩니다.
3. @PutMapping
@PutMapping은 HTTP PUT 요청을 처리합니다. 주로 기존 리소스를 업데이트할 때 사용됩니다.
4. @DeleteMapping
@DeleteMapping은 HTTP DELETE 요청을 처리합니다. 주로 리소스를 삭제할 때 사용됩니다.
5. @PatchMapping
@PatchMapping은 HTTP PATCH 요청을 처리합니다. 주로 리소스의 부분적인 업데이트를 할 때 사용됩니다.

어느걸 사용해야할까요? ^^ PutMapping으로도 구현해보셔요

2024-07-05 05:53 UTC, merged