충남대 BE_배민수_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #71
Opened 2024-06-26 09:22 UTC by minsu-cnu

실제 클라이언트와의 요청, 응답 테스트는 postman으로 진행했습니다.

과제 수행하면서 궁금했던 부분들이 있는데 답변 주시면 감사드리겠습니다!

1. 스프링이 처음이다보니 적용하려는 모든 기능이 다 처음이고, 워낙 방대해서 머릿 속에 정리하는 것과 지식을 체득하는 데에 어려움이 있었습니다.

예를 들어서 이번 과제에서는 컨트롤러에 모든 기능을 다 구현해도 되는건지, 아니면 MVC 패턴에 service, repository 구조로 더 분리해서 설계를 해야하는건지 어느 수준으로 구현을 해야할지 판단이 어려웠습니다. 이 외에도 찾다보면 과제에 적용 가능한 정말 많은 방법론과 기능들이 있었습니다.

이런 부분들은 자율적으로 학습 후에 본인 판단대로 설계 구조나 기술을 적용하면 되는건지, 아니면 라이브 클론코딩 강의에서 배운 내용에 국한하여 구현해도 충분한건지 궁금합니다! (어떤 식으로 학습하는게 맞는 것일지 궁금합니다.)

2. 1단계 과제를 구현할 때, insert와 update를 수행할 때 그 응답으로, 수정 및 업데이트가 적용된 DTO에 대한 정보를 JSON으로 응답하게 구현했습니다.

그런데 생각해보면 수정 및 삽입의 경우, 상태 코드나 수정 및 삽입 완료 또는 실패 메시지를 응답하는게 더 맞는 것 같기도 한데, 어떤 방법이 더 합리적인지 궁금합니다.

2024-06-28 16:09 UTC, jjongwa requested changes
안녕하세요! 이번 step2 리뷰어를 맡은 디노입니다 🦖

요구사항도 모두 만족한 것 같고, 여러 가지 고민한 흔적이 많이 보이네요! 👍👍 
잘 구현해 주셔서 많이 바꿀건 없고 질문 남긴 부분에 대해서만 조금 더 고민해서 적어 주시면 좋을 것 같습니다!


> step1 질문
1. 우선 가장 기본은 강의에서 배운 내용을 완벽하게 체득하는 것이구요! 그렇다고 추가적으로 공부한 부분을 과제에 적용하면 안되고 이런 건 아니라고 생각합니다ㅎㅎ 본인의 현재 상태와 능력에 맞게 진행해 주시면 될 것 같아요! 

2. 상황에 따라 어떤 게 합리적인지는 달라질 것 같아요! 예를 들어 어떤 상품에 대한 수정 요청을 보냈을 때, "수정 완료" 보다는 자신이 요청한 id에 대한 상품이 어떻게 최종적으로 바뀌었는지 응답으로 바로 확인하고 싶을 수도 있구요! (만약 "수정 완료"만 내보내준다면 다시 해당 id로 get 요청을 보내야겠죠?) 
무조건적인 정답은 없는 것 같습니다~!

step2와 3에 대한 질문은 회사 / 부서 / 팀 마다 달라지는 문제가 제가 명확이 이렇다! 하고 말씀드릴 순 없을 것 같아요..! 이 부분은 멘토링 시간에 얘기해 볼까요~!

2024-06-29 06:44 UTC, minsu-cnu commented on README.md
> +
조언 감사합니다!

확실히 기능 명세 부분에서, 과제 진행 따라가는데에 많이 벅찰 것으로 생각하고 스프링 공부와 과제에 집중하느라 정작 README.md 작성에 소홀했던 것 같습니다.

말씀 주신 내용 보고 방금 구글링으로 기능 명세 예시들을 찾아봤는데 좋은 예시들이 많이 있는 것 같아요. 이런걸 찾아보지 않고 단순하게 작성했던게 확실히 많이 부족했던 점인 것 같습니다. 말씀 주신 내용 반영하여 새로 작성해보았습니다!

2024-06-29 06:44 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +    }
제가 공부해 본 바로는 다음과 같다고 생각합니다!

1. 필드 주입 : 어떤 클래스의 필드에 Autowired 어노테이션을 명시해서, 해당 필드에 빈을 직접 주입


2. setter 기반 주입 : 클래스의 어떤 필드에 대한 setter를 작성하고, 이 setter에 Autowired를 명시하여, 스프링 컨테이너가 이 setter를 통해 필드에 빈을 주입해주는 방식

3. 생성자 기반 주입 : 클래스의 생성자를 통해 의존성을 주입해주는 방식.
-> 생성자 방식이므로 인스턴스 생성할 때 1회만 호출하는 것이 보장되고, 이에 따라 필드에 final 키워드를 사용 가능


3가지 방식 중 생성자 주입 방식을 일반적으로 권장한다고 하는데, 그 이유는 다음과 같다고 합니다.

1. 생성자 주입 방식의 장점 : 인스턴스 생성 시 최초 1회만 주입하기 때문에 해당 객체에 대한 불변성을 보장할 수 있음

2. 순환 참조 문제 : A, B 두 객체가 서로에게 의존성이 있는 경우 순환 참조가 발생할 수 있는데, 앞서 3가지 주입 방식 모두 해당 문제가 발생할 수 있다고 합니다.

그런데 필드 주입과 setter 기반 주입 방식은 런타임에 에러가 발생해서 서비스 운영에 문제가 될 수 있는데, 생성자 주입 방식은 컴파일 타입에 에러가 발생하기 때문에 서비스 진행 전에 미리 문제를 예방할 수 있다고 합니다.

3. 단위 테스트 : 필드 주입 방식의 경우에는 순수 자바 코드에서는 의존성 주입이 제대로 이루어지지 않아 null 문제가 발생하는데, 생성자 기반 주입 방식의 경우에는 순수 자바 코드에서도 의존성 주입이 잘 이루어져서 단위 테스트에서도 용이하다고 합니다.

2024-06-29 06:44 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +public class AdminController {
컨트롤러로는 지금은 ProductController와 AdminController가 있습니다. ProductController는 클라이언트의 Product에 대한 CRUD 요청에 대응하기 위한 메소드들을 모아둔 컨트롤러이고, AdminController는 관리자 페이지에서 관리자가 Product에 관해 CRUD 요청을 날리는 것에 대응하기 위한 메소드들을 따로 모아둔 컨트롤러입니다!

기능 자체는 비슷하지만, 그 기능을 수행하는 유저, URL, 목적이 다르기 때문에 컨트롤러를 분리하였습니다.

2024-06-29 06:44 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +//    }
넵 해당 주석 삭제하여 반영하겠습니다!

2024-06-29 06:45 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +        return "redirect:/admin/products";
조언 감사합니다. 해당 부분 반영하겠습니다!

2024-06-29 06:45 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +    public String deleteProduct(Product product, RedirectAttributes redirectAttributes) {
넵 해당 부분 제거하여 반영하겠습니다!

2024-06-29 06:45 UTC, minsu-cnu commented on src/main/java/gift/product/controller/AdminController.java
> +        return "redirect:/admin/products";
post 같은 경우에는 id를 쓸 일이 없어서 PathVariable로 바인딩하지 않은 상태입니다. 그렇지만 현재 위치해있는 업데이트 폼에서 현재 위치 제자리로 post를 날리는 구조이기 때문에 url에 id를 명시해두었습니다.

GetMapping을 사용한 updateForm은 url에 있는 id에 해당하는 product에 대한 업데이트 폼 뷰(페이지)를 반환하는 메소드입니다.

PostMapping을 사용한 updateForm은, 해당 업데이트 폼 페이지에서 관리자 유저가 적용 버튼을 누르면, 현재 위치에 post 요청을 날려서 DB에 update를 수행하고 상품 전체 페이지로 리다이렉트 시켜주는 메소드입니다.

2024-06-29 06:45 UTC, minsu-cnu commented on src/main/java/gift/product/dto/ProductDTO.java
> +}
record 타입을 명시해두면, 파라미터에 명시되어있는 인자들의 타입과 식별자명을 참고하여 자동으로 생성자와 getter, equals, toString 등를 만들어줍니다. 이를 통해 보일러 플레이트 코드 문제를 해소할 수 있습니다.

record는 다음과 같은 특징이 있습니다.
1. 모든 필드가 불변성을 갖기에 setter는 만들어주지 않습니다
2. class가 final이라 이를 상속받는 하위 클래스를 만들 수 없습니다.
3. java.lang.Record class를 상속받는 클래스를 만든 것이기 때문에, 다중 상속이 안되는 자바 특성 상, 다른 클래스를 상속받을 수 없습니다.
4. 일반적으로 getter는 get + 필드명 으로 만드는데, record는 필드명과 유사한 이름으로 getter를 만들어줍니다. ex) id(), name() 등

기존의 class로 record와 같은 역할을 수행하려면 생성자와 getter 등을 명시적으로 선언해두고, 필드를 final로 불변성을 갖도록 하면 된다고 생각합니다!

2024-06-29 06:45 UTC, minsu-cnu commented on src/test/java/gift/ProductTest.java
> +public class ProductTest {
해당 조언 반영하여 접근제어자를 제거하였습니다. 감사합니다!

2024-06-29 06:46 UTC, minsu-cnu commented on src/test/java/gift/ProductTest.java
> +    }
감사합니다!

2024-06-29 06:46 UTC, minsu-cnu commented on src/test/java/gift/ProductTest.java
> +        Assertions.assertThat(productAll.get(0).getImageUrl()).isEqualTo("사진링크");
말씀 주신 코드를 보고 assertAll과 assertSoftly에 대해 알아봤는데, 기존 제 방식대로라면 assertThat 중 하나가 실패하면 그 이후의 assert문을 수행하지 않는다는 것을 알게 되었고, 실패하더라도 모든 assert문을 실행하기 위해 말씀 주신 2가지 방법을 쓴다는 것을 알게 되었습니다.

assertSoftly는 assertAll의 기능에 더하여 실패한 코드의 라인 번호까지 알려주는게 좀 더 유용한 것 같아서 assertSoftly를 사용하도록 리팩토링을 해보았습니다. 또한 테스트 코드 작성의 편의를 위해 static import를 해보았습니다!

2024-06-29 06:46 UTC, minsu-cnu commented on src/test/java/gift/ProductTest.java
> +        Assertions.assertThat(productAll.size()).isEqualTo(1);
말씀 주신 내용은 처음 접해보는 메소드라 한번 적용해서 리팩토링해보았습니다. 유용하고 좋은 것 같아요!

2024-06-29 06:46 UTC, minsu-cnu commented on src/main/java/gift/product/model/Product.java
> +    }
클라이언트가 product를 DB에 insert하는 요청을 했을 때, 응답으로 등록된 product를 반환하는데 이 때 여기에 DB에 저장됐을 때 갖는 id를 포함시켜 반환함으로써, 클라이언트가 추가된 product의 DB 상에서의 id 값을 알게끔 하기 위해 id에 대한 setter을 열어두었습니다.

하지만 setter를 이런 식으로 사용하면, 프로젝트 규모가 커질수록 여기저기서 setter를 통해 값을 변경할 일이 있을 때, 변경하는 코드 부분에서 그걸 왜 setter로 값을 바꿔버리는지 그 의도를 한 눈에 파악하기가 어렵다는 단점이 있는 것 같습니다.

그래서 단순히 setId 보다는, setProductIdFromDatabase 같이 값 변경 의도를 메소드명에 담아내는게 좋을 것 같아 리팩토링해보려고 했는데 이 경우 update와 delete 로직이 정상적으로 수행이 되질 않았고, 그 이유를 아직 파악하지 못한 상태라서 일단은 setId로 명명을 해두었습니다.

추가적으로, id 외의 name, price, imageUrl의 setter를 열어둔 이유는, post 요청의 body를 Product형 인수에 바인딩할 때 setter가 필요하다고 하여 열어두었습니다.

setter를 사용하지 않는 방법을 찾아보니 @RequestBody를 명시하면 된다고 하는데, 이 경우에는 application/x-www-form-urlencoded를 스프링이 이해하지 못하여 에러가 발생하였습니다.

다른 해결책으로 ObjectMapper를 사용하는 방법을 보았는데, 추가적으로 사용해야하는 라이브러리가 있으며 로직도 복잡하기도 하고, setter를 열어두었을 때가 훨씬 간단한 것 같아서, 이 점이 setter의 장점인 것 같다고 판단이 되어서 구현할 때 setter를 열어두는 방식을 채택하게 되었습니다.

2024-06-29 06:47 UTC, minsu-cnu commented on src/main/java/gift/product/repository/ProductRepository.java
> +        }, keyHolder);
말씀 주신 방법으로 구현했을 때는 DB에서 auto increment로 설정되는 id 값이 product 객체에 설정이 되지 않아서, 클라이언트에게 응답 product 객체에 DB 상의 id 값을 포함한다는 로직에 차질이 생길 것으로 예상이 되었습니다.

위와 같은 이유로 KeyHolder를 통해 DB 상에서 저장된 id 값을 가져와 product에 setting하는 과정에서 createPreparedStatement를 사용하게 되었습니다!

2024-06-30 13:35 UTC, jjongwa commented on src/main/java/gift/product/controller/AdminController.java
> +    }
정리 잘 해 주셨어요! 💯
한가지 덧붙이자면, 클래스의 생성자가 하나일 때는 `@Autowired` 를 생략해도 정상적으로 주입이 됩니다!

2024-06-30 13:50 UTC, jjongwa commented on src/main/java/gift/product/controller/AdminController.java
> +        return "redirect:/admin/products";
현재 작성된 대로 update에서 Product 자체를 input으로 받아 처리하고, pathVariable을 사용하지 않는다면 이러한 문제가 발생할 수 있을 것 같아요!

요청:[POST] /admin/products/update/1

input으로 들어온 Product 정보:
```
Product {
     id: 2
    name: 상품2
    price: 15,000
    imageUrl: urlurlurl
}
```

url만 보았을 때는 id가 1번인 상품에 대해 update 요청을 날린 것으로 보이지만, 실제로는 id가 2번인 상품의 정보가 바뀌게 되는데요,
이를 방지하는 방식은 크게 두 가지가 있을 것 같네요..!
1. pathVariable에 들어온 id값과 Product의 id값을 비교해 다르면 예외 처리
2. Product 객체를 input으로 받지 않고 필드에 id가 없는 dto의 형태로 받아 처리

ProductController에서의 updateProduct는 2번의 방식을 사용하셨는데, 관리자가 요청을 보낼 때에도 실수할 수 있는 가능성은 여전히 있다고 생각합니다~!

2024-06-30 13:50 UTC, jjongwa commented on src/main/java/gift/product/dto/ProductDTO.java
> +}
👍 👍

2024-06-30 14:10 UTC, jjongwa commented on src/main/java/gift/product/model/Product.java
> +    }
우선 다음과 같은 방식으로 바꾼다면 setId를 쓰지 않아도 될 것 같네요.! (그냥 여러 가지 방법 중 예시입니다.!)


```
public Product insertProduct(ProductDTO productDTO) {
        Product product = new Product(productDTO.name(), productDTO.price(), productDTO.imageUrl());
        return productRepository.save(product);
    }
```

```
public Product save(Product product) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        var sql = "INSERT INTO Product (name, price, imageUrl) VALUES (?, ?, ?)";
       
        ...

        return new Product(
                keyHolder.getKey().longValue(),
                product.getName(),
                product.getPrice(),
                product.getImageUrl()
        );
    }
```

그리고, post 요청의 body를 product로 받아야 하기 위해 Product의 setter를 열어주어야 한다면 
저는 아예 body를 product로 받지 않는 방법도 선택해 볼 수 있을 것 같아요!

이 부분은 현재 미션에서 얘기해 보기엔 조금 길어질 것 같아, 객체지향 관련 키워드로 조금 더 공부해 보시는 걸 추천드려요~!

2024-06-30 14:12 UTC, jjongwa approved these changes
리뷰 반영 잘 해주셨어요~!
1주차 미션 요구사항은 잘 지켜주신 것 같아 이번 주차 미션은 이만 approve 하겠습니다~!

2024-06-30 14:13 UTC, merged