전남대 BE_이현기_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #75
Opened 2024-06-26 12:22 UTC by geist9110

### 느낀점
관리자 화면을 thymeleaf로 구현하고자 하니, 상당히 까다로운 부분이 많았습니다. 특히 html 코드가 길어질수록 관리가 힘들어 좋은 코드를 만들진 못해 아쉽습니다. 항상 springboot를 쓰면 JPA로 db를 연결했는데 이번 기회에 JDBC를 직접 사용하여 sql query문으로 db를 관리해보니 다음에는 최적화까지 시켜서 작성할 수 있을것만 같은 자신감이 듭니다.

### 궁금한 점
- Product 객체에 id값이 들어있고, ProductRepository 클래스의 productsMap 인스턴스도 Map을 통해 id값을 중복으로 가지고 있습니다. 그렇다고 Product 객체에 id 변수를 빼버리면 get, post, patch, delete 메서드의 복잡도가 많이 증가할거 같습니다. 이러한 상황에서 어떤 부분을 고려하면 코드의 복잡도도 낮추고, 메모리의 낭비도 줄일 수 있을지 알고 싶습니다.

- 이번에 관리자 페이지를 만들면서 느낀건데, 리다이렉션을 어디서 해주어야 하는건지 감이 잘 안잡힙니다. 예를 들어, 특정 API를 실행후 페이지를 다른 페이지로 보내고 싶다면 이걸 프론트의 코드에서 API를 추가적으로 백엔드로 요청을 보내어 해결하는 것이 이상적인지, 아니면 애초에 백엔드에서 API로직이 끝나면 자동으로 리다이렉션을 시켜야하는건지 잘 모르겠습니다.

2024-06-28 17:48 UTC, soominsohn requested changes
안녕하세요 현기님! 리뷰어 앤지입니다. 만나서 반가워요!
전체적으로 잘 작성해 주셨군요 👍 
작성해주신 코드에 대한 질문과
반영해주셨으면 좋은 부분들에 대해 리뷰 남겼습니다.
리뷰 보시고 편하게 답변 달아주세요!
___
**궁금한점 답변**
1. jdbc를 적용하시기 전에 Map을 통해 자료를 관리하셨네요. Map은 데이터를 저장하는 자료구조일 뿐이지, 자료구조 때문에 Product 객체의 식별 값을 뺄 이유는 없다고 생각합니다. 

2. 리다이렉션 위치
    1. Model을 사용하는 경우 
        1. 서버에서 리다이렉션 처리를 하면 좋습니다.
        2. 현기님 코드에서는 생성/수정/삭제 로직 모두 RestController에서 이루어지기 때문에 딱히 사용할 일이 없을 것 같네요!
    2. RestController로 API 응답을 반환하는 경우
        1. 프론트엔드에서 리다이렉션 처리를 하면 좋습니다.
        2. 서버에서 add/update/delete 처리를 하고 응답을 받으면, 클라이언트에서 리다이렉션 처리를 해줍니다.
        3. 이미 현기님은 productAPI.js 에서 리다이렉션 처리를 해주고 잘 해주시고 계시네요!

2024-06-28 17:48 UTC, soominsohn commented on src/main/java/gift/AdminPageController.java
> +    }
Pagination 처리를 해주셨군요! 좋은 시도입니다.
왜 이번 미션에서 이 처리를 사용하셨고, 현기님이 생각하시는 Pagination의 장점이 무엇인가요?

Pagination을 사용하는 이유와 함께 `org.springframework.data.domain`의 @PageableDefault 어노테이션과 Pagable 인터페스를 공부해보면 조금 더 깔끔하게 처리를 할 수 있을거에요. 
이번 미션 목표에서는 Pagination을 다루지 않고 있기 때문에 굳이 반영하지 않으셔도 됩니다.

2024-07-01 05:53 UTC, geist9110 commented on src/main/java/gift/ProductController.java
- 둘은 어디에 데이터를 실어서 보낼지가 가장 큰 차이점이라 생각합니다. `@RequestBody` 는 HTTP 요청의 Body 부분에 데이터를 실어서 보낸다면, `@RequestParam` 은 HTTP 요청의 URI 부분에 데이터를 실어서 보냅니다.
- `@RequestBody` 에서 `@RequestParam` 으로 변경한 이유는 스프링에서 만큼은 정규 과정에서 배운것만을 써보자는 의미에서 다시 변경한 것입니다. 제 생각에 위 상황에서는 Product 객체 하나를 중심으로 움직이기에 `@RequestBody` 가 더 적합한 어노테이션이라 생각합니다. 하지만, 아직 강사님께서 수업시간에 알려주시지 않으셔서 최대한 배제하고자 하는 의미에서 `@RequestParam` 으로 다시 변경했습니다.

2024-07-01 05:54 UTC, geist9110 commented on src/main/java/gift/ProductController.java
> +
의존성 주입 방법에는 생성자 주입, 필드 주입, 수정자 주입 3가지가 있습니다. 생성자 주입을 사용한 이유는 제일 큰 이유는 순환 참조 방지랑 불변성 보장입니다. 지금은 단 하나의 레포지토리만을 의존성 주입을 하지만, 몇 주 뒤에는 얼마나 많은 객체들이 서로 얽히고 얽힐지 모릅니다. 이렇게 되면 필드 주입, 수정자 주입같은 경우에는 디버깅을 하는데 왜 문제가 생겼는지 찾는데 시간이 오래걸립니다. 하지만 생성자 주입같은 경우 빌드시 이를 바로 확인할 수 있어 디버깅을 하는데 수고를 줄일 수 있을거라 판단해 생성자 주입을 사용했습니다.

2024-07-01 05:55 UTC, geist9110 commented on src/main/java/gift/ProductController.java
> +
PUT의 경우 객체가 존재하지 않아도 새로 생성할 수 있는 반면, PATCH는 객체가 존재하지 않는 경우에는 에러를 발생시킵니다. 위에서 PUT을 사용하게 되면 사실상 객체를 업데이트하는 기능에 객체를 추가하는 기능까지 포함됩니다. 그렇게 되면 하나의 메서드가 두가지 역할을 가질뿐만 아니라, addProduct라는 객체를 추가하는 메서드의 역할까지 침범한다 생각해서 PATCH를 사용했습니다.

2024-07-01 05:56 UTC, geist9110 commented on src/main/java/gift/ProductController.java
> +    }
둘 다 URI를 통해 값을 받아오는 역할은 같지만, `/admin/{id}` 와 같이 계층을 나누어 받는것과 `/admin?id=1` 와 같이 동일한 계층에서 받는지의 차이가 있다 생각합니다. `@PathVariable` 어노테이션은 view를 사용할때 쓰는것이 더 적합하다 생각해 `@RequestParam` 을 사용했습니다. 하지만, 다시 보니 products 안의 id라는 고유한 값으로 들어가는 것이니 `@PathVariable` 이 더 적합한거 같습니다.

2024-07-01 06:00 UTC, geist9110 commented on src/main/java/gift/ProductRepository.java
> +    }
모든 API를 통해 변경이 이루어지는 부분에 대해서 변경후 값을 반환하여 일관성을 유지하고자 하는 목적으로 사용했습니다. 하지만, 현재 사용하지 않는 값을 반환하여 오히려 가독성이 낮아질 수 있어 반환 값이 필요없어 보입니다.

2024-07-01 06:03 UTC, geist9110 commented on src/main/java/gift/ProductRepository.java
> +        return null;
Delete와 마찬가지로 모든 API가 일관되게 값을 반환하고자 하는 의미에서 사용했습니다.
클라이언트 사이드 렌더링이면 이 부분이 성능 개선에 도움을 줄 수 있다 생각하는데, 현재 서버사이드 렌더링을 사용하기에 이 부분도 필요가 없을거 같습니다.

2024-07-01 06:16 UTC, geist9110 commented on src/test/java/gift/selenium/AddPageTest.java
> +}
1. e2e 테스트는 End-to-End 테스트로, 애플리케이션의 흐름을 처음부터 끝까지 테스트하는 것입니다.
2. API만 제공하게 된다면, RestController에 값이 들어가는 것 부터 레포지토리에 값이 변경되는것까지 확인하는 하나의 흐름으로 테스트할 수 있을거 같습니다. 하지만, 이렇게되면 Intergration 테스트와의 차이를 잘 모르겠습니다.

2024-07-01 06:16 UTC, geist9110 commented on src/main/java/gift/ProductRepository.java
> +        return null;
추가적으로, null을 반환하게 되면 비어있는 객체가 넘어가 추후에 알 수 없는 문제가 생길 요소로 보입니다. 이 부분은 예외처리를 통하여 문제를 해결하도록 하겠습니다.

2024-07-01 10:01 UTC, soominsohn approved these changes
안녕하세요 현기님! 피드백 잘 봤습니다.
정말 많은 학습을 해주셨군요!

현기님이 작성해주신 코드에서 어떤 사고의 흐름으로 작성하게 되었는지 궁금해서 드린 질문과, 꼭 알고 가셨으면 하는 부분들에 대해 질문드렸어요.
답변해주셔서 고맙습니다.

첫 미션이었는데 정말 잘 해주셨어요! 이번 미션은 여기서 머지할게요!
다음 미션도 기대하고 있겠습니다+_+! 파이팅이에요!

2024-07-01 10:01 UTC, soominsohn commented on src/test/java/gift/selenium/AddPageTest.java
> +}
네 맞아요 잘 설명해주셨습니다. 💯 
현기님이 말씀해주신대로 E2E 테스트는 애플리케이션의 흐름을 처음부터 끝까지 테스트 하는 것입니다.

이번 미션에서는 어드민 페이지(프론트)가 있어 selenium을 이용한 테스트가 가능했지만, 다음 미션부터는 API만 작성하는 걸로 알고 있어요. 만약 이런 환경에서 어떻게 테스트 하실지 궁금해 질문드렸습니다.

API의 E2E 테스트도 역시 애플리케이션의 흐름을 처음부터 끝까지 테스트 하는 것으로, 여기선 사용자의 입력으로부터 응답이 제대로 오는지 테스트하는 것입니다.
또 질문주신 Integration 테스트는 주로 모듈간의 상호작용을 테스트하며, 이들이 함께 올바르게 동작하는지를 확인하는데 중점을 둡니다.

차이가 모호할 수 있지만, 무엇을 중점적으로 검증하냐에 따라 다릅니다.
앞으로 미션을 진행하면서 이러한 테스트의 차이를 염두에두고 작성해주시면 좋아요. :thumb

2024-07-01 10:01 UTC, merged