충남대 BE_이경빈_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #83
Opened 2024-06-26 16:00 UTC by cussle

1주차 과제(1단계) 제출합니다.

궁금한 점 몇 가지 질문 드립니다!

1. 프로그램 설계에 대해서 고민을 많이 했습니다. 자연스럽게 아키텍처 패턴을 어떤 걸 적용할지에 대한 고민으로 이어졌는데, 이번 과제는 Layered Pattern + MVC Pattern의 조합으로 진행했습니다. 아키텍처 패턴을 정하는 게 실제로 얼마나 중요한 건지, 정하는 방법 같은 게 있는지 궁금합니다.

2. 테스트 작성을 올바르게 한 게 맞는지 궁금합니다! MVC 패턴을 적용할 땐 Model 단위 테스트만 진행했는데, 이번엔 각 계층 별로 테스트를 진행했습니다.

3. 지난 Step1의 미니 과제에서도 else 예약어 사용을 금지했는데, 그러한 이유가 있는지 궁금합니다. 가독성이나 복잡도가 증가한다는 이유 외에도 다른 이유가 있는 걸까요?

2024-06-29 12:41 UTC, asebn1 requested changes
안녕하세요 경빈님~
6주간 코드리뷰어를 맡게된 공재호라고합니다. 잘부탁드려요.
코드를 보니 전반적으로 스프링에 대한 이해도가 높고
계층분리, dto사용, 에러처리, 추가기능구현까지 많이 고민하신 것 같아요
부족한 부분은 없으나 몇 가지 코멘트 드렸습니다.
리뷰 확인해주시고 궁금한 점 코멘트로 남겨주세요 (DM도 좋아요)

---

### Step1

> 1. 프로그램 설계에 대해서 고민을 많이 했습니다. 자연스럽게 아키텍처 패턴을 어떤 걸 적용할지에 대한 고민으로 이어졌는데, 이번 과제는 Layered Pattern + MVC Pattern의 조합으로 진행했습니다. 아키텍처 패턴을 정하는 게 실제로 얼마나 중요한 건지, 정하는 방법 같은 게 있는지 궁금합니다.

초기 설계에서 장기적으로의 시스템 확장성까지 고려하는 게 중요하다고 생각해요. 잘못된 패턴으로 발생할 수 있는 비용이 생각보다 큽니다. 유지보수, 테스트할 때 매우 중요하다고 느껴요. 정하는 방법은 팀에서 개발자들이 선호하는 방식을 선택합니다. (신규 개발이 아니라면 대부분 레거시코드일거에요ㅎㅎ)

> 2. 테스트 작성을 올바르게 한 게 맞는지 궁금합니다! MVC 패턴을 적용할 땐 Model 단위 테스트만 진행했는데, 이번엔 각 계층 별로 테스트를 진행했습니다.

잘 작성하신 것 같습니다. `@DisplayName`을 붙여서 설명을 작성할 수 있을 것 같아요.

> 3. 지난 Step1의 미니 과제에서도 else 예약어 사용을 금지했는데, 그러한 이유가 있는지 궁금합니다. 가독성이나 복잡도가 증가한다는 이유 외에도 다른 이유가 있는 걸까요?

if 조건을 만족하지않는 나머지 모두를 의미해서 오류 발생확률이 더 크다고 생각해요.

---

### Step2

> 1. 스프링부트로 웹을 개발할 때 Thymeleaf를 사용하는 게 가장 일반적인지 궁금합니다!

일반적으로 프론트 영역은 프론트엔드 개발자가 개발합니다. admin같은 부분은 백엔드 개발자가 하는 경우가 꽤 있는데 팀바팀인 것 같아요~

> 2. 페이지를 메인(R, D), edit(U), form(update) 세 개로 구성했는데, 간단한 기능을 가진 웹의 경우 하나의 페이지로 합치는 게 좋은가요? 항상 웹을 할 때 가지는 의문이었는데, 페이지 개수를 최대한 줄이는 게 좋은지, 최대한 잘게 쪼개는 게 좋은지 궁금합니다! 지금 과제의 경우 모달 창이나 자바스크립트를 통해 HTML element를 동적으로 변화시키면 하나로도 충분할 것 같은데, 어떤게 좋은 선택일까요?

요구사항이나 사용자경험(UX)에 따라 다를 것 같아요. 사용자 경험을 향상시킬 수 있는 방향이라 느낀다면 변경해도 좋다고 생각해요.

> 3. 지금의 방식처럼 form action 으로 데이터를 받아오는 방식과, AJAX를 이용해 비동기적으로 데이터를 받아오는 방식 둘 중 어떤 게 더 일반적으로 사용되는지(선호되는지) 알고싶습니다! 평소엔 항상 AJAX만 이용하다가, 이번 과제를 할 때 form 전송 방식을 사용했는데, 이 방식이 더 간단하고 직관적으로 보이는 것 같았습니다.

백엔드 개발자가 프론트를 하는 일은 보통 admin 관련 작업인데 이는 너무 팀바팀이라 팀의 개발자들이 어떤 언어를 선호하는지에 따라 다를 것 같아요. 제가 경험한 팀에선 후자인 것 같아요.

---

### Step3

> 첫 단계부터 가장 고민한 게 아키텍처 패턴인데, 최종적으로 완성한 코드가 패턴을 준수하고 있는지 확인받고 싶습니다.

기본적인 레이어드 아키텍처를 준수하도록 잘 구현하신 것 같아요. 아래 코멘트 확인해주세요!

> 저장 로직을 데이터베이스로 변경함에 따라 테스트도 수정하였는데, mock을 이용한 테스트 코드를 작성했습니다. step1때도 잘 이해하지 못한 상태로 코드를 작성했는데, 단위 테스트에 Mockito가 자주 사용되는지 궁금합니다!

네~ 작성해주신 것처럼 mock을 사용해 모킹테스트를 작성하는 경우가 많습니다.

추가로 궁금한 내용 있으면 말씀해주세요!

2024-06-29 12:41 UTC, asebn1 commented on src/main/java/gift/repository/ProductRepository.java
> +    }
`save`를 통해 id값에 따라 저장, 업데이트 기능을 사용하고있네요.
기능을 분리할 수 없을까요?

2024-06-29 12:41 UTC, asebn1 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    private ProductRepository productRepository;
테스트를 잘 작성해주셨네요! 💯

2024-06-29 12:41 UTC, asebn1 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +import static org.mockito.Mockito.*;
현재 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)를 기반으로 하고 있습니다.
No wildcard imports 부분 참고해주세요~

2024-07-01 07:04 UTC, cussle commented on src/main/java/gift/controller/AdminController.java
> +    }
"의존성 주입" 개념 자체가 모호하게 느껴져서 이번에 다시 공부해봤습니다!

**의존성 주입**(Dependency Injection): 소프트웨어 디자인 패턴 중 하나로, 객체의 생성과 객체 간의 의존성을 처리하는 방식이며, 코드의 결합도를 낮추고 유연성을 높일 수 있다.

#### 의존성 주입 방법
1. 생성자 주입(Constructor Injection)
	- 의존성을 생성자의 매개변수로 전달받아 주입
	- 객체가 생성될 때 필요한 의존성을 모두 주입받기 때문에, 객체가 완전한 상태로 만들어짐
	- 장점
		- 의존성 주입이 객체 생성 시점에서 완료되므로, 불변성을 보장
		- 주입받는 객체가 반드시 필요하다는 것을 명확히 할 수 있음
		- 테스트가 용이
	- 단점
		- 의존성이 많아질 경우 생성자의 인자가 많아짐

2. Setter 주입 (Setter Injection)
	- Setter 메서드를 통해 의존성을 주입
	- 장점
		- 의존성을 선택적으로 주입할 수 있어, 필요에 따라 의존성을 변경하거나 교체하기 용이
		- 테스트가 용이
	- 단점
		- 객체가 불완전한 상태로 존재할 수 있기 때문에, 필수 의존성 주입 여부를 보장하기 어려움

3. 필드 주입 (Field Injection)
	- 필드에 직접 `@Autowired` 애너테이션을 사용하여 의존성을 주입
	- 장점
		- 간단하고 코드가 간결해짐
	- 단점
		- 의존성 주입이 필드에 직접적으로 이루어지기에, 테스트하기 어려움
		- 순환 의존성 문제 발생 가능
		- Java Reflection API를 사용하기 때문에 스프링 외의 프레임워크에서는 사용할 수 없음

각각의 장단점이 존재하는 것을 보고 상황에 따라 선택하여 사용하면 될 줄 알았는데, 다음의 이유로 생성자 주입 방식이 권장된다는 점도 새롭게 알게되었습니다.

1. 객체의 불변성 확보
	- 의존 관계의 변경이 필요한 상황은 거의 없음

2. 테스트 코드의 작성

3. 스프링에 비침투적인 코드 작성

4. 순환 참조 에러 방지
	- 객체의 생성 시점에 순환 참조 에러를 예방할 수 있음

스프링 외의 프레임워크는 다뤄본 적이 없어서 2번과 3번은 잘 와닿진 않지만, 이정도로 이해했습니다!

2024-07-01 07:07 UTC, cussle commented on src/main/java/gift/controller/AdminController.java
> +        model.addAttribute("product", product);
`product` 변수를 `productDTO`로 변경하여 더 명확하게 DTO 객체임을 나타내도록 수정하겠습니다!

2024-07-01 07:18 UTC, cussle commented on src/main/java/gift/controller/AdminController.java
> +    }
수정의 경우 PUT을, 삭제의 경우 DELETE를 사용하는 게 더 적절하다고 생각합니다.

다만 현재 products.html에서 form을 이용한 통신을 하고 있는데, `GET`과 `POST` 요청만 직접적으로 보낼 수 있다고 알고 있었습니다.

조금 알아보니, HTTP Method Override를 통해 이 외의 요청도 보낼 수 있다는 것을 알게 되었습니다.

``` Java
<form th:action="@{'/admin/products/' + ${product.id}}" method="post" style="display:inline">
  <input type="hidden" name="_method" value="put">
  <button type="submit">수정</button>
</form>

<form th:action="@{'/admin/products/' + ${product.id}}" method="post" style="display:inline">
  <input type="hidden" name="_method" value="delete">
  <button type="submit">삭제</button>
</form>
```

```
    @PutMapping("/{id}")
    public String updateProduct(@PathVariable("id") Long id, @ModelAttribute ProductDTO productDTO) {
        productService.updateProduct(id, productDTO);
        return "redirect:/admin/products";
    }

    @DeleteMapping("/{id}")
    public String deleteProduct(@PathVariable("id") Long id) {
        productService.deleteProduct(id);
        return "redirect:/admin/products";
    }
```

간단히 적용해보았는데, 이런식으로 변경하라는 말씀이실까요..?!

2024-07-01 12:25 UTC, cussle commented on src/main/java/gift/controller/ProductController.java
> +    }
`ApiExceptionHandler`라는 클래스를 만들어서 모든 예외 처리를 중앙에서 관리하도록 수정하였습니다.

금일 라이브 클론코딩 강의에서 배운 `@ControllerAdvice`를 활용하였습니다!

2024-07-01 13:14 UTC, cussle commented on src/main/java/gift/service/ProductService.java
> +    }
링크해주신 글 잘 읽었습니다! 기존엔 `ProductService`에서 변환해주는 메서드를 위치시켰는데, 리팩토링 과정에서 `util`패키지로 분리했습니다.

말씀을 들어보니 특정 도메인 `Product`에 강하게 결합된 `ProductMapper` 클래스를 프로젝트 전반에서 사용되는(도메인에 무관한) 유틸리티 크래스를 담는 `util` 패키지로 이동시킨 것이 어색한 것 같습니다.

기존 코드처럼 다시 `ProductService`로 변환 메서드를 이동시키겠습니다!

2024-07-01 13:18 UTC, cussle commented on src/main/java/gift/model/Product.java
> +    private String imageURL;
`ProductDTO` 에서는 `imageUrl`을, `Product` 및 `ProductRepository` 에서는 `imageURL`을 사용하고 있어서, 모두 `imageUrl`로 수정하였습니다!

2024-07-01 13:34 UTC, cussle commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +import static org.mockito.Mockito.*;
`ProductServiceTest` 클래스와 `ProductRepositoryTest` 클래스에서 와일드카드 임포트를 사용하지 않고 필요한 클래스만 임포트하도록 수정하였습니다.

2024-07-01 13:41 UTC, cussle commented
@asebn1 리뷰해주신 사항 잘 확인했습니다!! 꼼꼼하게 확인해주셔서 감사합니다. 링크해주신 글들이 정말 많이 도움되었어요!

수정 제안해주신 사항을 바탕으로 전체적으로 리팩토링 후 다시 커밋하였습니다. 다만 HTTP Method 관련, 객체지향 생활체조 원칙 9번 제한사항과 관련하여 추가적인 질문이 있어 남겨두었습니다.

답변 달아주시면 정말 감사하겠습니다! :)

2024-07-01 14:01 UTC, asebn1 commented on src/main/java/gift/controller/AdminController.java
> +    }
`@PutMapping`, `@DeleteMapping`로 잘 구현해주셨군요!
HTML 폼을 사용하면 GET과 POST 요청만 보낼 수 있어서 개인적으로 선호하는 방식은 아니에요. 
해당 HTTP Method를 제공하는 ajax를 사용해보는 것도 방법이 될 수 있을 것 같아요

2024-07-01 14:12 UTC, asebn1 commented on src/main/java/gift/model/Product.java
> +    }
setter가 개선되었군요 👍 
getter도 제거할 수 있겠지만 JPA를 사용하지 않는 시점에서 제거하는게 오히려 더 과한 리팩토링이 될 수 있겠다는 생각이 드네요.
이부분은 JPA가 적용되면 다시 고민해봅시다 🔥🔥

2024-07-01 14:15 UTC, asebn1 approved these changes
경빈님 첫 주차부터 열심히 노력하신 흔적이 많이 보이네요!!
열심히 성장하시는게 보여 뿌듯합니다 ㅎㅎ 말씀주신 내용을 코멘트로 남겨두었어요
이번 미션은 이만 머지할게요
다음 미션도 화이팅!!

2024-07-01 14:15 UTC, merged