강원대 BE_김송목_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #90
Opened 2024-06-27 03:43 UTC by kimsongmok

책도 찾아보고 구글링도 많이해서 얻어낸 결과물입니다. 그래서 사실 코드가 말끔하지 않을 수 있으며, 제대로 된 코드인지도 잘 모르겠습니다. 아직 많이 배워야될 것 같습니다. 아직 제 지식이 아닌것 같습니다.
더 열심히 배워서 2단계를 더 잘해보겠습니다.

2024-06-27 14:58 UTC, kimsongmok commented
3단계 까지 완료했습니다

2024-06-27 15:18 UTC, kimsongmok commented
데이터베이스 연동안되는현상 고쳤습니다

2024-06-28 13:22 UTC, jaymarystella requested changes
안녕하세요 송목님.
리뷰어 제이입니다. 만나서 반갑습니다.
첫번쨰 미션 구현하느라 고생많으셨어요.
몇가지 코멘트 남겨두었는데 확인해보시고 반영부탁드려요.
특별히 받고싶은 코멘트 있으시면 말씀주세요.

2024-06-28 13:22 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    return ResponseEntity.status(201).body(productService.save(product));
숫자명시하지않고 만들 수 있을까요?

2024-06-28 13:22 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    return ResponseEntity.noContent().build();
> 책도 찾아보고 구글링도 많이해서 얻어낸 결과물입니다. 그래서 사실 코드가 말끔하지 않을 수 있으며, 제대로 된 코드인지도 잘 모르겠습니다. 아직 많이 배워야될 것 같습니다. 아직 제 지식이 아닌것 같습니다.

고생많이하셨습니다. 하나씩 수정해보면서 어려운점 있으시면 말씀주세요. 어느부분에서 그렇게 느끼셨을까요? 
현재의 지식상태를 알려주시면 같이 이야기하는데 도움이 될거같아요.

2024-06-30 12:43 UTC, jaymarystella commented
PR target branch 를 본인의 branch로 수정해서 요청주세요. Merge를 할 수 없는 상태입니다.

2024-06-30 16:33 UTC, kimsongmok commented on src/main/java/gift/controller/ProductController.java
> +    return ResponseEntity.noContent().build();
제가 많이 부족한 것 같습니다... 일단 책, 구글과 지피티가 없으면 코드도 제대로 못짜는 스프링 초보라서 아무것도 제대로 못짯습니다.. 공부는 하고있는데 솔직히 제가느끼기엔 과제 수준이 처음 배우는 초보한테 적절한 수준은 아니였던 것 같습니다.
또, 강사님이 추천해주신 책으로 공부하고 있는데 거기에선 롬복을 쓰라고 되어있는데, 강사님은 롬복을 쓰지 말라 하셔서 혼란이 옵니다.
1주차때도 이런데 2, 3주차는 얼마나 뒤쳐질까요??
리뷰어님 정말 감사합니다. 일단 다 고쳐 보겠습니다.

2024-06-30 16:33 UTC, kimsongmok commented on src/main/java/gift/controller/ProductViewController.java
> +    model.addAttribute("products", productService.findAll());
넵 한번 확인해 보겠습니다

2024-06-30 16:34 UTC, kimsongmok commented on src/main/java/gift/model/Product.java
> +  // Getters and Setters
아 구글에서 가져오다가 그렇게 된것 같습니다. 수정하겠습니다.

2024-06-30 16:34 UTC, kimsongmok commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
책에 쓰여있는 내용과 인터넷 내용을 참고해서 자세히는 몰랐습니다. 다시 공부해보겠습니다.

2024-06-30 16:38 UTC, kimsongmok commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
옵션에서 혹시 이상한 부분이 있을까요..?? 제대로 공부해보고 싶습니다.

2024-07-01 14:51 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    return ResponseEntity.noContent().build();
네 일단은 롬복은 신경쓰지 마세요. 어차피 롬복은 스프링이랑 상관없습니다. 
그리고 공부하면 되니 뒤쳐진다고 생각하지마세요. 다 할 수 있어요. 어려운점 있으면 DM주셔도됩니다.

2024-07-01 14:52 UTC, jaymarystella commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
이상한 부분이라기보다 spring.jpa.hibernate.ddl-auto 요 옵션이 어떤것들이 있는지 찾아보고 학습해보시면 좋을거같아요. 
지금 스프링도 처음인데 jpa까지 하려니 막막하실거같기도해요. 일단 우선순위를 정해드리면 jpa보다는 스프링과 sql쪽을 먼저 학습하시는걸 추천드립니다.

2024-07-02 05:38 UTC, closed without merging