경북대 BE_정수현_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #91
Opened 2024-06-27 04:35 UTC by suhyeon7497

1. 원래 GetMapping할 때, product가 존재하지 않으면 return null을 하게 하려 했었는데, 들어보니 null을 반환하는 것은 좋지 못한 것이라고 들었는데, 어떻게 반환하면 좋을지 궁금합니다.

2. id는 {id:[1-9][0-9]*} regex로 표현이 가능한데 다르게 들어오는 경우는 필터링 되게 하는 것이 올바를까요?

2024-06-30 08:54 UTC, sang5c requested changes
안녕하세요 수현님! 리뷰를 맡은 박상오입니다. 잘 부탁드려요! 💪  

컨벤션이 제대로 지켜지지 않아서 Request change를 드립니다. 확인해보시고 수정해주세요!

질문에 대해 답변을 드리면 

> 원래 GetMapping할 때, product가 존재하지 않으면 return null을 하게 하려 했었는데, 들어보니 null을 반환하는 것은 좋지 못한 것이라고 들었는데, 어떻게 반환하면 좋을지 궁금합니다.

이 부분은 차주에 배울 내용이니 수업 듣고 이해가 안가시면 다시 질문해주세요!

> id는 {id:[1-9][0-9]*} regex로 표현이 가능한데 다르게 들어오는 경우는 필터링 되게 하는 것이 올바를까요?  

해당 값을 사용해서 시스템에 치명적인 작업을 한다면 당연히 검사해야 합니다.  
저는 현재 상황에서는 `하면 좋으나, 굳이 안해도 된다`는 입장입니다. id가 Long 타입인 경우 기본적으로 정수를 받게 되고, 0이하의 정수는 클라이언트의 실수로도 전달하기 힘든 값이기에 정규식으로 검사하는 효과가 미미하다고 생각해요.  
대신 값을 받은 후 사용하는 과정에서 허용하는 값을 받은게 맞는지 확인할 필요는 있습니다.

2024-06-30 08:54 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("")
path가 비어있는 경우 생략 가능합니다 :) 

```suggestion
    @GetMapping
```

2024-06-30 08:54 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +    @PostMapping()
소괄호 생략이 가능합니다 :) 

```suggestion
    @PostMapping
```

2024-06-30 08:54 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +        if(!products.containsKey(id)){
띄어쓰기가 제대로 수행되지 않았네요. 전체 코드를 대상으로 자동 정렬을 수행해주세요!  
동일한 다른 부분에 대해서는 리뷰를 추가하지 않았습니다.

2024-06-30 08:54 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +            return null;
null 대신 어떻게 하면 좋을지는 다음 수업에서 배울 예정입니다. 수업 듣고 과제 진행해보신 다음 질문 주시면 다시 답변 드릴게요!

2024-06-30 08:54 UTC, sang5c commented on src/main/java/gift/controller/ProductController.java
> +            System.out.println("{%d}에 매칭되는 Product가 이미 존재하지 않습니다.".formatted(id));
System.out.printf()를 사용하는 방법도 있습니다. 참고만 해주세요~
```suggestion
            System.out.printf("{%d}에 매칭되는 Product가 이미 존재하지 않습니다.%n", id);
```  


한 가지 더 팁을 드리면 System.out.println()을 사용해서 출력하는 형태는 안티 패턴인데요,  
만약 처음 접하는 개념이라면 무시해도 좋습니다 :)   

Logger를 사용해서 로그를 출력하면 기본 포맷(날짜, 시간 등 필요한 추가 정보)부터 로그 레벨 제어, 성능 향상을 얻을 수 있습니다.  


```java
    private static final Logger log = LoggerFactory.getLogger(ProductController.class);

    // 생략
    public ResponseEntity<Product> getProductById(@PathVariable Long id) {
           // ...
          log.info("hello world!");
    }
```

<img width="1508" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/28697758/b98d7873-a6b5-4827-bd08-9b571afa4761">

2024-06-30 08:54 UTC, sang5c commented on src/main/resources/application.properties
> +spring.application.name=spring-gift
<img width="76" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/assets/28697758/f44eb002-5d43-4a8b-a951-9a92ee11c58f">

위 이미지의 빨간 표시는 no newline at a end of file 경고입니다.
프로그램 실행에 있어서 잠재적인 문제점을 경고해주는걸 무시하지 않아야 한다고 생각해요.
아래 글을 참고해서 수정해보시면 좋을 것 같습니다.
https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/

2024-07-01 05:51 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("")
넵!

2024-07-01 05:51 UTC, suhyeon7497 commented on src/main/java/gift/controller/ProductController.java
> +    @PostMapping()
넵!

2024-07-01 06:08 UTC, suhyeon7497 commented on src/main/resources/application.properties
> +spring.application.name=spring-gift
넵 고치겠습니다!

2024-07-01 13:25 UTC, closed without merging

2024-07-01 13:25 UTC, sang5c commented
3단계에서 통합 머지하기 위해 close합니다.