전남대 BE_김수랑_1주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #94
Opened 2024-06-27 05:21 UTC by rdme0

1. ProductModel 객체를 이대로 두는 것이 좋을지 아니면 ProductModel의 책임이 너무 무거워서 ProductService 객체로 분리해야 할지 궁금합니다.

2. ProductModel의 ArrayList에 접근하는 모든 메소드에 synchronized 키워드를 추가했는데 이렇게 구현하면 모델이 완벽하게 thread safe 하게 되는건지, 그리고 이보다 성능을 더 높이면서 thread safe하게 할 수 있는 다른 방법이 있는지 궁금합니다.

2024-06-30 03:54 UTC, Hongdonggeon requested changes

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/controller/ProductController.java
> +    private final String WELL_DONE_MESSAGE = "Success";
보통 이런 상수를 선언할때는 static 변수로 선언하는데요! 이 이유에 대해 찾아보시면 좋을 것 같아요!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/api")
모든 api들이 `/api/products` 까지는 공통인 것 같아서 `RequestMapping`에 경로를 `/api/products` 로 가져가도 될 것 같아요

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<ResponseDTO> addProduct(@RequestBody @Valid ProductDTO productDTO) {
validation 까지 구현해주셨네요 👍

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/controller/ProductController.java
> +        return new ResponseEntity<>(new ResponseDTO(false, WELL_DONE_MESSAGE), HttpStatus.OK);
이건 참고차 드리는 리뷰예요. 정해진 건 없지만 Http Method Delete 성공 응답코드로 204 No Content를 많이 사용하기도 한답니다!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductService.java
> +            throws RuntimeException{ //C
필요없는 주석은 삭제해주세요!
생성자 주입 주석들도 없어도 될 것 같아요!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductService.java
> +            throw new InvalidIdException("id를 입력하지 말아주세요. 저희가 알아서 추가합니다.");
이 에러는 발생시킬 필요가 없다고 생각이 드는데요! id를 입력하는 창을 없애는게 사용자 측면에서 덜 헷갈릴 것 같아요!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/resources/static/js/getProducts.js
> +      window.location.href = '/api/products';
잘못 입력해서 상품 추가에 실패한 경우에는 조회 목록 창으로 안넘어가는게 사용자 입장에서 더 편할 것 같다고 생각이 들어요!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/resources/static/js/getProducts.js
> +      window.location.href = '/api/products';
수정도 상품 추가처럼 실패한 경우에는 조회 목록창으로 안넘어가는게 좋을 것 같아요!

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/exception/CustomException.java
> +}
지금 현재 커스텀 예외 클래스들 구조가 CustomException을 구현하고 RuntimeException들을 상속하고 있는데요.  구조를 이렇게 결정하신 이유가 궁금합니다! 

이 리뷰대로 반영하라는건 아니구요! 제 개인적인 생각에 대해 말씀드릴게요 :)
모든 커스텀 예외 클래스들의 구조가 같아서, CustomException이 RuntimeException을 상속하고 message 필드 + 생성자를 가지고 있고, 다른 커스텀 클래스들이 CustomException을 상속하는 구조면 어떨까 싶은데 어떻게 생각하실까요?

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
공통 예외까지 👍

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/dao/ProductDao.java
> +        return DriverManager.getConnection("jdbc:h2:mem:gift", "sa", "");
application.properties 에 있는 정보들인데요. 만약 수정한다면 properties와 이곳 둘다 수정하게 될거예요! 사용하는 곳이 더 많아진다면 관리하기 힘들어지겠죠!
`@Value` 나 `@ConfigurationProperties`와 같은 것들을 이용해서 application.properties의 정보들을 가져와서 사용할 수 있는데요! 이 방법을 적용해보는건 어떨까요?

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductService.java
> +            throw new NullContentException("입력 값에 빈 곳이 있습니다. 다시 제대로 입력해주세요");
이러한 검증은 서비스 계층보다 도메인에서 하는게 더 어울릴 것 같아요! 
현재는 도메인객체의 필드가 많지 않지만, 필드들이 많아지거나 서비스에서 사용하는 도메인 객체가 많아진다면, 서비스에서 해야하는 검증이 너무 많아질거예요

2024-06-30 03:54 UTC, Hongdonggeon commented on src/main/java/gift/domain/ProductDTO.java
> +public record ProductDTO(
도메인과 Dto를 같이 사용하고 있는데요. 같이 사용하고 있는 이유에 대해 궁금합니다 
도메인을 Dto까지 사용하게 되면 어떤 단점이 있는지 생각해보면 좋을 것 같아요 
- 도메인 vs Dto 의 차이 
- 도메인과 Dto를 분리해야하는 이유 
에 대해 공부해보면 좋을 것 같아요

2024-06-30 04:14 UTC, Hongdonggeon commented
## 과제 하면서 궁금한 점 - 답변 

1. ProductModel 객체를 이대로 두는 것이 좋을지 아니면 ProductModel의 책임이 너무 무거워서 ProductService 객체로 분리해야 할지 궁금합니다.
->일단 Step 3에서 Service와 Dao로 분리하게 되었지만, Step1 당시에는 분리하기가 좀 애매했던 느낌이라 아직 궁금증이 남아있습니다!
> 말씀하신 모델 객체가 Dto 객체들을 말씀하시는거죠? Dto 객체를 모델 객체라고 표현하신거라면, ProductModel 책임이 무겁다고 생각하신 이유가 궁금해요! 현재로서는 모델에서 해주는게 없다고 생각이 드는데요! 오히려 서비스의 책임이 너무 무겁다는 생각이 들어요.

저는 Step 1부터 쭉 Product를 가져올 때 java 컬렉션 프레임워크 중 Map이 아닌 ArrayList를 사용하였습니다. 저는 ArrayList가 Map보다 더 익숙해서 ArrayList를 고르게 되었지만 이게 올바른건지, 실무에서는 둘 중에 어떤 것을 고르는 경우가 많은지 궁금합니다.
> 실무에서는 둘다 사용해요! ArrayList와 Map은 데이터 구조가 아예 달라서 쓰임새도 다르죠. ArrayList는 배열형식이고 Map은 키쌍구조여서 데이터 형식이 배열이라면 ArrayList를 사용할테고 키쌍으로 저장해야한다면 Map을 사용할 것 같아요
ArrayList와 오히려 비교한다면 LinkedLIst가 비교 대상일 것 같아요

Step 1에서 ProductModel ArrayList에 접근하는 모든 메소드(CRUD)에 synchronized 키워드를 추가했는데 이렇게 구현하면 모델이 완벽하게 thread safe 하게 되는건지, 그리고 이보다 성능을 더 높이면서 thread safe하게 할 수 있는 다른 방법이 있는지 궁금합니다.
> synchronized 키워드를 이용한다면 멀티 스레드 환경에서 동시성이 해결되긴 할거예요. 하지만 synchronized를 과도하게 사용한다면, 성능도 저하가 되겠죠,, 이 요구사항에서 멀티 스레드 환경에 대해서 고려한다면, 수정하는 쪽에서만 synchronized 키워드를 사용해도 되지 않을까 싶어요. 
멀티 스레드 환경에서 고려해야할게 크게 메모리 가시성과 상호 배제일 것 같은데, java에서는 아래와 같은 키워드들을 제공하고 있어요
- volatile (메모리 가시성 확보, 상호 배제 x)
- synchronized (메모리 가시성 확보, 상호 배제 O)
- Atomic 객체 (메모리 가시성 확보, 상호 배제 O) 
synchronized의 대체 방법이라면 Atomic 객체가 될 수 있겠네요! 성능차이는 한번 세 키워드에 대해서 공부해보고 알아보면 좋을 것 같아요!


저는 Step 1 ~ 2때 사용자가 아닌 서버가 product Id를 auto increment하게 정의하는 방식으로 구현하다보니 서버에서 ProductDTO의 id 값을 변경하는 방식으로 구현하였습니다. 여기서 DTO는 꼭 불변이여야 해서 레코드로 구현하는게 바람직한지, 아니면 저처럼 DTO 객체의 값들을 변경할 수 있게 일반 class로 구현해도 되는지 궁금합니다.
> Record 객체를 사용하지 않고 일반 class로 구현하더라도 불변 객체로 선언하는게 좋다고 생각이 드는데요 (불변 객체가 좋은 이유에 대해 알아보면 좋을 것 같아요!)
혹시 그런 고민을 하게 된 이유에 대해서 궁금해요

2024-07-01 08:33 UTC, rdme0 commented on src/main/java/gift/controller/ProductController.java
> +    private final String WELL_DONE_MESSAGE = "Success";
final 키워드만 있을 때는 인스턴스가 생기고 변수 할당이 1번 되지만 static 키워드 까지 쓰게 된다면 컴파일 시간에 변수가 클래스에서 할당이 되어 프로그램이 종료될 때 까지 메모리에 남게 됩니다. 이는 모든 클래스의 인스턴스가 똑같은 값을 쓴다는 면에서 non static 일 때보다 상수의 목적에 더 가깝기 때문에 상수를 선언할 때 관례적으로 static final을 선언하게 됩니다.

2024-07-01 08:40 UTC, rdme0 commented on src/main/java/gift/exception/CustomException.java
> +}
제가 예외 처리를 할때 if (instanceof CustomException) 을 사용하면서 한번 인터페이스를 만들어보고도 싶어서 CustomException 인터페이스를 만들었지만 인터페이스는 RuntimeException 클래스를 상속할 수 없어서CustomException을 구현하고 RuntimeException 상속하는 방식으로 구현했습니다.   
지금 보니까 그냥 `public class CustomException extends RuntimeException` 으로 하고 CustomException 밑으로 자식 클래스들을 만드는 구조가 더 깔끔하겠다고 판단하여 리팩터링 하였습니다.

2024-07-01 08:59 UTC, rdme0 commented on src/main/java/gift/domain/ProductDTO.java
> +public record ProductDTO(
- DTO는 데이터를 전송하기 위한 객체이며, 계층형 아키텍쳐에서는 Controller - Service에서 유일하게 오고 가며 필드만 갖고 있는 객체입니다. 반면에 도메인은 DTO와 달리 비즈니스 로직이 있는 메서드까지 갖고 있으며, DB에 바로 mapping이 될 수 있어야 합니다.

- DB에 들어가는 값이 잘못될 경우 매우 번거로운데, 데이터의 변경이 빈번한 서버의 상위 계층(view layer)에서는 DTO, DB와 직접적인 접촉이 있는 하위 계층에서는 도메인으로 분리해주는 것이 안정성이 좋습니다.

2024-07-01 09:57 UTC, rdme0 commented
## RE : 과제 하면서 궁금한 점 - 답변
1 . Step1 당시에는 데이터베이스를 만들지 않아서 `ProductModel` 이라는 클래스로 대체했었는데 그 클래스의 책임이 domain + serivce + repositary 였습니다. 그때 model코드의 양 자체는 생각보다 많지 않아서 책임 분리를 할지 말지 고민하게 되었지만 지금 프로젝트를 리팩터링 하면서 깨달은 것이 특정 클래스의 책임이 크다는 것의 척도는 코드의 양이 아니라 응집력이라는 것을 알게 되었고, 질문 당시 클래스를 분리하는 것이 맞았다고 생각합니다.

4 . 제가 그때 당시에 dto와 model에 대한 이해가 부족했습니다. Step1 당시 데이터베이스를 만들지 않고 컬렉션 프레임워크로 구현을 해야 했어서, db의 auto increment를 코드로 구현하려다 보니 dto의 id필드를 변경해야 하지 않나  
(ProductDTO의 id = null -> 특정 값으로 변경)  
라고 생각하였습니다. 그런데 지금 생각해보니 dto는 불변 객체로 하고 도메인의 로직으로 다루면 됐던 것 같습니다!

코드리뷰 감사합니다! 덕분에 저의 부족한 부분을 알게 되었고, 공부하게 되면서 더욱 성장하게 된 것 같습니다 😄

2024-07-08 16:50 UTC, Hongdonggeon approved these changes
코멘트 다 반영한 것 확인해서 1주차 과제는 머지하겠습니다!

2024-07-08 16:50 UTC, merged