경북대 BE_이지호_1주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-product pull request #99
Opened 2024-06-27 06:06 UTC by GitJIHO

> step1브렌치를 step2로 pull하여 시작했습니다
[DOCS: 2단계 README 작성] 부터 step2 입니다

**코드 작성하면서 어려웠던 점**
---

- Admin용 Controller를 따로 구현하였는데 해당 방법이 맞는지 궁금합니다.

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분**
---

- 디렉토리 구조를 어떤식으로 구성해야 적절한지 궁금합니다.
- html 코드가 효율적으로 작성되었는지 알고싶습니다.

2024-06-28 15:03 UTC, sang5c requested changes
지호님 2단계도 잘 구현해주셨습니다!  
커밋도 잘 나뉘어 있네요 👍  

step1에서 작성한 리뷰에 대해서는 다시 작성하지 않았으니 확인해주세요~!  
step1과 관련이 있어 request change를 드립니다.  
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/28#pullrequestreview-2148064822

---
> Admin용 Controller를 따로 구현하였는데 해당 방법이 맞는지 궁금합니다.

맞는 방법은 없다고 생각해요. 상황에 따라 다방면으로 고민해야 하고, 충분한 이유가 있는 선택은 모두 맞는 방법입니다.  
따로 구현하지 않았다면 어떻게 했었을지, 어떤 생각으로 나누게 되었는지 적어주시면 좋을 것 같아요.  
조금 일반적인 답변을 드리자면 어드민 페이지에 접근할 수 있는 경로들을 구분하여 관리하는 클래스를 나누었다 볼 수 있겠네요.

> 디렉토리 구조를 어떤식으로 구성해야 적절한지 궁금합니다.  

이 부분도 2주차 미션을 진행해보신 다음 답변드릴게요.  
자바에서는 `패키지`라 호칭하는데 지금 클래스가 많지 않은데 굳이 패키지를 나눠야 할까?도 고민해보시면 좋겠네요!

> html 코드가 효율적으로 작성되었는지 알고싶습니다.

아직 효율을 따질 만큼 충분한 코드가 작성되지 않아 보여요! 문법적으로 잘못됐냐를 물으시는게 맞다면, 문제 없습니다 :)  
다른 질문 의도가 있으셨다면, 질문 배경을 조금 더 알려주세요.

2024-06-30 11:34 UTC, GitJIHO commented on src/main/java/gift/ProductController.java
> +import org.springframework.web.bind.annotation.RequestParam;
네 주의하겠습니다!

2024-06-30 11:41 UTC, GitJIHO commented on src/main/resources/templates/product-form.html
> +</html>
좋은 정보 감사드립니다!! 개행 추가하였습니다

2024-06-30 11:44 UTC, GitJIHO commented on src/main/resources/templates/product-list.html
> +</html>
네 감사합니다!

>따로 구현하지 않았다면 어떻게 했었을지, 어떤 생각으로 나누게 되었는지 적어주시면 좋을 것 같아요.

- 기존에 있던 productController를 @Controller 어노테이션으로 바꾸고 조건에 맞게 수정해주었을 것 같습니다! Controller를 두개 가져가는 방식이 문제가 원하는 코딩 방식인지 의문이 들어 질문 드렸습니다!

>자바에서는 패키지라 호칭하는데 지금 클래스가 많지 않은데 굳이 패키지를 나눠야 할까?도 고민해보시면 좋겠네요!

- 아하 앞으로는 패키지라는 호칭을 사용하도록 하겠습니다! 감사합니다

> 아직 효율을 따질 만큼 충분한 코드가 작성되지 않아 보여요! 문법적으로 잘못됐냐를 물으시는게 맞다면, 문제 없습니다 :)
다른 질문 의도가 있으셨다면, 질문 배경을 조금 더 알려주세요.

- product-form에서 수정과 삭제 기능 모두 처리하는데, 이를 html을 기능별로 분리해서 작성하는것이 더 효율적일지 고민되어 질문 드렸습니다..!

2024-07-01 12:45 UTC, closed without merging